import {readingList,toggleReadingList,moveReadingList,recallNames,nameConnections,readingStats,keyIdeas,readingCardText,gardenSettings} from './reading-room-data.js';
import {normalizeSearch} from './discovery.js';

export function createReadingRoom(api){
  const {names,themes,esc,icon,chapterScene,nameSeal,chapterArt}=api;
  const byId=id=>names.find(n=>n.id===id);
  const get=()=>api.getSaved();
  const context=()=>api.currentId()||get().last?.id||'allah';
  const settings=gardenSettings(names,chapterArt);
  let atlasFilter='all',atlasQuery='',questionQuery='',galleryPage=0,galleryLight='night',session=null,cardUrl=null,cardName=null;
  const back=()=>'<button class="text-button room-back" data-room="home">← Reading room</button>';
  const intro=text=>`<p class="room-intro">${text}</p>`;
  const open=(title,body,extra='')=>api.sheet(title,`${body}${extra==='room-home'?'':back()}`,`room-sheet ${extra}`);
  const status=text=>{const node=document.querySelector('#room-status');if(node)node.textContent=text;};
  function patch(value){const ok=api.savePatch(value);if(!ok)api.toast('This change could not be saved. Please keep a copy before leaving.');return ok;}
  function read(id,section=null){api.closeSheet();api.openSection(id,section);}
  function row(n,extra='') {return `<div class="room-name-row"><button class="room-read" data-room-read="${n.id}"><span class="room-seal" aria-hidden="true">${nameSeal(n.id)}</span><span><strong>${esc(n.name)}</strong><small>${esc(n.meaning)}</small></span>${icon('arrow')}</button>${extra}</div>`;}
  const tool=(action,title,line)=>`<button class="room-tool" data-room="${action}"><span><strong>${title}</strong><small>${line}</small></span>${icon('arrow')}</button>`;
  function homeEntrance(){const stats=readingStats(names,get());return `<section class="room-entrance"><span class="eyebrow">MAKE THE BOOK YOUR OWN</span><button data-room="home"><span><strong>Your reading <em>room.</em></strong><span>${stats.queued?`${stats.queued} ${stats.queued===1?'Name':'Names'} waiting in your list.`:'Follow a meaning. Keep a question. Return with fresh eyes.'}</span></span>${icon('arrow')}</button></section>`;}
  function home(){const stats=readingStats(names,get());open('Your reading room',intro('A place to connect what you read, revisit what you know, and keep the questions that matter.')+`<div class="room-statline"><span><strong>${stats.read}</strong> Names marked as read</span><span><strong>${stats.queued}</strong> in your reading list</span></div><p class="room-caption">A record of the pages you choose to return to, at your own pace.</p><section class="room-group"><h3>Find a way in.</h3>${tool('atlas','Map of the Names','See all 99 across the attribute groups')}${tool('search','Search the whole book','Find a phrase inside an explanation')}${tool('gallery','Walk through the gardens',`${settings.length} illustrated settings to explore`)}</section><section class="room-group"><h3>Understand more deeply.</h3>${tool('recall','A little recall',stats.revisit?`${stats.revisit} meanings you chose to revisit`:'Consider a few meanings, then reveal the explanation')}${tool('connections','Follow a connection',`Begin with ${esc(byId(context()).name)}`)}${tool('ideas','Key ideas in the book','Perfection, mercy, knowledge, and more')}</section><section class="room-group"><h3>Keep a thread.</h3>${tool('list','Your reading list','Choose and arrange what to read next')}${tool('questions','Questions to revisit',stats.questions?`${stats.questions} ${stats.questions===1?'question':'questions'} kept with the relevant Names`:'A notebook for what you want to understand')}${tool('card','Take a Name with you','A reading card to copy or download')}</section><div class="room-footer"><button class="text-button" data-action="kept">Saved passages & reflections ${icon('arrow')}</button><button class="text-button" data-action="backup">Backup & restore ${icon('arrow')}</button></div>`,'room-home');}
  function atlas(){atlasFilter='all';atlasQuery='';open('Map of the Names',intro('Explore the companion’s attribute groups. Each Name belongs to the same Lord; these groups are ways into the reading.')+`<label class="search-label" for="atlas-search">Find a Name on the map</label><input class="room-search" id="atlas-search" type="search" placeholder="Name, Arabic, or meaning"><div class="room-filters" role="group" aria-label="Map filter">${[['all','All Names'],['unread','Not yet read'],['saved','Saved']].map(([key,label])=>`<button data-atlas-filter="${key}" aria-pressed="${key==='all'}">${label}</button>`).join('')}</div><p id="atlas-count" class="room-caption" role="status"></p><div id="atlas-groups"></div>`,'room-atlas');updateAtlas();}
  function updateAtlas(){
    const saved=get(),needle=normalizeSearch(atlasQuery),matches=names.filter(n=>(!needle||normalizeSearch([n.name,n.arabic,n.meaning,...(n.aliases||[])].join(' ')).includes(needle))&&(atlasFilter!=='unread'||!saved.finished.includes(n.id))&&(atlasFilter!=='saved'||saved.bookmarks.includes(n.id)));
    document.querySelector('#atlas-count').textContent=`${matches.length} ${matches.length===1?'Name':'Names'} · Open a group to explore.`;
    document.querySelectorAll('[data-atlas-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.atlasFilter===atlasFilter)));
    document.querySelector('#atlas-groups').innerHTML=themes.map(t=>{
      const group=matches.filter(n=>n.theme===t.id);if(!group.length)return '';
      return `<details class="atlas-group" ${needle?'open':''}><summary><span class="atlas-image" aria-hidden="true">${chapterScene('',group[0].id)}</span><span><strong>${esc(t.label)}</strong><small>${group.length} ${group.length===1?'Name':'Names'} · ${group.filter(n=>saved.finished.includes(n.id)).length} marked as read</small></span><span aria-hidden="true">+</span></summary><p>${esc(t.invitation)}</p><div class="atlas-names">${group.map(n=>`<button data-room-read="${n.id}" aria-label="Read ${esc(n.name)}: ${esc(n.meaning)}"><small>${String(n.number).padStart(2,'0')}${saved.finished.includes(n.id)?' · Read':''}</small><span lang="ar" dir="rtl">${n.arabic}</span><strong>${esc(n.name)}</strong><span>${esc(n.meaning)}</span></button>`).join('')}</div></details>`;
    }).join('')||'<p class="room-empty">No Names match. Try another spelling or choose All Names.</p>';
  }
  function list(focusId){const list=readingList(get(),names);open('Your reading list',intro('Arrange a few Names to return to. Reading arrows follow book order or your chosen path; this list is yours to arrange.')+`<p class="room-caption">${list.length?`${list.length} ${list.length===1?'Name':'Names'} waiting. Mark a reading as read to remove it from this list.`:'Your list is empty. Add a Name from the menu below or from its reading tools.'}</p><ol class="room-queue">${list.map((id,i)=>{const n=byId(id);return `<li data-list-id="${id}"><span class="queue-number">${i+1}</span><div>${row(n)}<div class="queue-controls"><button data-list-move="${id}" data-direction="-1" ${i===0?'disabled':''} aria-label="Move ${esc(n.name)} earlier">↑ Earlier</button><button data-list-move="${id}" data-direction="1" ${i===list.length-1?'disabled':''} aria-label="Move ${esc(n.name)} later">↓ Later</button><button data-list-remove="${id}" aria-label="Remove ${esc(n.name)} from reading list">Remove</button></div></div></li>`;}).join('')}</ol><div class="room-add"><label for="queue-name">Add a Name to your list</label><select id="queue-name">${names.filter(n=>!list.includes(n.id)).map(n=>`<option value="${n.id}" ${n.id===context()?'selected':''}>${n.number}. ${esc(n.name)} · ${esc(n.meaning)}</option>`).join('')}</select><button class="primary" data-room="add-list" ${list.length===names.length?'disabled':''}>Add to my list ${icon('bookmark')}</button></div><p id="room-status" role="status"></p>`,'room-list');if(focusId){document.querySelector(`[data-list-id="${focusId}"] .room-read`)?.focus();}}
  function changeList(next,id){if(patch({readingList:next.readingList,nextReading:next.nextReading})){api.refreshJourney();list(id);}}
  function recall(){const n=recallNames(names,get()),hasRead=(get().reviewNames||[]).length||(get().finished||[]).length||(get().bookmarks||[]).length;open('A little recall',intro('Bring a meaning to mind before looking at the explanation. This is a chance to understand Allah’s attributes more deeply.')+`<div class="recall-intro-art" aria-hidden="true">${chapterScene('',n[0]?.id||'allah')}</div><h3>${hasRead?'Return to familiar Names.':'Begin with three Names.'}</h3><p>${hasRead?'We’ll begin with the Names you chose to revisit, then your read or saved Names.':'The first set introduces Allah, Ar-Rahman, and As-Salam. Read each explanation at your own pace.'}</p><button class="primary" data-recall-start="reading">Begin ${n.length} ${n.length===1?'Name':'Names'} ${icon('arrow')}</button><div class="room-footer">${get().bookmarks.length?'<button class="text-button" data-recall-start="saved">Use my saved Names</button>':''}${get().reviewNames.length?'<button class="text-button" data-recall-start="revisit">Only meanings I want to revisit</button>':''}</div><p class="room-caption">No timer or score. Your recall choices do not mark readings as read.</p>`,'room-recall');}
  function recallCard(){if(session.index>=session.names.length){open('A meaning to carry with you',intro(`You considered ${session.names.length} ${session.names.length===1?'Name':'Names'}. Return whenever a meaning needs more time.`)+`<p class="room-caption">${get().reviewNames.length} ${get().reviewNames.length===1?'meaning is':'meanings are'} kept for another look.</p><button class="primary" data-room="recall">Choose another set ${icon('arrow')}</button><button class="text-button room-back" data-room-read="${session.names.at(-1).id}">Read the last Name in full</button>`);return;}
    const n=session.names[session.index];open('Consider the meaning',`<p class="room-caption">NAME ${session.index+1} OF ${session.names.length}</p><div class="recall-name"><span lang="ar" dir="rtl">${n.arabic}</span><h3>${esc(n.name)}</h3></div><p class="recall-question">What does this Name teach you about Allah?</p>${!session.revealed?'<button class="primary" data-room="reveal">Reveal the explanation</button>':`<section id="recall-answer" tabindex="-1"><span class="eyebrow">${esc(n.meaning)}</span><h3>${esc(n.takeaway)}</h3><p>${esc(n.sections[0].paragraphs.join(' '))}</p><div class="recall-actions"><button class="primary" data-recall-choice="understood">Continue ${icon('arrow')}</button><button class="text-button" data-recall-choice="revisit">Keep this meaning for another look</button></div></section>`}<button class="text-button room-back" data-room-read="${n.id}">Open the full reading ${icon('arrow')}</button><button class="text-button room-back" data-room="recall">Leave this set</button>`,'room-recall');if(session.revealed)document.querySelector('#recall-answer').focus({preventScroll:true});}
  function connections(id=context()){const n=byId(id);if(!n)return;open('Follow a connection',`<div class="connection-centre"><span lang="ar" dir="rtl">${n.arabic}</span><h3>${esc(n.name)}</h3><p>${esc(n.takeaway)}</p></div>`+intro('Different meanings, the same Lord. Follow a connection and notice what each Name helps you understand.')+nameConnections(n,names).map(c=>`<section class="connection-branch"><p class="room-caption">${c.kind==='pair'?'READ TOGETHER':c.kind==='related'?'A RELATED NAME':'IN THE SAME ATTRIBUTE GROUP'}</p>${row(c.name)}<p>${esc(c.kind==='theme'?themes.find(t=>t.id===n.theme)?.invitation||c.reason:c.reason)}</p><button class="text-button" data-room-connections="${c.name.id}">Explore connections from ${esc(c.name.name)} ${icon('arrow')}</button></section>`).join(''),'room-connections');}
  function ideas(){open('Key ideas in the book',intro('Stay close to the explanations in the readings. Open an idea, then follow it back to its Name for the full context.')+`<div class="idea-list">${keyIdeas.map(k=>{const n=byId(k.id);return `<details><summary>${esc(k.term)}<span aria-hidden="true">+</span></summary><p class="room-caption">FROM ${esc(n.name.toUpperCase())} · ${esc(n.meaning)}</p><p>${esc(n.sections[k.section].paragraphs.join(' '))}</p><button class="text-button" data-room-read="${n.id}" data-room-section="${k.section}">Read this explanation in context ${icon('arrow')}</button></details>`;}).join('')}</div><p class="room-caption">Original companion explanations, not quotations from a published translation. The full readings include source notes.</p>`,'room-ideas');}
  function questions(){questionQuery='';open('Questions to revisit',intro('Keep what you want to understand alongside the Name that raised it. These questions are for your own study and can be brought to a trusted teacher.')+`<div class="room-add"><label for="question-name">Which Name are you considering?</label><select id="question-name">${names.map(n=>`<option value="${n.id}" ${n.id===context()?'selected':''}>${esc(n.name)} · ${esc(n.meaning)}</option>`).join('')}</select><button class="primary" data-room="new-question">Open my question ${icon('pen')}</button></div><label class="search-label" for="question-search">Search your questions</label><input id="question-search" class="room-search" type="search" placeholder="Find a Name or your own words"><p id="question-count" class="room-caption" role="status"></p><div id="question-entries"></div><button class="text-button room-back" data-room="export-questions">Save a text copy of my questions ${icon('arrow')}</button>`,'room-questions');updateQuestions();}
  function updateQuestions(){const needle=normalizeSearch(questionQuery),entries=names.filter(n=>get().questions[n.id]?.trim()&&(!needle||normalizeSearch(n.name+' '+get().questions[n.id]).includes(needle)));document.querySelector('#question-count').textContent=`${entries.length} ${entries.length===1?'question':'questions'}`;document.querySelector('#question-entries').innerHTML=entries.map(n=>`<button class="question-entry" data-question-name="${n.id}"><strong>${esc(n.name)}</strong><span>${esc(get().questions[n.id])}</span><small>Return to your question ${icon('arrow')}</small></button>`).join('')||'<p class="room-empty">Your questions will appear here. Writing is always optional.</p>';}
  function question(id=context()){const n=byId(id);if(!n)return;open(`Your question · ${esc(n.name)}`,`<p class="question-meaning">${esc(n.takeaway)}</p><label class="search-label" for="question-writing">What would you like to understand more deeply?</label><textarea id="question-writing" data-name-id="${n.id}" rows="7" maxlength="50000" dir="auto" placeholder="A word, a distinction, or a question to return to…">${esc(get().questions[n.id]||'')}</textarea><p id="question-status" role="status" class="room-caption">${get().questions[n.id]?'Saved in this browser.':'Your writing stays in this browser.'}</p><button class="text-button room-back" data-room-read="${n.id}">Return to the full reading ${icon('arrow')}</button><button class="text-button room-back" data-room-connections="${n.id}">Explore related meanings ${icon('arrow')}</button><button class="text-button room-back" data-room="questions">All my questions ${icon('arrow')}</button>`,'room-question');}
  function exportQuestions(){const entries=names.filter(n=>get().questions[n.id]?.trim());if(!entries.length){api.toast('Write a question to make a personal copy.');return;}const text=['THE BEAUTIFUL NAMES — MY QUESTIONS',...entries.map(n=>`${n.name} · ${n.meaning}\n\n${get().questions[n.id]}`)].join('\n\n────────────\n\n');copyPanel('Your questions to keep',text,'beautiful-names-questions.txt');}
  function copyPanel(title,text,filename){open(title,`<label class="search-label" for="room-copy">Your text copy</label><textarea id="room-copy" readonly rows="12" dir="auto">${esc(text)}</textarea><div class="room-footer"><button class="primary" data-room="copy-text">Copy text</button><a id="room-download" class="text-button" download="${filename}">Download text file ${icon('arrow')}</a></div><p id="room-status" role="status" class="room-caption"></p>`);cardUrl=URL.createObjectURL(new Blob(['\uFEFF',text],{type:'text/plain;charset=utf-8'}));document.querySelector('#room-download').href=cardUrl;}
  function card(id=context()){const n=byId(id);if(!n)return;cardName=n.id;open('Take a Name with you',intro('Keep a short companion reading close. The text copy includes the explanation and its source attribution.')+`<article class="portable-card"><div class="portable-art" aria-hidden="true">${chapterScene('',n.id)}</div><div><span lang="ar" dir="rtl">${n.arabic}</span><h3>${esc(n.name)}</h3><p class="portable-meaning">${esc(n.meaning)}</p><blockquote>${esc(n.takeaway)}</blockquote><p>${esc(n.sections[0].paragraphs.join(' '))}</p><small>THE BEAUTIFUL NAMES · ORIGINAL COMPANION READING</small></div></article><button class="primary" data-room="card-copy">Copy or download this reading ${icon('arrow')}</button><button class="text-button room-back" data-room-read="${n.id}">Read the Name in full</button>`,'room-card');}
  function gallery(reset=true){if(reset){galleryPage=0;galleryLight=api.getTheme();}const pages=Math.ceil(settings.length/4),group=settings.slice(galleryPage*4,galleryPage*4+4);open('Walk through the gardens',intro('Let a setting draw you toward a reading. These garden illustrations accompany the Names; they do not depict Allah.')+`<div class="room-filters" role="group" aria-label="Garden illustration light"><button data-gallery-light="day" aria-pressed="${galleryLight==='day'}">Daylight</button><button data-gallery-light="night" aria-pressed="${galleryLight==='night'}">Moonlight</button></div><div class="room-gardens">${group.map(a=>`<article><div class="gallery-art">${chapterScene('',a.id,true,galleryLight)}</div><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p><details><summary>Explore ${a.names.length} ${a.names.length===1?'Name':'Names'} in this setting <span aria-hidden="true">+</span></summary>${a.names.map(n=>row(n)).join('')}</details></article>`).join('')}</div><nav class="room-pager" aria-label="Garden pages"><button data-gallery-step="-1" ${galleryPage===0?'disabled':''} aria-label="Previous gardens">${icon('back')}</button><span>${galleryPage+1} of ${pages}</span><button data-gallery-step="1" ${galleryPage===pages-1?'disabled':''} aria-label="Next gardens">${icon('arrow')}</button></nav>`,'room-gallery');}
  function nameTools(id=context()){const n=byId(id),queued=readingList(get(),names).includes(n.id);open(`Stay with ${esc(n.name)}`,intro(esc(n.takeaway))+`<div class="room-group"><button class="room-tool" data-room-queue="${n.id}" aria-pressed="${queued}"><span><strong>${queued?'Remove from reading list':'Add to reading list'}</strong><small>${queued?'You can arrange your list in the reading room':'Leave this Name waiting for another visit'}</small></span>${icon(queued?'check':'bookmark')}</button><button class="room-tool" data-room-connections="${n.id}"><span><strong>Follow a connection</strong><small>Understand related attributes</small></span>${icon('arrow')}</button><button class="room-tool" data-question-name="${n.id}"><span><strong>Keep a question</strong><small>Return to what you want to understand</small></span>${icon('pen')}</button><button class="room-tool" data-room-card="${n.id}"><span><strong>Take this Name with you</strong><small>A portable companion reading</small></span>${icon('arrow')}</button></div><button class="text-button" data-action="source">Reading notes & source ${icon('arrow')}</button>`);}
  async function copyText(){const field=document.querySelector('#room-copy');if(!field)return;try{await navigator.clipboard.writeText(field.value);status('Copied. Your text is ready to keep.');}catch{field.focus();field.select();status('Text selected. Use Copy to keep it.');}}
  function handleClick(event){const target=event.target.closest('button,a');if(!target)return false;const d=target.dataset;
    if(d.roomRead){read(d.roomRead,d.roomSection===undefined?null:Number(d.roomSection));return true;}
    if(d.atlasFilter){atlasFilter=d.atlasFilter;updateAtlas();return true;}
    if(d.listMove){changeList(moveReadingList(get(),d.listMove,Number(d.direction),names),d.listMove);return true;}
    if(d.listRemove){changeList(toggleReadingList(get(),d.listRemove,names));return true;}
    if(d.roomQueue){const next=toggleReadingList(get(),d.roomQueue,names);if(patch({readingList:next.readingList,nextReading:next.nextReading})){api.refreshJourney();nameTools(d.roomQueue);}return true;}
    if(d.recallStart){session={names:recallNames(names,get(),d.recallStart),index:0,revealed:false};if(session.names.length)recallCard();else api.toast('There are no Names in this set yet.');return true;}
    if(d.recallChoice&&session?.revealed){const id=session.names[session.index].id,review=new Set(get().reviewNames);if(d.recallChoice==='revisit')review.add(id);else review.delete(id);if(patch({reviewNames:[...review],recalledNames:[...(get().recalledNames||[]).filter(value=>value!==id),id]})){session.index++;session.revealed=false;recallCard();}return true;}
    if(d.roomConnections){connections(d.roomConnections);return true;}
    if(d.questionName){question(d.questionName);return true;}
    if(d.roomCard){card(d.roomCard);return true;}
    if(d.galleryLight){galleryLight=d.galleryLight;gallery(false);return true;}
    if(d.galleryStep){galleryPage=Math.max(0,Math.min(Math.ceil(settings.length/4)-1,galleryPage+Number(d.galleryStep)));gallery(false);return true;}
    if(!d.room)return false;
    switch(d.room){case 'home':home();break;case 'atlas':atlas();break;case 'search':api.openSearch();break;case 'list':list();break;case 'add-list':{const id=document.querySelector('#queue-name')?.value;if(id)changeList(toggleReadingList(get(),id,names),id);break;}case 'recall':recall();break;case 'reveal':if(session){session.revealed=true;recallCard();}break;case 'connections':connections();break;case 'ideas':ideas();break;case 'questions':questions();break;case 'new-question':question(document.querySelector('#question-name').value);break;case 'export-questions':exportQuestions();break;case 'card':card();break;case 'card-copy':copyPanel('Your reading to keep',readingCardText(byId(cardName),api.sourceUrl),`beautiful-names-${cardName}.txt`);break;case 'copy-text':copyText();break;case 'gallery':gallery();break;case 'tools':nameTools();break;default:return false;}return true;
  }
  function handleInput(event){const el=event.target;if(el.id==='atlas-search'){atlasQuery=el.value;updateAtlas();return true;}if(el.id==='question-search'){questionQuery=el.value;updateQuestions();return true;}if(el.id==='question-writing'){const questions={...get().questions};if(el.value.trim())questions[el.dataset.nameId]=el.value;else delete questions[el.dataset.nameId];const ok=patch({questions});document.querySelector('#question-status').textContent=ok?'Saved in this browser.':'Could not save. Keep a text copy before leaving.';return true;}return false;}
  function cleanup(){if(cardUrl){URL.revokeObjectURL(cardUrl);cardUrl=null;}}
  return {homeEntrance,home,nameTools,handleClick,handleInput,cleanup};
}
