import { useState } from 'react';
import { Choices, Reading, Study } from './Study';

const meanings = [
 ['Presence','Where is attention?','The heart attends to the act and words instead of wandering elsewhere.','Attention can stay with the words without grasping their meaning.'],
 ['Understanding','What do the words mean?','The heart apprehends the meaning of what is being said.','Understanding adds something to presence; the two are not interchangeable.'],
 ['Reverence','Whom am I addressing?','Recognition of divine greatness and of one’s own dependence gives rise to reverence.','One can attend to and understand someone without revering them.'],
 ['Awe','What gives rise to fear?','Awe is fear arising from reverence and recognition of divine power.','Ghazali distinguishes it from fear of an ordinary threat.'],
 ['Hope','What am I looking toward?','Knowledge of divine kindness, generosity, and promise gives rise to hope.','Fear of power does not by itself imply hope of reward.'],
 ['Shame','Where have I fallen short?','Awareness of shortcomings in worship gives rise to shame.','This is a distinct awareness, not another name for awe or hope.'],
];
export function SixMeaningsStudy() {
 const [selected,setSelected]=useState(0); const [compare,setCompare]=useState(false);const item=meanings[selected];
 return <Study eyebrow="Prayer · six distinct meanings" title="Attention is only the beginning." intro="Choose a meaning to see what it adds. These are distinctions to understand, not levels to unlock or a score for prayer." sources={[["Presence and understanding · I, 161",161],["Reverence, awe, hope, shame and their causes · I, 162",162]]} note="The six names, their differences, and their causes follow this passage. The questions are editorial reading prompts." question="Can someone be present with the words yet miss their meaning?" answer="Yes. Ghazali explicitly separates attending to the words from understanding them. The distinction gives the work of understanding its own place.">
 <div className="meaning-index" role="group" aria-label="Explore six inward meanings">{meanings.map((m,i)=><button key={m[0]} aria-pressed={selected===i} onClick={()=>{setSelected(i);setCompare(false);}}><span>0{i+1}</span><strong>{m[0]}</strong></button>)}</div>
 <Reading label={item[0]} title={item[1]}><p>{item[2]}</p></Reading>
 <button className="study-reveal" aria-expanded={compare} onClick={()=>setCompare(!compare)}>What does this add? <span aria-hidden="true">{compare?'−':'+'}</span></button>{compare&&<p className="meaning-addition">{item[3]}</p>}
 </Study>;
}
const mirrors=[
 ['A guide','Discernment with direction','A guide familiar with faults and their treatment helps name what is hidden.','The text specifies insight and sincere care. A title alone does not establish those qualities.'],
 ['A friend','Ask for truthful observation','A truthful, perceptive, religious friend is asked to observe conduct and point out faults.','Friendship becomes a deliberate request for candour, beyond reassurance.'],
 ['An opponent','Look past the motive','Hostility can expose what flattery conceals. Look for what can be learned.','Examining a criticism is different from accepting every accusation as fact.'],
 ['Other people','Turn the observation inward','A fault noticed in someone else prompts examination of its presence in oneself.','The inquiry returns to the reader; it does not become a catalogue of other people’s faults.'],
];
export function FeedbackStudy(){const [selected,setSelected]=useState(1); const item=mirrors[selected];return <Study eyebrow="Character · four routes to self-knowledge" title="Where can a clearer view come from?" intro="Self-love can conceal what needs attention. Ghazali gives four routes that interrupt solitary self-assessment." sources={[["The guide and truthful friend · III, 64",810],["The opponent and other people · III, 65",811]]} note="The routes come from the passage. The cautions below distinguish learning from feedback from giving another person unlimited authority." question="What makes the fourth route different from judging other people?" answer="Its destination is one's own conduct. What is disliked elsewhere becomes a question to investigate inwardly."><Choices label="Choose a source of feedback" items={mirrors.map(m=>m[0])} value={selected} onChange={setSelected}/><div className="feedback-window"><span aria-hidden="true">↘</span><strong>{item[0]}</strong><small>Observation returns to the self</small></div><Reading label="What this route contributes" title={item[1]}><p>{item[2]}</p><p className="study-boundary">{item[3]}</p></Reading></Study>}
export function TreatmentStudy(){const [selected,setSelected]=useState(0); const states=[['Holding too tightly','Practise fitting generosity','The passage treats miserliness through giving to those entitled to receive.'],['Giving without measure','Recover fitting restraint','Giving has become a new excess when it disregards its proper recipients and purposes.'],['Responding to need','Let the need govern','Keeping and giving answer to their proper occasions; attachment to either extreme no longer directs the choice.']];const item=states[selected];return <Study eyebrow="Character · treatment and its limit" title="The opposite is a remedy, not the destination." intro="Follow the example of keeping and giving. The direction of correction depends on the condition being treated." sources={[["Treatment through its causes · III, 60",806],["Recognising balance after treatment · III, 63",809]]} note="These are conditions in Ghazali's account, not spending advice or an assessment of the reader. No quantities or universal regimen are prescribed." question="Has treatment succeeded if a miser becomes a reckless spender?" answer="No. The passage calls both extremes disorders. Correction aims at the fitting measure, and must change when the condition changes."><Choices label="Compare conditions of keeping and giving" items={states.map(s=>s[0])} value={selected} onChange={setSelected}/><div className="treatment-line" aria-hidden="true"><span className={selected===0?'chosen':''}>Keeping</span><span className={selected===2?'chosen':''}>Fitting need</span><span className={selected===1?'chosen':''}>Giving</span></div><Reading label="Direction of correction" title={item[1]}><p>{item[2]}</p></Reading><p className="study-caption">Diagnosis and capacity come before a personal regimen. A harder exercise is not automatically a better one.</p></Study>}
const duties=[['Withhold belief','The carrier’s confidence is not evidence.'],['Discourage it','Advise the carrier to stop the conduct.'],['Refuse allegiance','Ghazali explicitly calls for disapproval of the tale-bearer for God’s sake, rather than treating the transmission as friendship.'],['Avoid suspicion','Do not let the report establish a bad opinion of the absent person.'],['Do not spy','Do not pursue private investigation to feed the report.'],['Do not repeat','Even repeating it to condemn the carrier can reproduce the same act.']];
export function ReceiverStudy(){const [selected,setSelected]=useState(0);return <Study eyebrow="Tongue · the receiver has a part" title="The report can stop here." intro="Ghazali addresses the person who receives a harmful report. Follow the six duties separately, rather than compressing them into a general instruction to be careful." sources={[["The definition and six duties · III, 156",902]]} note="The third duty includes the text's explicit religious disapproval of the tale-bearer. This reading does not convert it into permission to retaliate or mistreat someone." question="Why is ‘someone told me this’ not a way to repeat the report innocently?" answer="The attribution does not remove the transmission. The receiver becomes another carrier when the same content is passed on."><p className="study-caption">This concerns tale-bearing. Credible reports of danger or abuse may require appropriate safeguarding action; these duties do not require silence about harm.</p><ol className="receiver-duties">{duties.map((d,i)=><li key={d[0]}><button aria-pressed={selected===i} onClick={()=>setSelected(i)}><span>0{i+1}</span>{d[0]}<span aria-hidden="true">{selected===i?'−':'+'}</span></button>{selected===i&&<p>{d[1]}</p>}</li>)}</ol></Study>}
const purposes=[
 ['Seeking justice','A wronged person addresses someone able to obtain redress.','Disclosure is directed toward the right being sought.'],
 ['Stopping a wrong','Help is sought from someone who can bring a wrong to an end.','The purpose must actually be correction, not exposure for its own sake.'],
 ['Asking for a ruling','A person explains a situation to obtain informed guidance.','The text prefers an anonymous description when that is sufficient.'],
 ['Protective counsel','Relevant information is given where protection or sincere advice requires it.','Say only what the purpose needs; resentment can disguise itself as concern.'],
 ['Identification','An established description is used when needed to identify someone.','Ghazali prefers an alternative expression when one is available.'],
 ['Open conduct','The text distinguishes conduct a person openly displays from concealed matters.','This does not authorise exposing unrelated, private faults.'],
];
export function DisclosurePurposes(){const [selected,setSelected]=useState(0); const item=purposes[selected];return <Study eyebrow="Tongue · six bounded purposes" title="A purpose carries its own limit." intro="The text allows certain disclosures for a recognised purpose that cannot otherwise be reached. Compare the purpose with the limit beside it." sources={[["Justice, correction, guidance and protection · III, 152",898],["Identification and open conduct · III, 153",899]]} note="These are the six categories in the historical text. Applying them to a real case requires attention to circumstances and may need qualified counsel; selecting a category grants no permission." question="If an anonymous description achieves the purpose, what follows?" answer="The text prefers avoiding identification where it is unnecessary. A recognised purpose does not make every detail relevant."><Choices label="Compare six purposes of disclosure" items={purposes.map(p=>p[0])} value={selected} onChange={setSelected}/><Reading label="Purpose" title={item[0]}><p>{item[1]}</p></Reading><div className="purpose-limit"><span className="study-kicker">Its limit</span><p>{item[2]}</p></div></Study>}
