// Connect the visible objects to the advice without changing the original readings.
export const artworkCaptions: Partial<Record<number, string>> = {
  3: 'A young shoot needs repeated care. Keep asking Allah for help while you wait.',
  5: 'The shoes are small beside the mountains. Keep a humble view of yourself, and stay willing to learn.',
  8: 'A bag rests at a stopping place. Use what you need here without forgetting the journey ahead.',
  10: 'The footprints turn toward the open way home. You can turn back after a wrong choice.',
  11: 'The repaired bowl can still hold something good. Bring your need for healing to Allah with hope.',
  13: 'An empty chair makes room for a quiet moment. Being alone does not have to end your hope in Allah.',
  14: 'The spade and watering can are ready for use. Make a real effort and ask Allah for help.',
  15: 'The tissues belong beside the prayer mat too. Sadness and faith can exist together.',
  17: 'A basket of food waits at a doorway. Help may arrive through someone you did not expect.',
  18: 'Sand keeps falling while the page is still open. Let the time you have lead to a good action.',
  19: 'A book waits in a quiet place. Give the Quran your attention as well as your time.',
  21: 'The mat has a place in this room. Give prayer a real place in your day.',
  22: 'Footprints lead back toward home. Let asking for forgiveness become an honest return.',
  23: 'The steps rise one at a time. Keep practicing a good habit, even when it feels hard.',
  24: 'Water reaches the soil a little at a time. Keep giving remembrance a place in your day.',
  26: 'Dry twigs feed a small flame. Do not dismiss a wrong because it seems small; turn away before it grows.',
  28: 'The garden has clear borders and room to grow. Allah’s guidance is for your good.',
  29: 'There is only so much room in the bag. Think about what you put first when choices compete.',
  30: 'Strong roots support the fruit above. Nourish your faith and let it grow into good actions.',
  31: 'The book and tools are together. Put something you have learned into practice.',
  33: 'The river keeps moving. Do your part, and trust Allah with what you cannot control.',
  34: 'An ant and a fish each need provision. Allah provides for the smallest creatures; turn to Him for help.',
  38: 'A meal, shoes, and a secure doorway hold everyday gifts. Notice what is supporting your life today.',
  39: 'A plant still needs care after it starts growing. Keep caring for your actions without congratulating yourself.',
  41: 'The watering can stays beside the plant. Keep dua and patience part of a long wait.',
  42: 'A tiny grain can disappear beside a stone. Even a small deed matters.',
  43: 'The bag is ready beside the path. Remember the journey instead of endlessly collecting more.',
  45: 'Rain reaches a living tree. Faith and difficulty can be present at the same time.',
  47: 'The boat meets rough water. Hold on to faith while you face the storm.',
  52: 'The path continues beyond the resting bag. Keep going toward a worthwhile purpose.',
  53: 'A book and prayer mat are already in place. Build good habits before a difficult day arrives.',
  54: 'Look closely at the blossoms and fruit. Pay attention to creation and remember its Creator.',
  55: 'The young shoot still needs water. Give your attention to the useful work you can do now.',
  56: 'A blossom rests in a repaired bowl. Keep hope in Allah’s promise of ease during hardship.',
  57: 'There is room at the table for another person. Let mercy shape the way you treat people.',
  59: 'An unfinished page leaves room for more. Keep turning to Allah even when you do not understand a test.',
  60: 'The wrapping is open, but the giver still matters. Thank Allah as well as enjoying the gift.',
  61: 'The path is made of many steps. Keep choosing a good practice when distractions return.',
  63: 'A clear mirror reflects what is before it. Give your heart care through worship and remembrance.',
  65: 'A few stepping stones show a way forward. Consider what you can learn and change during a trial.',
  66: 'Food, a book, a phone, and a prayer mat share one room. Notice which activities fill your days.',
  68: 'A meal and a place to pray are still here. Bring your worry to Allah and notice the good you can do.',
  70: 'An open notebook waits beside the bed. Review your day honestly and turn back to Allah before sleep.',
  72: 'Two bags of different sizes sit beside a prayer mat. Worship matters at every age.',
  74: 'A young plant grows from freshly turned soil. Let regret lead to repentance and repair.',
  75: 'The bridge offers a step across the stream. Take the responsible action available to you with trust in Allah.',
  79: 'Fresh growth reaches through the soil. Make room for the Quran to renew your heart.',
  80: 'A closed gate leaves time to choose another way. Pause before following a desire.',
  81: 'A path divides, and you can take only one way forward. Trust Allah with what happened and what passed you by.',
  82: 'Pruning tools lie beside an overgrown path. Notice harmful choices and begin turning away from them.',
  85: 'Water is being given to a small plant. Ask Allah for help and healing, and keep caring for your heart.',
  86: 'The tree stays rooted as the light changes. Stay grounded in faith as your circumstances change.',
  88: 'Water and a support both help the plant. Practice gratitude in ease and patience under pressure.',
  89: 'The gift is ready to leave the table. Before you give it, consider whose pleasure you seek.',
  90: 'The fish is at home in the water. Stay close to the guidance you need, even without anyone’s praise.',
  92: 'A closed gate stands beside a clear path. Keep patience and trust when things differ from your plan.',
  93: 'Ash, gold, and a clear crystal invite a closer look. Examine what you are seeking and what it does to your heart.',
  96: 'The stones cross the stream one step at a time. Meet difficulty with trust and patient effort.',
  97: 'A notebook sits beside the things of an ordinary day. Let repeated good actions shape your life’s story.',
  98: 'A compass rests beside a signpost. Consider where you place your trust and which guidance you follow.',
  100: 'An open notebook leaves room to look again. Review your actions honestly while keeping hope.',
  101: 'Food, a phone, and a notebook share the table. Look at the reasons behind your ordinary choices.',
  104: 'A fallen leaf lies beside a cup. Enjoy what you have without expecting it to last forever.',
  105: 'The table is set to share. Keep kindness and generosity part of your changing days.',
  106: 'Shoes and a parcel are ready at the door. Take your next useful step for Allah’s sake.',
  107: 'A young tree bends against its support. Give care to how you respond while difficulty is still present.',
  109: 'One pot is broken; other plants still need care. Acknowledge the loss and gently notice what remains.',
  110: 'A basket and a bundle wait beside the path. Notice the burdens you carry and the good that still remains.',
  111: 'A gate marks a place to pause. Stop before following a desire that leads toward disobedience.',
};
