import { assetUrl } from "./assetUrl";
import type { Chapter, ConceptNode, VisualModel } from "./data";
import type { Instrument, Journey, SourceLink, SystemBook, TaxonomyGroup } from "./systemTypes";

type Seed = { id: number; shortTitle: string; formalTitle: string; overview: string; thesis?: string; moves: Array<{ title: string; body: string }>; closer: Array<{ title: string; body: string }>; distinction: [string, string, string, string, string]; misreading: string; reflection: string; audit: string[]; nodes: string[]; model: VisualModel };
const bab = (id: number) => (id <= 4 ? "the first chapter, on the excellence of brotherhood" : id <= 12 ? "the second chapter, on the rights of companionship" : "the third chapter, on the wider ties");
const makeChapter = (seed: Seed): Chapter => ({
  id: seed.id, shortTitle: seed.shortTitle, formalTitle: seed.formalTitle, overview: seed.overview,
  reflection: seed.reflection, relatedNodes: seed.nodes, visualModel: seed.model,
  deep: { thesis: seed.thesis ?? seed.moves[0].body, context: seed.overview, moves: seed.moves, closeReading: seed.closer,
    distinction: { title: seed.distinction[0], firstLabel: seed.distinction[1], first: seed.distinction[2], secondLabel: seed.distinction[3], second: seed.distinction[4] },
    misreading: seed.misreading, observation: seed.reflection, selfAudit: seed.audit,
    sourceAnchor: `Book 15, ${bab(seed.id)}, ${seed.formalTitle}.` },
});
const chain = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "chain", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const pair = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "pair", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const spectrum = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "spectrum", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });

export const book15Chapters: Chapter[] = [
  makeChapter({
    id: 1, shortTitle: "Three chapters", formalTitle: "The shape of the book",
    overview: "The book on friendship has three chapters, and they move outward from the closest tie to the widest.",
    thesis: "Three chapters: what friendship is worth, the eight rights it creates, and the claims of people you never chose.",
    moves: [
      { title: "Announce the three", body: "The excellence of affection and brotherhood in God, with its conditions, degrees, and benefits; the rights of companionship, its manners, its reality, and what it entails; and the right of the Muslim, of kin, of the neighbour, and of ownership — and how to live with those connected by these ties." },
      { title: "Note the movement", body: "From a chosen bond, to what that bond obliges, to the ties nobody chooses. The third chapter is about people you are connected to whether or not you would have selected them." },
      { title: "Note where the weight is", body: "The second chapter enumerates eight rights, and it is the longest. The book's distinctive move is that friendship has a determinate content that can be listed." },
      { title: "Note what the first chapter contains", body: "Conditions and degrees — so that brotherhood is not one thing, and the second chapter's rights fall differently at different degrees." },
      { title: "Note the movement across the three chapters", body: "The three chapters run from most chosen to least, and the ordering is the book's argument. First a bond you enter deliberately, on a stated basis. Then what that bond turns out to oblige, in eight enumerable rights. Then the people you are tied to without ever having decided anything — the Muslim in general, kin, the neighbour, and those in your household. By the time the last chapter arrives, the reader has a full account of what a chosen tie demands, and the unchosen ones are measured against it." },
      { title: "See what enumerating friendship claims", body: "And the distinctive move is that friendship is given a determinate content. Most writing about it describes a quality — warmth, loyalty, an affinity — which is exactly the kind of thing nobody can be held to. Eight rights, listed, is a claim that the tie has obligations you either meet or do not, and that a person can audit his own friendships the way he could audit a contract. That is what makes the second chapter the longest and the book unusual." },
    ],
    closer: [
      { title: "Why the widest circle comes last", body: "The rights owed to a chosen brother are the fullest, and the rights of a neighbour or a kinsman are established by comparison with them. Working outward means each ring is defined by what it keeps of the one inside it." },
      { title: "Its place in the quarter", body: "Eating, marriage, earning, and the lawful have all concerned what a person does. This is the first book of the quarter about a relationship chosen for its own sake, and the one after it is about having none." },
    ],
    distinction: ["Two ways to arrange a book on human ties", "Outward from the chosen", "The fullest bond first, and the wider ties defined by what they keep of it.", "By category", "Friends, relatives, neighbours as parallel subjects, which would lose the gradation."],
    misreading: "Do not read the third chapter as an afterthought. It covers every relationship a person has not chosen, which is most of them.",
    reflection: "Notice that the book on friendship is followed immediately by the book on seclusion.",
    audit: ["Which circle is my question in?", "Chosen, or given?", "What do the wider ties keep?", "Why is seclusion next?"],
    nodes: ["ukhuwwa", "structure", "suhba"],
    model: chain("Three rings", "Each defined by what it keeps of the one inside.", [["Brotherhood", "Chosen, with conditions and degrees.", "support"], ["Its rights", "Eight of them, enumerated.", "support"], ["The given ties", "Muslim, kin, neighbour, ownership — unchosen.", "balance"]]),
  }),
  makeChapter({
    id: 2, shortTitle: "Conditions and degrees", formalTitle: "The first chapter",
    overview: "Before any rights are listed, the bond itself is given conditions and grades — which is what stops the eight rights from being a uniform demand.",
    thesis: "The case for brotherhood is built before any duty is named, and its conditions and degrees come with it.",
    moves: [
      { title: "Name the subject", body: "The excellence of affection and of brotherhood in God, and its conditions, its degrees, and its benefits — four things, of which two are qualifications." },
      { title: "Note the conditions", body: "Brotherhood in God is a bond entered on a basis, and the chapter sets out what has to be true of the person and of the ground on which the tie is formed." },
      { title: "Note the degrees", body: "It is graded, which means that two people can both truly be brothers and owe each other different amounts." },
      { title: "Say why the grading matters", body: "The eight rights of the next chapter are stated in full. Without the degrees, they would read as a single standard that almost no friendship meets — and the chapter on property makes the grading explicit by dividing that right into three ranks." },
      { title: "Note why the degrees have to come first", body: "The grading is what keeps the eight rights from being useless. Stated flat, they describe a friendship in which property is held in common, needs are met before they are voiced, and fidelity continues past death into the care of the man's family — a standard almost nobody meets, which would leave every reader in default and the chapter unusable. Degrees mean two people can both genuinely be brothers and owe each other different amounts, and the property right is later divided into three ranks precisely to show how." },
      { title: "See what the conditions are doing", body: "And the conditions belong to the same apparatus. A brotherhood in God is entered on a basis, and the chapter states what has to be true of the person and of the ground the tie is formed on. Which quietly settles that this is not a description of whoever you happen to spend time with. The eight rights attach to a bond of a particular kind, formed deliberately, and the next section is going to call it a contract." },
    ],
    closer: [
      { title: "The benefits", body: "The chapter treats them alongside the conditions, which is the Ihya's usual order: establish that it repays what is about to be asked of it, and only then say what it requires." },
      { title: "What conditions do to a claim", body: "A bond with conditions can be examined. Someone who claims brotherhood can be asked on what ground, and the story in the chapter on property turns on exactly that — a man is told he was not ashamed to claim brotherhood in God and then behave as he did." },
    ],
    distinction: ["Two ways to hold a friendship", "Graded", "With degrees, so that the rights fall differently on different ties.", "Uniform", "One standard for every friendship, which almost none would meet."],
    misreading: "Do not read the levels as excuses. They set what is owed — and in the chapter on money, the man at the lowest level is told that what he offered was not friendship at all.",
    reflection: "Ask on what ground your closest friendships were actually formed.",
    audit: ["On what ground was this formed?", "What degree is it?", "Would it meet a condition?", "What does the grading decide?"],
    nodes: ["ukhuwwa", "darajat", "shurut"],
    model: pair("Why the first chapter comes first", "It qualifies everything in the second.", [["Conditions", "On what ground the bond is formed, which can be examined.", "support"], ["Degrees", "So that two true brotherhoods can owe different amounts.", "support"]]),
  }),
  makeChapter({
    id: 3, shortTitle: "A contract", formalTitle: "What kind of thing brotherhood is",
    overview: "The sentence that opens the second chapter, and it changes the category of the whole subject.",
    thesis: "Friendship is treated as a contract, with the marriage contract as the comparison — which is what makes rights follow from it.",
    moves: [
      { title: "Give the claim", body: "Becoming someone's brother is a contract, he says — a tie between two people, like a marriage between two spouses." },
      { title: "Draw the parallel", body: "As marriage entails rights that must be fulfilled in discharge of the right of marriage, so does the contract of brotherhood." },
      { title: "Give the map", body: "So your brother has upon you a right in property, and in person, and in the tongue, and in the heart — by pardon and by supplication, by sincerity and fidelity, and by lightening and the leaving of affectation and imposition." },
      { title: "Give the number", body: "These duties gather into eight rights. Friendship is therefore given a definite content that can be listed and examined." },
      { title: "Take the comparison with marriage seriously", body: "Calling brotherhood a contract, and comparing it to marriage, is a strong claim and it is meant to be. A contract has terms; it can be met or breached; and what it obliges does not depend on how anybody feels on a given day. So the affection is not what generates the duties — the tie does, and the duties stand when the warmth is absent. That is precisely what people do not expect of friendship, and it is why the chapter can enumerate anything at all." },
      { title: "Note how the eight are grouped", body: "And the grouping is worth holding, because the eight are not a flat list. There is what you owe with your property, what you owe with your person, what you owe with your tongue — and the tongue is split into what must be withheld and what must be said. Then the heart's items: pardon, supplication, sincerity and fidelity. And last, lightening. Four instruments, running from the most external to the most internal, and ending with a duty about the cost of the whole arrangement." },
    ],
    closer: [
      { title: "What the parallel to marriage does", body: "Marriage is the paradigm of a relationship with enforceable content. Placing friendship beside it says that affection is not the whole of the tie, and that a person can be failing a friend in a specific and nameable way while feeling perfectly warm toward him." },
      { title: "The four registers", body: "Property, person, tongue, heart. The eight rights distribute across them unevenly — two on the tongue alone, in opposite directions — which is where the chapter's most interesting material sits." },
    ],
    distinction: ["Two things a friendship can be", "A contract", "With rights that can be listed, discharged, or failed.", "An affection", "A feeling, which cannot be audited and which can coexist with failing someone."],
    misreading: "Do not read the contract language as cold. Its effect is to make specific demands available where warmth alone would leave a person free to feel well of himself while doing nothing.",
    reflection: "Ask whether you would rather be owed something by a friend or felt warmly toward.",
    audit: ["Do I treat friendship as owed?", "Which register do I fail in?", "Could my failure be named?", "What does the marriage parallel add?"],
    nodes: ["aqd", "ukhuwwa", "huquq"],
    model: spectrum("Four registers, eight rights", "Distributed unevenly on purpose.", [["Property", "The first right, in three ranks.", "support"], ["Person", "Help, before being asked.", "support"], ["The tongue", "Two rights, pulling in opposite directions.", "balance"], ["The heart", "Pardon, supplication, fidelity, and lightening.", "support"]]),
  }),
  makeChapter({
    id: 4, shortTitle: "Who to pick", formalTitle: "Choosing who to be close to",
    overview: "Before any of the duties of friendship, Ghazali asks who is worth having one with — and gives a method for answering it that most advice on the subject skips.",
    thesis: "What to look for in a friend follows from what you want the friendship for, which is the step most advice on the subject skips.",
    moves: [
      { title: "Start with the flat statement", body: "“Not every person is fit for company.” And the report he puts under it: “a person follows the religion of his close friend, so let each of you look at who he is taking as one.”" },
      { title: "Give the method", body: "What you should look for depends on what you want the friendship for. A condition is just whatever is needed to reach the aim — so name the aim and the conditions become obvious. Most advice about friends skips that step and goes straight to a list of virtues." },
      { title: "Name the aims honestly", body: "Some are worldly: his money, his standing, or simply liking his company. Ghazali sets those aside as not his subject, without sneering at them. The religious ones he lists plainly: learning from his knowledge and practice; using his standing as cover from people who would disturb you and get between you and worship; his money, so you are not spending your life chasing food; help when something serious happens; the benefit of his prayers; and his intercession later." },
      { title: "Give Umar's version", body: "“Stick with truthful friends and live in their shelter — they are an ornament in easy times and a resource in hard ones. Put your friend's behaviour in the best light until something comes from him you cannot explain away. Keep clear of your enemy, and be careful even of your friend, except the trustworthy — and nobody is trustworthy but someone who fears God. Do not keep company with a corrupt man, or you will pick it up; do not let him near your secrets; and take advice on your affairs from people who fear God.”" },
      { title: "See why naming the aim comes first", body: "The method is the useful part and it inverts the usual advice. Most counsel about friendship starts with a list of virtues to look for. Ghazali starts by asking what you want the friendship for, on the ground that a condition is simply whatever is required to reach an aim — so until the aim is named, the list of conditions is arbitrary. Different purposes genuinely select for different people, and a man who has not asked what he is after will apply somebody else's criteria and be puzzled when they do not fit." },
      { title: "Note the honesty about the worldly aims", body: "And the handling of the worldly aims is worth catching. Money, standing, and simply enjoying somebody's company are named plainly and set aside as not the subject — without a word of disparagement. He does not pretend such friendships do not exist, or that people ought not to have them. He says they are not what this chapter is about, which is a different move from condemning them, and it is what lets the religious aims be listed with equal plainness." },
      { title: "Take Umar's qualification seriously", body: "And the sharpest line in Umar's counsel is the one people skip: be careful even of your friend, except the trustworthy — and nobody is trustworthy but somebody who fears God. That is a caution set inside an instruction to keep close company, and it holds the two together rather than choosing. The same passage tells you to read your friend's conduct in the best light until something arrives you cannot explain away, which is the working form of the same balance." },
    ],
    closer: [
      { title: "'Alqama's deathbed list", body: "Dying, 'Alqama al-'Utaridi told his son: keep company with someone who protects you if you serve him and does you credit if you are seen with him; who provides for you if your money runs out. Who puts his hand out when you put yours out with something good; who counts the good he sees in you and closes over the bad. Who gives when you ask, and starts the conversation when you go quiet, and stands by you when disaster lands. Who backs you up when you speak, puts you in charge when you attempt something together, and gives way to you when you disagree." },
      { title: "And the joke Ghazali leaves in", body: "Al-Ma'mun asked someone to explain that advice. The man said: do you know why he told his son that? Al-Ma'mun said no. He said — “because he wanted him not to keep company with anybody at all.” Ghazali reports the joke rather than deleting it, and then gives the harder version: keep company only with someone who keeps your secret, hides your faults, stands by you in trouble, spreads the good about you and folds away the bad. And if you cannot find him, keep company with nobody but yourself." },
    ],
    distinction: ["Two ways to decide who to be close to", "From the aim", "Name what you want the friendship to do, and the qualities to look for follow from it.", "From a list of virtues", "Which produces a standard nobody meets — as the joke about 'Alqama's son points out."],
    misreading: "The list is not a filter for rejecting people. Ghazali includes the joke about it being impossible, and the practical instruction that comes with it is Umar's: put your friend's behaviour in the best light until you cannot.",
    reflection: "Ask what you actually want from your closest friendship, and then whether you have ever chosen on that basis.",
    audit: ["What is this friendship for?", "Would I have chosen differently knowing that?", "Whose religion am I picking up?", "Do I read my friends generously or narrowly?"],
    nodes: ["ukhuwwa", "sohba", "din"],
    model: chain("How the conditions get set", "The order runs one way, and most advice reverses it.", [["Name the aim", "What do you want the friendship to do?", "support"], ["The conditions follow", "A condition is just what is needed to reach the aim.", "support"], ["Then the qualities", "Which is why a bare list of virtues produces nobody.", "balance"]]),
  }),
  makeChapter({
    id: 5, shortTitle: "Two hands", formalTitle: "The first right: property",
    overview: "The first right, and its opening image is chosen with unusual care — Ghazali explains why it is the image it is.",
    thesis: "The first right is over property, and the levels are set by what you would actually hand over.",
    moves: [
      { title: "Give the image", body: "The likeness of two brothers is the likeness of two hands, one of which washes the other." },
      { title: "Explain the choice", body: "He likened them to two hands and not to a hand and a foot, because the two hands cooperate toward a single purpose." },
      { title: "Apply it", body: "So two brothers: their brotherhood is complete only when they accompany one another toward a single aim — so that they are, in one respect, like a single person." },
      { title: "Draw the consequence", body: "This requires sharing in ease and in hardship, partnership in outcome and in circumstance, and the lifting of exclusive possession and of self-preference." },
      { title: "Note the precision of the image", body: "The image is chosen with unusual care and he says so. Two hands, not a hand and a foot — because the two hands work together at one task, and a hand and a foot do not. Which means the likeness is not about closeness or about serving each other; it is about a shared object. Two people are brothers on this account when they are going the same way, and it is the shared direction rather than the mutual affection that makes them, in one respect, a single person." },
      { title: "Follow what that requires", body: "And the consequences drawn are correspondingly hard. Sharing in ease and in hardship — both, not the second only. Partnership in what happens and in how things stand. And then the two phrases that do the work: the lifting of exclusive possession, and of preferring oneself. Neither is a feeling. Both describe a settled arrangement about property and priority, which is why the next section can grade the tie by how far into that arrangement two people have actually gone." },
    ],
    closer: [
      { title: "Why the image is argued rather than asserted", body: "Two hands and a hand and a foot are both pairs that work together. What separates them is that the hands do the same work toward the same end, and Ghazali spends a sentence on the difference — which turns a familiar simile into a claim about what a friendship is for." },
      { title: "The condition it smuggles in", body: "Brotherhood is complete only when the two accompany one another toward a single aim. That is a condition on the bond, not a description of it, and it means a friendship with no shared direction is incomplete by definition." },
    ],
    distinction: ["Two pairs that work together", "Two hands", "Doing the same work toward the same end, which is the likeness chosen.", "A hand and a foot", "Cooperating, but not toward one purpose — which is why it was not chosen."],
    misreading: "Do not take the sharing as merely generous. What the image requires is the lifting of exclusive possession, which is a stronger claim than generosity with what remains yours.",
    reflection: "Ask what single aim you and your closest friend are actually accompanying each other toward.",
    audit: ["Do we share an aim?", "Or only company?", "Is possession lifted, or shared?", "Which pair are we?"],
    nodes: ["mal", "huquq", "ukhuwwa"],
    model: pair("Why two hands", "The difference is the argument.", [["Same end", "Which makes the two in one respect a single person.", "support"], ["Merely cooperating", "A hand and a foot, which was available and not chosen.", "balance"]]),
  }),
  makeChapter({
    id: 6, shortTitle: "Three ranks", formalTitle: "How far the sharing goes",
    overview: "The right of property is graded into three, and the anecdote attached to the lowest of them is one of the sharpest in the Ihya.",
    thesis: "Three levels of sharing, from meeting a need out of your surplus to not dividing what is yours from what is his.",
    moves: [
      { title: "Give the lowest", body: "At the lowest level you treat your friend roughly as you would someone who works for you: you meet his need out of what you happen to have spare." },
      { title: "Give the counsel attached to it", body: "Abu Hazim said: if you have a friend for God's sake, do not do business with him. Ghazali says he meant a friend at this level." },
      { title: "Give the anecdote", body: "A man came to the house of one he had made a brother and said: I need four thousand of your wealth. The man said: take two thousand." },
      { title: "Give the response", body: "He turned away from him and said: you preferred the world to God. Were you not ashamed to claim brotherhood in God and then say this?" },
      { title: "Note where the lowest level is set", body: "The lowest rank is set with deliberate plainness: you meet his need out of your surplus, roughly as you would for somebody in your employ. That is not offered as a failure. It is a real rank of the tie, and most friendships live there. What the ranking does is stop a person at that level from imagining he has the thing the highest level describes — and it gives the anecdote that follows something to be a contrast with." },
      { title: "Take Abu Hazim's counsel seriously", body: "And the advice not to do business with a friend, which Ghazali reads as applying at this level specifically, is shrewder than it looks. At the lowest rank the property boundary is intact — what is his is his, and what is yours is yours. A transaction puts that boundary under pressure at exactly the point where neither party has agreed to dissolve it, and the friendship is what gets damaged when the deal goes badly. The counsel protects the tie by keeping it out of the arena it is least equipped for." },
      { title: "Read the exchange over the four thousand", body: "And the exchange is severe because the offer was generous. A man asks for four thousand and is offered two — half, immediately, without argument, from a friend who could presumably have refused entirely. The reply is that this is preferring the world to God, and that the claim of brotherhood should have made him ashamed. The point is not that half is stingy. It is that a division was made at all, and at the rank being claimed there was supposed to be nothing left to divide." },
    ],
    closer: [
      { title: "What the anecdote actually charges", body: "Not meanness — half of what was asked was given. The charge is that the claim of brotherhood in God had been made, and that the offer measured what the friendship was worth against something else. The refusal is of the accounting rather than of the amount." },
      { title: "How the grading protects the reader", body: "He pins that advice to the lowest level specifically, which means “don't mix friendship with business” is aimed at one case rather than offered as a general rule. Knowing which level a friendship is at is what makes the advice usable at all." },
    ],
    distinction: ["Two ways to refuse a request", "By what is left over", "Meeting a need out of what you have spare — the lowest of the three levels.", "By an accounting", "Weighing the friendship against the sum, which is what the anecdote refuses."],
    misreading: "Do not read the anecdote as requiring anyone to hand over four thousand. What is being judged is a claim that had already been made about the relationship, not the sum itself.",
    reflection: "Ask what level your friendships would come out at if you graded them purely on what has actually been asked for and actually given.",
    audit: ["Which rank is this?", "Have I met a need from surplus only?", "What claim have I made about it?", "Am I refusing an amount or an accounting?"],
    nodes: ["mal", "darajat", "ithar"],
    model: spectrum("Three ranks of sharing", "The lowest carries its own counsel.", [["Out of surplus", "The brother placed at the rank of a servant.", "balance"], ["As an equal", "Sharing rather than supplying.", "support"], ["Undivided", "Which the next section describes.", "support"]]),
  }),
  makeChapter({
    id: 7, shortTitle: "My shoe", formalTitle: "The highest rank",
    overview: "The top of the three ranks, given by a verse and then by a detail of speech that is more demanding than the verse.",
    thesis: "At the highest level the word 'mine' has gone — and the test Ghazali reports for it is a shoe.",
    moves: [
      { title: "Give the verse", body: "The highest level is what the Quran describes the believers with: their affairs are settled by consultation between them, and they spend out of what We have given them." },
      { title: "Give the reading", body: "Meaning that they were mixed together in their properties, none of them distinguishing his own baggage from another's." },
      { title: "Give the detail", body: "One of them would not keep company with anybody who said “my shoe.”" },
      { title: "Note what the detail tests", body: "Not generosity but grammar. The possessive is the last place a division survives after everything has been shared, and the test reaches it." },
      { title: "See what the verse is being read to say", body: "The reading of the verse is the strong move here. Their affairs settled by consultation, and spending out of what We have given them — read as describing people whose properties had been run together to the point where none of them could pick out his own baggage from another's. That is a considerably more concrete claim than the verse is usually taken to make, and it gives the highest rank a definite content rather than leaving it as an intensity of feeling." },
      { title: "Note what the test about the shoe reaches", body: "And the detail is the sharpest thing in the chapter because it tests grammar rather than generosity. A man who would not keep company with anybody who said my shoe is not measuring what people give away; he is listening for where the division survives after everything has nominally been shared. The possessive is the last thing to go, and it goes without anybody deciding to keep it — which is why it makes a better test than any amount of counting what was handed over." },
    ],
    closer: [
      { title: "Why the shoe rather than something valuable", body: "Nobody notices a claim over a shoe, which is precisely why it works as a test. Someone who has actually stopped dividing things up never produces the word; someone who has divided them in principle will produce it over something trivial before anything else." },
      { title: "The relation to the anecdote before it", body: "The man who offered two thousand had done arithmetic. The man who says “my shoe” has done grammar. Same division underneath — but the second is harder to spot and much harder to fake." },
    ],
    distinction: ["Two places a division shows", "In an amount", "Refusing part of what was asked, which is visible and can be argued about.", "In a word", "The possessive over something worthless, which nobody notices and which nobody can fake."],
    misreading: "Do not treat this as a rule about speech. The point is diagnostic: the word is evidence of a division, and removing the word without removing the division would be an affectation the eighth right forbids.",
    reflection: "Listen to yourself for an hour and count the possessives.",
    audit: ["What do I say my about?", "Would I notice?", "Is the division real or verbal?", "Which is harder to fake?"],
    nodes: ["ithar", "mal", "ukhuwwa"],
    model: pair("Two tests of one division", "The second cannot be performed.", [["The amount", "Visible, arguable, and easy to justify.", "balance"], ["The word", "Over a shoe, unnoticed, and not fakeable.", "support"]]),
  }),
  makeChapter({
    id: 8, shortTitle: "Before being asked", formalTitle: "The second right: the person",
    overview: "The right of the person, and its distinctive clause is about timing rather than about effort.",
    thesis: "The second right is help in person, given before it is asked for and put ahead of your own business.",
    moves: [
      { title: "Give the right", body: "Help with the person, in the fulfilling of needs and the undertaking of them." },
      { title: "Give the clause", body: "The undertaking of them before being asked." },
      { title: "Say why that matters", body: "A need met on request is a favour granted; a need met before the request is a burden never taken up. The second spares the friend the asking, which is the part that costs him." },
      { title: "Give the ordering", body: "The giving of them precedence over one's own needs, which is what places this right above ordinary helpfulness." },
      { title: "Note what the clause about asking removes", body: "The clause is short and it changes the whole right. Undertake his needs before he asks — which means the duty is to notice, not to respond. A need met on request has already cost the friend something before anything was given: he had to work out whether to ask, and then ask, and then be in the position of somebody who was helped. Meeting it first cancels all of that, and it is the only version of help that leaves him nothing to carry." },
      { title: "See where the precedence clause puts this", body: "And then the second clause raises it past ordinary helpfulness: his needs come before your own. Not instead of them, and not as a general disposition of kindness — before them, in order, when both are live and only one can be met. That is what distinguishes this right from being a good sort of person, and it is why it sits second, immediately after the property right whose highest rank had already dissolved the boundary between whose need is whose." },
    ],
    closer: [
      { title: "The cost the clause removes", body: "Book 14 argued at length that asking a person about his affairs is itself a harm — a tearing of a covering. This right removes the parallel cost from the other side: a friend who does not have to ask is spared the exposure that asking involves." },
      { title: "Why anticipation rather than generosity", body: "Generosity is measured by what is given. This right is measured by when, and the earlier it happens the less the friend has had to reveal about his own need — which makes it a right about dignity as much as about help." },
    ],
    distinction: ["Two ways to meet a need", "Before the asking", "Which spares the friend the exposure of having to ask.", "On request", "Which meets the need and leaves the cost of the asking with him."],
    misreading: "Do not read this as requiring omniscience. It requires attention — noticing what a friend has not said — which is a different demand from guessing.",
    reflection: "Ask when you last had to ask a friend for something, and what the asking cost you.",
    audit: ["Do I wait to be asked?", "What have I noticed and not acted on?", "What does asking cost them?", "Whose needs come first?"],
    nodes: ["nafs", "huquq", "sitr"],
    model: chain("Three levels of help", "The right is at the third.", [["When asked", "The need met, and the asking already paid for.", "balance"], ["Before asking", "Which spares the friend the exposure.", "support"], ["Before your own", "Given precedence, which is what makes it a right.", "support"]]),
  }),
  makeChapter({
    id: 9, shortTitle: "Silence", formalTitle: "The third right: the tongue, by keeping still",
    overview: "The longest of the eight, and it is a catalogue of things not said — including several that would be said out of interest rather than malice.",
    thesis: "The third right is silence: about his faults, in his absence, and in front of him.",
    moves: [
      { title: "Give the first item", body: "That he be silent about mentioning his faults, in his absence and in his presence — rather that he feign ignorance of them." },
      { title: "Give the second", body: "That he be silent about contradicting him in what he says, and not dispute with him or argue him down." },
      { title: "Give the third", body: "That he be silent about spying and about asking after his circumstances." },
      { title: "Give the fourth", body: "If he sees him on a road or on an errand, that he not open with him by asking his purpose — where he has come from and where he is going — and not ask him about it; for perhaps mentioning it is heavy on him, or he would need to lie about it." },
      { title: "Note what the four silences have in common", body: "The four are all refusals to use information. Do not mention his faults — and go further, act as though you had not noticed them. Do not contradict him or argue him down. Do not go looking into how he is placed. And do not ask, when you meet him on the road, where he is coming from or going. Each removes something a person would ordinarily feel entitled to: to be honest about a fault, to be right in an argument, to know what a friend is doing." },
      { title: "Take the fourth silence seriously", body: "And the last is the most finely judged. Not asking a friend where he is going sounds like indifference until the reason is given: mentioning it may be heavy for him, or he may find himself needing to lie. So the question is not intrusive in itself — it is a question that forces a choice, and the friend will pay for it either by disclosing something he would rather not or by saying something false. Declining to ask spares him a cost the asker would never have seen." },
    ],
    closer: [
      { title: "The reason attached to the fourth", body: "Or he would need to lie about it. The instruction is not only that the question is intrusive but that it manufactures an occasion for a friend to be untruthful — so the harm of the question includes what it does to the person answering." },
      { title: "How it connects to the previous book", body: "Book 14 argued that asking about a person's affairs is a tearing of a covering, and forbidden without doubt in the ordinary case. This right applies the same principle inside a friendship, where the temptation to ask is warmest and the excuse of concern is readiest." },
    ],
    distinction: ["Two reasons a question is wrong", "It intrudes", "The covering torn, which is the harm to the one asked.", "It manufactures a lie", "Putting a friend in a position where the easy answer is untrue."],
    misreading: "Do not read the silence about faults as dishonesty. The next right requires speech, and the two are stated as one right in two directions — what is forbidden is exposure, not truthfulness.",
    reflection: "Recall the last time you asked a friend where he had been, and why you asked.",
    audit: ["What do I ask out of interest?", "Have I put someone in a position to lie?", "Do I contradict as a habit?", "Which of the four do I fail?"],
    nodes: ["lisan", "sitr", "huquq"],
    model: spectrum("Four silences", "Each is something a friend would notice.", [["About faults", "In his absence and his presence, feigning ignorance.", "support"], ["About contradicting", "Not disputing or arguing him down.", "support"], ["About his affairs", "No spying and no asking after his circumstances.", "support"], ["About his errand", "Which he may find heavy, or need to lie about.", "warning"]]),
  }),
  makeChapter({
    id: 10, shortTitle: "And speech", formalTitle: "The fourth right: the tongue, by speaking",
    overview: "The same organ, the opposite instruction — and the pairing is what makes the two rights more than a rule about tact.",
    thesis: "The fourth right reverses the third — there are things friendship requires you to say, and staying quiet fails it.",
    moves: [
      { title: "State the pairing", body: "For brotherhood, as it requires silence about what is disliked, requires also speech about what is loved." },
      { title: "Note what that rules out", body: "A friend who is merely discreet has satisfied one right and failed the other. Withholding is not the whole of what the tongue owes." },
      { title: "Give the content", body: "The right covers the saying of what pleases him, the acknowledging of what is good in him, and the speaking of it in his absence as in his presence." },
      { title: "Note the symmetry", body: "The third right forbids mentioning faults behind his back. The fourth requires mentioning virtues behind his back. Both are about what is said when he cannot hear it." },
      { title: "Note why discretion alone fails", body: "The pairing is the point of the fourth right, and it corrects the usual picture of a good friend. Discretion satisfies the third right entirely — a man who says nothing damaging has met that obligation in full. And he has failed a separate one, because brotherhood requires speech about what is loved as much as silence about what is disliked. Withholding is half the duty of the tongue, and the half that costs nothing." },
      { title: "See what the symmetry across absence establishes", body: "And the two rights are aimed at the same place: what is said when he is not there. The third forbids mentioning his faults behind his back, the fourth requires mentioning his virtues behind his back. Which means the test of both is conducted in rooms the friend will never enter, and neither can be satisfied by conduct in his presence. That is a demanding standard and it is also a checkable one, which is the character of the whole chapter." },
    ],
    closer: [
      { title: "Why two rights and not one", body: "Stated as a single rule about the tongue, it would collapse into being careful. Split in two, it becomes two separate failures, and most people fail the second — a person who never speaks ill of a friend and never speaks well of him has kept half of what he owes." },
      { title: "The test the pairing supplies", body: "What is said about him when he is absent, in both directions. That is one observable behaviour answering two rights, and it is not available to self-report — other people know the answer better than you do." },
    ],
    distinction: ["Two duties of one organ", "Silence", "About faults, disputes, and his affairs.", "Speech", "About what is good in him, said where he cannot hear it."],
    misreading: "Do not read the fourth as flattery. It concerns what is true and good and would otherwise go unsaid, and it is owed in his absence, where flattery has no purchase.",
    reflection: "Ask what you have said about your closest friend in the last month when he was not there.",
    audit: ["What do I say in his absence?", "Have I kept only the silence?", "Is anything good going unsaid?", "Who knows the answer better than I do?"],
    nodes: ["lisan", "huquq", "ukhuwwa"],
    model: pair("The same organ, both directions", "Most people keep only the first.", [["Silence", "About what is disliked, in absence and presence.", "support"], ["Speech", "About what is loved, in absence as in presence.", "support"]]),
  }),
  makeChapter({
    id: 11, shortTitle: "Slips, and fidelity", formalTitle: "The fifth, sixth, and seventh rights",
    overview: "Three rights of the heart, and the first of them is sorted before it is prescribed.",
    thesis: "The fifth, sixth and seventh rights cover slips, prayer, and loyalty that outlasts the person.",
    moves: [
      { title: "Give the fifth", body: "Pardoning slips and lapses. And a friend's lapse is either in his religion, or in what concerns you — and the two are treated differently." },
      { title: "Give the sixth", body: "Supplication for the brother in his life and after his death, with everything he loves for himself and for his family and for everything connected to him." },
      { title: "Note what the sixth extends", body: "After his death, and to his family. The right does not end with the person and does not stop at him, which is what distinguishes it from goodwill." },
      { title: "Give the seventh", body: "Fidelity and sincerity. And the meaning of fidelity is constancy in love and its continuance until death — and after death, with those he leaves behind." },
      { title: "Note why the fifth splits the lapse in two", body: "Pardoning slips is qualified immediately, and the qualification matters: a lapse is either in his religion or in what concerns you, and the two are handled differently. A wrong done to you is yours to forgive, and forgiving it costs nobody but you. A failing in his religion is not an injury to you at all, which means pardoning is not the operation it calls for — that belongs to a different duty, treated in the book on enjoining right, and the distinction keeps friendship from becoming a licence to overlook." },
      { title: "Take the reach of the sixth and seventh", body: "And the last two extend past the person in the same direction. Supplication continues after his death and covers his family and everything attached to him. Fidelity means constancy in love until death, and afterwards toward those he leaves behind. Both are constructed so the obligation outlives the man — which is what separates a tie of this kind from goodwill, since goodwill has nothing to attach to once its object is gone." },
    ],
    closer: [
      { title: "Why the sixth and seventh both reach past death", body: "A tie that ends when a person does was a convenience. Both of these rights are defined by what continues when nothing further can be received, which is the sharpest available test of whether the bond was for his sake." },
      { title: "The sorting in the fifth", body: "A lapse in religion and a lapse against you are different failures needing different responses, and Ghazali separates them before saying anything about pardon. It is the same method as everywhere in the Ihya: sort the case, then prescribe." },
    ],
    distinction: ["Two kinds of lapse", "In his religion", "Which concerns him and is not an offence against you.", "Against you", "Which is what pardon in the ordinary sense addresses."],
    misreading: "Do not read fidelity as mere persistence. It is defined as constancy in love, which is a state rather than a habit of contact, and it is required to continue where contact cannot.",
    reflection: "Ask what you still owe someone who has died.",
    audit: ["Which kind of lapse am I holding?", "Do I pray for anyone who cannot know?", "What continues after death?", "Was the tie for his sake?"],
    nodes: ["afw", "dua", "wafa"],
    model: chain("Three rights of the heart", "Two of them reach past death.", [["Pardon", "Sorted first: a lapse in religion, or against you.", "support"], ["Supplication", "In life and after death, and for his family.", "support"], ["Fidelity", "Constancy in love, and with those he leaves behind.", "support"]]),
  }),
  makeChapter({
    id: 12, shortTitle: "Lightening", formalTitle: "The eighth right",
    overview: "The last of the eight, and it is the only one that consists entirely in not doing something to a friend.",
    thesis: "The eighth right is to make yourself light: to drop the ceremony that turns a friendship into an obligation.",
    moves: [
      { title: "Give the right", body: "Lightening, and the leaving of affectation and imposition — that he not burden his brother with what is hard on him." },
      { title: "Note the two halves", body: "Affectation is what you do to yourself on his behalf; imposition is what you ask of him. The right forbids both, and they are the two ways a friendship becomes expensive." },
      { title: "Say what it protects", body: "The ease of the tie. A friendship that costs either party effort to maintain will be maintained until it is not, and the eighth right is aimed at the maintenance cost rather than at the affection." },
      { title: "Note the pattern", body: "It is Book 11's instruction about guests — do not burden yourselves for the guest, so that you come to dislike him — applied to a standing relationship rather than to an occasion." },
      { title: "Separate the two halves of the eighth right", body: "The distinction between the two halves is the useful part. Affectation is what you put yourself through on his behalf — the effort, the preparation, the standard you hold yourself to when he is coming. Imposition is what you ask of him. Both make the tie expensive, from opposite ends, and either will eventually be resented. Forbidding both means the maintenance cost of the friendship is itself a duty to keep low." },
      { title: "See why this is the last right", body: "And it belongs last because it governs everything before it. Seven rights have just been enumerated, several of them demanding — property, precedence, constancy past death — and a reader could reasonably close the chapter resolved to be an exhausting friend. The eighth is the correction: whatever is done must be done in a way that neither party has to brace for. It is the same instruction given to hosts in the book on eating, applied to a relationship that has no end date rather than to an evening." },
    ],
    closer: [
      { title: "Why it comes last", body: "The seven rights before it are demands. Ending on a right that forbids making demands is what keeps the list from producing the very burden it would otherwise create, and it is placed where a reader has just finished reading seven things he owes." },
      { title: "The mechanism it shares with Book 11", body: "There, effort undertaken for a guest produces dislike of the guest. Here, effort undertaken for a friend does the same. In both cases the fault is located where the burden is assumed, not where the feeling appears." },
    ],
    distinction: ["Two ways a friendship becomes expensive", "Affectation", "What you take on for his sake, which produces resentment of him.", "Imposition", "What you ask of him, which produces the same in the other direction."],
    misreading: "Do not read this as licensing indifference. It comes after seven rights that are demanding, and what it forbids is the ceremony around them rather than the substance of them.",
    reflection: "Ask which of your friendships costs you effort to maintain, and what the effort is spent on.",
    audit: ["What do I take on for them?", "What do I ask of them?", "Which friendship is expensive?", "Where does the burden get assumed?"],
    nodes: ["takalluf", "huquq", "ukhuwwa"],
    model: pair("Two halves of the eighth right", "Both make a friendship expensive.", [["Affectation", "What you do to yourself on his behalf.", "warning"], ["Imposition", "What you require of him.", "warning"]]),
  }),
  makeChapter({
    id: 13, shortTitle: "The unchosen", formalTitle: "The third chapter: the wider ties",
    overview: "The last chapter turns to relationships nobody selected, and the question it asks is how to live with people you are simply connected to.",
    thesis: "The third chapter turns to claims nobody chose — the Muslim, kin, the neighbour, and those you own.",
    moves: [
      { title: "Name the ties", body: "The right of the Muslim, of kin, of the neighbour, and of ownership — and how to live with those who are connected by these causes." },
      { title: "Note what they share", body: "None of them is chosen. A person acquires them by being born somewhere, living somewhere, or belonging to something, and the rights follow from the connection rather than from any decision." },
      { title: "Note how they are defined", body: "By comparison with the eight. What a neighbour or a kinsman is owed is established against what a chosen brother is owed, so the second chapter has to come first." },
      { title: "Note the phrase", body: "How to live with those connected by these causes. The chapter is about coexistence rather than about intimacy, which is a different subject and gets a different treatment." },
      { title: "Note what the unchosen ties have in common", body: "The four ties in this chapter share the feature that nobody selected them. You are born to kin, you live beside a neighbour, you belong to a community, you have people in your household. None of it involved a decision, and none of it can be undone by one — which is exactly the opposite of the contract the previous chapter described, where a basis was chosen and a person assessed before the tie was formed." },
      { title: "See why the second chapter had to come first", body: "And that is why the eight rights had to be established before this chapter could exist. What a neighbour or a kinsman is owed is defined by measuring against what a chosen brother is owed — less in some respects, differently in others, and the comparison is what makes the amounts statable at all. Without the enumeration, the rights of the unchosen ties would have no scale to be read against." },
      { title: "Take the word the chapter uses", body: "And the phrase the chapter is built on is how to live with those connected by these causes, which is a lower and more realistic aim than the second chapter's. Not intimacy, not brotherhood — coexistence, with people you did not pick and cannot return. That is the harder problem in most lives, and it is significant that the book treats it last, after establishing what a tie looks like when everything about it has gone right." },
    ],
    closer: [
      { title: "Why the unchosen ties need their own chapter", body: "The eight rights presuppose a bond formed on a ground and accompanied toward an aim. None of that is available with a neighbour, and yet something is owed — so the content has to be derived rather than transferred." },
      { title: "Where the quarter goes next", body: "Book 16 treats seclusion: whether to have these ties at all. Having spent a book establishing what companionship costs and what it is worth, the natural next question is whether a person is better off without it — and Ghazali answers it the way he answered marriage." },
    ],
    distinction: ["Two kinds of tie", "Chosen", "Formed on a ground, accompanied toward an aim, and owed eight rights.", "Given", "Acquired by living somewhere or being born to someone, and owed something derived."],
    misreading: "Do not assume the unchosen ties owe less because they are unchosen. The chapter exists to establish what they do owe, and proximity generates real claims in it.",
    reflection: "Count the people you are connected to and did not choose, and notice how many of them you have never thought of as owed anything.",
    audit: ["Whom have I not chosen?", "What do they claim?", "Is this coexistence or intimacy?", "What comes next in the quarter?"],
    nodes: ["jiwar", "rahim", "suhba"],
    model: spectrum("Four unchosen ties", "Each generates a claim without a decision.", [["The Muslim", "The widest, owed by the connection itself.", "balance"], ["Kin", "By birth, and not revocable.", "support"], ["The neighbour", "By proximity alone.", "support"], ["Ownership", "By what a person holds and who is held by it.", "balance"]]),
  }),
];

export const book15ConceptNodes: ConceptNode[] = [
  ["ukhuwwa", "Brotherhood", "A contract", "A bond between two persons, like the contract of marriage between spouses."],
  ["structure", "Three chapters", "Outward from the chosen", "The fullest bond first, and the wider ties defined against it."],
  ["suhba", "Companionship", "Its rights enumerated", "Eight, distributed across property, person, tongue, and heart."],
  ["shurut", "Conditions", "A bond can be examined", "Formed on a ground, which someone claiming it can be asked about."],
  ["darajat", "Degrees", "Not one standard", "Two true brotherhoods can owe different amounts."],
  ["aqd", "The contract", "Makes failure nameable", "Warmth alone leaves a person free to feel well of himself while doing nothing."],
  ["huquq", "Eight rights", "Determinate content", "Which is what makes a friendship auditable at all."],
  ["mal", "Property", "Two hands", "Cooperating toward one purpose, which is why the image was chosen."],
  ["ithar", "Self-preference lifted", "Tested by a word", "One who would not keep company with anyone who said: my shoe."],
  ["nafs", "The person", "Before being asked", "Which spares a friend the exposure that asking involves."],
  ["sitr", "The covering", "Torn by asking", "The same principle as Book 14, applied inside a friendship."],
  ["lisan", "The tongue", "Two rights, opposed", "Silence about faults, and speech about what is good — both in absence."],
  ["afw", "Pardon", "Sorted first", "A lapse in his religion and a lapse against you are different failures."],
  ["dua", "Supplication", "Past death", "For him and for his family, where nothing further can be received."],
  ["wafa", "Fidelity", "Constancy in love", "Continuing to death, and after it with those he leaves behind."],
  ["takalluf", "Affectation", "The eighth right", "What you take on for his sake, which produces resentment of him."],
  ["jiwar", "The neighbour", "Owed without a choice", "Proximity generating a claim that no decision created."],
  ["rahim", "Kin", "By birth", "A tie acquired rather than formed, and not revocable."],
].map(([id, label, kicker, description], index) => ({ id, label, kicker, description, position: ["left", "right", "top", "bottom"][index % 4] }));

const node = (id: string, label: string, micro: string, summary: string, guardrail: string, chapterId: number, glyph: Journey["nodes"][number]["glyph"]): Journey["nodes"][number] => ({ id, label, micro, summary, guardrail, chapterId, glyph });

export const book15Journeys: Journey[] = [
  {
    id: "what-is-owed", number: "01", question: "Is a friendship something you can fail?", title: "Make it a contract",
    description: "Take the sentence that places brotherhood beside marriage, the map of eight rights it produces, and the image Ghazali argues for rather than asserts.",
    payoff: "You get a friendship with determinate content, and a condition most friendships do not meet.",
    image: assetUrl("assets/system/book15-two-hands.jpg"), imageAlt: "Two identical work gloves laid side by side on a bench, both worn in the same places.", minutes: 12, color: "#278d91",
    nodes: [
      node("three-rings", "See the three rings", "Outward from the chosen", "The fullest bond first; the wider ties defined against it.", "The last covers everyone you did not choose.", 1, "order"),
      node("graded", "Note the grading", "Not one standard", "Conditions and degrees come before any rights are listed.", "Which is what stops the eight being a uniform demand.", 2, "balance"),
      node("a-contract", "Take the sentence", "Like the contract of marriage", "A bond with rights that must be fulfilled.", "Which makes failing a friend nameable.", 3, "know"),
      node("eight", "Take the map", "Four registers", "Property, person, tongue, heart — eight rights across them.", "Distributed unevenly on purpose.", 3, "pattern"),
      node("why-hands", "Note the argument", "Not a hand and a foot", "Two hands, because they work toward the same end.", "A familiar simile turned into a claim.", 5, "clear"),
      node("one-aim", "Take the condition", "Toward a single aim", "Brotherhood is complete only when the two accompany each other so.", "A condition, not a description.", 5, "diagnose"),
    ],
  },
  {
    id: "how-far", number: "02", question: "How far does this actually go?", title: "Follow one right to the top",
    description: "Take the three ranks of sharing, the anecdote that refuses an accounting rather than an amount, and the test that cannot be performed.",
    payoff: "You get a way of placing your own friendships that does not depend on what you feel about them.",
    image: assetUrl("assets/system/book15-my-shoe.jpg"), imageAlt: "A single pair of worn sandals set at a doorway among several other pairs, indistinguishable from them.", minutes: 11, color: "#bf7a35",
    nodes: [
      node("lowest", "Take the lowest rank", "Out of surplus", "The brother placed at the rank of a servant.", "Abu Hazim's counsel is attached to this rank only.", 6, "know"),
      node("the-four-thousand", "Take the anecdote", "Take two thousand", "And he turned away: you preferred the world to God.", "Half was given; the charge is not meanness.", 6, "witness"),
      node("the-accounting", "Find the charge", "An accounting, not an amount", "The friendship was weighed against a sum.", "The refusal is of the weighing.", 6, "diagnose"),
      node("the-verse", "Take the highest", "None distinguishing his baggage", "Mixed together in their properties.", "Described of the believers, not prescribed.", 7, "receive"),
      node("the-word", "Take the test", "My shoe", "One who would not keep company with anyone who said it.", "Grammar rather than generosity.", 7, "clear"),
      node("cannot-fake", "Note why it works", "Nobody notices it", "Which is exactly why it cannot be performed.", "Removing the word without the division is affectation.", 7, "steady"),
    ],
  },
  {
    id: "tongue-and-burden", number: "03", question: "What do I owe when nothing is happening?", title: "Take the quiet rights",
    description: "Follow the two rights of the tongue pulling in opposite directions, the rights that reach past death, and the one that forbids making demands.",
    payoff: "You leave with one observable test that answers two rights, and a diagnosis for the friendships that feel like work.",
    image: assetUrl("assets/system/book15-empty-chair.jpg"), imageAlt: "Two chairs at a table with one occupied place setting and one empty, the empty place still laid.", minutes: 12, color: "#c25f50",
    nodes: [
      node("four-silences", "Take the silences", "Including the interested ones", "Faults, contradiction, spying, and where he has been.", "Not only the malicious questions.", 9, "clear"),
      node("or-lie", "Note the reason", "Or he would need to lie", "The question manufactures an occasion for untruth.", "The harm includes what it does to the one answering.", 9, "diagnose"),
      node("and-speech", "Take the other half", "Speech about what is loved", "The same organ, the opposite instruction.", "Most people keep only the silence.", 10, "balance"),
      node("in-absence", "Find the test", "What is said when he is out", "One behaviour answering both rights.", "Not available to self-report.", 10, "witness"),
      node("past-death", "Note what continues", "And with those he leaves", "Supplication and fidelity both reach past death.", "The sharpest test of whom the bond was for.", 11, "steady"),
      node("lightening", "Take the last right", "Do not make it expensive", "Affectation on your side, imposition on his.", "Placed last, after seven demands.", 12, "guard"),
    ],
  },
];

export const book15Movements: TaxonomyGroup[] = [
  ["bab1", "1. The excellence of brotherhood", "Its conditions, degrees and benefits — and who is worth having one with.", [1, 2, 3, 4]],
  ["bab2", "2. The rights of companionship", "A contract with eight rights across property, person, tongue, and heart.", [5, 6, 7, 8, 9, 10, 11, 12]],
  ["bab3", "3. The wider ties", "The Muslim, kin, the neighbour, and ownership — claims nobody chose.", [13]],
].map(([id, label, description, chapterIds], index) => ({ id, label, description, chapterIds, color: ["#bf7a35", "#278d91", "#c25f50"][index % 3] })) as TaxonomyGroup[];

export const book15Instrument: Instrument = {
  title: "Eight rights, and one friendship",
  note: "Ghazali says the contract of brotherhood is a bond like the contract of marriage, and that it carries eight rights across property, person, the tongue, and the heart. Take one friendship you actually have — a real person, not friendship in general — and answer for it.",
  items: [
    {
      id: "friend", label: "One friendship you have", lede: "A particular person, and how things actually stand",
      note: "The first question is the book's own framing, which decides whether failing a friend is even a coherent idea. The second groups his eight rights into four. Note that two of the eight are the same organ pulling in opposite directions, and that the last of them forbids making demands.",
      axes: [
        {
          id: "kind", kicker: "The framing", question: "What do you take this friendship to be?",
          options: [
            { id: "contract", label: "Something with obligations I could fail", note: "The book's own claim: a bond like the contract of marriage." },
            { id: "affection", label: "An affection — we are simply close", note: "Which cannot be audited, and can coexist with failing someone." },
            { id: "aim", label: "We are going somewhere together", note: "His condition on complete brotherhood: accompanying toward a single aim." },
            { id: "unsure", label: "I have never framed it either way", note: "Which is the ordinary case, and what the second chapter is written for." },
          ],
        },
        {
          id: "right", kicker: "The eight rights", question: "Which of them is hardest for you here?",
          options: [
            { id: "mal", label: "Property and help — what it costs me", note: "The first two rights, of which the first is graded into three ranks." },
            { id: "lisan", label: "What I say, and what I do not", note: "The third and fourth: silence about faults, speech about what is good." },
            { id: "qalb", label: "Pardoning, praying, staying constant", note: "The fifth, sixth, and seventh, two of which reach past death." },
            { id: "khafif", label: "Keeping it easy — it has become work", note: "The eighth: affectation on your side, imposition on his." },
          ],
        },
      ],
      verdicts: [
        { key: "affection|*", name: "Then nothing can be failed", role: "warning", chapterId: 3, body: "The book's opening move on this is deliberate: the contract of brotherhood is a bond between two persons, like the contract of marriage between spouses — and as marriage entails rights that must be fulfilled, so does this. Held as an affection, a friendship has no content that can be discharged or failed.", action: "The effect of the contract language is not coldness but specificity. Warmth alone leaves a person free to feel well of himself while doing nothing, and eight enumerated rights make it possible to say exactly where a friend has been let down. Read the eight and see which of them you would not have thought of as owed." },
        { key: "aim|mal", name: "You have named his condition", role: "support", chapterId: 5, body: "This is exactly the condition Ghazali builds into the first right, and he argues for it rather than asserting it: two brothers are likened to two hands and not to a hand and a foot, because the hands cooperate toward a single purpose — so brotherhood is complete only when the two accompany one another toward one aim.", action: "Which means the rights are not a burden added to the friendship but the content of what you are already doing. The one to check is the right of the person: help undertaken before being asked, which spares your friend the exposure that asking involves — and given precedence over your own needs, which is what raises it above ordinary helpfulness." },
        { key: "*|khafif", name: "The right placed last", role: "balance", chapterId: 12, body: "The eighth right is lightening, and the leaving of affectation and imposition — that he not burden his brother with what is hard on him. It has two halves: what you take on for his sake, and what you ask of him, and both are how a friendship becomes expensive.", action: "Ghazali places it after seven demanding rights, and it is Book 11's warning about guests applied to a standing relationship: effort undertaken for someone produces dislike of them, and the fault sits where the burden is assumed rather than where the feeling appears. Ask what specifically you have taken on, and whether he asked for it." },
        { key: "*|lisan", name: "Two rights, not one", role: "balance", chapterId: 10, body: "The third right is silence — about his faults in his absence and his presence, about contradicting him, about spying and asking after his circumstances, and about where he has been, since perhaps mentioning it is heavy on him or he would need to lie about it. The fourth is the opposite: brotherhood requires speech about what is loved as it requires silence about what is disliked.", action: "Most people keep the first and fail the second, and a person who never speaks ill of a friend and never speaks well of him has kept half of what he owes. The test answers both at once and is not available to self-report: what is said about him when he is not there. Other people know your answer better than you do." },
        { key: "*|mal", name: "Which of three ranks", role: "balance", chapterId: 6, body: "The right of property is graded, which is what keeps it usable. The lowest rank is that you place your brother at the rank of a servant, meeting his need out of your surplus — and Abu Hazim's counsel not to deal with a brother in worldly affairs is attached to that rank specifically, not offered as a general rule.", action: "The anecdote is worth sitting with, because the charge in it is not meanness: a man asked for four thousand, was offered two, and turned away saying — were you not ashamed to claim brotherhood in God and then say this. Half was given. What was refused was the accounting, not the amount, and the question it puts is what claim you have already made about the relationship." },
        { key: "*|qalb", name: "Two of these reach past death", role: "support", chapterId: 11, body: "Supplication for the brother in his life and after his death, with everything he loves for himself and his family; and fidelity, which is constancy in love and its continuance until death — and after it, with those he leaves behind. Both are defined by what continues when nothing further can be received.", action: "That is also the sharpest test available of whom the bond was for. And note that pardon is sorted before it is prescribed: a lapse in his religion and a lapse against you are different failures, and only the second is what pardon ordinarily means. Establish which one you are holding before deciding what to do with it." },
        { key: "*|*", name: "Read the framing with the right", role: "balance", chapterId: 3, body: "How you hold the friendship, and where it is hardest. The book's claim is that the two are connected: a friendship held as an affection has no determinate content, so nothing about it can be located, and the difficulty stays a mood.", action: "Take the framing first, since it decides whether the second question has an answer. Then work the eight in his order — property, person, silence, speech, pardon, supplication, fidelity, lightening — and notice which of them you had not previously thought of as something owed." },
      ],
    },
  ],
};

export const book15Sources: SourceLink[] = [
  { label: "Primary Arabic text", note: "The complete public Arabic of Book 15 was read and used to establish the three chapters, the framing of brotherhood as a contract, the eight rights, and the ranks of sharing property.", url: "https://shamela.ws/book/9472/517" },
  { label: "Brotherhood as a contract", note: "The passage opening the second chapter, placing the contract of brotherhood beside the contract of marriage and mapping the eight rights across four registers.", url: "https://shamela.ws/book/9472/533" },
  { label: "The right of property", note: "The passage giving the image of the two hands, the reason it is not a hand and a foot, and the three ranks of sharing.", url: "https://shamela.ws/book/9472/533" },
  { label: "The tongue, by silence", note: "The passage cataloguing what is not said — faults, contradiction, spying, and asking after a friend's errand.", url: "https://shamela.ws/book/9472/536" },
  { label: "The tongue, by speech", note: "The passage requiring speech about what is loved as the previous right requires silence about what is disliked.", url: "https://shamela.ws/book/9472/540" },
  { label: "Fidelity and lightening", note: "The passages on constancy in love continuing past death, and on the leaving of affectation and imposition.", url: "https://shamela.ws/book/9472/547" },
  { label: "The wider ties", note: "The third chapter, on the right of the Muslim, of kin, of the neighbour, and of ownership, and how to live with those connected by them.", url: "https://shamela.ws/book/9472/553" },
  { label: "Forty-book structure", note: "Ghazali.org's listing places Book 15 as the fifth book of the Quarter of Customs and confirms its title.", url: "https://www.ghazali.org/listing-the-forty-books/" },
];

export const book15: SystemBook = {
  id: 15,
  title: "The Etiquette of Companionship",
  shortTitle: "Companionship",
  defaultJourneyId: "what-is-owed",
  chapters: book15Chapters,
  conceptNodes: book15ConceptNodes,
  journeys: book15Journeys,
  sources: book15Sources,
  taxonomy: {
    title: "Three chapters, three rings",
    note: "Ghazali's own three, moving outward from the closest tie to the widest. Eight of the thirteen reading sections belong to the second, which enumerates eight rights and is what makes a friendship into something that can be audited.",
    groups: book15Movements,
  },
  instrument: book15Instrument,
  editorialNote: "The three journeys, thirteen reading sections, visual models, and diagnostic are editorial learning aids. The sections follow Ghazali's three chapters in his order and are grouped under them in the movements list. The English is an original synthesis made from a reading of the public Arabic text, not a translation and not a substitute for one. Reports and inherited anecdotes are presented as material Ghazali transmitted; this edition does not independently grade every narration. Two matters of scope. The second chapter treats each of the eight rights at length, with extensive supporting material — reports, verses, and stories of the early Muslims — and this edition presents each right, the arguments Ghazali makes for it, and the passages where his reasoning is distinctive, rather than reproducing that supporting material. The anecdotes carried here, including the exchange over four thousand dirhams and the man who would not keep company with anyone who said 'my shoe', are given as reports of what particular people did and said; they illustrate a rank rather than setting a requirement, and Ghazali's own grading of the right of property into three ranks is what governs how they should be read. The third chapter, on the rights of kin, neighbours, and those connected by ownership, addresses a social order with arrangements — including forms of ownership over persons — that differ fundamentally from a modern reader's; this edition presents what the chapter covers and how its rights are derived, and reproduces none of its counsel. The diagnostic applies his own framing and his own eight rights to a friendship the reader supplies and cannot pronounce on anyone's relationships.",
};
