import { assetUrl } from "./assetUrl";
import type { Chapter, ConceptNode, VisualModel } from "./data";
import type { Instrument, Journey, SourceLink, SystemBook, TaxonomyGroup } from "./systemTypes";

type Seed = { id: number; shortTitle: string; formalTitle: string; overview: string; moves: Array<{ title: string; body: string }>; closer: Array<{ title: string; body: string }>; distinction: [string, string, string, string, string]; misreading: string; reflection: string; audit: string[]; nodes: string[]; model: VisualModel };
const bab = (id: number) => (id === 1 ? "the first chapter" : id <= 7 ? "the second and third chapters" : id <= 9 ? "the third chapter" : id <= 12 ? "the fourth chapter" : id <= 14 ? "the fifth chapter" : id === 15 ? "the sixth chapter" : "the seventh chapter");
const makeChapter = (seed: Seed): Chapter => ({
  id: seed.id, shortTitle: seed.shortTitle, formalTitle: seed.formalTitle, overview: seed.overview,
  points: seed.moves.slice(0, 3).map((m) => m.body), reflection: seed.reflection, relatedNodes: seed.nodes, visualModel: seed.model,
  deep: { thesis: seed.moves[0].body, context: seed.overview, moves: seed.moves, closeReading: seed.closer,
    distinction: { title: seed.distinction[0], firstLabel: seed.distinction[1], first: seed.distinction[2], secondLabel: seed.distinction[3], second: seed.distinction[4] },
    misreading: seed.misreading, observation: seed.reflection, selfAudit: seed.audit,
    sourceAnchor: `Book 1, ${bab(seed.id)}, ${seed.formalTitle}.` },
});
const chain = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "chain", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const pair = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "pair", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const spectrum = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "spectrum", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });

export const book01Chapters: Chapter[] = [
  makeChapter({
    id: 1, shortTitle: "Why it begins here", formalTitle: "The excellence of knowledge, teaching, and learning",
    overview: "The first book of the Ihya, and its placement is an argument. Ghazali opens the whole forty-book work not with belief and not with prayer but with the question of what is worth knowing.",
    moves: [
      { title: "Gather the testimony", body: "The verses and reports on the excellence of knowledge, of learning, and of teaching are assembled at length, each of the three treated separately, and the chapter closes with the rational evidence rather than the transmitted alone." },
      { title: "Note what the praise does not settle", body: "None of it establishes which knowledge is meant. The book's next six chapters are almost entirely occupied with that question, and several of them are unsparing about the answers being given in his own time." },
      { title: "Set the book's real subject", body: "Ghazali's concern is not that knowledge is undervalued but that the word has been captured. Three of the seven chapters are about misidentification, and one is about the people who profit from it." },
      { title: "Place it before everything", body: "The Quarter of Worship follows this book, and the Quarters of Custom, Perils, and Deliverance follow that. Putting the audit of knowledge before the acts of worship makes every later book conditional on getting this one right." },
    ],
    closer: [
      { title: "The shape of the seven chapters", body: "Excellence; the two obligations; what people wrongly count as religious knowledge; the blights of disputation; the etiquette of student and teacher; the blights of the scholars; and the intellect. Only the first and last are uncontroversial, and the five between them are a sustained critique." },
      { title: "Who the book is written against", body: "Not the ignorant. The sixth chapter, which is by far the longest, is devoted to distinguishing the scholars of the hereafter from the scholars of this world, and Ghazali says plainly whom he means by the second." },
    ],
    distinction: ["Two ways to open a revival", "With the audit of knowledge", "Asking what is worth knowing before prescribing anything, which is the order Ghazali chose.", "With the acts of worship", "Beginning at practice, which would leave the capture of the word unexamined."],
    misreading: "Do not take the opening chapter's warmth as the book's mood. It is the shortest analytic stretch in the book, and what follows is the most sustained criticism of scholars in the Ihya.",
    reflection: "Ask why a work meant to revive religion begins with a fight about a word.",
    audit: ["What did I expect this book to be?", "What does its placement claim?", "Whom is it written against?", "Which of the seven chapters do I need?"],
    nodes: ["ilm", "structure"],
    model: chain("Where the book sits", "Everything after it is conditional on it.", [["Knowledge", "What is worth knowing, audited first.", "support"], ["Worship", "The acts, which the next nine books treat.", "balance"], ["Custom, Perils, Deliverance", "The remaining three quarters, all of them presupposing the audit.", "balance"]]),
  }),
  makeChapter({
    id: 2, shortTitle: "Twenty parties", formalTitle: "The knowledge that is an individual obligation",
    overview: "One of the sharpest observations in the Ihya, and it is made almost in passing. Ghazali surveys the answers to a famous question and notices what they all have in common.",
    moves: [
      { title: "Put the question", body: "Seeking knowledge is an obligation upon every Muslim. People differed about which knowledge that is, and split over it into more than twenty parties." },
      { title: "Give the verdict on all of them", body: "He declines to reproduce the detail, and says the upshot is that every group placed the obligation on the knowledge it happens to be occupied with." },
      { title: "Name the parties", body: "The theologians said it is theology, since by it unity is grasped. The jurists said it is jurisprudence, since by it the acts of worship and the lawful and unlawful are known. The exegetes and traditionists said it is the Book and the Sunna, since by them all sciences are reached." },
      { title: "Include the fourth", body: "The Sufis said it was their own subject. Some meant knowing your own state and where you stand; some meant knowing sincerity, the faults of the self, and how to tell the angel's prompting from the devil's; and some meant inward knowledge, obligatory only on the particular people who work at it — which, Ghazali notes, quietly drops the word “every” out of the report." },
    ],
    closer: [
      { title: "Why the observation lands", body: "Each answer is defensible on its own, and the reasons given for them are real reasons. What convicts them is the pattern: the answers vary exactly with the answerer's occupation, which is a fact about the scholars rather than about the question." },
      { title: "What it does not conclude", body: "He does not say any of them are wrong that their subject matters, and he says later that the Sufi answer is true for someone who has taken that work on. What he rejects is the generalising — the move all twenty make." },
    ],
    distinction: ["Two ways to answer the question", "From the obligation", "Working out what a person must do and therefore must know, which is the next chapter.", "From your field", "Naming your own science as the obligation, which is what Ghazali says all twenty parties did."],
    misreading: "Do not read this as anti-intellectual. Ghazali held every one of these sciences in some regard and wrote in several of them; what he is diagnosing is a specific and very human error about scope.",
    reflection: "Ask what you would have answered, and whether your answer happens to be what you already study.",
    audit: ["Which party would I have joined?", "Is that what I already do?", "What reason did I have that was not that?", "Whose answer have I dismissed?"],
    nodes: ["fard-ayn", "ilm", "parties"],
    model: spectrum("Four answers, one pattern", "Each is the answerer's own field.", [["Theology", "Because by it unity is grasped.", "balance"], ["Jurisprudence", "Because by it the lawful and unlawful are known.", "balance"], ["Book and Sunna", "Because by them all the sciences are reached.", "balance"], ["The inward", "The states of the heart, sincerity, and the soul's blights.", "balance"]]),
  }),
  makeChapter({
    id: 3, shortTitle: "The act and its time", formalTitle: "What the individual obligation actually covers",
    overview: "Ghazali's own answer, and it is startlingly deflationary. The obligation is indexed to circumstance and expands only as circumstance does.",
    moves: [
      { title: "Give the rule", body: "This is the truth about the knowledge that is an individual obligation, and its meaning is the knowledge of how the obligatory act is performed. Whoever knows the obligatory act and the time at which it becomes obligatory has known the knowledge that is an individual obligation." },
      { title: "Work the examples", body: "At the time of a prayer, learn that prayer. If he lives to Ramadan, the obligation to learn the fast is renewed by it: that its time is from dawn to sunset, that what is required is intention and abstaining, and that it runs to the sighting of the crescent or two witnesses." },
      { title: "Give the sharpest case", body: "If he acquires wealth, he must learn the alms due on it — and not at once, but at the completion of the year. And if he owns nothing but camels, he is obliged to learn nothing but the alms of camels, and likewise for each category." },
      { title: "Extend it to circumstance", body: "If this Muslim were a merchant, and dealing in usury had become widespread in the town, it would become obligatory on him to learn how to guard against usury. The obligation follows the situation rather than the syllabus." },
    ],
    closer: [
      { title: "How the answer disposes of the twenty parties", body: "It does not refute any of them. It reframes the question so that the answer cannot be a field at all: what is owed is a function of what you are about to do, so two people with different lives owe different knowledge, and neither owes a discipline." },
      { title: "The remark about creed", body: "Ghazali notes that the Prophet was satisfied, from the rough Arabs, with assent and acknowledgement, without their learning any proof. What is individually obligatory in belief is therefore the two testimonies and their meaning, and not the demonstrations that the theologians' answer would require." },
    ],
    distinction: ["Two ways to size the obligation", "By what you must do", "The act, and the time it falls due, and nothing beyond either.", "By what a field contains", "A body of learning to be worked through, which no example in the chapter supports."],
    misreading: "Do not read the minimalism as discouraging study. The chapter is about what is obligatory, and Ghazali spends most of the book on what is worth pursuing well beyond that.",
    reflection: "List what you will actually have to do this month, and ask what you would need to know to do it correctly.",
    audit: ["What falls due for me this month?", "Do I know how it is performed?", "Have I sized the obligation by a field?", "Which category do I actually own?"],
    nodes: ["fard-ayn", "occasion", "parties"],
    model: chain("Indexed to circumstance", "The obligation arrives when the occasion does.", [["An act falls due", "A prayer time, a Ramadan, a year completed on wealth.", "support"], ["Learn how it is done", "Its manner and its time, which is the whole of what is owed.", "support"], ["And no further", "Own only camels, and only the alms of camels are obligatory.", "balance"]]),
  }),
  makeChapter({
    id: 4, shortTitle: "And the Perils too", formalTitle: "The obligatory knowledge of the heart",
    overview: "The passage that justifies the existence of the Ihya, and it is stated as a legal claim rather than as an exhortation.",
    moves: [
      { title: "Grant the Sufi answer, with a condition", body: "What the Sufis said about telling the enemy's suggestions from the angel's prompting is true too — for someone who has taken that work on. The concession is precise, and it is not a brush-off." },
      { title: "Then generalise a different part of it", body: "Since it is usually the case that a person is not free of the motives of evil, of showing off, and of envy, it becomes incumbent on him to learn from the science of the Quarter of Perils whatever he sees himself to need." },
      { title: "Ground it in the report", body: "How should it not be obligatory, when it was said that three things destroy: avarice obeyed, whim followed, and a man's admiration of himself — and no human being is free of them." },
      { title: "Draw the legal conclusion", body: "The other bad states of the heart — pride, conceit and the rest of that family — follow from these three, and getting rid of them is required of everyone individually. You cannot get rid of them without knowing what they are, what causes them, how they show, and how they are treated. Somebody who cannot recognise a fault walks into it." },
    ],
    closer: [
      { title: "The sentence that indicts everyone", body: "Most of what we have mentioned in the Quarter of Perils is among the individual obligations, and people have all abandoned them, occupying themselves with what does not concern them. A quarter of his own work is here classified as obligatory knowledge that nobody is learning." },
      { title: "Why the argument is airtight on its own terms", body: "Removing the three destroyers is agreed to be obligatory. The treatment of a thing is meeting its cause with its opposite. That is impossible without knowing the cause. Therefore the knowledge is obligatory. Nothing in the chain depends on anyone's view of what counts as a religious science." },
    ],
    distinction: ["Two kinds of obligatory knowledge", "Of the act", "How a prayer or a fast is performed, which the previous chapter established.", "Of the heart", "The limits, causes, signs, and treatment of what destroys, which follows from the duty to remove it."],
    misreading: "Do not read this as making the whole Quarter of Perils compulsory reading. Ghazali's phrase is what a person sees himself to need, which indexes it to the reader exactly as the previous chapter indexed the acts.",
    reflection: "Take one of the three destroyers and ask whether you could state its causes and its treatment.",
    audit: ["Could I state the causes of one of them?", "Which do I see myself needing?", "Have I treated this as optional?", "What am I occupied with instead?"],
    nodes: ["fard-ayn", "muhlikat", "qalb"],
    model: chain("Four steps to an obligation", "None of the steps depends on a view about the sciences.", [["Removing them is obligatory", "Agreed, and grounded in the report about the three destroyers.", "support"], ["Treatment is by the opposite", "Meeting a cause with its contrary.", "support"], ["Which needs the cause known", "Limits, causes, signs, and treatment.", "support"], ["So the knowledge is obligatory", "And is what Ghazali says everyone has abandoned.", "warning"]]),
  }),
  makeChapter({
    id: 5, shortTitle: "The cupper", formalTitle: "The knowledge that is a communal obligation",
    overview: "The most surprising passage in the book to a modern reader, and Ghazali knows it will be. He anticipates the objection in the middle of the paragraph.",
    moves: [
      { title: "Give the criterion", body: "A communal obligation is a body of knowledge that ordinary life cannot run without. These are the subjects where, if a town had nobody doing them, the town would be in trouble — and if one person does it, that covers it and the obligation lifts from everyone else." },
      { title: "Give the two examples", body: "Such as medicine, since it is necessary for the need of the survival of bodies; and arithmetic, since it is necessary in transactions and in the division of bequests and inheritances." },
      { title: "Anticipate the objection", body: "So do not be astonished at our saying that medicine and arithmetic are among the communal obligations — for the foundations of the crafts are also among the communal obligations." },
      { title: "Give the list", body: "Agriculture, weaving, and governance; indeed cupping and tailoring. For if a town were empty of a cupper, destruction would hasten to its people, and they would be in difficulty by exposing themselves to it." },
    ],
    closer: [
      { title: "What the criterion is doing", body: "It is entirely functional. Nothing about the dignity of a craft enters it; what enters is whether the town can do without it. On that test tailoring qualifies and a good deal of what was taught in the schools of his day does not, which is the point of the sentence about astonishment." },
      { title: "The theological ground he gives", body: "He adds that whoever sent the illness sent the cure and pointed us to it. The duty to practise medicine comes from the cure having been provided, not from the standing of doctors." },
    ],
    distinction: ["Two ways to rate a trade", "By what the town cannot do without", "Which puts cupping and tailoring among the religious obligations of a community.", "By its standing among the learned", "Which would exclude every one of the examples Ghazali gives."],
    misreading: "Do not read this as merely permitting worldly work. It classifies farming, weaving, tailoring, and cupping as obligations that a community sins by leaving unfilled, which is a stronger claim than permission.",
    reflection: "Ask what your town could not do without, and who is currently doing it.",
    audit: ["What could my town not do without?", "Do I rank crafts by dignity?", "Whose work am I discounting?", "Is anything here unfilled?"],
    nodes: ["fard-kifaya", "dunya", "ilm"],
    model: spectrum("What the criterion admits", "It is functional from end to end.", [["Medicine", "Necessary for the survival of bodies.", "support"], ["Arithmetic", "Necessary for transactions and inheritance.", "support"], ["Agriculture and weaving", "Foundations of the crafts, and equally obligations.", "support"], ["Cupping and tailoring", "Named explicitly, and destruction hastens without them.", "support"]]),
  }),
  makeChapter({
    id: 6, shortTitle: "Where the line falls", formalTitle: "Revealed and unrevealed knowledge",
    overview: "The division that organises the whole chapter, and its definition of a revealed science is negative and unusually clean.",
    moves: [
      { title: "Give the division", body: "The sciences, relative to the purpose in hand, divide into revealed and unrevealed." },
      { title: "Define the first", body: "By revealed I mean what is gained from the prophets, and to which the intellect does not guide, as it guides to arithmetic; nor experience, as it guides to medicine; nor hearing, as it guides to language." },
      { title: "Sort the second", body: "The sciences that are not revealed divide into praised, blamed, and permitted. The praised are those to which the welfare of worldly matters is connected, such as medicine and arithmetic." },
      { title: "Sort the praised again", body: "Those divide into what is a communal obligation and what is an excellence rather than an obligation. The double division is what allows the previous chapter's list and this chapter's warnings to sit in one scheme." },
    ],
    closer: [
      { title: "Why the definition is negative", body: "A revealed science is identified by what does not reach it: not reason, not experiment, not linguistic transmission. That leaves the category small and sharp, and it means most of what is taught under religious headings is not, on this definition, revealed knowledge at all." },
      { title: "The permitted class", body: "The third class is easy to overlook and does real work. It leaves a large space of knowledge that is neither obligatory nor blameworthy, which is what stops the scheme from requiring every hour of study to be justified." },
    ],
    distinction: ["Two ways a science can be religious", "By its source", "Gained from the prophets, and unreachable by reason, experience, or language.", "By its subject", "Concerning religious matters, which would admit most of what the fourth chapter attacks."],
    misreading: "Do not assume the revealed sciences are the praised ones and the rest are tolerated. Medicine and arithmetic are unrevealed and are communal obligations, and the following chapters blame several things taught as religious.",
    reflection: "Take the last thing you studied and ask which of the four boxes it falls in.",
    audit: ["Where does my study fall?", "Is it religious by source or by subject?", "What do I place in the permitted class?", "Have I justified every hour?"],
    nodes: ["ilm", "fard-kifaya", "shariyya"],
    model: pair("The first cut", "Defined by what cannot reach it.", [["Revealed", "From the prophets; not reason, not experience, not language.", "support"], ["Unrevealed", "Praised, blamed, or permitted, and the praised split again.", "balance"]]),
  }),
  makeChapter({
    id: 7, shortTitle: "How much is enough", formalTitle: "The praised measure of the praised sciences",
    overview: "A short chapter that keeps the scheme from becoming a licence, and it makes its case with an analogy to the body.",
    moves: [
      { title: "Give the three classes", body: "Knowledge in this respect is of three kinds: one blamed in its little and its much; one praised in its little and its much, and the more of it the better and more excellent; and one of which the measure of sufficiency is praised while going beyond it and exhausting it is not." },
      { title: "Give the analogy", body: "Like the states of the body. Some of them are praised in little and much, such as health and beauty. Some are blamed in little and much, such as ugliness and bad character." },
      { title: "Give the third state", body: "Some of them are such that moderation in them is what is praised, as with the giving of wealth — for extravagance is not praised in it, and it is still giving." },
      { title: "Note what the third class does", body: "It creates a category of genuinely good knowledge that a person can nevertheless pursue too far, which none of the preceding divisions allows for and which the following chapters need." },
    ],
    closer: [
      { title: "Why extravagance is the right comparison", body: "Extravagance is not a different act from giving; it is the same act past its measure, and nobody would defend it by pointing out that giving is praised. The analogy pre-empts exactly the defence that a scholar in the third class would want to make." },
      { title: "Where this bites in the book", body: "The following chapters criticise deep specialisation in rare legal cases and in the techniques of disputation. Neither is blamed as such; both are placed in the third class, which is a milder and much harder charge to answer." },
    ],
    distinction: ["Two ways to criticise a study", "As blamed in itself", "Bad in little and in much, which is the easiest charge to answer and rarely the one Ghazali makes.", "As past its measure", "Good up to sufficiency and not beyond, which is the charge in the following chapters."],
    misreading: "Do not read the third class as a call for shallowness. Its comparison is extravagance in giving, which presupposes that the thing itself is good and that a measure exists.",
    reflection: "Take a subject you have gone deep in and ask honestly which of the three classes it belongs to.",
    audit: ["Which class is my study in?", "What would sufficiency look like here?", "Am I defending depth by defending the subject?", "Where have I exhausted rather than sufficed?"],
    nodes: ["measure", "ilm", "shariyya"],
    model: spectrum("Three classes", "The third is the one the later chapters use.", [["Blamed throughout", "Bad in little and in much, like ugliness of character.", "warning"], ["Praised throughout", "Better the more of it there is, like health.", "support"], ["Praised to a measure", "Good up to sufficiency, like giving before it becomes extravagance.", "balance"]]),
  }),
  makeChapter({
    id: 8, shortTitle: "The first word", formalTitle: "What was changed of the terms of the sciences: jurisprudence",
    overview: "The famous passage on five captured words. Ghazali argues that the confusion he is attacking is lexical before it is anything else.",
    moves: [
      { title: "Name the mechanism", body: "The source of the confusion of the blamed sciences with the revealed ones is the distortion of praised names, their alteration, and their transfer, by corrupt purposes, to meanings other than what the righteous forebears and the first generation intended." },
      { title: "Name the five", body: "They are five words: jurisprudence, knowledge, unity, reminding, and wisdom. These are praised names, and those qualified by them hold the positions of religion — but they have now been transferred to blamed meanings." },
      { title: "State the consequence", body: "So hearts recoil from blaming anyone who is qualified by those blamed meanings, because of how widely these praised names are applied to them. The capture of the word protects the thing." },
      { title: "Take the first word", body: "With jurisprudence they have acted by specification rather than by transfer: they specified it to knowing rare branches in legal opinions, standing on the fine points of their reasons, multiplying speech about them, and memorising the statements attached to them — so that whoever goes deepest in that is called the most learned." },
    ],
    closer: [
      { title: "Why specification is not the same as transfer", body: "Ghazali is careful here. Nothing false is being said when a specialist in rare cases is called a jurist; the word simply now picks out a narrower thing than it did, and the honour attaching to the wider thing has come along with it. That is a subtler charge than misuse, and harder to rebut." },
      { title: "What the word covered before", body: "In the first generation it named the knowledge of the path of the hereafter, the subtleties of the soul's blights, and what spoils an act — a usage Ghazali documents from the earliest reports rather than asserting." },
    ],
    distinction: ["Two ways a word goes wrong", "By transfer", "Moved to a different meaning, which is what he says happened to the other four.", "By specification", "Narrowed to a part of its range while keeping the honour of the whole, which is what happened to this one."],
    misreading: "Do not read this as an attack on legal expertise. Ghazali was a first-rate jurist himself. His complaint is about what the word has come to pick out, and what comes with that.",
    reflection: "Notice how much of an argument is settled in advance by which word gets to name which thing.",
    audit: ["What does this word select for me?", "What honour comes with it?", "Have I confused a part for the whole?", "Which words in my field have narrowed?"],
    nodes: ["alfaz", "fiqh", "ilm"],
    model: pair("Two mechanisms", "Only one of them involves saying anything false.", [["Transfer", "The word moved to another meaning entirely.", "warning"], ["Specification", "The word narrowed, and the honour of the wider sense came with it.", "warning"]]),
  }),
  makeChapter({
    id: 9, shortTitle: "The other four", formalTitle: "Knowledge, unity, reminding, and wisdom",
    overview: "The remaining four captured words, and the last of them gets the most acid line in the book.",
    moves: [
      { title: "Knowledge", body: "It used to be applied to the knowledge of God, of His signs, and of His acts among His servants and His creation — so much so that when Umar died it was said that the knowledge had gone." },
      { title: "Unity", body: "It has now been made an expression for the craft of theology, for knowing the way of disputation, for encompassing the methods of contradicting opponents, and for the ability to be voluble in it by multiplying questions and raising doubts." },
      { title: "Reminding", body: "The word stands in the verse that says to remind, for the reminder benefits the believers, and many reports praise the assemblies of remembrance — and the name has been taken over by what now passes under it." },
      { title: "Wisdom", body: "The name of the wise has come to be applied to the physician, the poet, and the astrologer — and even to the man who rolls dice on the palms of the peasantry in the streets." },
    ],
    closer: [
      { title: "Why unity is the sharpest case", body: "Of the five, this is the one where the captured word names the thing the whole religion turns on, and where what has taken it is a technique of argument. Ghazali wrote in that technique himself, which is what makes the sentence a self-implicating one rather than a swipe." },
      { title: "The function of the dice-roller", body: "The last example is comic and it is doing work. A word whose range now runs from the physician to a street gambler has stopped selecting anything, and a name that selects nothing can no longer confer or withhold honour — which is the end state the chapter is describing." },
    ],
    distinction: ["Two states a praised word can be in", "Still selecting", "It picks out a definite thing, so calling someone by it says something.", "Emptied", "Its range has widened until it selects nothing, which is where wisdom has arrived."],
    misreading: "Do not treat the list as nostalgia for older usage. The complaint is functional: these words carry authority, and authority attached to the wrong referent misdirects people who are relying on the word to guide them.",
    reflection: "Take the most honoured word in your own field and ask what it currently selects for.",
    audit: ["What does that word select now?", "What did it select before?", "Who benefits from the change?", "Am I relying on a word to do my judging?"],
    nodes: ["alfaz", "tawhid", "hikma"],
    model: spectrum("Four more", "Each carries authority its referent no longer earns.", [["Knowledge", "Once the knowledge of God, His signs, and His acts.", "balance"], ["Unity", "Now the craft of disputation and the raising of doubts.", "warning"], ["Reminding", "The name taken over by what passes under it.", "warning"], ["Wisdom", "Applied to physician, poet, astrologer, and the dice-roller in the street.", "warning"]]),
  }),
  makeChapter({
    id: 10, shortTitle: "Why they turned", formalTitle: "The cause of people's turning to the science of disputation",
    overview: "The fourth chapter opens by asking a historical question rather than a moral one: why this science, and why now.",
    moves: [
      { title: "Put the question historically", body: "Ghazali asks what caused people to turn toward the science of legal disagreement, and answers by tracing changes in patronage, office, and the routes to advancement rather than by attributing it to a decline in piety." },
      { title: "Refuse the flattering comparison", body: "He devotes a section to what he calls the deception in likening these disputations to the consultations of the Companions and the discussions of the forebears, and he treats the comparison as the argument that has to be dismantled first." },
      { title: "Give the test", body: "Look at the disputants of your own day, he says, and see how one of their faces darkens when the truth becomes clear on his opponent's tongue, and how ashamed he is by it, and how he strives to deny it with the utmost of his power." },
      { title: "Close the comparison", body: "Notice how he holds it against the man who silenced him for the rest of his life — and then feels no embarrassment comparing himself to the Companions helping each other get at the truth." },
    ],
    closer: [
      { title: "Why the test is behavioural", body: "The comparison to the forebears is about intention, and intentions cannot be checked. Ghazali replaces it with something observable: what happens to a man's face when his opponent turns out to be right. Anyone can run that test, on himself or on a room." },
      { title: "The conditions he does give", body: "The chapter is not a blanket prohibition. He sets out conditions under which disputation is permitted, among them that a participant not prevent the one helping him to look into the matter from moving from one proof to another and from one difficulty to another, since that is how the forebears' disputations went." },
    ],
    distinction: ["Two ways to test a disputation", "By what happens when you lose", "Whether the truth arriving on the other tongue is welcome, which anyone can observe.", "By the intention behind it", "Which cannot be checked and which is what the flattering comparison appeals to."],
    misreading: "Do not read the chapter as forbidding argument. It gives conditions for permissible disputation and complains that they are not met, which presupposes that meeting them is possible.",
    reflection: "Watch your own face the next time someone you are arguing with turns out to be right.",
    audit: ["What happens to me when I lose?", "Do I welcome the truth from that direction?", "Which condition do I fail?", "Whom have I blamed for silencing me?"],
    nodes: ["munazara", "jah", "ilm"],
    model: pair("Two tests", "One of them can actually be run.", [["The forebears' intention", "Unverifiable, and what the flattering comparison rests on.", "warning"], ["The darkened face", "Observable, immediate, and what Ghazali substitutes.", "support"]]),
  }),
  makeChapter({
    id: 11, shortTitle: "The wine of the inward", formalTitle: "The blights of disputation and what it breeds",
    overview: "The most concentrated attack in the book, and it works by a single analogy that sets the whole scale of the charge.",
    moves: [
      { title: "Name the target precisely", body: "Know and verify that the disputation set up for the purpose of overcoming, of silencing, of showing superiority and eloquence before people, of boasting and wrangling and drawing people's faces toward oneself." },
      { title: "State the charge", body: "It is the wellspring of all the character traits blamed by God and praised by God's enemy." },
      { title: "Give the analogy", body: "It stands to the inward grave sins — pride, conceit, envy, rivalry, self-praise, love of status — the way drinking stands to the visible ones: adultery, slander, killing, theft." },
      { title: "Work the analogy", body: "As one given the choice between drinking and the enormities belittles the drinking and goes to it, and that then calls him in his drunkenness to commit the rest — so one overcome by the love of silencing and of victory is called by it to harbour all the filths in his soul, and it stirs up in him every blamed trait." },
    ],
    closer: [
      { title: "Why the analogy is the argument", body: "It answers the obvious defence, which is that argument is not itself one of the great sins. Ghazali agrees; his claim is about position rather than magnitude. What makes drinking serious is not what it is but what it opens the door to, and that is exactly the charge here." },
      { title: "How he supports it", body: "He goes through the traits one at a time — envy first, with the report that envy consumes good deeds as fire consumes firewood — and shows each one being generated by the conditions of public dispute rather than merely coexisting with it." },
    ],
    distinction: ["Two ways an act can be serious", "By its magnitude", "How bad it is in itself, on which argument scores low and Ghazali does not disagree.", "By its position", "What it reliably opens onto, which is the whole force of the wine comparison."],
    misreading: "Do not extend the charge to disagreement or to inquiry. The target is named in the first sentence and every element of it concerns an audience: overcoming, silencing, display, and drawing faces toward oneself.",
    reflection: "Ask what you actually want from the next argument you are about to have.",
    audit: ["What do I want from this argument?", "Is there an audience in it?", "Which trait does it stir in me?", "Would I still argue with no one watching?"],
    nodes: ["munazara", "muhlikat", "jah"],
    model: chain("Why the position matters", "The magnitude is not the charge.", [["A small thing", "Argument, which nobody counts among the enormities.", "balance"], ["Opening onto", "Pride, conceit, envy, rivalry, self-praise, love of status.", "warning"], ["As drink does", "Onto the outward enormities, which is the comparison's whole force.", "warning"]]),
  }),
  makeChapter({
    id: 12, shortTitle: "What honesty would look like", formalTitle: "The conditions of permitted disputation",
    overview: "The constructive half of the fourth chapter, and it is specific enough to be checked against a real conversation.",
    moves: [
      { title: "Allow movement", body: "Among the conditions is that a participant not prevent the one helping him examine the matter from moving from one proof to another and from one difficulty to another, for so were the disputations of the forebears." },
      { title: "Bar the devices", body: "That there be excluded from his speech all the innovated fine points of wrangling, in what tells for him and against him alike — such as saying that this is not incumbent on me to mention, or that this contradicts your earlier speech and so is not accepted from you." },
      { title: "Give the reason", body: "For returning to the truth is the contrary of falsehood, and accepting it is obligatory. A rule that penalises a person for changing his position is a rule that penalises him for being corrected." },
      { title: "Describe what happens instead", body: "You see whole sessions spent in repulsion and wrangling: an objector says there are meanings besides what you mentioned and I know them and will not mention them, since I am not obliged to; and the one arguing says you must produce what you claim; and the objector insists that he need not." },
    ],
    closer: [
      { title: "The line about the objector", body: "The poor fool does not realise that saying “I know the answer and I am not going to give it, since I am not obliged to” is itself the entire problem. He is using a technicality to dodge the only thing the meeting was for." },
      { title: "Why the conditions are worth having", body: "They convert a complaint about motives into a checklist about conduct. Whether a person is arguing for victory is hidden; whether he permits his opponent to change proof, and whether he uses the devices, is not." },
    ],
    distinction: ["Two ways to treat a change of position", "As a correction", "Returning to the truth, which is obligatory to accept.", "As a concession to be exploited", "A contradiction with earlier speech, which the devices are designed to punish."],
    misreading: "Do not read the conditions as impossible standards. Each is a rule about what you allow the other person to do, and each can be adopted unilaterally in the next conversation you have.",
    reflection: "Notice whether you have ever used a procedural point to avoid answering something.",
    audit: ["Do I let an opponent change proof?", "Have I used the devices?", "Do I punish correction?", "What was this session for?"],
    nodes: ["munazara", "adab", "ilm"],
    model: chain("Three checkable rules", "None of them requires knowing anyone's motive.", [["Allow movement", "From proof to proof and difficulty to difficulty.", "support"], ["Drop the devices", "In what tells for you as much as against you.", "support"], ["Accept correction", "Returning to the truth is obligatory to accept.", "support"]]),
  }),
  makeChapter({
    id: 13, shortTitle: "The prayer of the inmost", formalTitle: "The first duty of the student",
    overview: "The fifth chapter opens with ten duties for the student, and the first is a precondition rather than a practice.",
    moves: [
      { title: "Give the first duty", body: "Clear the low traits and bad qualities out first — because knowledge is the heart's worship, the innermost self's prayer, and how the inside draws near to God." },
      { title: "Give the argument", body: "Just as the prayer your body owes is not valid until the body has been cleaned, the worship the inside owes — building the heart up with knowledge — is not valid until the heart has been cleaned of bad character." },
      { title: "Extend the notion of purity", body: "Religion was built on cleanliness, and it is so inwardly as much as outwardly. The verse that the idolaters are only impure alerts intellects to the fact that purity and impurity are not confined to what the senses reach." },
      { title: "Draw the conclusion", body: "An idolater can have clean clothes and a washed body and still be impure in himself — meaning the inside is filthy. And impurity is just a word for what you keep away from, so inward filth has the stronger claim on being kept away from." },
    ],
    closer: [
      { title: "Why the analogy is legal rather than poetic", body: "The comparison is to a condition of validity. Ritual purity is not a way of being more prepared for prayer; without it there is no prayer. Ghazali is making the same kind of claim about knowledge, which is far stronger than saying a good character helps a student." },
      { title: "The other nine", body: "The remaining duties concern reducing attachments, not being arrogant toward the teacher, avoiding the branches of disagreement early on, not neglecting any praiseworthy science, proceeding in order, and knowing why one is learning what one learns. They are practical where the first is constitutive." },
    ],
    distinction: ["Two things purification could be", "A condition of validity", "As ritual purity is to prayer, without which there is no prayer at all.", "A helpful preparation", "Good character making study easier, which is not the strength of Ghazali's claim."],
    misreading: "Do not conclude that the unpurified should not study. Ghazali is describing what makes the study count as the worship he says it is, not issuing an entry requirement to a classroom.",
    reflection: "Ask what your studying has been for, and whether the answer makes the analogy to prayer intelligible.",
    audit: ["What is my studying an instance of?", "What would invalidate it?", "Am I clean of garment only?", "Which trait would I have to address first?"],
    nodes: ["adab", "taharat", "qalb"],
    model: pair("Two kinds of precondition", "The chapter claims the stronger one.", [["A condition of validity", "No purity, no prayer; the analogy Ghazali actually draws.", "support"], ["A helpful aid", "Good character easing the work, which is the weaker reading.", "balance"]]),
  }),
  makeChapter({
    id: 14, shortTitle: "Four states of wealth", formalTitle: "The duties of the guiding teacher",
    overview: "The chapter on teaching opens with an economic analogy, and it produces both a ranking and one of the most quoted set of images in the Ihya.",
    moves: [
      { title: "Give the analogy", body: "A person has four states in his knowledge, as he has in acquiring wealth. The owner of wealth has a state of gaining, so he is an earner; a state of storing what he gained, so he is free of asking; a state of spending on himself, so he benefits; and a state of giving to others, so he is generous — and that is the noblest of his states." },
      { title: "Apply it", body: "So knowledge is acquired as wealth is acquired. It has a state of seeking; a state of obtaining that frees from asking; a state of insight, which is thought about what is obtained and enjoyment of it; and a state of giving insight, which is the noblest of the states." },
      { title: "Give the images for the one who acts", body: "So whoever knew, acted, and taught is the one called great in the kingdom of the heavens — for he is like the sun, which lights others while being itself alight, and like musk, which perfumes others while being itself fragrant." },
      { title: "Give the images for the one who does not", body: "Somebody who knows and does not act on it is like a ledger that is useful to everyone else and holds no knowledge of its own; like a whetstone that sharpens and cannot cut; like a needle that clothes people and is bare itself; like a wick that gives light while it burns away." },
    ],
    closer: [
      { title: "The verse he quotes", body: "It is only a wick that was kindled: it gives light to people while it burns. The image is the sharpest of the four because it grants the benefit entirely — the light is real and reaches others — and locates the loss in the one producing it." },
      { title: "The first duty that follows", body: "Compassion toward the learners, and that he treat them as his own children. Placing it first, immediately after an analogy about wealth and generosity, gives the whole chapter its direction: teaching is the giving state, and the disposition proper to giving is the one required." },
    ],
    distinction: ["Two ways to hold knowledge", "As the sun and musk", "Lighting and perfuming others while being alight and fragrant oneself.", "As the wick and the whetstone", "Really benefiting others while being consumed or unable to cut."],
    misreading: "Do not read the second set of images as saying such teaching is worthless. Every one of them grants that others are genuinely benefited, which is what makes them warnings rather than dismissals.",
    reflection: "Ask which of the four states you spend most of your time in.",
    audit: ["Which state am I in?", "Do I light or do I burn?", "Have I mistaken storing for having?", "What would giving look like here?"],
    nodes: ["adab", "muallim", "amal"],
    model: chain("Four states", "The last is named the noblest.", [["Gaining", "Seeking and acquiring, as an earner does.", "balance"], ["Storing", "Obtaining enough to be free of asking.", "balance"], ["Using", "Insight: thought about what is held, and enjoyment of it.", "support"], ["Giving", "Giving insight to others, which is the noblest of the states.", "support"]]),
  }),
  makeChapter({
    id: 15, shortTitle: "Two knowledges", formalTitle: "The signs of the scholars of the hereafter and the evil scholars",
    overview: "By a wide margin the longest chapter in the book, and the fiercest sustained passage in the Ihya about a class of people.",
    moves: [
      { title: "State why the chapter exists", body: "Severe warnings have come concerning the evil scholars, showing that they are the most severely punished of creation on the Day of Resurrection. So among the great and important matters is knowing the signs that distinguish the scholars of this world from the scholars of the hereafter." },
      { title: "Define the term", body: "By the scholars of this world we mean the evil scholars, whose aim from knowledge is the enjoyment of the world and reaching status and rank among its people. The definition is by aim rather than by doctrine or by competence." },
      { title: "Give the central distinction", body: "Knowledge is of two kinds: knowledge on the tongue, and that is God's proof against His creation; and knowledge in the heart, and that is the beneficial knowledge." },
      { title: "Give the warnings", body: "The most severely punished of people on the Day of Resurrection is a scholar whom God did not benefit by his knowledge. A man is not a scholar until he acts by his knowledge. And: do not learn knowledge to vie with the scholars by it, nor to dispute with the foolish by it, nor to turn people's faces toward you." },
    ],
    closer: [
      { title: "The force of the first kind", body: "Knowledge on the tongue is not called useless. It is called God's proof against His creation, which means it still functions — as evidence, and against the one carrying it. That is a heavier thing to say than that it is empty." },
      { title: "Why the definition is by aim", body: "Nothing in the definition concerns being wrong. A scholar of this world may be entirely correct in what he teaches, and the chapter still applies to him; the sorting is done by what the knowledge was sought for, which is why the signs that follow are almost all behavioural." },
    ],
    distinction: ["Two knowledges", "In the heart", "The beneficial knowledge, which is what the chapter's signs test for.", "On the tongue", "God's proof against His creation, which is functioning and is not in the carrier's favour."],
    misreading: "Do not use the chapter to sort other people. Every sign in it is stated as something a person can check in himself, and the Ihya's standing guard is that the inward state of another is not available.",
    reflection: "Read the three prohibitions in the last report and ask honestly which of them you have done.",
    audit: ["What did I seek this knowledge for?", "Is mine on the tongue or in the heart?", "Have I vied, disputed, or drawn faces?", "Am I using this chapter on someone else?"],
    nodes: ["ulama-akhira", "jah", "amal"],
    model: pair("Sorted by aim, not by accuracy", "A scholar of this world may be entirely correct.", [["Of the hereafter", "Knowledge in the heart, and acted upon.", "support"], ["Of this world", "Sought for enjoyment, status, and rank among the world's people.", "warning"]]),
  }),
  makeChapter({
    id: 16, shortTitle: "One name, four meanings", formalTitle: "The intellect, its nobility, its reality, and its divisions",
    overview: "The closing chapter, and it ends the book the way the book began: by showing that a dispute is really about a word.",
    moves: [
      { title: "Diagnose the disagreement", body: "People differed over the definition of the intellect and its reality, and most of them were unaware that this name is applied to different meanings — and that became the cause of their disagreement." },
      { title: "Give the resolution", body: "The truth that lifts the covering here is that the intellect is a name applied by sharing to four meanings, as the word for an eye is applied to several things. And what is of this kind should not have one definition sought for all its divisions; each division should be disclosed separately." },
      { title: "Give the first meaning", body: "The attribute by which a human being is separated from the rest of the animals, and by which he is made ready to receive theoretical knowledge and to manage the hidden crafts of thought. It is what al-Muhasibi meant in calling the intellect an instinct by which the perception of theoretical knowledge is made ready — as though a light cast into the heart." },
      { title: "Defend it", body: "Whoever denied this and reduced the intellect to necessary knowledge alone was not fair, for the heedless and the sleeping are called possessors of intellect on account of this instinct being in them, despite the absence of the knowledge." },
    ],
    closer: [
      { title: "The parallel he draws", body: "As life is an instinct by which the body is made ready for voluntary motion and sense perception, so the intellect is an instinct by which some animals are made ready for theoretical knowledge. The comparison is what makes the instinct sense of the word defensible rather than merely asserted." },
      { title: "How the book closes on its own method", body: "The first chapters showed that five praised words had been captured, and this one shows that a philosophical disagreement was really four meanings under one name. The Ihya opens by arguing that a great deal of confusion in religion is confusion about words, and it ends the same book by demonstrating it on a case with no polemical stake." },
    ],
    distinction: ["Two ways to settle a definitional dispute", "By separating the senses", "Recognising one name over several meanings and defining each apart.", "By finding one definition", "Seeking a single account that covers all uses, which Ghazali says is the error itself."],
    misreading: "Do not read the four meanings as four faculties. It is one word doing four jobs, in the way the word for an eye does several, and Ghazali says so explicitly.",
    reflection: "Notice how many arguments you have had that were four meanings under one name.",
    audit: ["Which sense am I using?", "Have I sought one definition for all?", "Where else does this pattern hold?", "What dispute of mine is lexical?"],
    nodes: ["aql", "alfaz", "ilm"],
    model: pair("Where the disagreement was", "The same method as the book's opening chapters.", [["Four meanings", "One name applied by sharing, each to be disclosed apart.", "support"], ["One definition sought", "Which Ghazali names as the cause of the whole dispute.", "warning"]]),
  }),
];

export const book01ConceptNodes: ConceptNode[] = [
  ["ilm", "Knowledge", "A captured word", "The Ihya opens by arguing that the confusion is lexical before it is anything else."],
  ["structure", "Seven chapters", "Five of them critical", "Excellence, the obligations, the misidentified, disputation, etiquette, the scholars, the intellect."],
  ["fard-ayn", "Individual obligation", "The act and its time", "Indexed to circumstance, and expanding only as circumstance does."],
  ["parties", "Twenty parties", "Each naming its own field", "The answers vary exactly with the answerer's occupation."],
  ["occasion", "The occasion", "What makes it due", "Own only camels and only the alms of camels are obligatory."],
  ["muhlikat", "The three destroyers", "Nobody is free of them", "Avarice obeyed, whim followed, and admiration of oneself."],
  ["qalb", "The heart", "Where the obligation lands", "Its blamed states cannot be removed without knowing their causes."],
  ["fard-kifaya", "Communal obligation", "What the town needs", "Medicine, arithmetic, farming, weaving, tailoring, and cupping."],
  ["dunya", "Worldly welfare", "A religious category", "Sciences the standing of worldly affairs depends on are obligations."],
  ["shariyya", "Revealed knowledge", "Defined negatively", "Not reached by reason, by experience, or by linguistic transmission."],
  ["measure", "The measure", "Praised to a point", "Like giving wealth, which becomes extravagance past its measure."],
  ["alfaz", "The five words", "Praised names captured", "Jurisprudence, knowledge, unity, reminding, and wisdom."],
  ["fiqh", "Jurisprudence", "Narrowed, not moved", "Specified to rare branches while keeping the honour of the wider sense."],
  ["tawhid", "Unity", "The sharpest case", "Now an expression for the craft of disputation and the raising of doubts."],
  ["hikma", "Wisdom", "Emptied", "Applied to physician, poet, astrologer, and the dice-roller in the street."],
  ["munazara", "Disputation", "The wine of the inward", "Blamed by position rather than by magnitude."],
  ["jah", "Status", "The aim being diagnosed", "What the evil scholars are defined by seeking."],
  ["adab", "Etiquette", "Ten duties each", "For the student and for the teacher, the first of each being constitutive."],
  ["taharat", "Purification", "A condition of validity", "As ritual purity is to prayer, not as preparation is to work."],
  ["muallim", "The teacher", "The giving state", "The noblest of the four states, and the first duty is compassion."],
  ["amal", "Acting on it", "The sorting test", "A man is not a scholar until he acts by his knowledge."],
  ["ulama-akhira", "Two kinds of scholar", "Sorted by aim", "One may be entirely correct and still be a scholar of this world."],
  ["aql", "The intellect", "One name, four meanings", "The disagreement dissolves once the senses are separated."],
].map(([id, label, kicker, description], index) => ({ id, label, kicker, description, position: ["left", "right", "top", "bottom"][index % 4] }));

const node = (id: string, label: string, micro: string, summary: string, guardrail: string, chapterId: number, glyph: Journey["nodes"][number]["glyph"]): Journey["nodes"][number] => ({ id, label, micro, summary, guardrail, chapterId, glyph });

export const book01Journeys: Journey[] = [
  {
    id: "what-must-i-know", number: "01", question: "What am I actually obliged to know?", title: "Size the obligation honestly",
    description: "Watch twenty parties answer a famous question and all make the same mistake, then take Ghazali's own answer, which is indexed to your circumstances rather than to a field.",
    payoff: "You get a rule you can apply to this month, and one claim that indicts almost every reader.",
    image: assetUrl("assets/system/book01-twenty-parties.jpg"), imageAlt: "Four lecterns arranged in a circle facing inward, each holding a different open book, with an empty space at the centre.", minutes: 14, color: "#278d91",
    nodes: [
      node("the-question", "Put the question", "Obligatory on every Muslim", "More than twenty parties split over which knowledge is meant.", "The reasons each party gives are real reasons.", 2, "know"),
      node("the-pattern", "Catch the pattern", "Each named its own field", "The answers vary exactly with the answerer's occupation.", "Not a claim that any of the sciences is worthless.", 2, "diagnose"),
      node("the-rule", "Take the rule", "The act and its time", "Whoever knows the obligatory act and when it falls due knows what is owed.", "This reframes the question so the answer cannot be a field.", 3, "order"),
      node("only-camels", "Take the limit", "Only the alms of camels", "Own one category and only that category's ruling is obligatory.", "Minimal about obligation, not about study.", 3, "clear"),
      node("the-heart-too", "Add the heart", "The three destroyers", "No human being is free of avarice, whim, and self-admiration.", "Indexed too: what a person sees himself to need.", 4, "guard"),
      node("the-indictment", "Take the indictment", "All have abandoned it", "Most of the Quarter of Perils is classified here as individually obligatory.", "The argument does not depend on any view about the sciences.", 4, "witness"),
    ],
  },
  {
    id: "what-counts-as-knowledge", number: "02", question: "What even counts as religious knowledge?", title: "Redraw the boundary",
    description: "Find out why a cupper is doing something religiously obligatory, where the line between revealed and unrevealed actually falls, and why some genuinely good study can be pursued too far.",
    payoff: "You get a functional map that admits tailoring and puts a limit on specialisation.",
    image: assetUrl("assets/system/book01-the-cupper.jpg"), imageAlt: "A craftsman's bench with a loom shuttle, a tailor's shears and a set of surgical cups laid out in an even row on clean linen.", minutes: 13, color: "#bf7a35",
    nodes: [
      node("the-criterion", "Take the criterion", "What the town needs", "If a town were empty of one who does it, its people would be in difficulty.", "Entirely functional; dignity does not enter it.", 5, "know"),
      node("the-list", "Read the list", "Down to cupping", "Farming, weaving, governance, cupping, tailoring.", "A stronger claim than permission: a community sins by leaving them unfilled.", 5, "witness"),
      node("the-cut", "Make the first cut", "Revealed or not", "Defined by what does not reach it: reason, experience, language.", "Which leaves the category small and sharp.", 6, "clear"),
      node("permitted", "Notice the third class", "Neither owed nor blamed", "A large space that need not be justified.", "It stops the scheme demanding an account of every hour.", 6, "balance"),
      node("the-measure", "Take the measure", "Praised to a point", "Like giving, which past its measure becomes extravagance.", "Presupposes the thing is good; that is what makes it hard to answer.", 7, "steady"),
    ],
  },
  {
    id: "which-words-were-taken", number: "03", question: "Why do the words not mean what they meant?", title: "Follow five captured names",
    description: "Take Ghazali's claim that the confusion is lexical, watch him separate narrowing from transfer, and follow four more words to the one that has stopped selecting anything at all.",
    payoff: "You get a mechanism for how authority attaches to the wrong thing, and a test you can run on your own field.",
    image: assetUrl("assets/system/book01-five-words.jpg"), imageAlt: "Five brass nameplates on a plastered wall, four still bright and legible and the fifth rubbed smooth and blank.", minutes: 12, color: "#c25f50",
    nodes: [
      node("mechanism", "Name the mechanism", "Praised names transferred", "Corrupt purposes moving words to meanings the first generation did not intend.", "The capture of the word protects the thing.", 8, "diagnose"),
      node("narrowing", "Separate the two", "Specified, not moved", "Nothing false is said, and the honour of the wider sense comes along.", "A subtler charge than misuse, and harder to rebut.", 8, "pattern"),
      node("unity", "Take the sharpest", "Unity as technique", "Now an expression for disputation and the raising of doubts.", "Ghazali wrote in that technique himself.", 9, "clear"),
      node("dice-roller", "Follow it to the end", "Even the dice-roller", "A word whose range runs from physician to street gambler selects nothing.", "And a name that selects nothing can neither confer nor withhold honour.", 9, "witness"),
      node("your-field", "Run the test", "On your own word", "Ask what the most honoured word in your field currently picks out.", "The complaint is functional, not nostalgic.", 9, "steady"),
    ],
  },
  {
    id: "why-arguing-is-dangerous", number: "04", question: "What is wrong with arguing?", title: "Weigh it by position, not size",
    description: "Ask the historical question first, meet the analogy that sets the whole scale of the charge, and take the conditions that turn a complaint about motives into a checklist about conduct.",
    payoff: "You get one behavioural test you can run on yourself and three rules you can adopt unilaterally.",
    image: assetUrl("assets/system/book01-the-cup.jpg"), imageAlt: "A single overturned drinking cup on a low table, and beyond it an open doorway into a dark room.", minutes: 13, color: "#586fa8",
    nodes: [
      node("the-history", "Ask why, historically", "Patronage and office", "Ghazali traces the turn to routes of advancement rather than to a decline in piety.", "A historical question before a moral one.", 10, "know"),
      node("darkened-face", "Take the test", "When your opponent is right", "Watch what happens to a disputant's face when the truth lands on the other tongue.", "Observable, unlike the intention the flattering comparison appeals to.", 10, "diagnose"),
      node("the-wine", "Take the analogy", "Position, not magnitude", "As drink relates to the outward enormities, so this to the inward ones.", "It answers the defence that argument is not itself a great sin.", 11, "forces"),
      node("the-target", "Note the target", "An audience in every clause", "Overcoming, silencing, display, and drawing faces toward oneself.", "Disagreement and inquiry are not what is named.", 11, "clear"),
      node("allow-movement", "Adopt the first rule", "Let him change proof", "From proof to proof and difficulty to difficulty, as the forebears did.", "Unilateral: it is a rule about what you allow.", 12, "order"),
      node("no-devices", "Adopt the rest", "Accept correction", "Returning to the truth is obligatory to accept, so do not penalise it.", "The devices exist to punish being corrected.", 12, "guard"),
    ],
  },
  {
    id: "what-is-it-for", number: "05", question: "What is all this learning for?", title: "Find which state you are in",
    description: "Take the condition of validity the student's first duty rests on, place yourself among four states of knowledge, and meet the fiercest chapter in the book — which sorts by aim rather than by accuracy.",
    payoff: "You leave with a set of images you will not forget and a test that only works on yourself.",
    image: assetUrl("assets/system/book01-the-wick.jpg"), imageAlt: "A single lamp burning on a broad table, its light reaching an open book, the wick visibly shortened.", minutes: 14, color: "#a97837",
    nodes: [
      node("the-condition", "Take the condition", "As purity is to prayer", "Not preparation but validity; without it there is no prayer at all.", "Far stronger than saying good character helps.", 13, "know"),
      node("inward-impurity", "Widen purity", "Clean of garment only", "An idolater may be washed and still impure in substance.", "Impurity names what is to be kept away from.", 13, "clear"),
      node("four-states", "Place yourself", "Gain, store, use, give", "Giving insight is named the noblest of the four.", "Most people mistake storing for having.", 14, "pattern"),
      node("sun-and-wick", "Take the images", "Light or burn", "The sun is alight while it lights; the wick gives light while it burns.", "Every image grants that others are genuinely benefited.", 14, "witness"),
      node("two-knowledges", "Separate the two", "Tongue or heart", "Knowledge on the tongue is God's proof against His creation.", "Not called empty — called evidence, and not in your favour.", 15, "diagnose"),
      node("by-aim", "Note the sorting", "Not by accuracy", "A scholar of this world may be entirely correct in what he teaches.", "And every sign is one you can only check on yourself.", 15, "guard"),
    ],
  },
];

export const book01Movements: TaxonomyGroup[] = [
  ["bab1", "1. The excellence of knowledge", "Learning, teaching, and why the Ihya begins here.", [1]],
  ["bab2", "2. The two obligations", "Twenty parties, the act and its time, the heart, the cupper, and the measure.", [2, 3, 4, 5, 6, 7]],
  ["bab3", "3. What is wrongly counted as religious", "Five praised names and what became of them.", [8, 9]],
  ["bab4", "4. The blights of disputation", "Why people turned to it, what it breeds, and when it is permitted.", [10, 11, 12]],
  ["bab5", "5. The etiquette of student and teacher", "A condition of validity, and four states of knowledge.", [13, 14]],
  ["bab6", "6. The blights of the scholars", "The longest chapter, sorting by aim rather than by accuracy.", [15]],
  ["bab7", "7. The intellect", "One name over four meanings, and a dispute dissolved.", [16]],
].map(([id, label, description, chapterIds], index) => ({ id, label, description, chapterIds, color: ["#bf7a35", "#278d91", "#c25f50", "#586fa8", "#a97837"][index % 5] })) as TaxonomyGroup[];

export const book01Instrument: Instrument = {
  title: "What is obligatory on you now",
  note: "Ghazali says that people split into more than twenty parties over which knowledge is individually obligatory, and that every group placed the obligation on the knowledge it happens to be occupied with. His own answer is not a field at all: whoever knows the obligatory act and the time at which it falls due has known what is obligatory. Answer both, and the reading is what his chapters say about that pair.",
  items: [
    {
      id: "obligation", label: "Your own case", lede: "Answer for this month, not in general",
      note: "The first question names Ghazali's four parties in his own terms. The second is his own worked list of occasions — a prayer time, a Ramadan, a year completed on wealth, a trade entered into where usury is common, and the states of the heart. The pairing is designed to show the gap between the knowledge you assume is owed and the knowledge he says is owed by you.",
      axes: [
        {
          id: "occasion", kicker: "The occasion", question: "What has actually come up for you this month?",
          options: [
            { id: "worship", label: "An act of worship whose time is arriving", note: "His first examples: a prayer at its time, a fast when Ramadan comes." },
            { id: "wealth", label: "Wealth or a trade I have entered", note: "His second: alms when the year completes, and guarding against usury if you trade where it is common." },
            { id: "trait", label: "A trait of mine I know is destructive", note: "Avarice obeyed, whim followed, or admiration of oneself." },
            { id: "settled", label: "Nothing new — my circumstances are settled", note: "The answer Ghazali forecloses, and he says why." },
          ],
        },
        {
          id: "party", kicker: "The twenty parties", question: "Which knowledge had you been treating as the obligation?",
          options: [
            { id: "creed", label: "Knowing what to believe, and why", note: "The theologians' answer: theology, since by it unity is grasped." },
            { id: "law", label: "The rulings — lawful and unlawful", note: "The jurists' answer: jurisprudence, since by it the acts of worship are known." },
            { id: "text", label: "The Quran and the reports", note: "The exegetes' and traditionists' answer: by them all sciences are reached." },
            { id: "inward", label: "The states of the heart and sincerity", note: "The Sufis' answer, and Ghazali grants part of it with a condition attached." },
          ],
        },
      ],
      verdicts: [
        { key: "wealth|law", name: "Only the alms of camels", role: "balance", chapterId: 3, body: "You are in the jurists' party and what has come up is wealth, which is the case Ghazali uses to make his sharpest cut. His rule: if a man acquires wealth he must learn the alms due on it — and not at once, but when the year completes. And if he owns nothing but camels, he is obliged to learn nothing but the alms of camels.", action: "So the obligation here is one category, not the corpus. He adds the case that fits a trader exactly: if dealing in usury has become widespread in your town, it becomes obligatory to learn how to guard against that. The obligation follows your situation, not the syllabus of your field." },
        { key: "worship|creed", name: "Assent was accepted without proof", role: "balance", chapterId: 3, body: "You are in the theologians' party and what has come up is an act of worship. Ghazali's remark on this is pointed: the Prophet was satisfied, from the rough Arabs, with assent and acknowledgement, without their learning any proof at all.", action: "What is individually obligatory in belief is the two testimonies and their meaning, not the demonstrations. What is obligatory for you this month is the other thing entirely: the manner of the act whose time is arriving, and the time at which it falls due. That is a smaller and more specific task than the one you had set yourself." },
        { key: "trait|inward", name: "True, with a condition, and then wider", role: "support", chapterId: 4, body: "You are in the Sufis' party and what has come up is a trait. Ghazali does two things here. He grants their answer — understanding the enemy's suggestions and the angel's touch is true knowledge — but limits it to one who addresses himself to it. Then he generalises a different part of it to everyone.", action: "That wider part is the one that applies to you: removing the blamed states of the heart is an individual obligation, and they cannot be removed without knowing their limits, their causes, their signs, and their treatment, since one who does not know an evil falls into it. Your occasion and his ruling coincide, which is rarer in this instrument than it looks." },
        { key: "settled|*", name: "Ghazali closes that answer", role: "warning", chapterId: 4, body: "He forecloses this directly. Since it is usually the case that a person is not free of the motives of evil, of showing off, and of envy, it becomes incumbent on him to learn from the Quarter of Perils what he sees himself to need. And the report he grounds it on says three things destroy — avarice obeyed, whim followed, and a man's admiration of himself — and no human being is free of them.", action: "So there is no settled state on his account, and the obligation that stands when nothing else has come up is the one about the heart. His own summary is the sentence to sit with: most of what is in the Quarter of Perils is among the individual obligations, and people have all abandoned them, occupying themselves with what does not concern them." },
        { key: "trait|*", name: "This is the abandoned obligation", role: "warning", chapterId: 4, body: "A destructive trait has come up, and whatever field you had been treating as the obligation, Ghazali's argument here does not depend on any view about the sciences. Removing such traits is agreed to be obligatory; treatment is meeting a cause with its opposite; that requires knowing the cause; therefore the knowledge is obligatory.", action: "Take the one trait rather than the quarter. His phrase is what a person sees himself to need, which indexes this exactly as he indexed the acts of worship. Name its causes and its signs, and if you cannot, that is the specific gap the chapter says is an obligation and not an interest." },
        { key: "worship|*", name: "The act, and the time it falls due", role: "support", chapterId: 3, body: "An act of worship is arriving, and Ghazali's rule addresses that directly: the meaning of the individual obligation is the knowledge of how the obligatory act is performed, so whoever knows the act and the time at which it becomes obligatory has known what is owed.", action: "His worked example is worth copying exactly. For the fast, he lists four things: that its time runs from dawn to sunset, that what is required is intention and abstaining, and that it runs until the crescent is sighted or two witnesses testify. That is the whole obligation for that act — a short, finite, checkable list rather than a subject." },
        { key: "wealth|*", name: "Only the category you own", role: "balance", chapterId: 3, body: "Wealth or a trade has come up. Ghazali's treatment is indexed twice over: the obligation does not fall at once but when the year completes, and it covers only what you actually own rather than the categories of alms in general.", action: "Add his situational case if it applies: a merchant in a town where dealing in usury has become widespread is obliged to learn how to guard against it. Note that this is generated by your circumstances and would not be obligatory on your neighbour, which is the whole shape of his answer." },
        { key: "*|*", name: "Read the occasion against the party", role: "balance", chapterId: 2, body: "An occasion, and a field you had been treating as the obligation. Ghazali's observation about the twenty parties is that each named the knowledge it happened to be occupied with, and his own answer sidesteps the question by making the obligation a function of circumstance.", action: "Take the occasion as the answer and the party as the thing to be set aside for the moment. Whatever your field is worth — and he does not say it is worth nothing — it is not what determines what is owed by you this month." },
      ],
    },
  ],
};

export const book01Sources: SourceLink[] = [
  { label: "Primary Arabic text", note: "The complete public Arabic of Book 1 was read and used to establish the two obligations, the five captured words, the treatment of disputation, the duties of student and teacher, and the signs of the scholars.", url: "https://shamela.ws/book/9472/4" },
  { label: "The individual obligation", note: "The passage surveying the more than twenty parties and observing that each placed the obligation on the knowledge it was occupied with.", url: "https://shamela.ws/book/9472/14" },
  { label: "The obligation of the heart", note: "The passage stating the rule as the knowledge of the obligatory act and its time, and classifying most of the Quarter of Perils as individually obligatory.", url: "https://shamela.ws/book/9472/15" },
  { label: "The communal obligation", note: "The passage giving the criterion for a communal obligation and naming agriculture, weaving, governance, cupping, and tailoring among them.", url: "https://shamela.ws/book/9472/16" },
  { label: "What was changed of the terms", note: "The passage on the five praised names — jurisprudence, knowledge, unity, reminding, and wisdom — and what became of each.", url: "https://shamela.ws/book/9472/31" },
  { label: "The blights of disputation", note: "The passage comparing disputation's relation to the inward enormities with the relation of drink to the outward ones.", url: "https://shamela.ws/book/9472/45" },
  { label: "The duties of the teacher", note: "The passage giving the four states of knowledge on the analogy of wealth, with the images of the sun, the musk, the whetstone, and the wick.", url: "https://shamela.ws/book/9472/55" },
  { label: "The signs of the scholars", note: "The passage distinguishing the scholars of the hereafter from the scholars of this world, and the two kinds of knowledge.", url: "https://shamela.ws/book/9472/58" },
  { label: "Forty-book structure", note: "Ghazali.org's listing places Book 1 as the first book of the Quarter of Worship and confirms its title.", url: "https://www.ghazali.org/listing-the-forty-books/" },
];

export const book01: SystemBook = {
  id: 1,
  title: "Knowledge",
  shortTitle: "Knowledge",
  defaultJourneyId: "what-must-i-know",
  chapters: book01Chapters,
  conceptNodes: book01ConceptNodes,
  journeys: book01Journeys,
  sources: book01Sources,
  taxonomy: {
    title: "Seven chapters",
    note: "Ghazali's own seven, in his order. Only the first and the last are uncontroversial; the five between them are a sustained critique of what was being taught as religious knowledge in his own time, and the sixth is by a wide margin the longest.",
    groups: book01Movements,
  },
  instrument: book01Instrument,
  editorialNote: "The five journeys, sixteen reading sections, visual models, and diagnostic are editorial learning aids. The sections follow Ghazali's seven chapters in his order and are grouped under them in the movements list. The English is an original synthesis made from a reading of the public Arabic text, not a translation and not a substitute for one. Reports and inherited anecdotes are presented as material Ghazali transmitted; this prototype does not independently grade every narration, and the Arabic carries the graders' notes alongside many of them. Two things should be said about scope. This is the first book of the Ihya and one of its longest, and its sixth chapter alone — on the blights of the scholars — runs to roughly a third of the book; Section 15 presents its argument and its central distinction rather than reproducing its full catalogue of signs, and a reader who wants that catalogue should go to the text. And the treatments of individual and communal obligation are given here as Ghazali gives them, including his classification of medicine, arithmetic, agriculture, weaving, governance, cupping, and tailoring as communal obligations; that is his own list and his own criterion. The chapter on the evil scholars is fierce and is stated fiercely here, but every sign in it is framed as something a person checks in himself, and the Ihya's standing position is that the inward state of another is not available. The diagnostic applies his rule and his four parties to a pair of answers the reader supplies about his own circumstances and cannot pronounce on anyone's state.",
};
