import { assetUrl } from "./assetUrl";
import type { Chapter, ConceptNode, VisualModel } from "./data";
import type { Instrument, Journey, SourceLink, SystemBook, TaxonomyGroup } from "./systemTypes";

type Seed = { id: number; shortTitle: string; formalTitle: string; overview: string; thesis?: string; moves: Array<{ title: string; body: string }>; closer: Array<{ title: string; body: string }>; distinction: [string, string, string, string, string]; misreading: string; reflection: string; audit: string[]; nodes: string[]; model: VisualModel };

const makeChapter = (seed: Seed): Chapter => ({
  id: seed.id, shortTitle: seed.shortTitle, formalTitle: seed.formalTitle, overview: seed.overview,
  points: seed.moves.slice(0, 3).map((m) => m.body), reflection: seed.reflection, relatedNodes: seed.nodes, visualModel: seed.model,
  deep: { thesis: seed.thesis ?? seed.moves[0].body, context: seed.overview, moves: seed.moves, closeReading: seed.closer,
    distinction: { title: seed.distinction[0], firstLabel: seed.distinction[1], first: seed.distinction[2], secondLabel: seed.distinction[3], second: seed.distinction[4] },
    misreading: seed.misreading, observation: seed.reflection, selfAudit: seed.audit,
    sourceAnchor: `Book 34, ${seed.id <= 10 ? "Part One, on poverty" : "Part Two, on abstinence"}, ${seed.formalTitle}.` },
});
const chain = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "chain", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const pair = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "pair", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const spectrum = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "spectrum", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });

export const book34Chapters: Chapter[] = [
  makeChapter({
    id: 1, shortTitle: "Five states of lacking", formalTitle: "The reality of poverty and the states and names of the poor",
    overview: "Ghazali defines poverty precisely, notes that on the definition everything but God is poor, then narrows to poverty of wealth and sorts those who lack it into five states, each with its own name.",
    thesis: "Poverty is defined precisely, and on the definition it turns out to be a relation rather than a bank balance.",
    moves: [
      { title: "Define it", body: "Poverty is the lack of what one needs. Lacking what one does not need is not called poverty, and if what is needed is present and within reach then the one who needs it is not poor." },
      { title: "Take the definition to its end", body: "On that definition everything other than God is poor, since each thing needs its existence to continue into the next moment and that continuance is derived. Only one existent has an underived existence, so there is one rich and everything else is in need of Him." },
      { title: "Narrow the subject", body: "The book means poverty of wealth in particular. A servant's poverty with respect to the kinds of things he needs has no limit, and what is treated here is only the part reached by money." },
      { title: "Sort the five states", body: "The one who lacks wealth may be in any of five conditions, and Ghazali names each so that its rulings can be discussed separately." },
    ],
    closer: [
      { title: "The five, in order", body: "The detached, who would dislike wealth if it came and flee from taking it. The contented in the sense of being pleased, who neither desires it enough to rejoice at it nor dislikes it enough to be pained. The satisfied, to whom having it is more beloved than not, but not enough to make him seek it. The grasping, who leaves seeking only from inability. And the compelled, who lacks what he cannot do without, like the hungry man without bread." },
      { title: "The state above all five", body: "Beyond these there is a condition higher than detachment, in which the presence and absence of wealth are equal to him, so that he neither flees it nor welcomes it. Ghazali marks it as the summit rather than treating it as the ordinary target." },
    ],
    distinction: ["Two people with empty hands", "The state, not the circumstance", "What differs is the disposition toward what is absent, which is what the five names sort.", "The circumstance alone", "Both lack the same thing, and from outside the five states are indistinguishable."],
    misreading: "Do not read the ladder as a ranking of persons by income. Every one of the five describes someone who lacks the same thing, and what is graded is the state toward it.",
    reflection: "Place yourself honestly on the five before reading further. Most readers place themselves one rung above where the definitions put them.",
    audit: ["Which of the five actually describes me?", "Would I rejoice if it came?", "Do I refrain from seeking, or am I unable to seek?", "Is what I lack a need or a want?"],
    nodes: ["faqr", "five-states"],
    model: spectrum("Five states of one who lacks", "The circumstance is identical; the disposition is what is graded.", [["Detached", "Would dislike it and flee it if it came.", "support"], ["Pleased", "Neither rejoices at it nor is pained by it.", "support"], ["Satisfied", "Prefers having it, but will not seek it.", "balance"], ["Grasping", "Refrains only from inability.", "warning"], ["Compelled", "Lacks what he genuinely cannot do without.", "balance"]]),
  }),
  makeChapter({
    id: 2, shortTitle: "Why poverty is praised", formalTitle: "The excellence of poverty in general",
    overview: "Ghazali gathers the reports praising poverty, and the placement after the five states means the reader already knows that the praise cannot attach to circumstance alone.",
    thesis: "The reports praising poverty are gathered, and where they sit in the book matters as much as what they say.",
    moves: [
      { title: "Gather the testimony", body: "The verses, reports, and sayings praising the poor are assembled, and they are extensive." },
      { title: "Note what the praise attaches to", body: "Since the previous section established five different states within the same circumstance, the praise cannot be attaching to the mere absence of money." },
      { title: "Keep the reason in view", body: "What is praised is the freedom from what wealth brings with it, which is a matter of the disposition rather than of the balance." },
      { title: "Prepare the qualification", body: "The next sections narrow the praise explicitly to particular states within poverty, which is where the general commendation becomes usable." },
    ],
    closer: [
      { title: "Why order matters here again", body: "As with hope in Book 33, the definition precedes the encouragement. A reader who met this material first could conclude that poverty is meritorious as such, which the five states already exclude." },
      { title: "The link to Book 27", body: "The Perils quarter censured wealth and miserliness. This is the other side of the same analysis, and Ghazali's care about disposition rather than circumstance runs identically through both." },
    ],
    distinction: ["Two things the praise could attach to", "The state", "A disposition toward what is absent, which is what the five names sorted.", "The circumstance", "Having no money, which by itself distinguishes nothing."],
    misreading: "Do not read this as a claim that being poor is meritorious in itself. The book's own structure makes that reading unavailable.",
    reflection: "Ask whether you would still be praised on this account if your circumstances changed but your disposition did not.",
    audit: ["Do I take this praise as applying to me?", "On which of the five states would it apply?", "What would change in me if wealth arrived?", "Am I praising a circumstance I did not choose?"],
    nodes: ["faqr"],
    model: pair("Where the praise lands", "The five states make the distinction unavoidable.", [["On the disposition", "What a person is toward what he lacks, which he can work on.", "support"], ["On the circumstance", "The empty hand alone, which distinguishes nothing.", "warning"]]),
  }),
  makeChapter({
    id: 3, shortTitle: "Which poor", formalTitle: "The particular excellence of the pleased, the satisfied, and the truthful among the poor",
    overview: "Ghazali narrows the praise to specific states within poverty, which is where the general commendation becomes a description of something a person can actually be.",
    thesis: "The praise narrows to particular states inside poverty rather than covering everyone whose hands are empty.",
    moves: [
      { title: "Name the states praised", body: "The particular excellence attaches to those who are pleased, those who are satisfied, and those who are truthful in their condition, rather than to everyone whose hands are empty." },
      { title: "Explain why these", body: "Each of the three names a disposition that the previous section's ladder identified, and each is a state a person occupies rather than a circumstance he suffers." },
      { title: "Exclude the grasping", body: "The grasping man who refrains only from inability is not covered, since nothing in his disposition differs from the wealthy man's except opportunity." },
      { title: "Keep the compelled in view", body: "The one in genuine need is a separate case, and the sections on asking and on its limits are where his situation is treated." },
    ],
    closer: [
      { title: "The move this section makes", body: "It converts a general commendation into a specific one, which is what makes the rest of the book possible: rules of conduct can be given to someone in a describable state and cannot be given to a circumstance." },
      { title: "Why truthfulness appears here", body: "Because the states are inward and only the person occupying one can report it, so honesty about which rung he is on is part of the state itself." },
    ],
    distinction: ["Two poor men, one opportunity", "The satisfied", "He would not seek it even given the means, which is a disposition.", "The grasping", "He refrains only because he cannot, which the arrival of means would immediately reveal."],
    misreading: "Do not use the narrowing to disqualify others. Every one of these states is inward, and the section's own emphasis on truthfulness applies to self-report first.",
    reflection: "Imagine the means to seek arriving tomorrow, and watch what you would do. That is the test that separates the third rung from the fourth.",
    audit: ["Would I seek it if I could?", "Am I truthful about which state I am in?", "Do I claim contentment that opportunity would dissolve?", "What in me is waiting for a chance?"],
    nodes: ["faqr", "five-states"],
    model: chain("Narrowing the praise", "Each step makes the commendation more usable.", [["Poverty in general", "A circumstance covering five different states.", "balance"], ["The pleased and satisfied", "Dispositions within it, which is where the praise settles.", "support"], ["Truthful about which", "The states are inward, so honest self-report is part of the state.", "support"]]),
  }),
  makeChapter({
    id: 4, shortTitle: "Poverty over wealth", formalTitle: "The excellence of poverty over wealth",
    overview: "The comparison the whole first part has been building toward, and Ghazali handles it with the same care he brings to every comparison of states.",
    thesis: "The comparison the first part has been building toward, taken at its strongest rather than its most comfortable.",
    moves: [
      { title: "State the position", body: "Poverty is given precedence over wealth, and the reports supporting it are assembled." },
      { title: "Locate the reason", body: "The precedence rests on what each condition tends to produce rather than on the conditions themselves, which is consistent with the treatment of blessing and trial in Book 32." },
      { title: "Keep the qualification", body: "Since five states exist within poverty and more than one within wealth, the comparison is between what each tends to make of a person rather than between two balances." },
      { title: "Prepare the harder question", body: "The next section takes the sharper form of the comparison, between the satisfied poor man and the grateful rich man, which is where the general answer is tested." },
    ],
    closer: [
      { title: "Why the general answer is not enough", body: "A comparison between the best case of one condition and the worst of the other settles nothing. Ghazali therefore immediately narrows to the matched pair." },
      { title: "The Perils quarter behind this", body: "Book 27 examined what wealth does to a person and Book 26 what attachment to the world does. The precedence claimed here rests on those analyses rather than on an independent argument." },
    ],
    distinction: ["Two ways to compare conditions", "By tendency", "What each tends to make of a person, which is what the reports are about.", "By instance", "Whether this poor man is better than that rich man, which no general claim settles."],
    misreading: "Do not read the precedence as a verdict on individuals. The following section exists precisely because the general claim does not settle particular cases.",
    reflection: "Notice whether you find this comparison comfortable, and consider which side of it you are on.",
    audit: ["Which condition am I actually in?", "What has it tended to make of me?", "Do I use this claim to judge others or to examine myself?", "What would the other condition make of me?"],
    nodes: ["faqr", "wealth"],
    model: pair("What is being compared", "The claim is about tendencies, not about persons.", [["Tendency of poverty", "What the condition tends to remove and to make possible.", "support"], ["Tendency of wealth", "What it tends to bring with it, as the Perils quarter set out.", "warning"]]),
  }),
  makeChapter({
    id: 5, shortTitle: "The matched pair", formalTitle: "The relation of the satisfied poor man to the grateful rich man",
    overview: "The sharpest form of the comparison, and Ghazali takes it seriously rather than settling it by preference. Each side is represented by its best case.",
    thesis: "The sharpest form of the comparison: the satisfied poor man against the grateful rich one.",
    moves: [
      { title: "Match the cases", body: "The comparison is set between a poor man who is satisfied and a rich man who is grateful, so that neither side is represented by its failure." },
      { title: "Show why it is hard", body: "Both states are praised in their own right, both are dispositions rather than circumstances, and each has something the other lacks." },
      { title: "Report the considerations", body: "Ghazali sets out what tells in each direction rather than asserting a result, which is his method wherever two praised states are compared." },
      { title: "Connect it to Book 32", body: "This is the same structure as the comparison of patience and gratitude: two commended states, and a question that dissolves once each is seen for what it consists of." },
    ],
    closer: [
      { title: "Why the matched pair is the only honest form", body: "Comparing the best of one condition with the worst of the other is how most such arguments are conducted and why they settle nothing. Matching the cases is what makes the question real." },
      { title: "What the reader is left with", body: "Not a ranking to adopt but a way of examining his own case, since he can identify which of the four positions he actually occupies." },
    ],
    distinction: ["Two comparisons that look alike", "Matched", "The best case of each condition is set against the best case of the other.", "Unmatched", "One side is represented by its virtue and the other by its failure, which decides nothing."],
    misreading: "Do not take a general precedence and apply it to a matched pair. The reason this section exists is that the general answer does not carry over.",
    reflection: "Identify which of the four positions you occupy: satisfied poor, grasping poor, grateful rich, or ungrateful rich.",
    audit: ["Which of the four am I?", "Am I comparing my best case to someone's worst?", "What does my condition ask of me that the other would not?", "Which would be harder for me?"],
    nodes: ["faqr", "wealth", "five-states"],
    model: chain("The four positions", "Only the matched comparison is worth making.", [["Satisfied poor", "Would not seek it even given means.", "support"], ["Grateful rich", "Uses it for what it was given for, as Book 32 defined gratitude.", "support"], ["Grasping poor", "Refrains only from inability.", "warning"], ["Ungrateful rich", "Holds it without the use that gratitude consists of.", "warning"]]),
  }),
  makeChapter({
    id: 6, shortTitle: "Conduct in poverty", formalTitle: "The manners of the poor man in his poverty",
    overview: "Ghazali turns from the analysis of states to conduct, and the instructions are aimed at keeping a person in the state he claims rather than at enduring the circumstance.",
    thesis: "From the analysis of states to conduct — what poverty actually asks of somebody in it.",
    moves: [
      { title: "Aim the instructions", body: "The manners are given to someone in the condition, and their purpose is to protect the disposition that made the condition praiseworthy." },
      { title: "Guard the inward", body: "Since the five states are inward, the conduct that maintains them concerns what the person does with his attention as much as what he does with his hands." },
      { title: "Refuse display", body: "The consistent warning is against poverty becoming a claim on others, which would convert the state into the very thing Book 28 anatomised." },
      { title: "Keep dignity", body: "The manners are shaped so that the poor man's condition neither humiliates him nor becomes a lever, which is the balance the following sections on asking develop." },
    ],
    closer: [
      { title: "Why conduct follows the anatomy", body: "Only after the five states have been separated can rules be given, since the same act would maintain one state and destroy another." },
      { title: "The link to the second half", body: "These manners are the practical form of what the second part treats as detachment. The two halves of the book meet here rather than running in parallel." },
    ],
    distinction: ["Two ways of carrying a condition", "Held quietly", "The state is maintained inwardly and makes no claim on anyone.", "Held as a position", "The condition becomes something others are meant to notice and answer."],
    misreading: "Do not read the manners as requiring concealment of genuine need. The sections on asking address necessity directly and permit it.",
    reflection: "Ask whether anyone around you is expected to notice your circumstances, and what that expectation is doing.",
    audit: ["Does my condition make a claim on anyone?", "What do I want noticed?", "Am I protecting a state or performing one?", "Where has hardship become a position?"],
    nodes: ["faqr", "adab"],
    model: pair("What the manners protect", "The rules exist to keep the state rather than the circumstance.", [["The disposition", "What made the condition praiseworthy in the first place.", "support"], ["The appearance", "A condition arranged to be registered by others.", "warning"]]),
  }),
  makeChapter({
    id: 7, shortTitle: "Receiving without asking", formalTitle: "The manners of the poor man in accepting a gift that comes unasked",
    overview: "A gift that arrives without being sought is a distinct case, and Ghazali treats it carefully because both accepting and refusing can be wrong.",
    thesis: "A gift that arrives unasked is its own case, and needs its own rules.",
    moves: [
      { title: "Separate the case", body: "What arrives unasked is not what was sought, and the rules differ accordingly." },
      { title: "Examine the giver's purpose", body: "The considerations include why it is being given and what accepting would place the receiver under, which is why the case cannot be settled by a rule about money alone." },
      { title: "Examine the receiver's state", body: "Since the five states differ, the same gift may be right for one person to take and wrong for another, according to what it would do to the disposition." },
      { title: "Refuse the easy answers", body: "Neither blanket acceptance nor blanket refusal survives the analysis, and Ghazali sets out the conditions rather than issuing a rule." },
    ],
    closer: [
      { title: "Why refusing can be the fault", body: "Refusal can be a form of the display the previous section warned against, or an imposition on the giver, and Ghazali treats it as needing justification exactly as acceptance does." },
      { title: "The connection to the first state", body: "Only the detached, on the definition of the first rung, would flee a gift. For anyone below that rung, fleeing it is a claim to a state he does not occupy." },
    ],
    distinction: ["Two refusals of a gift", "From the state", "The person genuinely occupies the rung on which wealth is disliked, and the refusal follows from it.", "From the appearance", "The refusal claims a rung the person does not occupy, and is itself a display."],
    misreading: "Do not read the permission to accept as encouragement to seek. The whole of the next section is about the difference.",
    reflection: "Recall the last thing you were offered and refused, and ask honestly which of the two refusals it was.",
    audit: ["Why did I refuse the last offer?", "What would accepting have placed me under?", "Am I claiming a rung I am not on?", "Whose purpose does my refusal serve?"],
    nodes: ["faqr", "adab", "giving"],
    model: chain("Deciding an unasked gift", "Neither answer is automatic.", [["Whose purpose", "Why it is being given, and what it would place you under.", "balance"], ["Which state", "What accepting would do to the disposition you occupy.", "balance"], ["Which refusal", "Whether refusing follows from the state or performs one.", "warning"]]),
  }),
  makeChapter({
    id: 8, shortTitle: "Asking", formalTitle: "The prohibition of asking without necessity, and the manners of the one compelled",
    overview: "Ghazali forbids asking without necessity and then treats the compelled case with unusual care, since the fifth state of poverty is exactly the one in which asking may be required.",
    thesis: "Asking without necessity is forbidden, which forces the question of what necessity is.",
    moves: [
      { title: "State the prohibition", body: "Asking without necessity is forbidden, and the reasons given concern what it does to the asker as much as what it takes from the giver." },
      { title: "Name what it costs the asker", body: "Asking places a person under obligation and installs a habit of looking to people, which is the disposition the whole first part has been examining." },
      { title: "Admit the compelled case", body: "The fifth state is one of genuine necessity, and there the prohibition does not hold. Ghazali does not treat need as a failure of state." },
      { title: "Give the manners for it", body: "Where asking is permitted it still has conditions, which govern how it is done, of whom, and in what measure." },
    ],
    closer: [
      { title: "Why this is placed after the manners of receiving", body: "Because the two cases are adjacent and constantly confused. Something arriving unasked and something obtained by asking are treated as different acts throughout." },
      { title: "The consistency with the rest of the quarter", body: "As with patience in Book 32, a genuine need that can be met is not a thing to be endured for its own sake. The permission for the compelled follows the same logic." },
    ],
    distinction: ["Two people with the same empty hand", "Compelled", "The need is genuine and unmeetable otherwise, and asking is permitted with conditions.", "Not compelled", "The need is not genuine or is otherwise meetable, and asking is forbidden."],
    misreading: "Do not read the prohibition as a counsel to endure genuine hunger. The compelled case is explicitly excepted and given its own rules.",
    reflection: "If you have asked recently, ask which of the two cases you were in, and whether you examined that at the time.",
    audit: ["Was the need genuine and otherwise unmeetable?", "What did asking place me under?", "Has looking to people become a habit?", "Would I have accepted the same from a stranger?"],
    nodes: ["asking", "faqr", "necessity"],
    model: pair("Where the prohibition stops", "The exception is genuine and bounded.", [["Compelled", "Permitted, with conditions on how, of whom, and how much.", "balance"], ["Not compelled", "Forbidden, for what it does to the asker as much as the giver.", "warning"]]),
  }),
  makeChapter({
    id: 9, shortTitle: "How much is enough", formalTitle: "The measure of sufficiency that makes asking forbidden",
    overview: "Having permitted asking under necessity, Ghazali has to say what counts as having enough, and the answer is deliberately not a single figure.",
    thesis: "Having permitted asking under necessity, Ghazali has to fix the line, and does.",
    moves: [
      { title: "Pose the question", body: "If asking is permitted only under necessity, then the boundary has to be located: how much a person must have before asking becomes forbidden to him." },
      { title: "Refuse a single figure", body: "The measure varies with circumstances, as with the measure of food in Book 23, and a fixed number would misdescribe the cases." },
      { title: "Give the considerations", body: "Ghazali examines the kinds of things needed, their amounts, and their timing, which is the same three-part frame used for the discipline of eating." },
      { title: "Keep it checkable", body: "Though no single figure is given, the considerations are concrete enough that a person can apply them to his own case, which is the point." },
    ],
    closer: [
      { title: "Why kinds, amounts, and times", body: "It is the same analysis as the measures of food, and for the same reason: a need is not a quantity but a relation between a person, a thing, and a moment." },
      { title: "What this protects against", body: "Both a person who asks while sufficient and a person who refuses to ask while genuinely in need, since a boundary with no content would leave both unchecked." },
    ],
    distinction: ["Two ways to set a boundary", "By considerations", "Kinds, amounts, and times, applied to the actual person and moment.", "By a figure", "A single number, which would be easier to apply and would misdescribe most cases."],
    misreading: "Do not read the absence of a figure as an absence of a boundary. Ghazali gives the considerations precisely so that the boundary can be located in a particular case.",
    reflection: "Apply the three considerations to your own situation and see where they put you.",
    audit: ["What do I actually need, in kind?", "In what amount, and by when?", "Have I set my own boundary generously?", "Would I accept my reasoning from someone else?"],
    nodes: ["asking", "sufficiency"],
    model: chain("Locating sufficiency", "The same frame as the measures of eating in Book 23.", [["Kinds", "What is genuinely needed rather than wanted.", "balance"], ["Amounts", "How much of it, for this person.", "balance"], ["Times", "By when, and for how long.", "balance"]]),
  }),
  makeChapter({
    id: 10, shortTitle: "Those who ask", formalTitle: "The states of those who ask",
    overview: "The first part closes by sorting those who ask, which completes the anatomy: having sorted those who lack, Ghazali sorts those who approach others about it.",
    thesis: "The first part closes by sorting those who ask, which completes the account of the state.",
    moves: [
      { title: "Sort the askers", body: "Those who ask are not one kind, and their states differ as widely as the five states of those who lack." },
      { title: "Distinguish need from habit", body: "The central division is between one who asks from genuine necessity and one for whom asking has become a way of living." },
      { title: "Include the giver's position", body: "Since asking is a transaction, the states of the askers bear on what a giver is doing when he gives, which the book on charity treats in detail." },
      { title: "Close the part", body: "With those who lack sorted and those who ask sorted, the analysis of poverty is complete and the book turns to detachment." },
    ],
    closer: [
      { title: "Why sorting the askers matters to the reader", body: "Most readers of this book are more often asked than asking, and the sorting is what lets a giver respond to a person rather than to a category." },
      { title: "The symmetry of the two halves of Part One", body: "The part opens by sorting the states of those who lack and closes by sorting the states of those who ask, and the same principle governs both: the circumstance is identical and the state is what differs." },
    ],
    distinction: ["Two people asking the same thing", "From necessity", "The need is genuine and the asking is bounded by it.", "From habit", "Asking has become a means of living, and no amount would end it."],
    misreading: "Do not use the sorting to withhold from those in need on suspicion of the second case. Ghazali's own treatment of giving elsewhere weighs heavily against making the giver a judge.",
    reflection: "Recall the last person who asked you for something, and notice how quickly you sorted them and on what evidence.",
    audit: ["How do I sort people who ask me?", "On what evidence?", "Have I used the second category to excuse myself?", "What would I want assumed about me?"],
    nodes: ["asking", "giving"],
    model: pair("The symmetry of Part One", "The same principle opens and closes it.", [["Those who lack", "One circumstance, five states, sorted by disposition.", "balance"], ["Those who ask", "One act, several states, sorted the same way.", "balance"]]),
  }),
  makeChapter({
    id: 11, shortTitle: "Detachment is an exchange", formalTitle: "The reality of abstinence",
    overview: "Part Two opens with a definition that reframes the whole subject. Detachment is not the absence of desire but its redirection, and it therefore has two conditions.",
    thesis: "Detachment is defined by what you turn toward, not by what you give up — which reframes the whole second part.",
    moves: [
      { title: "Give the definition", body: "Abstinence is the turning of desire away from a thing toward what is better than it. Whoever turns from one thing to another, by sale or exchange, turns from the first because he is disinterested in it and toward the second because he desires it." },
      { title: "Name the two sides", body: "His condition with respect to what is left is called abstinence, and with respect to what is taken it is called desire and love. Both are present in one act." },
      { title: "Give the first condition", body: "What is turned from must itself be desirable in some respect. One who turns from what is not sought is not called detached: leaving stones and dirt is not abstinence, and leaving dirhams and dinars is." },
      { title: "Give the second condition", body: "What is turned toward must be better in his own estimation, so that the desire for it prevails. A seller does not sell unless the price is better to him than the goods." },
    ],
    closer: [
      { title: "The consequence Ghazali draws", body: "Whoever sells the world for the hereafter is detached in the world, and whoever sells the hereafter for the world is also detached, but in the hereafter. Custom has specialised the name to the first, as it has specialised other words." },
      { title: "The Quranic usage", body: "Joseph's brothers are described as having been, regarding him, of the detached, because they sold him for what they hoped would be better to them. The word is used exactly as the definition requires." },
    ],
    distinction: ["Two things that look like detachment", "An exchange", "Something desirable is left because something better is desired more.", "An absence", "Nothing is left because nothing was wanted, which the first condition excludes."],
    misreading: "Do not conclude that detachment requires having no desires. On this definition it requires having a stronger one, which is the opposite claim.",
    reflection: "Take something you have left and name what you took instead. If you cannot, the definition says you did not do this.",
    audit: ["What did I actually turn toward?", "Is it better in my own estimation, or only in my speech?", "Was what I left genuinely desirable to me?", "Have I called an absence of desire a virtue?"],
    nodes: ["zuhd", "exchange", "conditions"],
    model: chain("The structure of an exchange", "Both conditions must hold for the name to apply.", [["Something desirable", "What is left must be genuinely wanted; leaving stones is not detachment.", "balance"], ["Something better", "What is taken must be better in the person's own estimation.", "support"], ["The desire prevails", "The stronger want carries the exchange, as with any seller.", "support"]]),
  }),
  makeChapter({
    id: 12, shortTitle: "Why detachment is praised", formalTitle: "The excellence of abstinence",
    overview: "The testimony for detachment, gathered after the definition, so that a reader knows the praise attaches to an exchange rather than to a deprivation.",
    thesis: "The testimony is gathered after the definition, so that detachment is not confused with deprivation.",
    moves: [
      { title: "Gather the testimony", body: "The verses, reports, and sayings are assembled, and they are among the most extensive in the quarter." },
      { title: "Read them through the definition", body: "Every commendation of leaving the world is, on the definition, a commendation of taking something judged better, which changes what the reader is being urged toward." },
      { title: "Note what is not praised", body: "Deprivation without an exchange fails the definition and therefore falls outside the praise, however uncomfortable it is." },
      { title: "Prepare the degrees", body: "Since the definition turns on what is taken, the degrees of detachment will be graded by what a person turns toward, which the next section sets out." },
    ],
    closer: [
      { title: "Why the definition changes the reading", body: "Material praising the abandonment of the world reads as an instruction to suffer if the exchange is not in view. With it, the same material reads as an instruction to value something correctly." },
      { title: "The connection to Book 26", body: "The Censure of This World supplied the argument for why the exchange is a good one. This book supplies the account of what making it consists of." },
    ],
    distinction: ["Two ways of leaving the world", "As an exchange", "Something better is taken, and the leaving follows from valuing it more.", "As a deprivation", "Something is given up and nothing is taken, which the definition excludes from the name."],
    misreading: "Do not conclude that hardship undertaken without an exchange is worthless. Ghazali's point is narrower: it is not what this word means and not what these reports commend.",
    reflection: "Read one commendation of detachment and ask what it is urging you to take rather than to leave.",
    audit: ["What am I being urged toward here?", "Have I heard this as a call to suffer?", "What have I given up without taking anything?", "Do I value what I claim to have chosen?"],
    nodes: ["zuhd", "exchange"],
    model: pair("Two readings of one body of praise", "Everything downstream depends on which definition is in play.", [["As valuing", "The reports urge taking something better, and the leaving follows.", "support"], ["As suffering", "The reports urge giving things up, with nothing named on the other side.", "warning"]]),
  }),
  makeChapter({
    id: 13, shortTitle: "Graded by what you take", formalTitle: "The degrees and divisions of abstinence",
    overview: "Since detachment was defined by what is turned toward, its degrees follow from that, and Ghazali grades them by the object of the desire that carried the exchange.",
    thesis: "Since detachment was defined by its object, its degrees follow from how completely the object has changed.",
    moves: [
      { title: "Give the highest degree", body: "One who turns from everything other than God, including the gardens themselves, and loves nothing but God, is the absolutely detached." },
      { title: "Give the degree below it", body: "One who turns from every worldly portion but still desires the equivalents in the hereafter is detached, but below the first, since what he took is of the same kind as what he left." },
      { title: "Give the partial degree", body: "Somebody who gives up some of what the world offers and not the rest is detached in the part he gave up — a man who lets go of money but not standing, or of good food but not good clothes." },
      { title: "Draw the practical consequence", body: "Since the grading follows the object taken, a person can locate his own degree by asking what he actually wanted more, which is checkable in a way that intensity of renunciation is not." },
    ],
    closer: [
      { title: "Why the partial degree is included", body: "Ghazali does not withhold the name from someone who has left one thing and not another. It is a real degree, and naming it lets a reader see where his exchange stopped." },
      { title: "The uncomfortable case", body: "Leaving wealth while keeping standing is his own example, and it connects directly to Book 28, where standing is shown to be the harder of the two to relinquish." },
    ],
    distinction: ["Two exchanges of the world", "For something of another kind", "What is taken is not a better version of what was left, which is the higher degree.", "For a better version", "What is taken is the same kind of portion, expected elsewhere, which is a real degree and a lower one."],
    misreading: "Do not read the highest degree as the only real one. Ghazali grades rather than excludes, and the partial degree is named as detachment.",
    reflection: "Ask what you left and what you took, then find your own degree on the three.",
    audit: ["Which degree is mine?", "What did I take, of what kind?", "Which portion have I left untouched?", "Have I left wealth and kept standing?"],
    nodes: ["zuhd", "degrees", "exchange"],
    model: spectrum("Three degrees, graded by the object", "The grading follows what was taken, not how much was left.", [["Partial", "Some portions left and others kept, which is a real degree.", "balance"], ["For the hereafter", "Every worldly portion left, the same kinds desired elsewhere.", "support"], ["For God alone", "Everything besides Him left, including the gardens.", "support"]]),
  }),
  makeChapter({
    id: 14, shortTitle: "What is left", formalTitle: "The object of abstinence",
    overview: "Ghazali turns from the structure of the exchange to its content, and asks what exactly a person is turning from when he is said to be detached from the world.",
    thesis: "From the structure of the exchange to its content: what exactly is being turned away from.",
    moves: [
      { title: "Name the object", body: "The world here is not the created order but the portion of it a person takes as his own, which is the same distinction Book 26 established." },
      { title: "Exclude what cannot be left", body: "Since detachment requires an exchange, what is genuinely necessary cannot simply be abandoned, and the section on necessities takes that up directly." },
      { title: "Include what is easily missed", body: "The object extends past property to standing, comfort, and the arrangements a person builds around himself, which are harder to see as portions." },
      { title: "Keep the definition governing", body: "Whatever is named as the object, the two conditions still apply: it must be genuinely desirable, and what replaces it must be better in his own estimation." },
    ],
    closer: [
      { title: "The link back to Book 26", body: "That book distinguished the world as fruit, as means, and as attachment. This section is the same distinction applied to the question of what a detached person has actually turned from." },
      { title: "Why the object has to be specified", body: "Because a person can perform an impressive renunciation of what he never wanted, and the first condition of the definition is designed to catch exactly that." },
    ],
    distinction: ["Two things called the world", "The portion", "What a person takes as his own and would be pained to lose, which is what can be left.", "The creation", "What exists, which is not what any of this material is about."],
    misreading: "Do not extend the object to what is genuinely necessary. Ghazali devotes a section to the necessities precisely because they are not simply to be abandoned.",
    reflection: "List what you would be pained to lose. That list is the object, and it is rarely only property.",
    audit: ["What would I be pained to lose?", "How much of it is not property?", "What have I renounced that I never wanted?", "Which arrangement around me is a portion?"],
    nodes: ["zuhd", "world"],
    model: pair("Specifying the object", "The first condition of the definition is what makes this necessary.", [["Genuinely wanted", "What a person would be pained to lose, which is what leaving costs something.", "balance"], ["Never wanted", "What can be renounced impressively at no cost, which fails the condition.", "warning"]]),
  }),
  makeChapter({
    id: 15, shortTitle: "Sorted by the object", formalTitle: "The division of abstinence according to the kinds of what is left",
    overview: "Having named the object, Ghazali sorts detachment by its kinds, so that a person's condition can be described in one area rather than as a single verdict.",
    thesis: "Detachment is sorted by kind, so that it can be located rather than merely aspired to.",
    moves: [
      { title: "Sort by kind", body: "Detachment is divided according to the kinds of thing turned from, so that a person may be detached in one and not in another." },
      { title: "Make it a description rather than a verdict", body: "The sorting converts a single judgment into a set of specific ones, which is how the partial degree of the previous section becomes usable." },
      { title: "Follow the rulings", body: "Different kinds carry different considerations, since what is permitted, necessary, or merely customary differs across them." },
      { title: "Prepare the necessities", body: "The sorting leads directly to the question the next sections take up: what happens where the thing in question cannot be dispensed with at all." },
    ],
    closer: [
      { title: "Why sorting beats ranking", body: "A person told he is or is not detached learns nothing actionable. A person shown that he is detached in four kinds and not in a fifth knows where the work is." },
      { title: "The recurring method", body: "This is the same move Book 22 made with the names of character and Book 32 with the names of patience: one capacity, described by where it is exercised." },
    ],
    distinction: ["Two ways to describe a state", "By kind", "Detached in these areas and not in those, which locates the work.", "As a whole", "Detached or not, which is unanswerable and tells a person nothing."],
    misreading: "Do not use the sorting to grant yourself the name on the strength of one area. The point of sorting is to make the untouched areas visible.",
    reflection: "Sort your own case across the kinds, and notice which one you left off the list.",
    audit: ["In which kinds am I actually detached?", "Which did I not think to include?", "Where is the exchange still unmade?", "What am I counting once and claiming across the board?"],
    nodes: ["zuhd", "kinds"],
    model: chain("From verdict to description", "The sorting is what makes the state workable.", [["A single verdict", "Detached or not, which no one can answer honestly.", "warning"], ["Sorted by kind", "Detached here and not there, across the areas that exist.", "balance"], ["The work located", "The untouched kinds become visible and can be addressed.", "support"]]),
  }),
  makeChapter({
    id: 16, shortTitle: "What cannot be left", formalTitle: "Abstinence in what is necessary for life",
    overview: "The hardest case for a doctrine of detachment: things that cannot be dispensed with. Ghazali does not resolve it by pretending they can be.",
    thesis: "The hardest case for any doctrine of detachment: the things nobody can do without.",
    moves: [
      { title: "Pose the difficulty", body: "Food, clothing, and shelter cannot be abandoned, so detachment with respect to them cannot mean going without them." },
      { title: "Relocate the exchange", body: "What can be exchanged is not the thing but the measure and the attachment, which returns the reader to the measures of Book 23 and the restricted blessings of Book 32." },
      { title: "Name the six", body: "Ghazali lists the necessities that require this treatment: food, clothing, dwelling, its furnishings, what is married, and what is possessed, and takes each in turn." },
      { title: "Give the principle", body: "In each, detachment is having no more than the need requires and no attachment to what is had, which is a workable standard where abandonment is not." },
    ],
    closer: [
      { title: "Why this is the longest stretch of the book", body: "Because it is where detachment meets ordinary life. The preceding analysis is what makes the detail intelligible, and the detail is what makes the analysis usable." },
      { title: "The consistency with Book 32", body: "A necessity is a restricted blessing: a good from one aspect and a burden from another. Both duties fall on it, and detachment here is the form gratitude and patience take together." },
    ],
    distinction: ["Two ways to be detached from a necessity", "In measure and attachment", "No more than the need requires, and no holding on to what is had.", "By abandonment", "Going without it, which is impossible for a necessity and is not what is being asked."],
    misreading: "Do not read this as licence to keep whatever you call necessary. The measure is set by the need, and the sections on food in Book 23 show how exacting that can be.",
    reflection: "Take one of the six and ask what the need actually requires, as against what you have.",
    audit: ["Which of the six is furthest from its measure?", "What am I calling necessary?", "Am I attached to what I genuinely need?", "Where would less be enough?"],
    nodes: ["zuhd", "necessities", "measure"],
    model: chain("Detachment where abandonment is impossible", "The exchange moves from the thing to the measure.", [["The thing", "Cannot be abandoned, since the need is real.", "balance"], ["The measure", "Reduced to what the need requires, which is exchangeable.", "support"], ["The attachment", "Released, which is the part that was the portion all along.", "support"]]),
  }),
  makeChapter({
    id: 17, shortTitle: "The six in detail", formalTitle: "Detachment in food, clothing, dwelling, furnishings, and what is possessed",
    overview: "The longest stretch of the book, in which the principle is applied to each necessity in turn, with the concreteness that makes the rest of the analysis operable.",
    thesis: "The principle is applied across food, clothing, housing and furnishing — the longest stretch of the book.",
    moves: [
      { title: "Work through each", body: "Each of the six is taken separately, since the measure of need differs and what counts as excess in one is not what counts in another." },
      { title: "Give concrete measures", body: "The treatment is specific rather than exhortatory, as with the four measures of eating in Book 23, so that a reader can locate himself." },
      { title: "Keep the two variables", body: "In every case the two questions are the same: how much the need requires, and what the attachment is to what is held." },
      { title: "Expect the reader to fail somewhere", body: "The detail exists so that a person who is detached in five of the six can see the sixth, which is the purpose the sorting section already established." },
    ],
    closer: [
      { title: "Why the concreteness matters", body: "Without it, detachment remains an attitude a person can claim. With the measures specified, it becomes a set of conditions he can check, which is the difference this book keeps insisting on." },
      { title: "The accounts gathered here", body: "Ghazali fills this stretch with reports of how particular people lived, which function as worked examples of the measures rather than as feats to be admired." },
    ],
    distinction: ["Two ways to read the detail", "As measures", "Concrete standards against which a person locates his own case.", "As feats", "Impressive lives to be admired, which leaves the reader's own case untouched."],
    misreading: "Do not treat the strictest examples as the standard for everyone. Ghazali has already established that the measure follows the need, and needs differ by person and circumstance.",
    reflection: "Pick the necessity you are least detached in and set one concrete measure for it this week.",
    audit: ["Which of the six did I skip?", "What measure could I set concretely?", "Am I admiring these accounts instead of applying them?", "What would I be unwilling to reduce?"],
    nodes: ["zuhd", "necessities", "measure"],
    model: chain("The six necessities", "Each is taken separately because the measures differ.", [["Food", "The measures of Book 23 apply directly here.", "balance"], ["Clothing", "Between the two shows, neither fine nor conspicuously poor.", "balance"], ["Dwelling and furnishings", "What shelter requires, against what is accumulated in it.", "balance"], ["What is possessed", "Including people and relations, where the attachment is hardest to see.", "warning"]]),
  }),
  makeChapter({
    id: 18, shortTitle: "How it is recognised", formalTitle: "The signs of abstinence",
    overview: "The book closes as Book 22 did, with signs, because a state that only its holder can see needs an external test if it is to be checked at all.",
    thesis: "The book closes with signs, because a state only its holder can see needs an external test to be checkable at all.",
    moves: [
      { title: "State the need for signs", body: "Since detachment is an inward exchange, a person can claim it without having made it, and the signs are what make the claim checkable." },
      { title: "Give the governing sign", body: "The clearest is indifference between having and not having: whether the arrival or departure of a thing changes the person, which is the sixth state named at the very start of the book." },
      { title: "Add the behavioural signs", body: "The rest concern what a person does when what he claims to have left is offered, praised, or taken away, since each of those is a test the claim has to survive." },
      { title: "Close the two halves together", body: "The signs of detachment are the same test the five states of poverty were sorted by, which is why the book treats both under one cover." },
    ],
    closer: [
      { title: "The sign that closes the circle", body: "The first section named a state above all five in which the presence and absence of wealth are equal. The last section makes that the sign of detachment, so the book ends where it began with the ladder complete." },
      { title: "What the reader is left holding", body: "Two ladders that turn out to be one: five states toward what is absent, and three degrees toward what is exchanged, both read by the same question about what a change in circumstance would do." },
    ],
    distinction: ["Two responses to a change of circumstance", "Unchanged", "Arrival and departure make no difference, which is the sign the book ends on.", "Moved", "The person is altered by which way the circumstance went, and the claim has not survived."],
    misreading: "Do not treat indifference as a pose to be adopted. It is named as a sign of a state, and performing the sign without the state is what Book 30 spends its length examining.",
    reflection: "Imagine what you have left being offered back to you today, and watch what moves.",
    audit: ["What would move in me if it came back?", "What moves when it is praised?", "What moved when it was taken?", "Am I performing a sign or reporting one?"],
    nodes: ["zuhd", "signs", "five-states"],
    model: pair("The sign the book closes on", "It is the same test the book opened with.", [["Equal either way", "Arrival and departure change nothing, which is the state above the five.", "support"], ["Changed by which way", "The circumstance still governs, and the exchange has not been made.", "warning"]]),
  }),
];

export const book34ConceptNodes: ConceptNode[] = [
  ["faqr", "Poverty", "Lacking what you need", "Lacking what is not needed is not poverty, and what is within reach is not lacked."],
  ["five-states", "Five states", "One circumstance, five dispositions", "Detached, pleased, satisfied, grasping, compelled, with a sixth above them all."],
  ["wealth", "Wealth", "Compared by tendency", "The comparison is between what each condition tends to make of a person."],
  ["adab", "Conduct", "Protecting the state", "The manners exist to keep the disposition that made the condition praiseworthy."],
  ["giving", "Receiving", "Unasked is a separate case", "Both accepting and refusing can be the fault, and each needs its reason."],
  ["asking", "Asking", "Forbidden, with an exception", "What it does to the asker matters as much as what it takes from the giver."],
  ["necessity", "Necessity", "The bounded exception", "Genuine and otherwise unmeetable need permits asking, under conditions."],
  ["sufficiency", "Sufficiency", "Kinds, amounts, times", "No single figure, because a need is a relation rather than a quantity."],
  ["zuhd", "Abstinence", "An exchange, not an absence", "Turning desire from a thing toward what is better than it."],
  ["exchange", "The exchange", "Two conditions", "What is left must be wanted, and what is taken must be better in your own estimation."],
  ["conditions", "The conditions", "Why stones do not count", "Leaving what was never desired fails the first condition of the name."],
  ["degrees", "Three degrees", "Graded by what is taken", "For God alone, for the hereafter's portions, or in part only."],
  ["world", "The portion", "Not the creation", "What a person takes as his own and would be pained to lose."],
  ["kinds", "Kinds", "Description, not verdict", "Detached here and not there, which is what locates the work."],
  ["necessities", "The six", "Where abandonment is impossible", "Food, clothing, dwelling, furnishings, and what is possessed."],
  ["measure", "The measure", "What the need requires", "Where the thing cannot be left, the measure and the attachment can."],
  ["signs", "The signs", "Unmoved either way", "Whether arrival and departure change the person is the test the book ends on."],
].map(([id, label, kicker, description], index) => ({ id, label, kicker, description, position: ["left", "right", "top", "bottom"][index % 4] }));

const node = (id: string, label: string, micro: string, summary: string, guardrail: string, chapterId: number, glyph: Journey["nodes"][number]["glyph"]): Journey["nodes"][number] => ({ id, label, micro, summary, guardrail, chapterId, glyph });

export const book34Journeys: Journey[] = [
  {
    id: "which-poor", number: "01", question: "What kind of not-having is mine?", title: "Place yourself on the five states",
    description: "Define poverty precisely, watch the definition make everything but God poor, then narrow to wealth and sort the five dispositions that share one empty hand.",
    payoff: "You stop describing a circumstance and start describing a state you can work on.",
    image: assetUrl("assets/system/book34-five-states.jpg"), imageAlt: "Five identical ivory alcoves along a sunlit wall, each holding an empty brass bowl turned to a slightly different angle.", minutes: 12, color: "#278d91",
    nodes: [
      node("define-faqr", "Define it", "Lacking what you need", "What is not needed is not lacked, and what is within reach is not absent.", "The definition makes everything but God poor before it narrows.", 1, "name"),
      node("narrow-subject", "Narrow the subject", "Poverty of wealth", "A servant's needs have no limit; this book treats the part reached by money.", "The wider sense is granted and set aside.", 1, "clear"),
      node("sort-five", "Sort the five", "One hand, five states", "Detached, pleased, satisfied, grasping, compelled.", "What is graded is the disposition, not the balance.", 1, "pattern"),
      node("find-sixth", "Find the sixth", "Equal either way", "Above detachment, a state in which presence and absence are the same.", "Marked as the summit rather than the ordinary target.", 1, "steady"),
      node("place-praise", "Place the praise", "Not on the circumstance", "The commendation narrows to the pleased, the satisfied, and the truthful.", "This narrowing is what makes it usable.", 3, "balance"),
    ],
  },
  {
    id: "poor-or-rich", number: "02", question: "Is it better to have less?", title: "Compare the matched cases",
    description: "Take the general precedence of poverty over wealth, then test it in the only honest form: the satisfied poor man against the grateful rich man.",
    payoff: "You get a comparison you can actually place yourself in rather than a slogan.",
    image: assetUrl("assets/system/book34-matched-pair.jpg"), imageAlt: "A bright marble court where two identical brass scales stand level, one bearing a full vessel and one an empty one.", minutes: 12, color: "#586fa8",
    nodes: [
      node("state-precedence", "Take the precedence", "By tendency", "Poverty is given precedence for what the conditions tend to make of a person.", "A claim about tendencies, not about persons.", 4, "know"),
      node("match-the-cases", "Match the cases", "Best against best", "The satisfied poor man set against the grateful rich man, so neither side is its failure.", "Unmatched comparisons settle nothing.", 5, "balance"),
      node("four-positions", "Find the four", "Two conditions, two states each", "Satisfied poor, grasping poor, grateful rich, ungrateful rich.", "Only one of the four is yours.", 5, "pattern"),
      node("read-book-32", "Read it with Book 32", "Gratitude is right use", "The grateful rich man is the one using it for what it was given for.", "Wealth held without that use is the fourth position.", 5, "know"),
      node("locate-yourself", "Locate yourself", "Which of the four", "The comparison is worth making only where you actually stand.", "Comparing your best case to another's worst decides nothing.", 5, "mirror"),
    ],
  },
  {
    id: "asking-and-taking", number: "03", question: "May I take it, and may I ask?", title: "Separate receiving from seeking",
    description: "Work the conduct of poverty: what to do with a gift that arrives unasked, when asking is forbidden and when it is permitted, and how much counts as enough.",
    payoff: "Two acts that are constantly confused become separately decidable.",
    image: assetUrl("assets/system/book34-open-hand.jpg"), imageAlt: "An ivory threshold where a covered dish rests unattended beside a closed door and an open one.", minutes: 14, color: "#c25f50",
    nodes: [
      node("protect-state", "Protect the state", "Not the appearance", "The manners exist to keep the disposition rather than to display the condition.", "Concealing genuine need is not what is asked.", 6, "guard"),
      node("unasked-gift", "Decide an unasked gift", "Both answers need reasons", "Whose purpose, what it places you under, and what accepting would do to your state.", "Refusing can itself be a display.", 7, "balance"),
      node("prohibit-asking", "See why asking is forbidden", "What it does to the asker", "It places a person under obligation and installs the habit of looking to people.", "The prohibition is not about the giver's inconvenience.", 8, "know"),
      node("admit-necessity", "Admit necessity", "The fifth state", "Genuine and otherwise unmeetable need permits asking, with conditions.", "Need is not treated as a failure of state.", 8, "clear"),
      node("measure-enough", "Measure enough", "Kinds, amounts, times", "No single figure, but three considerations concrete enough to apply.", "The absence of a figure is not the absence of a boundary.", 9, "diagnose"),
    ],
  },
  {
    id: "what-is-zuhd", number: "04", question: "What does detachment actually mean?", title: "Find the exchange inside it",
    description: "Take the definition that reframes the second half: detachment is not the absence of desire but its redirection, with two conditions that make it checkable.",
    payoff: "You can tell whether you have made an exchange or only undergone a loss.",
    image: assetUrl("assets/system/book34-the-exchange.jpg"), imageAlt: "A sunlit market sill where one hand's worth of coins lies beside a sealed letter, the coins pushed slightly away.", minutes: 13, color: "#bf7a35",
    nodes: [
      node("define-zuhd", "Define it", "Turning toward what is better", "Desire turns from a thing toward what is better than it, and both sides are present.", "It is one act described from two ends.", 11, "name"),
      node("first-condition", "Apply the first condition", "Leaving stones is not it", "What is left must be genuinely desirable, or the name does not apply.", "This catches renunciation of what was never wanted.", 11, "diagnose"),
      node("second-condition", "Apply the second", "Better in your estimation", "What is taken must be better to you, so that the desire for it prevails.", "A seller does not sell unless the price is better to him.", 11, "balance"),
      node("read-the-praise", "Read the praise through it", "Valuing, not suffering", "Every commendation of leaving the world urges taking something judged better.", "Deprivation without an exchange falls outside the name.", 12, "mirror"),
      node("grade-degrees", "Grade the degrees", "By what you took", "For God alone, for the hereafter's portions, or in part only.", "The partial degree is named as detachment, not excluded.", 13, "pattern"),
    ],
  },
  {
    id: "what-cannot-leave", number: "05", question: "What about what I cannot give up?", title: "Move the exchange to the measure",
    description: "Face the hardest case for detachment, follow Ghazali through the six necessities, and end on the sign that tests whether any of it was real.",
    payoff: "Detachment becomes something you can practise in the things you cannot abandon.",
    image: assetUrl("assets/system/book34-the-measure.jpg"), imageAlt: "A bright pantry sill holding six graduated vessels, each filled to a different marked line, with a plain cloth folded beside them.", minutes: 15, color: "#a97837",
    nodes: [
      node("pose-difficulty", "Pose the difficulty", "Food cannot be abandoned", "Detachment in a necessity cannot mean going without it.", "The difficulty is genuine and is not dissolved by rhetoric.", 16, "diagnose"),
      node("move-exchange", "Move the exchange", "To measure and attachment", "What is exchangeable is not the thing but how much and how held.", "This is the form gratitude and patience take together.", 16, "balance"),
      node("work-the-six", "Work the six", "Each measured separately", "Food, clothing, dwelling, furnishings, and what is possessed.", "The measure follows the need, which differs by person.", 17, "order"),
      node("sort-by-kind", "Sort by kind", "Description, not verdict", "Detached in some areas and not others, which is what locates the work.", "One area does not earn the name across the board.", 15, "pattern"),
      node("test-the-sign", "Test the sign", "Unmoved either way", "Whether arrival and departure change you is the test the book ends on.", "Performing the sign without the state is Book 30's subject.", 18, "witness"),
    ],
  },
];

export const book34Movements: TaxonomyGroup[] = [
  ["reality-faqr", "1. The reality of poverty", "The definition, and the five states of one who lacks.", [1]],
  ["excellence-faqr", "2. The excellence of poverty", "The testimony, read after the five states.", [2]],
  ["which-poor", "3. Which poor are praised", "The pleased, the satisfied, and the truthful.", [3]],
  ["over-wealth", "4. Poverty over wealth", "A precedence about tendencies rather than persons.", [4]],
  ["matched", "5. The matched pair", "Satisfied poor against grateful rich.", [5]],
  ["manners", "6. Conduct in poverty", "Protecting the state rather than displaying the condition.", [6]],
  ["receiving", "7. Receiving unasked", "Where both accepting and refusing need reasons.", [7]],
  ["asking", "8. Asking", "Forbidden without necessity, permitted with conditions.", [8]],
  ["sufficiency", "9. How much is enough", "Kinds, amounts, and times instead of a figure.", [9]],
  ["askers", "10. Those who ask", "Sorting the askers as the lacking were sorted.", [10]],
  ["reality-zuhd", "11. The reality of abstinence", "An exchange, with two conditions on it.", [11]],
  ["excellence-zuhd", "12. The excellence of abstinence", "The testimony, read through the exchange.", [12]],
  ["degrees-zuhd", "13. Degrees of abstinence", "Graded by what is turned toward.", [13]],
  ["object", "14. What is left", "The portion rather than the creation.", [14]],
  ["kinds", "15. Sorted by kind", "Detached here and not there.", [15]],
  ["necessary", "16. What cannot be left", "Moving the exchange to measure and attachment.", [16]],
  ["six", "17. The six necessities", "Food, clothing, dwelling, furnishings, and what is possessed.", [17]],
  ["signs", "18. The signs of abstinence", "Unmoved by arrival or departure.", [18]],
].map(([id, label, description, chapterIds], index) => ({ id, label, description, chapterIds, color: ["#bf7a35", "#278d91", "#c25f50", "#586fa8", "#a97837"][index % 5] })) as TaxonomyGroup[];

export const book34Instrument: Instrument = {
  title: "Two ladders, one question",
  note: "Ghazali sorts those who lack into five states and grades abstinence by what a person turned toward. Both ladders are read by the same question: what would a change of circumstance actually do to you. Place yourself on each, honestly rather than aspirationally.",
  items: [
    {
      id: "case", label: "Your own case", lede: "Something you do not have, and something you have left",
      note: "The five states are Ghazali's own, from the opening of Part One. The exchange axis is the definition of abstinence from the opening of Part Two, where leaving something is only detachment if something better was taken.",
      axes: [
        {
          id: "lacking", kicker: "The five states", question: "Toward something you do not have, which of these is actually true?",
          options: [
            { id: "compelled", label: "I genuinely cannot do without it", note: "The fifth state. Ghazali treats this as need rather than as a failure, and permits asking under conditions." },
            { id: "grasping", label: "I would seek it if I could", note: "The fourth. Refraining from inability rather than from disposition, which opportunity would immediately reveal." },
            { id: "satisfied", label: "I would take it if it came easily", note: "The third. Having it is preferred, but not enough to make you seek it." },
            { id: "pleased", label: "It genuinely does not move me", note: "The second. Neither rejoicing at it nor pained by its absence." },
            { id: "detached", label: "I would rather it did not come", note: "The first. Wealth would be disliked and fled, for what it brings with it." },
          ],
        },
        {
          id: "exchange", kicker: "The exchange", question: "For something you have left, what did you take instead?",
          options: [
            { id: "nothing-left", label: "I have not left anything", note: "The axis does not apply yet, which is itself an honest answer." },
            { id: "nothing", label: "Nothing; I simply lost it", note: "A loss rather than an exchange, which fails the definition of the name." },
            { id: "worse", label: "Something I value less", note: "The exchange ran the wrong way, which Ghazali says makes a person detached in the other direction." },
            { id: "better", label: "Something genuinely better to me", note: "Both conditions met: what was left was wanted, and what was taken is better in your own estimation." },
          ],
        },
      ],
      verdicts: [
        { key: "compelled|*", name: "This is need, not a rung", role: "balance", chapterId: 8, body: "Genuine necessity is the fifth state, and Ghazali does not treat it as a failure of disposition. It is the case in which the prohibition on asking does not hold.", action: "Meet the need. The sections on asking give the conditions, and the measure of sufficiency is set by kinds, amounts, and times rather than by a figure. Nothing in the ladder asks you to endure a need you could meet." },
        { key: "grasping|*", name: "The fourth state", role: "warning", chapterId: 1, body: "Refraining from inability is not the same as refraining from disposition, and Ghazali places it below the states the praise attaches to. Opportunity would reveal the difference immediately.", action: "The honest move is to stop describing this as contentment. The work is on the wanting rather than on the circumstance, since the circumstance is not what is being graded." },
        { key: "satisfied|nothing", name: "A loss, not an exchange", role: "warning", chapterId: 11, body: "You are on the third rung toward what you lack, and what you left was lost rather than exchanged. On the definition, that is not what the word abstinence names.", action: "Name what you would take instead, and ask whether it is genuinely better to you. Ghazali is explicit that leaving a beloved thing without something more beloved is impossible, so an unnamed exchange usually means a loss being described as a virtue." },
        { key: "satisfied|better", name: "A real exchange, from the third rung", role: "support", chapterId: 13, body: "You would take it if it came easily and you have made a genuine exchange elsewhere. Both are real positions and neither is the summit.", action: "The degrees of abstinence are graded by what you took. Ask whether what you turned toward is of another kind, or a better version of the same portion expected elsewhere, since Ghazali ranks those differently." },
        { key: "*|worse", name: "The exchange ran backwards", role: "warning", chapterId: 11, body: "Something was left and something less was taken. Ghazali's definition is symmetrical: whoever sells the hereafter for the world is also detached, but in the hereafter.", action: "Name both sides of the trade plainly. The definition makes the direction visible, and that visibility is most of what it is for." },
        { key: "*|nothing", name: "Name what you took", role: "balance", chapterId: 11, body: "Leaving something without taking anything fails the second condition of the definition, and Ghazali says the thing is not merely unnamed but impossible: a beloved thing is not left except for something more beloved.", action: "If you cannot name what you took, look again. Either the thing left was never wanted, which fails the first condition, or something was taken that you have not admitted to yourself." },
        { key: "*|nothing-left", name: "Start with the first ladder", role: "balance", chapterId: 1, body: "The exchange axis has nothing to read yet, which is a legitimate answer. What remains is your position on the five states, and that is where the book asks you to begin.", action: "The five states are sorted by disposition rather than circumstance, so the work is available now. Ghazali's narrowing of the praise to the pleased and the satisfied is where the target sits." },
        { key: "pleased|better", name: "Both ladders holding", role: "support", chapterId: 18, body: "Not moved by what is absent, and a genuine exchange behind what was left. Ghazali's sign for abstinence is exactly this indifference between having and not having.", action: "Test it rather than resting on it. Imagine what you left being offered back today and watch what moves; the book closes on that test because a state only its holder can see needs one." },
        { key: "detached|better", name: "Test the claim", role: "support", chapterId: 18, body: "You place yourself on the first rung and report a genuine exchange. Ghazali names a state above even this, in which presence and absence are simply equal, and he treats the summit as rare.", action: "The signs section exists for this claim specifically. Watch what happens when the thing is offered, when it is praised, and when it is taken, since each of those is a test the claim has to survive." },
        { key: "*|*", name: "Read both together", role: "balance", chapterId: 5, body: "The two ladders do not report the same thing, which is ordinary. One describes what you are toward what you lack, and the other what you did with what you left.", action: "Take the lower of the two readings as the honest one and work there. Ghazali's whole method in this book is that the circumstance is identical across states, so only the disposition is worth examining." },
      ],
    },
  ],
};

export const book34Sources: SourceLink[] = [
  { label: "Primary Arabic text", note: "The complete public Arabic of Book 34 was read in full and used to establish the five states of the poor, the conditions on asking, the definition of abstinence as an exchange, and the treatment of the necessities.", url: "https://shamela.ws/book/9472/1348" },
  { label: "The five states", note: "The passage defining poverty, drawing the consequence that everything but God is poor, and sorting those who lack wealth into five states with a sixth above them.", url: "https://shamela.ws/book/9472/1349" },
  { label: "Abstinence as an exchange", note: "The passage defining abstinence as turning desire from a thing toward what is better, with the two conditions and the Quranic usage of Joseph's brothers.", url: "https://shamela.ws/book/9472/1375" },
  { label: "Forty-book structure", note: "Ghazali.org's listing places Book 34 as the fourth book of the Quarter of Deliverance and confirms its title.", url: "https://www.ghazali.org/listing-the-forty-books/" },
];

export const book34: SystemBook = {
  id: 34,
  title: "Poverty and Abstinence",
  shortTitle: "Poverty and Abstinence",
  defaultJourneyId: "which-poor",
  chapters: book34Chapters,
  conceptNodes: book34ConceptNodes,
  journeys: book34Journeys,
  sources: book34Sources,
  taxonomy: {
    title: "Eighteen source movements",
    note: "Ten movements on poverty and eight on abstinence, following Ghazali's two parts. His treatment of the six necessities runs far longer than any other stretch and is presented as two consecutive readings, the principle and its application.",
    groups: book34Movements,
  },
  instrument: book34Instrument,
  editorialNote: "The five journeys, eighteen reading sections, visual models, and two-ladder diagnostic are editorial learning aids. The sequence preserves Ghazali's two parts, poverty first and then abstinence. The English is an original synthesis made from a complete reading of the public Arabic text, not a translation and not a substitute for one. Reports and inherited anecdotes are presented as material Ghazali transmitted; this prototype does not independently grade every narration. This book praises poverty and treats asking as forbidden outside necessity; both are presented as Ghazali's analysis of inward states, and neither is offered as social or economic counsel. He is explicit that genuine need permits asking and that the compelled state is not a failure of disposition, and nothing here asks anyone to endure a need they could meet. The diagnostic places a state so that work can begin. It cannot pronounce on anyone's standing, and questions about what is owed, permitted, or required in a particular material situation need the complete Arabic, a reliable full edition, and qualified guidance.",
};
