import { assetUrl } from "./assetUrl";
import type { Chapter, ConceptNode, VisualModel } from "./data";
import type { Instrument, Journey, SourceLink, SystemBook, TaxonomyGroup } from "./systemTypes";

type Seed = { id: number; shortTitle: string; formalTitle: string; overview: string; thesis?: string; moves: Array<{ title: string; body: string }>; closer: Array<{ title: string; body: string }>; distinction: [string, string, string, string, string]; misreading: string; reflection: string; audit: string[]; nodes: string[]; model: VisualModel };
const part = (id: number) => (id <= 6 ? "Part One, on intention" : id <= 11 ? "Part Two, on sincerity" : "Part Three, on truthfulness");
const makeChapter = (seed: Seed): Chapter => ({
  id: seed.id, shortTitle: seed.shortTitle, formalTitle: seed.formalTitle, overview: seed.overview,
  reflection: seed.reflection, relatedNodes: seed.nodes, visualModel: seed.model,
  deep: { thesis: seed.thesis ?? seed.moves[0].body, context: seed.overview, moves: seed.moves, closeReading: seed.closer,
    distinction: { title: seed.distinction[0], firstLabel: seed.distinction[1], first: seed.distinction[2], secondLabel: seed.distinction[3], second: seed.distinction[4] },
    misreading: seed.misreading, observation: seed.reflection, selfAudit: seed.audit,
    sourceAnchor: `Book 37, ${part(seed.id)}, ${seed.formalTitle}.` },
});
const chain = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "chain", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const pair = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "pair", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const spectrum = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "spectrum", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });

export const book37Chapters: Chapter[] = [
  makeChapter({
    id: 1, shortTitle: "Why intention matters", formalTitle: "Why intention is so valuable",
    overview: "The book opens with the most famous saying in the tradition: “Actions are only by intentions.” Ghazali gathers what the Quran and the Prophet say about intention — and warns straight away that this saying is easy to misuse.",
    thesis: "What a person means by an action decides its worth — so intention, sincerity and truthfulness have to be understood, not just claimed.",
    moves: [
      { title: "A chain of warnings", body: "Ghazali opens with a sharp chain. People are lost, except those who know. Those who know are lost, except those who act. Those who act are lost, except the sincere. And the sincere are in great danger. Action without intention is wasted effort. Intention without sincerity is showing off. And sincerity without truthfulness is dust in the wind." },
      { title: "Three parts, one subject", body: "So the book has three parts: intention, sincerity and truthfulness. They aren't three separate topics. Sincerity turns out to be pure intention, and one of the meanings of truthfulness turns out to be sincerity. Each part goes deeper into the one before." },
      { title: "The famous saying", body: "The Prophet said, “Actions are only by intentions, and each person gets what they intended. Whoever emigrated for God and His Messenger, their emigration is for God and His Messenger. Whoever emigrated for some worldly gain, or to marry a woman, their emigration is for what they emigrated for.” One man who emigrated to marry a woman named Umm Qays became known as “the emigrant of Umm Qays”." },
      { title: "God looks at hearts", body: "The Prophet said, “God does not look at your appearance or your wealth. He looks at your hearts and your deeds.” Ghazali says He looks at hearts because that is where intention lives. And the Prophet said that when two Muslims fight with swords, both killer and killed are in the Fire — the one killed, “because he wanted to kill his companion.”" },
      { title: "Sharing a reward you couldn't earn", body: "On an expedition, the Prophet said, “There are people back in Medina who have been with us in every valley we crossed and every hardship we faced.” How, if they stayed home? “An excuse held them back, and they shared with us through their good intention.” He also described a man who wishes he had money to spend in good ways like a generous rich man — “and the two are equal in reward.”" },
      { title: "The man and the sand", body: "A report says a man passed great dunes of sand during a famine and thought, “If this sand were food, I would share it out among the people.” God told their prophet: “Tell him: God has accepted your charity, thanked your good intention, and given you the reward as if it had been food and you had given it away.”" },
      { title: "What the early Muslims said", body: "Sufyan al-Thawri said, “They used to learn intention for their deeds the way you learn the deeds themselves.” Someone said, “Many a small deed is made great by its intention, and many a great deed is made small by its intention.” And a report from the Torah says, “Whatever is done for My sake, a little of it is a lot. Whatever is done for someone else, a lot of it is a little.”" },
    ],
    closer: [
      { title: "The seeker who wanted to always be working", body: "A seeker went from scholar to scholar asking, “Who can show me a deed that keeps me working for God every hour of the day and night?” He was told, “Do all the good you can. When you get tired or stop, keep intending to do it — because someone who intends good is like someone who does it.”" },
      { title: "The danger ahead", body: "“Actions are only by intentions” is the easiest saying to misuse. Read carelessly, it seems to say that meaning well is all that matters. Two later sections close the two usual misreadings: that a good intention can turn a wrong act into a good one, and that you can create an intention just by saying it to yourself." },
    ],
    distinction: ["Two ways to take the famous saying", "As something to understand", "An action's worth comes from its motive — which means you need to know what a motive is.", "As an excuse", "Anything is fine if you meant well — which the book spends two sections refusing."],
    misreading: "Don't read the opening as settling everything. Almost every practical question the saying raises is answered later, and several of the answers are strict.",
    reflection: "Think about how you have used “actions are only by intentions” in the past — to look harder at yourself, or to let yourself off.",
    audit: ["Have I used this saying as an excuse?", "What do I think an intention actually is?", "What good am I intending that I can't yet do?", "Which of the three — intention, sincerity, truthfulness — do I most need?"],
    nodes: ["niyya", "structure"],
    model: chain("Three parts, one inside the next", "Each part turns out to sit inside the next one.", [["Intention", "The heart being stirred toward what it sees will serve its goal.", "support"], ["Sincerity", "That stirring made pure, with nothing mixed in. Sincerity is a quality of an intention.", "support"], ["Truthfulness", "Six meanings, one of which is sincerity itself.", "support"]]),
  }),
  makeChapter({
    id: 2, shortTitle: "What intention is", formalTitle: "What intention really is",
    overview: "Ghazali defines intention by looking at how any deliberate action happens. That definition is what lets him say later that you can't simply create an intention by deciding to have one.",
    thesis: "Intention is the heart being moved toward something it sees as good for it — it sits between knowing, which comes before it, and acting, which follows it.",
    moves: [
      { title: "Three words, one thing", body: "Intention, will and purpose are different words for the same thing: a state of the heart. Knowledge comes before it, as its root. Action comes after it, as its fruit. That order matters for the whole book." },
      { title: "What any action needs", body: "Every deliberate action — every chosen movement or stillness — needs three things: knowledge, will and ability. You can't want something you don't know about, so knowledge is needed. You don't act unless you want to, so will is needed. And you need the power to do it." },
      { title: "Seeing isn't wanting", body: "People are made so that some things suit them and some harm them. So they need to recognise which is which: you can't reach for food you can't see, or run from a fire you can't see. But knowing isn't enough. A sick person can see food and know it's good for them, and still not eat, because they have no appetite. What moves you is the pull toward the thing." },
      { title: "Wanting isn't doing", body: "And wanting isn't enough either. Someone disabled may see food, want it, and still be unable to reach it. So God created the ability and the limbs. Ghazali traces the chain: the limbs wait for ability, ability waits for the pull, and the pull waits for knowing — or believing — that something is good for you." },
      { title: "The definition", body: "So intention is the middle link: the heart being stirred and moved by desire toward something that suits its purpose, now or later. The first mover is the purpose itself. Being stirred toward it is the intention. And the limbs moving to serve that stirring is the action." },
      { title: "One motive or two", body: "Sometimes one motive moves you. Sometimes two join together. Ghazali says there are four ways this happens, like people carrying a load. It can be one person alone, or two strong people who could each carry it. It can be two weak people who can only carry it together, or a strong person helped by a weak one. The next section explains each." },
    ],
    closer: [
      { title: "Why the order matters", body: "Because intention sits after knowing and before doing, you can't reach it directly. You can only work on what you know and believe, and on what distracts you. That is why a later section says an intention can't be produced just by announcing it." },
      { title: "Not a moment of resolve", body: "Ghazali's definition is not a mental act you perform before doing something. It is a real movement of the heart, with knowledge behind it and action in front of it." },
    ],
    distinction: ["Two things you can have about an action", "Knowing it's good", "Available by learning — and on its own it moves nothing, as the sick person shows.", "Being drawn to it", "The pull that actually produces the action — which learning alone doesn't give you."],
    misreading: "Don't think of intention as saying “I intend…” in your head before you act. Ghazali defines it as a real movement of the heart, which is a different thing.",
    reflection: "Take something you know is good but haven't done, and notice which part is missing: knowing, wanting, or being able.",
    audit: ["Which of the three is missing here?", "Do I know it's good but feel no pull toward it?", "Have I mistaken a thought for an intention?", "What would give me the pull?"],
    nodes: ["niyya", "irada", "knowledge"],
    model: chain("What every chosen act needs", "Take away any one of the three, and nothing happens.", [["Knowledge", "You can't want what you don't know, which is why knowing is the root and condition.", "support"], ["Will", "The heart stirred toward what will serve its goal, now or later.", "support"], ["Power", "The ability without which wanting produces no action.", "support"]]),
  }),
  makeChapter({
    id: 3, shortTitle: "Mixed motives", formalTitle: "The kinds of intention",
    overview: "An action takes its value from the motive behind it. But motives often come in pairs. Ghazali names four patterns — with everyday examples — and this sorting becomes the key to the rest of the book.",
    thesis: "An action follows the motive behind it; when two motives combine, the second is either a partner that could act alone, a helper that makes it easier, or a co-worker neither could act without.",
    moves: [
      { title: "One motive: pure", body: "The first pattern is a single motive with nothing else. A lion suddenly comes at you, and you jump up and run. Your only reason for standing is to escape. That intention is called pure, and the action is called sincere — in relation to that one purpose — because nothing else is mixed in." },
      { title: "Two strong motives: companions", body: "In the second pattern, two motives join and each could move you on its own. A poor relative asks you for help, and you help because they are poor and because they are family. If they weren't poor, you'd still help a relative. If they weren't family, you'd still help someone poor. Or a doctor tells you not to eat, and it happens to be the Day of Arafa, so you fast — for either reason alone you'd have gone without." },
      { title: "Two weak motives: partners", body: "In the third pattern, neither motive would be enough alone, but together they move you. A rich relative asks for money and you say no. A poor stranger asks and you say no. A poor relative asks, and you give. Or someone gives charity in public, partly for reward and partly for praise — neither reason alone would have made them give, but together they did." },
      { title: "A strong motive and a weak one: helpers", body: "In the fourth pattern, one motive is enough alone, and a weaker one joins in and makes it easier. You have a habit of praying extra prayers or giving charity. One day people happen to be watching, and it feels a little easier because they are there. You know you'd have done it alone, and you know showing off alone wouldn't have made you do it. But the watching still slipped in." },
      { title: "The action follows the motive", body: "Ghazali says the point of this sorting is simple: an action has no value of its own. It takes its value from the motive that drives it. That is why the Prophet said, “Actions are only by intentions.”" },
      { title: "What follows, and what doesn't", body: "Two things follow. Two people doing exactly the same action can be in completely different positions. And one person can be in a different position at the end of an action than at the start, if their motive changes. But one thing does not follow: that a motive can turn any action into any other. A later section shows a whole class of actions this rule doesn't touch." },
    ],
    closer: [
      { title: "Why it needs sorting", body: "This short section is the hinge of the book. Everything before it defines what a motive is. Everything after it works out what follows from actions taking their value from motives — including how to judge a mixed action, which comes in the part on sincerity." },
      { title: "Test it on yourself", body: "Ghazali's examples are ordinary on purpose: helping family, fasting, giving in public. The same four patterns show up in almost everything we do, which is why the book keeps coming back to them." },
    ],
    distinction: ["Two things the rule could mean", "Value comes from the motive", "How an action counts follows what moved you to do it — Ghazali's reading.", "The motive decides what the act is", "An action becomes whatever you meant it to be — which the next sections refute."],
    misreading: "Don't stretch the rule beyond what it says. It is about where an action's value comes from, not about whether you can redescribe a wrong act as a good one.",
    reflection: "Take something you did recently with two motives and work out which of the four patterns it was.",
    audit: ["What really moved me to do this?", "Would I have done it for the good reason alone?", "Did being watched make it easier?", "Where does my motive change halfway through?"],
    nodes: ["niyya", "motive"],
    model: pair("Where the ruling comes from", "The difference is between judging an act and changing what it is.", [["From the motive", "An act is judged by what stirred it — the rule as stated.", "support"], ["From its label", "An act becomes whatever it's called — the stretch the book refuses.", "warning"]]),
  }),
  makeChapter({
    id: 4, shortTitle: "Why intention beats action", formalTitle: "The secret of the saying “A believer's intention is better than his action”",
    overview: "The Prophet said, “A believer's intention is better than their action.” Ghazali tests three popular explanations, shows why each fails, and then gives his own — which explains what all worship is really for.",
    thesis: "Intention is better than action because worship is aimed at changing the heart, and intention is already in the heart, while actions only reach it indirectly.",
    moves: [
      { title: "Three wrong explanations", body: "Some say intention is better because it is secret, and secret deeds are better. True, but then intending to reflect would be better than reflecting, which makes no sense. Some say it's because intention lasts longer. But the intention in prayer may last only moments while the actions continue. Some say intention alone beats action alone. True, but an action with no intention has no good in it at all, so that isn't a real comparison." },
      { title: "What it really means", body: "Ghazali says every act of worship is made of an intention and an action. Both are good. But of the two parts, the intention does more toward the goal. It is like saying bread is better than fruit — meaning for nourishment. To understand it, you have to know what the goal of worship is." },
      { title: "What worship is for", body: "The goal is the heart: its health, its safety in the next life, and the joy of meeting God. That joy belongs to whoever dies loving and knowing God. Love comes from knowing Him, and closeness comes from remembering Him often. And the heart can only be free for that when it is free of the pull of this world — when it leans toward good and away from bad." },
      { title: "The body trains the heart", body: "Actions help because body and heart affect each other. When your hand is hurt, your heart feels it. When your heart is frightened, your body shakes. The heart is the ruler and the limbs are its servants. So actions done by the body strengthen the qualities in the heart. The Prophet said, “There is a piece of flesh in the body — if it is sound, the whole body is sound.”" },
      { title: "Putting your forehead on the ground", body: "Ghazali gives examples. The point of prostration isn't bringing forehead and floor together. It's that doing a humble action strengthens humility in the heart. Someone who feels tenderness for an orphan and strokes the orphan's head finds the tenderness grows. But if you stroke an orphan's head with your mind elsewhere, as if touching a cloth, nothing reaches your heart." },
      { title: "Medicine to the right place", body: "So intention is better, because it is already in the heart, where the goal is. Ghazali compares it to treating a stomach ache. You could rub ointment on the chest, hoping some effect reaches the stomach. Or you could drink medicine that goes straight to the stomach. The drink is better, because it reaches the place itself." },
      { title: "Why a good intention counts", body: "This also explains why the Prophet said, “Whoever intends a good deed and doesn't do it has a good deed written for them.” The heart turning toward good is itself the main thing. The Quran says of animal sacrifice, “Their flesh and blood don't reach God. It is your God-consciousness that reaches Him.”" },
    ],
    closer: [
      { title: "Worse than nothing", body: "An act of worship done carelessly is empty — it's as if it never happened, since it didn't change the heart. But worship done to show off is worse than empty, because it strengthens the very quality it was meant to remove: the love of people's praise." },
      { title: "Why the method matters", body: "The three rejected explanations are ones a careful reader might hold. Showing exactly where each breaks makes the fourth convincing. Ghazali uses the same method again when he sorts the sayings about sincerity." },
    ],
    distinction: ["Two ways to explain why intention is better", "By what each part does", "Both serve the same goal and intention does more — Ghazali's reading.", "By circumstance", "Because it's secret or lasts longer — explanations that lead to things the saying can't mean."],
    misreading: "Don't conclude that actions don't matter. Ghazali's reading needs both parts present and both good. Actions are how the heart is trained.",
    reflection: "Test the three rejected explanations on yourself before reading Ghazali's. Most readers hold one of them.",
    audit: ["Which explanation did I believe?", "Do my actions reach my heart?", "When did I last do something good with my mind elsewhere?", "Am I treating intention as a replacement for doing?"],
    nodes: ["niyya", "motive"],
    model: spectrum("Three explanations broken, one kept", "Each breaks because it leads to something the saying can't mean.", [["Secrecy", "Would make intending to think better than actually thinking.", "warning"], ["Duration", "Comes down to “more is better”, and isn't true of prayer anyway.", "warning"], ["Nothing to compare", "Compares something good with nothing, when the saying compares two good things.", "warning"], ["Contribution", "Both serve the goal, and one does more for it.", "support"]]),
  }),
  makeChapter({
    id: 5, shortTitle: "What intention can't change", formalTitle: "The details of acts and how intention affects them",
    overview: "Ghazali divides all actions into three kinds — sins, acts of worship, and ordinary permitted things — and shows how intention works differently for each. A sin, he says, can never be turned into a good deed by meaning well.",
    thesis: "Intention can turn worship and ordinary actions into something better or worse — but it can never turn a sin into a good deed, and trying to do good by forbidden means is a further wrong.",
    moves: [
      { title: "Three kinds of action", body: "However many kinds of action there are, they fall into three groups: sins, acts of obedience, and permitted things. Intention works differently on each, which is why the famous saying needs this section." },
      { title: "Sins stay sins", body: "Sins don't change by intention. Ghazali warns the ignorant not to take “actions are only by intentions” to mean a sin becomes a good deed if you mean well. His examples: someone backbites a person to please someone else, feeds the poor with someone else's money, or builds a school or mosque with money gained unlawfully, meaning well. “All of this is ignorance.” The good intention doesn't stop it being wrong." },
      { title: "Meaning well makes it worse", body: "In fact, Ghazali says, intending good through what the law forbids is an extra wrong. If you knew it was forbidden, you are defying the law. If you didn't know, you are at fault for not knowing, because seeking knowledge is a duty on every Muslim, and we only know what is good through the law. Sahl said, “The worst sin is ignorance” — and worse still is not knowing that you don't know." },
      { title: "The sword and the robber", body: "Ghazali gives a picture. Suppose someone gives a sword and a horse to a known highway robber, saying, “I wanted to be generous, and I hoped he'd use them to defend Muslims.” Everyone agrees that's forbidden, even though generosity is loved by God. He says the same applies to teaching religious knowledge to someone who plainly wants it only for status and money. Knowledge is a weapon, and you don't hand weapons to people set on misusing them." },
      { title: "Worship can be spoiled or multiplied", body: "The second kind, acts of worship, depend on intention in two ways. Their basic worth: they must be done for God, or showing off turns them into sin. And their reward: one act of worship can hold many good intentions, and each intention earns its own reward." },
      { title: "Eight intentions in one sitting", body: "Ghazali's example is sitting in a mosque. You can intend to visit God in His house, and to wait from one prayer to the next. You can intend to hold back your eyes and limbs from wrong, and to focus your heart on God. You can intend to remember God, to teach someone or gently correct a mistake, and to make a friend for God's sake. And you can intend to stay away from sin out of respect for God's house. One sitting, eight rewards." },
      { title: "Even perfume", body: "The third kind, permitted things, can become worship or sin by intention. The Prophet said, “Whoever wears perfume for God comes on the Day of Judgement smelling sweeter than musk.” Perfume worn to show off wealth or attract improper attention becomes a sin. But you can intend to follow the Prophet's practice on Friday, honour the mosque, spare others unpleasant smells, and avoid giving anyone a reason to gossip about you." },
    ],
    closer: [
      { title: "Asked about everything", body: "Ghazali warns never to treat any movement as too small. A report says a person will be asked on the Day of Judgement even about the kohl on their eyes. Someone once dried the ink on a letter with a pinch of dust from his neighbour's wall, thinking, “It's only dust.” He heard a voice: “Whoever takes his neighbour's dust lightly will find out how heavy the reckoning is.”" },
      { title: "Ahmad and the wall", body: "A student had visited Imam Ahmad ibn Hanbal for years. Suddenly Ahmad stopped speaking to him. When the student finally asked why, Ahmad said, “I heard you plastered the outside wall of your house and the plaster took a fingertip's width of the public street. You aren't fit to pass on knowledge.” Ghazali says that is how carefully the early Muslims watched their students." },
    ],
    distinction: ["Two things a good intention can do", "Shape an open action", "Worship and permitted acts take their value from the motive — the rule's real field.", "Convert a forbidden act", "Turning a sin into a good deed by meaning well — which Ghazali calls ignorance and an extra wrong."],
    misreading: "Don't soften this because the outcomes in the examples are genuinely good — a mosque built, a poor person fed. Ghazali chose them for that reason. A good result doesn't make a wrong route right.",
    reflection: "Look for a place where you have used a good aim to justify something you wouldn't otherwise do.",
    audit: ["Have I tried to make something wrong right by meaning well?", "Is a good result doing the arguing for me?", "Did I not know, or avoid finding out?", "How many good intentions could I bring to one ordinary act?"],
    nodes: ["motive", "conversion", "knowledge"],
    model: chain("Three kinds, one exception", "The rule about motives has limits, and this kind is outside them.", [["Disobedience", "Intention can't change it, and meaning well by it is an extra wrong.", "warning"], ["Obedience", "Takes its ruling from the motive — where the rule works.", "support"], ["Allowed acts", "Also shaped by the motive — which is where most of life actually happens.", "balance"]]),
  }),
  makeChapter({
    id: 6, shortTitle: "You can't just decide", formalTitle: "That intention isn't something you can just choose",
    overview: "This section changes how the whole book reads. Ghazali describes what most people do when told to “have a good intention” — say it to themselves — and says that isn't an intention at all.",
    thesis: "An intention can't be created by saying it to yourself; it is a real pull of the heart, which can only be grown indirectly, by working on its causes.",
    moves: [
      { title: "The mistake", body: "Someone hears “actions are only by intentions” and the advice to have good intentions. So while teaching, trading or eating, they say to themselves, “I intend to teach for God,” or “I intend to eat for God,” and think that is an intention. Ghazali says: far from it. That is just talking to yourself — a thought passing to another thought." },
      { title: "What intention really is", body: "Intention is the soul actually being stirred, turning and leaning toward something it sees as good for it, now or later. And a pull that isn't there can't be invented by deciding. It's like a person who has just eaten a big meal saying, “I intend to feel hungry,” or someone saying, “I intend to fall in love with so-and-so.” It's impossible." },
      { title: "The only way", body: "The only way to get your heart to turn toward something is to work on the things that cause that turning. Sometimes that is in your power and sometimes it isn't. The soul only moves toward an action when it believes its goal is tied to that action. And even then, it only moves if it isn't busy with some stronger goal." },
      { title: "The early Muslims waited for it", body: "That is why some early Muslims held back from good deeds when they didn't have the intention. Ibn Sirin didn't pray at al-Hasan al-Basri's funeral, saying, “I don't have the intention for it.” When a great scholar of Kufa died, Sufyan al-Thawri was asked if he'd attend. He said, “If I had the intention, I would.” Someone asked Tawus to pray for him, and he said, “When I find an intention for it.”" },
      { title: "The comb and the mirror", body: "One early Muslim, combing his hair, asked his wife to bring the comb. She asked, “Should I bring the mirror too?” He was silent for a while, then said yes. Asked why he paused, he said, “I had an intention for the comb, but no intention for the mirror came to me, so I waited until God gave me one.”" },
      { title: "When a lesser thing is better", body: "Ghazali draws a surprising conclusion. If you have a real intention for something permitted but not for something more virtuous, the permitted thing is better for you. Forgiving is better than getting your rights back — unless your intention is only present for getting your rights. And if you are worn out from worship, a little rest or light talk may be better than more prayer. Ali said, “Refresh your hearts — when they are forced, they go blind.”" },
      { title: "The chess player's sacrifice", body: "This can look strange to people who only see the surface. A skilled chess player gives up a strong piece on purpose to win the game, and a beginner laughs. A skilled fighter pretends to retreat to draw the enemy into a narrow pass. Ghazali says the path to God is a battle with the devil and a treatment of the heart, and wise people use tactics that look odd to others." },
    ],
    closer: [
      { title: "Ahmad and the book", body: "Dawud ibn al-Muhabbar wrote a book called The Intellect. Imam Ahmad glanced through it and handed it back, saying its chains of narration were weak. Dawud said, “I didn't write it for the narrations. I read it as someone who wants to act on it, and I benefited.” Ahmad said, “Give it back so I can read it the way you did.” He kept it a long time, then said, “May God reward you — I benefited too.”" },
      { title: "Different levels of intention", body: "People's intentions in worship differ. Some act from fear of the Fire. Some act from hope of Paradise, which is a valid intention, though lower. The highest is worshipping God because He deserves it, for His majesty. Ghazali says that one is rare, and hard for anyone attached to this world even to understand." },
    ],
    distinction: ["Two things that can come before an action", "Saying it to yourself", "Words in your head or on your tongue — which Ghazali says is not an intention at all.", "Being moved", "The heart actually drawn toward the action — which is the whole of what intention means."],
    misreading: "Don't read this as making good intentions hopeless. It moves the work rather than removing it: you can work on what you believe and what distracts you, and the pull often follows. And don't use it as an excuse to skip required duties.",
    reflection: "Remember the last time you “made an intention”. You probably said something to yourself — which is exactly what this section is about.",
    audit: ["Did I say an intention, or was I really moved?", "What causes of a good intention could I work on?", "Do I believe my goal is tied to this action?", "Am I pretending to be hungry after a big meal?"],
    nodes: ["irada", "niyya", "causes"],
    model: pair("What saying it isn't", "The two examples are chosen because nobody doubts them.", [["Saying it", "Just words on the tongue, like a full person “intending” to be hungry.", "warning"], ["Setting up the causes", "The only way to a real pull toward something — and it doesn't always work.", "support"]]),
  }),
  makeChapter({
    id: 7, shortTitle: "Why sincerity matters", formalTitle: "Why sincerity is so valuable",
    overview: "The second part of the book turns to sincerity. Ghazali gathers verses, sayings and stories — including a shocking report about the first people judged, and a story about a worshipper, a tree and the devil.",
    thesis: "Sincerity is what saves a person from the devil, and without it even the greatest deeds — knowledge, generosity, even dying in battle — can be worthless.",
    moves: [
      { title: "The command", body: "The Quran says, “They were only commanded to worship God, making their religion sincerely His.” And, “Whoever hopes to meet their Lord, let them do good deeds and not associate anyone in the worship of their Lord.” That verse was revealed about someone who works for God but also loves to be praised for it." },
      { title: "A little is enough", body: "The Prophet told Mu'adh, “Make your deeds sincere, and a little will be enough.” And he said, “Whoever is sincere to God for forty days, springs of wisdom flow from their heart onto their tongue.” When Sa'd thought he was better than poorer Companions, the Prophet said, “God helps this community through its weak ones — through their prayers and their sincerity.”" },
      { title: "The first three judged", body: "The Prophet said the first judged will be three people. A scholar says, “I taught and studied day and night.” God says, “You lie. You wanted people to say, ‘He is a scholar’ — and it was said.” A rich man says, “I gave charity day and night.” “You lie. You wanted people to call you generous — and they did.” A man killed in battle says, “I fought until I was killed.” “You lie. You wanted to be called brave — and you were.”" },
      { title: "A true account called a lie", body: "Notice something about that report. The scholar's account of his deeds wasn't false. He really did teach. He wasn't told he hadn't done it. He was called a liar about what he wanted. When this report was told to Mu'awiya, he wept until people feared for him, then said, “God spoke the truth: ‘Whoever wants the life of this world and its glitter, We will pay them in full for their deeds here…’”" },
      { title: "The worshipper and the tree", body: "A worshipper heard that some people worshipped a tree instead of God. Angry, he took his axe to cut it down. The devil met him disguised as an old man and tried to stop him, but the worshipper threw him to the ground. The devil tried again and lost again. Then he offered a deal: “Go home, and I'll leave two gold coins under your pillow every night. You can give them to the poor — that's more useful than cutting a tree.”" },
      { title: "How he lost", body: "The worshipper agreed. Two mornings he found coins. On the third, nothing. Furious, he took his axe again. This time the devil pinned him down easily, like a sparrow. The worshipper asked, “How did I beat you before, and you beat me now?” The devil said, “The first time you were angry for God, so God put me under your control. This time you were angry for yourself and for the money, so I beat you.”" },
      { title: "“Be sincere and be free”", body: "Ghazali says this story matches the Quran, where the devil admits he can't mislead “Your sincere servants”. Only sincerity frees a person from the devil. Ma'ruf al-Karkhi used to strike his chest and say, “My soul, be sincere, and you'll be set free.” Ya'qub al-Makfuf said, “The sincere person hides their good deeds the way they hide their bad ones.”" },
    ],
    closer: [
      { title: "The cat and the donkey", body: "Someone was seen in a dream and asked how he found his deeds. He said everything done for God was there — even a pomegranate seed he picked up from the road, and a cat of his that died. But a donkey worth a hundred gold coins that died brought no reward. Why? “When they told you it had died, you cursed it. If you'd said, ‘It's for God,’ you'd have found it among your good deeds.”" },
      { title: "The man who ploughed on Arafa day", body: "Abu Ubayd al-Tustari was ploughing his field on the afternoon of the Day of Arafa when a saintly friend invited him to come on pilgrimage. He said no. Asked why, he said, “I have no intention for Hajj, and I intended to finish ploughing this field tonight. If I went for his sake, I'd be mixing something other than God into God's work — and staying with what I'm doing is greater to me than seventy pilgrimages.”" },
    ],
    distinction: ["Two ways a person can be called a liar", "In what they said", "The statement doesn't match the facts — the usual kind of lie.", "In what they wanted", "The statement matches the facts, but the motive behind it is false — as the report of the three shows."],
    misreading: "Don't read the report of the three as being only about fooling other people. The scholar told the truth about his deeds. What was false was what he wanted from them.",
    reflection: "Ask what you'd answer if asked what you did with what you know — and then what might be said back to you about why.",
    audit: ["Would my account of my good deeds be true?", "Would my account of why I did them be true?", "What do I want people to say about me?", "When I get angry for a good cause, whose sake is it for?"],
    nodes: ["ikhlas", "riya", "sidq"],
    model: chain("Where Part Two is heading", "It's the only part that ends in a calculation.", [["Its weight", "The evidence, including the report about the three people judged first.", "support"], ["The definition", "Purity with nothing mixed in — with a surprising result.", "support"], ["The dangers", "Four layers of showing off, some disguised as good.", "warning"], ["The maths", "What a mixed deed is actually worth, given as a rule.", "balance"]]),
  }),
  makeChapter({
    id: 8, shortTitle: "Pure milk", formalTitle: "What sincerity really is",
    overview: "Ghazali defines sincerity as purity: nothing else mixed in. He shows how easily other motives slip into good deeds — and a startling consequence of the definition that he states plainly.",
    thesis: "Sincerity means an action has one motive, with nothing mixed in — and in religion that motive must be nearness to God, which only someone who truly loves God can keep pure.",
    moves: [
      { title: "Milk between two impurities", body: "Anything that can be mixed with something else is called pure when it is cleared of the mixture. The Quran describes milk that comes out “from between waste and blood — pure, and pleasant to drink.” Its purity is that nothing else is mixed in. Sincerity is the same: an action cleared of anything mixed into its motive." },
      { title: "A startling consequence", body: "Since intention means answering a motive, when there is only one motive, the action is “pure” in relation to it. So, Ghazali says, someone who gives charity purely to show off is, strictly speaking, “sincere” — in that one motive. But ordinary usage has narrowed the word “sincerity” to mean purely seeking nearness to God, just as a word for “leaning” came to mean leaning away from the truth." },
      { title: "What slips in", body: "Ghazali's real subject is someone whose main motive is God, with something else mixed in. He gives many examples. Fasting partly for the diet. Going on pilgrimage partly for the change of air, or to get away from trouble at home. Praying at night partly to keep awake and watch your belongings. Studying partly to earn money or be respected. Visiting the sick partly so people visit you when you're ill. Doing wudu partly to cool off." },
      { title: "Even a little spoils it", body: "When any of these makes the action even a bit easier, it has left pure sincerity. A report says God declares, “I am the One who least needs a partner.” Any worldly share the soul enjoys, small or large, clouds an action. And since people are soaked in their wants, it has been said that whoever has even one moment in their life purely for God will be saved — because it is so rare." },
      { title: "Only a lover can manage it", body: "So who can be completely sincere? Ghazali says only someone who loves God so much that love of this world has no place left in their heart. Such a person eats only to have strength to worship. Even their sleep, taken to rest for worship, becomes worship. For everyone else, he says, the door to perfect sincerity is mostly closed. The cure is weakening the soul's wants and loosening the heart's grip on this world." },
      { title: "Thirty years in the front row", body: "Someone said, “I made up thirty years of prayers that I had prayed in the front row of the mosque. One day I came late and had to pray in the second row, and I felt embarrassed in front of people. Then I realised that people seeing me in the front row had been my secret pleasure all along, without my noticing.”" },
      { title: "The preacher's test", body: "Ghazali says scholars and preachers are the most exposed to this. A preacher tells himself he is spreading God's religion. But if a better speaker appears and the crowds leave him, it hurts. If his motive were religion, he would thank God that someone else is doing the job. Umar was glad when Abu Bakr led the community, because someone better suited had taken it on." },
    ],
    closer: [
      { title: "Don't trust your promises", body: "Some scholars tell themselves, “If someone better came along, I'd be glad.” Ghazali says promising that before it is tested is pure self-deception. The soul easily makes such promises in advance, and changes its mind when the moment comes." },
      { title: "Where the word's direction comes from", body: "Ghazali states the odd consequence about showing off because the definition is strict and he won't exempt himself from it. It shows that the word “sincerity” gets its religious direction from usage, while the definition underneath is about purity." },
    ],
    distinction: ["Two things the word carries", "A shape", "One unmixed motive — what the definition actually says.", "A direction", "That the motive be nearness to God — which the word gets from usage, not from its shape."],
    misreading: "Don't take the remark about the pure show-off as approval. It follows from a strict definition, and Ghazali states it so readers see where the word's religious meaning comes from.",
    reflection: "Ask whether your good deeds have one motive or several, before asking which motives they are.",
    audit: ["How many motives does this act have?", "What worldly share makes it easier for me?", "Would I be glad if someone did my good work better?", "What secret pleasure might be in my front-row seat?"],
    nodes: ["ikhlas", "motive", "riya"],
    model: pair("Two parts of the word", "Separating them is what makes the definition usable.", [["Unmixed", "One motive with nothing else mixed in — the shape of the word.", "balance"], ["Toward closeness to God", "Which motive it is — supplied by how the word is used, not by the analysis.", "support"]]),
  }),
  makeChapter({
    id: 9, shortTitle: "What the teachers said", formalTitle: "What the great teachers said about sincerity",
    overview: "Ghazali gathers famous definitions of sincerity and, for each one, says which single fault it addresses. That turns a list of sayings into a map.",
    thesis: "Each teacher's definition of sincerity targets one particular fault, while the fullest is that everything you do and don't do is for God alone.",
    moves: [
      { title: "Don't look at your own sincerity", body: "Al-Susi said, “Sincerity is not seeing your sincerity. Whoever sees sincerity in their sincerity needs sincerity for their sincerity.” Ghazali says this is about clearing self-admiration out of an action. Noticing your own sincerity and being pleased with it is itself a fault. But it addresses just one fault." },
      { title: "The fullest definition", body: "Sahl said, “Sincerity is that everything you do and everything you hold back from is for God alone.” Ghazali calls this the definition that gathers all the others. Ibrahim ibn Adham said something similar: “Sincerity is being honest in your intention with God.” When Sahl was asked what is hardest on the soul, he said, “Sincerity — because the soul gets nothing out of it.”" },
      { title: "No reward in either world", body: "Ruwaym said, “Sincerity in an action is wanting nothing in return for it, in this world or the next.” Ghazali says this shows that the soul's wants are a fault whether they are cashed in now or later. Worshipping only for the pleasures of Paradise still falls short of the highest sincerity." },
      { title: "But hope isn't failure", body: "Ghazali adds an important point. Someone who acts from hope of Paradise and fear of the Fire is sincere as far as this world's rewards go. The completely unmixed kind, wanting nothing but God, is the sincerity of the truthful — a level some reach, not a requirement laid on everyone." },
      { title: "Every action has a motive", body: "The judge al-Baqillani said anyone who claims to act with no motive at all is claiming a quality that belongs only to God. Ghazali agrees — but says the Sufis meant freedom from what people usually call rewards, like the pleasures of Paradise. People who delight in knowing God and praying to Him do have a “share” — but their share is God Himself." },
      { title: "Hidden from people", body: "Other sayings focus on showing off. Abu Uthman said, “Sincerity is forgetting that people are watching by always looking at the Creator.” Someone said, “Sincerity is a deed not even the devil sees so he can spoil it, or an angel so he can write it down” — meaning complete hiddenness. The disciples asked Jesus which deeds are pure. He said, “Those done for God, without wanting anyone to praise you for them.”" },
      { title: "Don't stop, don't show off", body: "Al-Fudayl said, “Leaving a deed because of people is showing off. Doing a deed for people is associating partners with God. Sincerity is God freeing you from both.” And when the Prophet was asked about sincerity, he said, “Say, ‘My Lord is God,’ and then stand straight as you have been commanded” — meaning worship no one, not even your own desires, except your Lord." },
    ],
    closer: [
      { title: "Why sorting helps", body: "Read as a list, these sayings look like rival definitions, and the strictest seems to win. Read as Ghazali arranges them, each is a treatment for one particular fault. So you can ask which saying fits your own problem, instead of trying to satisfy all of them at once." },
      { title: "Enough quotations", body: "Ghazali says there are many more sayings, but piling them up is pointless once the truth is clear. The fullest explanation, he says, is the Prophet's own." },
    ],
    distinction: ["Two ways to read a collection of definitions", "As rivals", "The strictest is right and the rest are rough versions — which makes them a test to pass.", "As a set of tools", "Each addresses one fault — which makes them a way to find your own."],
    misreading: "Don't measure yourself against Ruwaym's saying and decide that hoping for Paradise disqualifies you. Ghazali says plainly that it still counts as sincerity, and calls the completely unmixed kind a high level, not a rule.",
    reflection: "Find which saying addresses the fault you actually have, not the one that sounds most impressive.",
    audit: ["Which fault is mine?", "Do I admire my own sincerity?", "Have I stopped doing good because people might see?", "Am I holding myself to a level, or to a rule?"],
    nodes: ["ikhlas", "ujb", "riya"],
    model: spectrum("Each saying matched to its danger", "Matching them turns a list into a set of checks.", [["Not seeing it", "Aimed at being impressed with yourself while you act — one danger only.", "balance"], ["Stillness and movement", "A saying that covers the whole aim.", "support"], ["No reward wanted", "Aimed at the self's cut, whether now or later.", "balance"], ["The highest", "Wanting nothing but God's face — named as a level.", "support"]]),
  }),
  makeChapter({
    id: 10, shortTitle: "Four layers of showing off", formalTitle: "The levels of mixed motives and dangers that trouble sincerity",
    overview: "Ghazali shows how the devil spoils a sincere prayer in four stages, each more hidden than the last. Serious people escape the first and fall into the later ones — which are dressed up as good.",
    thesis: "Showing off comes in layers: acting well for the watcher, acting well “as an example”, acting the same alone so you can act well in public, and suddenly feeling humble only when someone is watching.",
    moves: [
      { title: "Obvious and hidden", body: "The things that spoil sincerity are some obvious and some hidden, some weak and some strong. Ghazali says you can only understand the differences through an example, and the clearest spoiler is showing off. So he takes someone praying sincerely, and shows four ways the devil gets in." },
      { title: "Layer one: for the watcher", body: "People start watching, or someone walks in. The devil whispers, “Make your prayer beautiful, so this person respects you and doesn't look down on you or gossip about you.” So the person becomes still and humble, and their prayer looks lovely. This is obvious showing off, and even beginners can spot it." },
      { title: "Layer two: as an example", body: "Someone who has learned to refuse that is approached differently. The devil comes dressed as good: “People follow you and copy you. If you pray well, you'll share their reward. So make your prayer beautiful in front of him — maybe he'll learn humility from you.” This is harder to spot. But Ghazali says it is still showing off. If humility is good, why wasn't it good enough for yourself when you were alone?" },
      { title: "Layer three: making them match", body: "Someone who has seen through that decides, “Real sincerity means praying the same alone as in public.” So they make their private prayer as beautiful as their public prayer. Ghazali says this is even more subtle showing off. They improved their private prayer so that their public prayer would look good. Their attention is still on people. True sincerity is when being watched by people and being watched by animals feel exactly the same." },
      { title: "Layer four: sudden humility", body: "The subtlest layer: people are watching, and the devil knows he can't say “be humble for them.” So he says, “Think of God's greatness. Be ashamed that He sees your heart wandering.” The person's heart becomes present and they think it is pure sincerity. But if it were really about God's greatness, that thought would come just as often when alone. If it only arrives when someone is watching, it is still showing off." },
      { title: "The black ant on a black rock", body: "Ghazali says this hidden showing off is, as a report puts it, “harder to detect in the heart than a black ant crawling on a black rock on a dark night.” The devil follows people who try to worship into everything, even good habits like wearing perfume on Friday. He whispers, “This is the Prophet's practice, don't skip it,” while a hidden pleasure in being seen is what really drives it." },
      { title: "The nicer mosque", body: "Even choosing a mosque can hide it. Someone spends time in a clean, beautiful mosque, and the devil reminds them of all the rewards of staying in mosques. But the real hidden pull may be enjoying how pleasant the building is. You can tell if they'd choose the nicer mosque over the plainer one." },
    ],
    closer: [
      { title: "Fake gold", body: "Ghazali compares this to fake gold mixed into a gold coin. Sometimes there's a lot and it's easy to see. Sometimes there's a little, and only an expert can tell. The fakeness in hearts is harder still. That's why it was said, “Two units of prayer from a scholar who understands this are better than a year of worship from someone who doesn't.” A tiny piece of real gold beats a big coin a fool accepts." },
      { title: "A question, not general worry", body: "The section doesn't ask for vague anxiety. It gives specific questions to ask at specific moments: Did this improve when someone came in? Would this thought come to me if I were alone?" },
    ],
    distinction: ["Two reasons a prayer improves when watched", "For the one watching", "The first layer, which beginners recognise and shame usually catches.", "For a reason that sounds good", "The later layers, whose reasons may be true, and whose motive is still the watcher — which Ghazali says still spoils sincerity."],
    misreading: "Don't conclude that being a good example is itself wrong, or that you should worship badly in public to be safe. What Ghazali names is improvement that appears because someone is watching.",
    reflection: "Notice whether anything about your prayer changes when someone walks in, and what reason you give yourself for it.",
    audit: ["Did my prayer change when someone was watching?", "What good-sounding reason did I give myself?", "Is my attention on people even when I'm alone?", "Does my humility only appear when someone can see?"],
    nodes: ["riya", "ikhlas", "motive"],
    model: chain("Four layers", "Each layer catches the person who escaped the one before.", [["For the watcher", "Praying beautifully so the watcher thinks well of you. Even beginners spot this.", "warning"], ["As an example", "Praying beautifully so the watcher copies you — a true reason, but the same motive.", "warning"], ["Making them match", "Improving private prayer so public prayer looks right — your eyes are still on people.", "warning"], ["Sudden humility", "Awe of God that only shows up when someone is watching.", "warning"]]),
  }),
  makeChapter({
    id: 11, shortTitle: "Weighing a mixed deed", formalTitle: "The ruling on a mixed deed, and whether it earns reward",
    overview: "What happens to a good deed with some showing off mixed in? Does it earn anything? Ghazali gives a clear rule — marking it honestly as his own view — and warns against the opposite mistake: giving up good deeds for fear of showing off.",
    thesis: "A mixed deed is weighed by which motive was stronger: equal motives cancel out, a stronger worldly motive brings blame, and a stronger religious motive earns reward for the difference — so don't stop doing good for fear of impurity.",
    moves: [
      { title: "The clear cases", body: "People disagreed about mixed deeds. But two cases are clear. A deed done only to show off counts against you and brings God's displeasure. A deed done purely for God earns reward. The question is the mixed deed." },
      { title: "Ghazali's honest view", body: "Ghazali admits that the plain wording of the reports suggests a mixed deed earns no reward, and that the reports don't entirely agree. Then he gives his own view, adding, “and the knowledge is with God.” Look at how strong each motive was." },
      { title: "Four outcomes", body: "If the religious motive and the selfish motive were equal, they cancel out: the deed is neither for you nor against you. If showing off was stronger, the deed doesn't help and actually harms you — though less than a deed done purely to show off. If seeking God was stronger, you are rewarded for the extra strength of that good motive." },
      { title: "An atom's weight", body: "Ghazali grounds this in the Quran: “Whoever does an atom's weight of good will see it, and whoever does an atom's weight of evil will see it,” and “God does not wrong anyone by an atom's weight.” A good intention shouldn't be wasted. If it outweighs the showing off, the part that matches the showing off is cancelled, and the rest remains." },
      { title: "A hand's span", body: "Why? Because deeds work by strengthening qualities in the heart. The urge to show off is a destroyer, and acting on it feeds it. The urge to please God is a saviour, and acting on it feeds that. If one action brings you a hand's span closer and another pushes you a hand's span away, you're back where you started. If one brings you two spans closer and the other pushes you one away, you're one span ahead." },
      { title: "Pilgrims who trade", body: "Ghazali points out that all Muslims agree someone who goes on Hajj and also brings goods to trade has a valid Hajj and is rewarded, even though a worldly share is mixed in. And he doubts that soldiers who prefer a campaign with more spoils lose all their reward. As long as the main motive is for God and the other is secondary, the reward isn't lost — just reduced." },
      { title: "Don't stop doing good", body: "But you can never be completely sure which motive was stronger, so stay humble and a little afraid. Still, don't abandon good deeds for fear of showing off — that is exactly what the devil wants. A servant of Abu Sa'id al-Kharraz began dropping tasks because he couldn't make every movement sincere. Abu Sa'id told him, “Sincerity doesn't stop you working. Keep working, and work at being sincere.”" },
    ],
    closer: [
      { title: "Sixty years of honesty", body: "Abd al-Aziz ibn Abi Rawwad said, “I have lived beside the Ka'ba for sixty years and made sixty pilgrimages. Whenever I checked myself afterwards, I found the devil's share bigger than God's. I wish it were simply neither for me nor against me.” Sufyan said, “I don't count anything of my deeds that people can see.”" },
      { title: "Harsh reports, rightly read", body: "What about reports like, “The smallest showing off is associating partners with God,” or God saying, “I don't need partners — whoever does a deed for Me and someone else, I leave it to the partner”? Ghazali says these are about deeds where the worldly aim was the main one, or where the motives were equal. They don't wipe out a deed whose main motive was God." },
    ],
    distinction: ["Two ways to judge a mixed deed", "By proportion", "Weighing which motive was heavier, down to an atom — Ghazali's view.", "By any mixture at all", "Any trace of another motive cancels the deed — what the reports seem to say on the surface, which he doesn't adopt."],
    misreading: "Don't use this rule to comfort yourself. Its middle outcome is that a truly balanced deed comes to nothing, and its lower outcome is blame. And don't use the danger as an excuse to stop doing good — Ghazali says that is the devil's goal.",
    reflection: "Take one good deed and try to say honestly which motive was heavier. The difficulty of answering is part of what this section teaches.",
    audit: ["Which motive was heavier here?", "Am I guessing in my own favour?", "Have I stopped doing something good because I feared showing off?", "What would make the good motive stronger?"],
    nodes: ["ikhlas", "riya", "motive"],
    model: spectrum("Four outcomes", "A sliding scale, not a pass mark.", [["Pure showing off", "Definitely against you — the heaviest case.", "warning"], ["Showing off is stronger", "Harmful, though lighter than pure showing off.", "warning"], ["Equal", "The two cancel out — neither for you nor against you.", "balance"], ["Closeness to God is stronger", "Reward in proportion to how much the religious motive was stronger.", "support"]]),
  }),
  makeChapter({
    id: 12, shortTitle: "Why truthfulness matters", formalTitle: "Why truthfulness is so valuable",
    overview: "The third part of the book turns to truthfulness. It looks like the simplest subject — just don't lie — but Ghazali shows it is the widest of the three.",
    thesis: "Truthfulness leads to goodness and to Paradise, and its highest form gives the title siddiq — the thoroughly truthful — which the Quran gives to prophets.",
    moves: [
      { title: "The Prophet's promise", body: "The Prophet said, “Truthfulness leads to goodness, and goodness leads to Paradise. A person keeps telling the truth until they are written with God as truthful. Lying leads to wickedness, and wickedness leads to the Fire. A person keeps lying until they are written with God as a liar.”" },
      { title: "A word used of prophets", body: "Ghazali says it's enough to know that the word siddiq — someone thoroughly truthful — comes from truthfulness. The Quran praises prophets with it: “Mention Abraham in the Book. He was thoroughly truthful, a prophet.” It says the same of Idris, and calls Ishmael “true to his promise”. And it praises “men who were true to the promise they made to God.”" },
      { title: "The best way to come to God", body: "Someone dreamt of Mansur al-Dinawari after his death and asked what God had done with him. He said, “He forgave me, had mercy on me, and gave me more than I hoped.” He was asked, “What is the best thing to bring before God?” He said, “Truthfulness. And the worst is lying.”" },
      { title: "You'd recognise them", body: "A man told a wise person, “I've never met a truthful person.” The wise person answered, “If you were truthful, you would recognise the truthful.” And God told David, according to a report: “Whoever is true to Me in private, I will make true in the eyes of people in public.”" },
      { title: "A claim that is tested", body: "Sufyan al-Thawri explained the verse, “On the Day of Judgement you will see those who lied about God with darkened faces,” as meaning “those who claimed to love God and weren't truthful about it.” Al-Junayd said the verse “so that He may question the truthful about their truthfulness” shows that even the truthful will be questioned — a serious matter." },
      { title: "Wise sayings", body: "Wahb ibn Munabbih said he found twenty-two sayings written in the margin of the Torah that good people used to study together. Among them: “No treasure is more useful than knowledge. No medicine is gentler than kindness. No guide is more sincere than truthfulness. No poverty is more humiliating than greed. No guard protects better than silence. No absent thing is nearer than death.”" },
    ],
    closer: [
      { title: "Wider than not lying", body: "A reader coming to a section on truthfulness expects a lesson about lying. The next two sections spend most of their length on intentions, resolutions, keeping promises and actions. Putting truthful speech first is what makes that widening visible." },
      { title: "How the three parts join", body: "One of the six meanings of truthfulness is sincerity, and sincerity is a quality of intention. So the three parts of the book close into one another here, rather than just ending one after another." },
    ],
    distinction: ["Two ways to read who the truthful are", "The best at not lying", "People who never tell a false sentence — which the six meanings show is too narrow.", "Truthful all the way through", "True in speech, intention, resolve, keeping promises, action, and in the real states of faith."],
    misreading: "Don't read this part as a chapter on lying tacked onto a book about intention. Sincerity is one of truthfulness's six meanings, so this part contains the one before it.",
    reflection: "Before reading the six meanings, write down what you think truthfulness covers.",
    audit: ["What did I think truthfulness covered?", "Am I truthful in private as in public?", "Do I claim to love God truthfully?", "Would I recognise a truthful person?"],
    nodes: ["sidq", "siddiq", "ikhlas"],
    model: chain("Why Part Three comes last", "It contains what came before it.", [["Intention", "The heart's stirring, covered in Part One.", "support"], ["Sincerity", "That stirring made pure — and the second of the six meanings here.", "support"], ["Truthfulness", "Six meanings, one of which is sincerity and another is honest speech.", "support"]]),
  }),
  makeChapter({
    id: 13, shortTitle: "Truth in words, aims and plans", formalTitle: "What truthfulness really is, and its levels: the first three",
    overview: "Ghazali lists six meanings of truthfulness and explains the first three: truthful speech, truthful intention, and truthful resolve. Already by the second, the word has gone far beyond not lying.",
    thesis: "Truthfulness has six meanings; the first three are truthful words — including the words you say to God — a truthful intention, which is sincerity, and a resolve that is firm rather than half-hearted.",
    moves: [
      { title: "Six meanings", body: "Truthfulness is used in six ways: truthful speech, truthful intention, truthful resolve, keeping that resolve, truthful action, and truly reaching the stations of faith. Whoever is truthful in all six is a siddiq. And whoever is truthful in some of them is truthful in those." },
      { title: "One: truthful speech", body: "The first is truthfulness of the tongue, in reporting things, including keeping promises. Everyone must guard their words and speak only the truth. This is the best-known kind. Its first perfection is avoiding misleading hints — technically true words meant to give a false picture. Some said hints are a way out of lying. Ghazali says they take lying's place, because what's wrong with lying is making someone believe what isn't so." },
      { title: "When hinting is allowed", body: "Ghazali admits there are times of genuine need: protecting yourself from an oppressor, keeping secrets from an enemy in war, and making peace between people. The Prophet said, “Someone who makes peace between two people, saying good things, is not a liar.” When the Prophet set out on a journey, he often didn't reveal where he was going, so news wouldn't reach enemies. Even then, a hint is better than a flat lie." },
      { title: "The circle on the floor", body: "Ghazali tells of a man hiding from an oppressor who came to his house. He told his wife, “Draw a circle on the floor with your finger, put your finger in the circle, and say, ‘He isn't here.’” So she spoke truly — he wasn't in the circle — and still protected him." },
      { title: "True words to God", body: "The second perfection of truthful speech is being truthful in the words you say to God. When you say in prayer, “I have turned my face to the One who created the heavens and the earth,” while your heart is busy with the world, that is a lie. When you say, “You alone we worship,” or “I am God's servant,” but you are really a servant of your desires or your money, your words aren't true." },
      { title: "Servant of the coin", body: "The Prophet said, “Wretched is the servant of the gold coin, the servant of the silver coin, the servant of fine clothes.” Ghazali says whatever your heart is tied to, you are its servant. A true servant of God is first freed from everything else. Then, at a higher level, they are even freed from their own wishes, content with whatever God wants for them." },
      { title: "Two: truthful intention", body: "The second meaning is truthfulness in intention, which is sincerity: having no motive in anything you do except God. If a worldly share gets mixed in, the intention isn't truthful, and the person may be called a liar — like the scholar in the report who taught but was told, “You lie; you wanted to be called a scholar.”" },
    ],
    closer: [
      { title: "The hypocrites' true sentence", body: "The Quran says, “God bears witness that the hypocrites are liars” — even though what they said was, “You are the Messenger of God,” which is true. Ghazali explains that their words also implied, by the situation, that they believed it. That hidden message about their hearts was the lie." },
      { title: "Three: truthful resolve", body: "The third meaning is truthful resolve. Someone may tell themselves, “If God gives me money, I'll give all of it or half in charity,” or “If God gives me power, I'll be fair.” A truthful resolve is firm, with no hesitation. Umar said, “I'd rather be brought forward and executed than lead a people that includes Abu Bakr” — a completely firm resolve. The next section asks what happens when the moment actually comes." },
    ],
    distinction: ["Two ways a true sentence can be a lie", "In the words", "The words don't match the facts — the only kind most people count.", "In what they imply", "The words match the facts, but they hint at something false about the speaker's heart — as with the hypocrites."],
    misreading: "Don't treat clever hints as a free way around lying. Ghazali says they stand in for lying, and allows them only for real need, like protecting someone from an oppressor or making peace.",
    reflection: "Test yourself on the second meaning, not just the first. Most people are more careful about their sentences than about their aims.",
    audit: ["Am I careful with words but careless with aims?", "Do I use technically true words to mislead?", "Are the words I say to God true?", "Is my resolve firm, or half-hearted?"],
    nodes: ["sidq", "ikhlas", "azm"],
    model: chain("The first three", "Ordered by how much of a person is involved.", [["Speech", "What you say and what it implies — made complete by dropping misleading hints.", "support"], ["Intention", "Sincerity under another name; a mixed motive spoils it.", "support"], ["Resolve", "The promise you make to yourself before the moment comes.", "balance"]]),
  }),
  makeChapter({
    id: 14, shortTitle: "Truth in keeping promises and deeds", formalTitle: "What truthfulness really is, and its levels: the last three",
    overview: "The last three meanings of truthfulness, and the end of the book. Keeping a resolve is harder than making one. Your actions must not hint at something inside you that isn't there. And the highest meaning — truly living the states of faith — is rare.",
    thesis: "The last three meanings are keeping your resolve when the moment comes, making your inside match your visible actions, and truly reaching fear, hope, love and trust rather than just their names.",
    moves: [
      { title: "Four: keeping the resolve", body: "Making a resolve costs nothing, so the soul is generous with it. But when the moment comes, and the chance is real and desires are stirred, the resolve often falls apart. That goes against truthfulness. Ghazali says this is why keeping a resolve is harder than making one, and why the Quran praises “men who were true to the promise they made to God.”" },
      { title: "Anas ibn al-Nadr", body: "Anas ibn al-Nadr missed the Battle of Badr and was upset. He said, “If God lets me see another battle with the Messenger, God will see what I do.” At Uhud, he told Sa'd ibn Mu'adh, “Ah — the scent of Paradise! I can smell it beyond Uhud.” He fought until he was killed. The verse about “men who were true to their promise” was revealed about him." },
      { title: "A promise broken is a lie", body: "The Quran describes people who promised God, “If He gives us from His bounty, we will give charity and be among the righteous.” When He gave to them, they became stingy and turned away — “because they broke their promise to God, and because they used to lie.” So God made a resolve a promise, breaking it a lie, and keeping it truthfulness." },
      { title: "Umar's honesty about himself", body: "Umar had said he'd rather be executed than lead a people including Abu Bakr. But he added, “unless my soul makes something seem attractive to me at the moment of death that I don't feel now.” Ghazali says this shows how hard keeping a resolve is — even Umar didn't take his future self for granted." },
      { title: "Five: truthful actions", body: "The fifth meaning is truthfulness in actions: making sure your visible actions don't suggest something inside you that isn't there. Someone may stand very humbly in prayer, not to impress anyone, while their heart is off in the marketplace. Their posture “speaks” a lie. The cure isn't stopping the actions. It is pulling your inside up to match them." },
      { title: "Inside better than outside", body: "Ghazali says if the gap between inside and outside is on purpose, it is showing off. If it isn't on purpose, it still falls short of truthfulness. The Prophet prayed, “O God, make my inside better than my outside, and make my outside good.” Someone asked, “Who will show me a person who weeps at night and smiles in the day?”" },
      { title: "Six: truly reaching the states", body: "The sixth and highest meaning is truthfulness in the states of faith: fear, hope, love of God, trust, contentment. Every believer has some fear of God. But Ghazali gives a test. When someone fears a ruler or a robber on the road, they go pale, can't eat or sleep, and change their plans. Yet they fear the Fire and still sin without flinching. The Prophet said, “I've never seen anything like the Fire, whose runaway sleeps.”" },
    ],
    closer: [
      { title: "Gabriel's true form", body: "Ghazali says fear and awe of God have no limit. The Prophet once asked Gabriel to show his true form. When he did, he filled the horizon, and the Prophet fainted. Gabriel said, “What if you saw Israfil? The Throne rests on his shoulders — and he shrinks from awe of God until he is like a tiny sparrow.” That, Ghazali says, is truthfulness in awe." },
      { title: "Sa'd ibn Mu'adh's three", body: "Sa'd ibn Mu'adh said, “In three things I'm strong: I've never prayed and let my mind wander to other things until I finished. I've never followed a funeral thinking of anything but what the dead person is saying and being told. And I've never heard the Messenger say anything without knowing it was true.” Ibn al-Musayyib said he hadn't thought those traits came together except in a prophet. Ghazali notes many great Companions didn't reach this — which is what makes it a level, not a demand." },
    ],
    distinction: ["Two cures for a gap between inside and outside", "Stop the action", "The cure for showing off, when the action is being done for the watcher.", "Raise the inside", "The cure here, when the action is right and the heart hasn't caught up with it yet."],
    misreading: "Don't read the fifth meaning as permission to keep up an appearance you haven't earned. Ghazali says the fix is to bring your inside up to match — and that dropping the good action belongs to a different problem.",
    reflection: "Look for a resolve you made when it was easy and haven't yet been tested on. Ghazali says keeping it is the harder part.",
    audit: ["Which resolve am I carrying that hasn't been tested?", "Do my actions suggest something my heart doesn't have?", "Is my fear of God as real as my fear of people?", "Which state of faith do I have only the name of?"],
    nodes: ["sidq", "azm", "siddiq", "riya"],
    model: spectrum("The last three", "Each is harder than the one before, and the last is called rare.", [["Fulfilment", "Harder than deciding, because the moment brings the temptation with it.", "balance"], ["Action", "Your outside not suggesting what your inside lacks — fixed by raising the inside up.", "support"], ["The levels", "Fear, hope, contentment, trust and love made real, not just named.", "support"]]),
  }),
];

export const book37ConceptNodes: ConceptNode[] = [
  ["niyya", "Intention", "A state of the heart", "With knowing before it and action after it."],
  ["structure", "Three parts", "One inside the next", "Sincerity is a quality of intention; sincerity is one of the six meanings of truthfulness."],
  ["irada", "Will", "The heart stirred", "The stirring toward what seems to serve your goal, now or later."],
  ["knowledge", "Knowledge", "Root and condition", "You can't want what you don't know, and knowing alone moves nothing."],
  ["motive", "The motive", "Where the ruling comes from", "The act follows what stirred it and takes its ruling from it."],
  ["conversion", "Conversion", "What it can't do", "Intention can't change a sin, and meaning well by it is an extra wrong."],
  ["causes", "The causes", "The only way", "You can't create a pull toward something by wanting to; you can only set up its causes."],
  ["ikhlas", "Sincerity", "Nothing mixed in", "Defined by its shape, which leads to a result Ghazali states without flinching."],
  ["riya", "Showing off", "Four layers", "Each hidden layer catches the person who escaped the one before."],
  ["ujb", "Self-admiration", "A danger of its own", "Watching your own sincerity is what al-Susi's saying is about."],
  ["sidq", "Truthfulness", "Six meanings", "Speech, intention, decision, keeping it, action, and the levels of religion."],
  ["azm", "Resolve", "And keeping it", "Counted as two meanings, because people happily decide and then flinch when it's time to act."],
  ["siddiq", "The siddiq", "Truthful through and through", "Earned by being truthful in all six, not by being very strong in one."],
].map(([id, label, kicker, description], index) => ({ id, label, kicker, description, position: ["left", "right", "top", "bottom"][index % 4] }));

const node = (id: string, label: string, micro: string, summary: string, guardrail: string, chapterId: number, glyph: Journey["nodes"][number]["glyph"]): Journey["nodes"][number] => ({ id, label, micro, summary, guardrail, chapterId, glyph });

export const book37Journeys: Journey[] = [
  {
    id: "what-is-an-intention", number: "01", question: "What is an intention, really?", title: "Take it apart before using it",
    description: "Fold three words into one meaning, find the three parts of any chosen act, and watch a famous saying survive three explanations that don't work.",
    payoff: "You get a definition that explains why the rest of the book has to limit the rule.",
    image: assetUrl("assets/system/book37-three-components.jpg"), imageAlt: "A pale workbench where a lamp, a key and a hand-tool lie in a row, arranged so that none can be used without the others.", minutes: 13, color: "#278d91",
    nodes: [
      node("three-words", "Fold the words together", "One meaning", "Intention, will and aim all come down to one state of the heart.", "A state, not a moment of deciding before you act.", 2, "know"),
      node("three-parts", "Find the parts", "Knowing, wanting, ability", "No chosen act gets done without all three.", "The order holds up the whole book.", 2, "order"),
      node("the-sick-man", "Notice the sick man", "Knowing isn't moving", "He sees the food, knows it's good for him, and doesn't reach for it.", "Knowing doesn't create a pull, which Section 6 builds on.", 2, "diagnose"),
      node("the-mechanism", "Say how it works", "The ruling follows the motive", "Two identical acts can mean completely different things.", "This is about judging an act, not relabelling it.", 3, "pattern"),
      node("three-breaks", "Break three explanations", "Secrecy, lasting longer, nothing to compare", "Each leads to something the famous saying can't mean.", "All three are explanations a careful person might reach.", 4, "clear"),
      node("contribution", "Keep the fourth", "What it does for the goal", "Both are good, and one does more for the same goal.", "It needs both to be there, so action can't be skipped.", 4, "steady"),
    ],
  },
  {
    id: "cannot-decide", number: "02", question: "Can I just decide to mean it?", title: "Meet the two limits",
    description: "Follow the two sections that stop the famous hadith on intentions becoming an excuse: one kind of act intention can't touch, and one thing saying your intention can't produce.",
    payoff: "You stop doing what almost everyone does when told to have a good intention.",
    image: assetUrl("assets/system/book37-full-man.jpg"), imageAlt: "A cleared table after a meal, the plate empty and pushed back, a second untouched dish set down beside it.", minutes: 12, color: "#c25f50",
    nodes: [
      node("three-classes", "Sort the acts", "Three kinds", "Sins, good deeds and allowed acts are ruled differently.", "The rule about motives has limits, and one kind is outside them.", 5, "order"),
      node("no-conversion", "Take the limit", "Not by intending", "A mosque built with stolen money doesn't become good by meaning well.", "Every example is one where the good result is real.", 5, "guard"),
      node("second-evil", "Notice the second charge", "The route, not the result", "Aiming at good through something forbidden is an extra wrong.", "The excuse of not knowing is shut in the same breath.", 5, "clear"),
      node("the-declaration", "Catch the declaration", "Just words on the tongue", "Saying you intend to eat for God isn't an intention at all.", "This is what most people do, which is why it needed a section.", 6, "diagnose"),
      node("full-man", "Test the impossible", "Intending to be hungry", "You can't create a pull by wanting to, just as you can't create an appetite.", "Ghazali isn't saying they're similar; he says it's the same thing.", 6, "witness"),
      node("the-causes", "Find the real work", "Set up the causes", "The only way to a real pull toward something is gaining its causes.", "He admits plainly that this isn't always in your power.", 6, "forces"),
    ],
  },
  {
    id: "what-counts-as-sincere", number: "03", question: "What counts as sincere?", title: "Separate the shape from the direction",
    description: "Define sincerity by its shape, follow the result Ghazali refuses to hide, and read the great teachers' definitions as a set of checks rather than one standard.",
    payoff: "You learn where the word's moral weight really comes from, and which definition fits your case.",
    image: assetUrl("assets/system/book37-pure-milk.jpg"), imageAlt: "A shallow white bowl of milk on a scrubbed stone counter, perfectly still and unclouded, in level daylight.", minutes: 13, color: "#586fa8",
    nodes: [
      node("the-milk", "Take the picture", "Nothing mixed in", "Purity means nothing else mixed in.", "The picture gives a shape, not yet a direction.", 8, "know"),
      node("consequence", "Follow the result", "Sincere in showing off", "A single unmixed motive fits the definition, whatever the motive is.", "Stated as a result, not to provoke.", 8, "clear"),
      node("the-convention", "Find the direction", "Supplied by how the word is used", "The moral meaning comes from how the word is used, just as with the word for going astray.", "This is what makes the definition usable, not just strict.", 8, "pattern"),
      node("assign-sayings", "Match the sayings", "One danger each", "Al-Susi deals with being impressed with yourself; Sahl gives the saying that covers everything.", "Read as competing, they become a standard nobody meets.", 9, "order"),
      node("the-concession", "Take the allowance", "Sincere compared with something", "Doing good out of hope for Paradise is sincere compared with wanting things now.", "The highest level is named as a level, not forced on everyone as a rule.", 9, "balance"),
    ],
  },
  {
    id: "how-mixed", number: "04", question: "How mixed is too mixed?", title: "Weigh it down to an atom",
    description: "Learn the layer of showing off that catches people who have already caught the obvious one, then take Ghazali's own maths for what a mixed deed is worth.",
    payoff: "You get a rule with four outcomes instead of a warning, and a test you can use in the moment.",
    image: assetUrl("assets/system/book37-the-atom.jpg"), imageAlt: "A small brass balance on an ivory sill, its two pans holding almost equal weights, the beam very slightly tipped.", minutes: 14, color: "#bf7a35",
    nodes: [
      node("sort-blights", "Sort the dangers", "Plain, hidden, weak, strong", "How hidden it is and how strong it is are two separate scales.", "Only understood through examples, which is why the section is a scene.", 10, "pattern"),
      node("first-grade", "See the first layer", "So they think well of you", "Your body goes humble when someone walks in.", "Not hidden even from beginners, and usually caught by shame.", 10, "diagnose"),
      node("second-grade", "Catch the second", "Dressed up as good", "Make it beautiful so they copy you — which is true, and the same motive.", "Someone not fooled by the first can be fooled by this.", 10, "guard"),
      node("the-timing", "Use the test", "Did it show up then?", "The question is whether you got better because someone was watching.", "When it happened, not what you were thinking.", 10, "witness"),
      node("the-rule", "Take the rule", "By how strong the motive is", "Ghazali marks it as his own judgment and says God knows best.", "The surface of the reports says no reward; he doesn't simply follow that.", 11, "know"),
      node("four-outcomes", "Hold the four outcomes", "Down to an atom", "Cancelling out, harm, reward for the difference, and a lighter case at the bottom.", "The proportion works both ways, which is what makes it a scale.", 11, "balance"),
    ],
  },
  {
    id: "six-meanings", number: "05", question: "What does truthfulness actually cover?", title: "Widen the word to six",
    description: "Find that speech is only the first of six meanings, that a true statement can be a lie, that keeping a decision is harder than making it, and that one cure runs the opposite way to the cure for showing off.",
    payoff: "You leave with the six as a checklist, and with the two cures kept apart.",
    image: assetUrl("assets/system/book37-six-meanings.jpg"), imageAlt: "Six shallow niches cut into one plastered wall, each holding a plain unmarked token, lit evenly from the left.", minutes: 14, color: "#a97837",
    nodes: [
      node("the-widening", "Notice the widening", "Speech is only the first", "Six meanings, and sincerity is the second.", "Part Three contains Part Two rather than just coming after it.", 12, "order"),
      node("equivocation", "Close the loophole", "A way out that isn't one", "Misleading hints count as lying, because the harm is in misleading.", "Ghazali mentions the permission, then explains it away.", 13, "guard"),
      node("true-and-false", "See the true lie", "A lie in the will", "The scholar described his deeds correctly and was told he was lying.", "The situation made it a claim about his heart.", 13, "diagnose"),
      node("fulfilment", "Weigh the fourth", "Harder than the third", "People happily decide, then flinch when the chance to act arrives.", "Umar's own exception is given to show how hard it is.", 14, "balance"),
      node("two-remedies", "Separate the cures", "Drop it, or catch up", "Showing off is treated by dropping the act; this is treated by raising the inside to match.", "Using the wrong one does the opposite of curing.", 14, "clear"),
      node("the-sixth", "Read the sixth as a level", "Made real, not just named", "The levels of religion lived for real, not just called by their names.", "Great Companions are said not to have reached this measure.", 14, "steady"),
    ],
  },
];

export const book37Movements: TaxonomyGroup[] = [
  ["fadl-niyya", "1. Why intention is valuable", "The evidence, and the three parts inside each other.", [1]],
  ["haqiqa-niyya", "2. What intention is", "Knowing, wanting and ability, and the sick man.", [2]],
  ["aqsam", "3. Kinds of intention", "An act takes its ruling from its motive.", [3]],
  ["khayr", "4. Better than the action", "Three explanations broken, and the fourth kept.", [4]],
  ["tafsil", "5. The details of acts", "Three kinds, and the one intention can't reach.", [5]],
  ["ikhtiyar", "6. Not something you can choose", "Saying an intention isn't having one.", [6]],
  ["fadl-ikhlas", "7. Why sincerity is valuable", "The evidence, and the report about the three.", [7]],
  ["haqiqa-ikhlas", "8. The reality of sincerity", "Pure milk, and the result of defining by shape.", [8]],
  ["aqawil", "9. What the great teachers said", "Each definition matched to the danger it deals with.", [9]],
  ["shawaib", "10. The layers of danger", "Four layers of showing off, each more hidden than the last.", [10]],
  ["mashub", "11. The mixed deed", "Four outcomes, weighed down to an atom.", [11]],
  ["fadl-sidq", "12. Why truthfulness is valuable", "The level, and the word that names it.", [12]],
  ["sidq-1", "13. The first three meanings", "Speech, intention and decision.", [13]],
  ["sidq-2", "14. The last three meanings", "Keeping it, action, and the levels.", [14]],
].map(([id, label, description, chapterIds], index) => ({ id, label, description, chapterIds, color: ["#bf7a35", "#278d91", "#c25f50", "#586fa8", "#a97837"][index % 5] })) as TaxonomyGroup[];

export const book37Instrument: Instrument = {
  title: "Weighing the motive",
  note: "Ghazali doesn't leave a mixed deed as just a warning; he gives a rule with four outcomes, weighed down to an atom, and says it's his own judgment. The second question comes from the section saying an intention can't be produced by announcing one. Take one act you really did — not a type of act — and answer both.",
  items: [
    {
      id: "act", label: "One act you actually did", lede: "Recent, specific, and one you'd rather not have picked",
      note: "The first question is Ghazali's maths from the section on the mixed deed. The second is from the section on intention not being something you choose, where he says saying you intend something is just words, and the only way to a real pull is gaining its causes.",
      axes: [
        {
          id: "balance", kicker: "How strong the motive was", question: "Of the two motives behind it, which was heavier?",
          options: [
            { id: "religious", label: "The religious motive, clearly", note: "Stronger than the other — the case Ghazali rewards for the difference." },
            { id: "equal", label: "About even", note: "The case where he says the two cancel out." },
            { id: "worldly", label: "The selfish motive, clearly", note: "Showing off or the self's share was stronger, which he says is harmful though lighter than pure showing off." },
            { id: "unclear", label: "I honestly can't tell", note: "The most common honest answer, and the one the second question reads." },
          ],
        },
        {
          id: "how", kicker: "How the intention came about", question: "What did you actually do about the intention?",
          options: [
            { id: "declared", label: "I said it to myself before starting", note: "Exactly the case Section 6 describes: “intending” to teach for God, or to eat for God." },
            { id: "causes", label: "I had worked on the causes beforehand", note: "The only route Ghazali allows — and he says it doesn't always work." },
            { id: "present", label: "The pull was just there", note: "Nothing was done, and something was there — a real answer, not a lesser one." },
            { id: "nothing", label: "I didn't think about it at all", note: "The act happened and the question never came up — which is where most acts really sit." },
          ],
        },
      ],
      verdicts: [
        { key: "religious|*", name: "Reward for the difference", role: "support", chapterId: 11, body: "Ghazali's rule here is clear: if the aim of getting close to God is stronger than the other motive, the reward matches how much stronger the religious motive was. He bases it on an atom's weight of good being seen — which is what makes it a proportion, not a free pass.", action: "Take the reading, not the reassurance. The rule he chose over the surface of the reports is a scale, so the honest question isn't whether the religious motive won, but by how much — and that is what he says is counted." },
        { key: "worldly|*", name: "Against you, but lighter than pure showing off", role: "warning", chapterId: 11, body: "Where showing off was stronger, Ghazali says the deed doesn't help, and is even harmful and leads to punishment. He adds straight away that the punishment is lighter than for a deed done purely to show off, with no wish for closeness to God at all.", action: "That extra line isn't comfort; it's the same scale going down. Read the section on the second layer of showing off next, because the motive easiest to misjudge is the one that came with a true thought attached." },
        { key: "equal|declared", name: "They cancel, and saying it did nothing", role: "warning", chapterId: 6, body: "Two readings meet here. Ghazali says that where the religious motive equals the selfish one they cancel out, so the deed is neither for you nor against you. And what you did about the intention was say it, which he says is just words, not an intention at all.", action: "Saying it was never going to shift the balance, so don't say it more firmly. What moves a pull is gaining its causes, and the useful question is which cause of this pull you could have set up and didn't." },
        { key: "equal|*", name: "They cancel out", role: "balance", chapterId: 11, body: "Ghazali's middle outcome, stated plainly: if the religious motive equals the selfish one, they cancel out, and the deed is neither for you nor against you. He doesn't soften it or call a balanced deed a partial success.", action: "This is the outcome that shows the rule is a scale, not a reassurance. What changes it isn't doing the deed more, but changing what weighs on it — the subject of all of Part One." },
        { key: "unclear|causes", name: "You're doing the only work there is", role: "support", chapterId: 6, body: "You can't weigh the motive, and what you did was work on the causes beforehand. Ghazali says the only way to gain the heart's pull toward something is to gain its causes — sometimes in your power and sometimes not. Not being able to weigh the result doesn't undo the work.", action: "Leave the weighing. Al-Susi's saying fits: whoever sees sincerity in their own sincerity has a sincerity that needs more sincerity — which Ghazali reads as pointing at being impressed with yourself. Not being able to check your own motive isn't the worst place to be." },
        { key: "unclear|declared", name: "That was just words", role: "warning", chapterId: 6, body: "You can't weigh the motive, and what you did was say the intention to yourself. Ghazali describes exactly this and rejects it: it's talking to yourself and talking with your tongue, and intention is far from all of it. The two answers are linked, because nothing was done that would give you anything to weigh.", action: "His comparison is a full person saying they intend to feel hungry. Stop treating the announcement as the work. Ask what would really stir you toward this deed, then which of those causes you can set up. He is honest that sometimes the answer is none." },
        { key: "unclear|*", name: "Find the balance first", role: "balance", chapterId: 11, body: "Ghazali's rule runs entirely on which motive was heavier, so a deed whose balance you don't know can't be read by it. That's a real position, not dodging; the section on the second layer of showing off exists because the balance really is hard to see.", action: "Use the timing test instead of looking inward. The question that catches the hidden layer isn't what you were thinking, but whether the deed got better when someone came into the room — a fact about the deed, not a verdict on yourself." },
        { key: "*|*", name: "Read the two together", role: "balance", chapterId: 11, body: "A balance of motives, and a particular way the intention came about. Ghazali's two sections answer different questions: one says what a mixed deed is worth, the other says what a person can actually do about it beforehand.", action: "Take the first as the assessment and the second as the work. Nothing in the book lets announcing an intention change the first — which is why the section on choice comes at the end of Part One." },
      ],
    },
  ],
};

export const book37Sources: SourceLink[] = [
  { label: "Primary Arabic text", note: "The complete public Arabic of Book 37 was read and used for the definition of intention, the three kinds of act, the account of sincerity, the four layers of showing off, and the six meanings of truthfulness.", url: "https://shamela.ws/book/9472/1520" },
  { label: "What intention really is", note: "The passage folding intention, will and aim into one meaning, and breaking every chosen act into knowing, wanting and ability.", url: "https://shamela.ws/book/9472/1524" },
  { label: "That intention isn't something you can just choose", note: "The passage rejecting a spoken intention as just words on the tongue, and saying the only way to a real pull toward something is gaining its causes.", url: "https://shamela.ws/book/9472/1532" },
  { label: "What sincerity really is", note: "The passage defining sincerity with the picture of pure milk, and drawing the result that a single unmixed motive fits the definition whatever it is.", url: "https://shamela.ws/book/9472/1538" },
  { label: "The ruling on a mixed deed", note: "The passage giving Ghazali's own rule for a mixed deed, weighed by how strong the motive is and based on an atom's weight of good and evil.", url: "https://shamela.ws/book/9472/1543" },
  { label: "Forty-book structure", note: "Ghazali.org's listing puts Book 37 seventh in the Quarter of Rescue and confirms its title.", url: "https://www.ghazali.org/listing-the-forty-books/" },
];

export const book37: SystemBook = {
  id: 37,
  title: "Intention, Sincerity, and Truthfulness",
  shortTitle: "Intention and Sincerity",
  defaultJourneyId: "what-is-an-intention",
  chapters: book37Chapters,
  conceptNodes: book37ConceptNodes,
  journeys: book37Journeys,
  sources: book37Sources,
  taxonomy: {
    title: "Fourteen reading sections",
    note: "Ghazali's three parts, in his order: six sections on intention, five on sincerity and three on truthfulness. His one long part on the six meanings of truthfulness is split into two readings — the only place this edition divides one of his parts.",
    groups: book37Movements,
  },
  instrument: book37Instrument,
  editorialNote: "The five journeys, fourteen reading sections, diagrams and self-check are learning aids made for this edition. The sections follow Ghazali's three parts and his own sections in order; the one split made here is that his part on the six meanings of truthfulness is given as two readings, and the list marks where the split falls. The English explains the ideas of the public Arabic text in plain words; it is not a translation. Reports and stories are given as Ghazali passed them on; this edition does not grade every one. The section on the details of acts is given in full, because the hadith that deeds are judged by intentions is most often misused in exactly the way that section forbids. The rule for a mixed deed is Ghazali's own judgment rather than a settled position; he says so himself, notes that the surface of the reports points the other way, and adds that God knows best, and all of that is kept here. His remark that someone who gives charity purely for show fits the bare definition of sincerity follows from that definition, and is included because he includes it and straight away explains where the word's moral direction comes from.",
};
