import { assetUrl } from "./assetUrl";
import type { Chapter, ConceptNode, VisualModel } from "./data";
import type { Instrument, Journey, SourceLink, SystemBook, TaxonomyGroup } from "./systemTypes";

type Seed = { id: number; shortTitle: string; formalTitle: string; overview: string; thesis?: string; moves: Array<{ title: string; body: string }>; closer: Array<{ title: string; body: string }>; distinction: [string, string, string, string, string]; misreading: string; reflection: string; audit: string[]; nodes: string[]; model: VisualModel };
const stageOf = (id: number) => (id <= 3 ? "the first stage, setting terms" : id <= 8 ? "the second stage, vigilance" : id <= 10 ? "the third stage, reckoning" : id === 11 ? "the fourth stage, punishment" : id <= 13 ? "the fifth stage, striving" : "the sixth stage, reproach");
const makeChapter = (seed: Seed): Chapter => ({
  id: seed.id, shortTitle: seed.shortTitle, formalTitle: seed.formalTitle, overview: seed.overview,
  reflection: seed.reflection, relatedNodes: seed.nodes, visualModel: seed.model,
  deep: { thesis: seed.thesis ?? seed.moves[0].body, context: seed.overview, moves: seed.moves, closeReading: seed.closer,
    distinction: { title: seed.distinction[0], firstLabel: seed.distinction[1], first: seed.distinction[2], secondLabel: seed.distinction[3], second: seed.distinction[4] },
    misreading: seed.misreading, observation: seed.reflection, selfAudit: seed.audit,
    sourceAnchor: `Book 38, ${stageOf(seed.id)}, ${seed.formalTitle}.` },
});
const chain = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "chain", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const pair = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "pair", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const spectrum = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "spectrum", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });

export const book38Chapters: Chapter[] = [
  makeChapter({
    id: 1, shortTitle: "The partnership", formalTitle: "The frontier-watch and its six stages",
    overview: "The book opens on one long comparison. Unlike most comparisons in the Ihya, this one is not an illustration. It is the actual structure of the book: the six stages are drawn out of it one by one.",
    thesis: "One sustained analogy runs the whole book: a merchant, a partner, and a set of accounts.",
    moves: [
      { title: "Set the trade", body: "When business partners settle up, what they want is for the profit to be safe. The mind is a merchant on the road to the next life. What it is after — its whole profit — is a clean self, because that is where its success lies." },
      { title: "Name the partner", body: "The mind takes the self on as a partner in this business, putting it to work at whatever will clean it. It is like a merchant who takes on a partner or an agent to trade with his money." },
      { title: "Name the difficulty", body: "But a partner can turn into an opponent who argues with you over the profit. So the mind has to deal with the self in four steps: first set it terms, then watch it, then call it to account, and finally punish or reproach it." },
      { title: "Give the six", body: "The stages of the watch are therefore six: setting terms, vigilance, reckoning, punishment, striving, and reproach. Ghazali says the account of them is necessary, and the rest of the book is that account in order." },
      { title: "Follow the commercial frame", body: "The whole book runs on one comparison, and it is worth taking seriously rather than as decoration. The mind is a merchant on the road to the next life. The profit it wants is a cleaned-up self. And it takes the self on as a working partner, the way a merchant takes on someone to trade with his money. That makes every stage that follows a term in a business relationship, not a devotional exercise." },
      { title: "Note where the difficulty enters", body: "The difficulty is put in the same language: a partner can become an opponent who fights you over the profit. That is exactly right. The self is not an enemy from outside. It is the party you are working with, and the dispute is over the share. That is why four of the six stages are things a merchant does with a partner he cannot get rid of: set terms, keep watch, check the accounts, and charge for losses." },
    ],
    closer: [
      { title: "Why the partner is an adversary", body: "The comparison would have been gentler if the self were only a servant. Ghazali chooses a partner who disputes the profit, because the self is not just lazy — it has interests of its own. A picture in which it only needed instruction would never produce the fourth, fifth and sixth stages." },
      { title: "The neglect clause", body: "“He must not stop watching it for a moment. If he neglects it, he will see nothing from it but betrayal and wasted capital, like a dishonest servant left alone with the money.” The whole of the second stage is in that sentence." },
    ],
    distinction: ["Two ways to take the merchant", "As the architecture", "Each stage is derived from something a merchant actually has to do, which is how the book is built.", "As an illustration", "A figure decorating a spiritual programme, which would leave the six stages unexplained."],
    misreading: "Do not read the trade language as making this a matter of calculation without warmth. The same analogy produces the reproach in stage six, which is the least commercial thing in the book.",
    reflection: "Notice that the model puts you on the merchant's side and your soul on the partner's, and ask whether that is how you have been thinking of it.",
    audit: ["Who is the merchant here, and who the partner?", "Where has the capital gone unwatched?", "Which of the six do I skip?", "Do I treat the soul as lazy or as interested?"],
    nodes: ["murabata", "six-stations", "nafs"],
    model: chain("The six stages", "Each one answers something the analogy makes necessary.", [["Set terms", "Assign the duties and impose the conditions before the day starts.", "support"], ["Watch", "Because a partner left alone with the capital is a partner unwatched.", "support"], ["Reckon", "Look at capital, profit, and loss when the trading is done.", "support"], ["Punish", "Because a loss that is not charged is a loss that repeats.", "warning"], ["Strive", "Make good what was missed rather than only stopping the leak.", "balance"], ["Reproach", "The stage the commercial model does not by itself predict.", "support"]]),
  }),
  makeChapter({
    id: 2, shortTitle: "The morning charge", formalTitle: "The first stage: setting terms with the self",
    overview: "The practical opening of the day. Ghazali gives the terms a person sets with his own soul, and the tone of the passage is closer to an address than to a rule.",
    thesis: "The day opens by setting terms with yourself, and Ghazali gives the terms.",
    moves: [
      { title: "Say what setting terms means", body: "The intellect assigns the soul its duties, imposes on it its conditions, guides it to the road of success, and binds it firmly to travelling those roads. All of it happens before anything has been done." },
      { title: "Give the address", body: "The charge is spoken to the self directly: you died and have been given back. So beware — and beware again — of wasting this day, because every breath is a priceless jewel." },
      { title: "Set the unit", body: "Know, O soul, that the day and the night are twenty-four hours. The unit is deliberately small and countable, which is what makes the following image possible and what makes an evening reckoning feasible at all." },
      { title: "Say why it must be renewed", body: "If the self obeys in some of it, the terms still have to be renewed for the rest, since no day is free of something new happening. Setting terms is something you do every day, not a resolution made once." },
      { title: "Note what makes setting terms different", body: "Setting terms happens before anything has been done, and that is what makes it different from every other stage. The mind assigns duties, sets conditions, points out the way, and binds the self to it — all in advance. So the day is decided at its start, by someone who is not yet tired, not yet provoked, and not yet standing in front of what he wants." },
      { title: "Take the address to the soul", body: "The charge is said out loud to the self, not just resolved on inwardly: you died and have been given back, so beware of wasting this day, since every breath is a priceless jewel. The form matters. A person is speaking to something, not simply deciding something. And the unit is deliberately small and countable — twenty-four hours — which is what makes both the store-rooms image and an evening audit possible." },
      { title: "Note why it is daily", body: "The terms have to be renewed every morning, because a self that obeyed in part still leaves the rest of the day unsettled, and no day is free of something new. That rules out making one big resolution and relying on it afterwards. That is how most people try to do this, and it is why they usually fail." },
    ],
    closer: [
      { title: "The relation to Book 37", body: "Book 37 showed that an intention cannot be produced just by declaring one; the only way is to arrange its causes. This chapter is one of those arrangements. Setting terms is not an intention made up on the spot. It is a condition placed on the day in advance — a cause, not a declaration." },
      { title: "Why an address rather than a plan", body: "The soul is a partner with interests of its own, so what is given is terms and not a schedule. Ghazali's language here is the language of one party binding another, and the reader is on both ends of it." },
    ],
    distinction: ["Two things done at the start of a day", "Setting terms", "Terms imposed on a party that will dispute them, renewed daily.", "Resolving", "A declaration made to oneself, which Book 37 said produces nothing by itself."],
    misreading: "Do not read the severity of the address as the point. What is load-bearing is the smallness of the unit and the daily renewal, not the intensity of the language.",
    reflection: "Try the unit rather than the tone. Twenty-four hours, named as twenty-four, is a different object from a day.",
    audit: ["What terms did I set this morning?", "Did I renew them, or set them once long ago?", "Is my unit the day or something vaguer?", "What new matter has arrived that the terms do not cover?"],
    nodes: ["musharata", "murabata", "nafs"],
    model: pair("What the stage actually is", "The difference decides whether it can work.", [["Terms on a day", "Conditions set in advance on a party that will dispute them.", "support"], ["A resolution", "A declaration to oneself, which Book 37 already refused.", "warning"]]),
  }),
  makeChapter({
    id: 3, shortTitle: "The empty treasury", formalTitle: "The twenty-four treasuries",
    overview: "The image that setting terms is built on, and its third element is the one that does the work. Two of the three treasuries are the ones everyone expects.",
    thesis: "Twenty-four store-rooms, one for each hour, and the third of them is what makes the image bite.",
    moves: [
      { title: "The lit treasury", body: "For every day and night, twenty-four store-rooms are laid out for you in a row. One is opened, and you find it full of light from the good you did in that hour. The joy of seeing it — since it is what you have to show the King — would be enough, if it were shared among the people of the Fire, to take their minds off their pain." },
      { title: "The dark treasury", body: "Another is opened, black and dark, its stench rising from it and its darkness covering him, and it is the hour in which he disobeyed. The dread that reaches him from it, if divided among the people of the Garden, would spoil their bliss for them." },
      { title: "The empty treasury", body: "Another is opened and found empty. It holds nothing that makes him glad and nothing that grieves him. It is the hour he slept, or was careless, or spent on something permitted in this world." },
      { title: "Name what it costs", body: "He grieves at its emptiness. His regret is that of a man who could have won a great profit and a great kingdom, but neglected it and let it slip away." },
      { title: "Note the third treasury", body: "Two of the three treasuries are what anybody would expect and the third is the point of the image. An hour spent asleep, or heedless, or busy with something entirely permitted, opens as a room with nothing in it — nothing to gladden and nothing to grieve. Which is where most of a life goes, and the ordinary reckoning has no category for it at all." },
      { title: "Take the measure of the grief", body: "The regret at the empty room is described exactly: it is how a man feels who could have won a fortune and a kingdom and was too slack to take it. It is not guilt. He did nothing wrong — and that is what makes the case hard. What he faces is the arithmetic of what was on offer and not taken, which no amount of avoiding sins would have fixed." },
      { title: "See what the image is doing", body: "The extravagance of the first two rooms is set up to make the third one land. The joy from one lit hour would take the people of the Fire's minds off their pain. The dread from one dark hour would spoil the bliss of the people of the Garden. Set against those, the empty room is the one a person can actually do something about tomorrow — and the image exists to make its emptiness felt." },
    ],
    closer: [
      { title: "Why the third is the point", body: "The first two treasuries are credit and debit, and any account of a day contains them. The third is neither, and it is the one most hours actually go into. The image is constructed so that the ordinary hour has a cost, and the cost is named as chagrin rather than as guilt." },
      { title: "Where the permissible sits now", body: "Book 37 divided acts into disobedience, obedience, and the permissible, and said that the permissible is where most of a life sits and is open to the motive. This chapter is what that costs when the motive was never supplied: not a black treasury but an empty one." },
    ],
    distinction: ["Two ways an hour can fail", "Filled darkly", "The hour of disobedience, which is a debit and which everyone counts.", "Left empty", "The hour of sleep, heedlessness, or permitted business, which is not a debit and is still a loss."],
    misreading: "Do not read the empty treasury as condemning rest or the permitted. What is named is that the hour produced nothing, and the chapter's own word for the response is chagrin at a missed profit, not blame for a sin.",
    reflection: "Count yesterday in twenty-four and ask honestly how many of the treasuries would be empty.",
    audit: ["How many of my hours are empty ones?", "Do I count only the dark ones?", "What would fill one of them?", "Am I treating loss as though it were neutrality?"],
    nodes: ["treasuries", "musharata", "mubah"],
    model: spectrum("Three kinds of hour", "The middle one is the one the image was built for.", [["Lit", "Filled with light from what was done in it.", "support"], ["Empty", "Sleep, heedlessness, or permitted business; neither credit nor debit, and still a loss.", "balance"], ["Dark", "The hour of disobedience, whose dread would spoil the bliss of the Garden.", "warning"]]),
  }),
  makeChapter({
    id: 4, shortTitle: "Like the knowledge of death", formalTitle: "The second stage: the reality of vigilance and its degrees",
    overview: "The definition, and it is unusually careful. Ghazali separates three things that are normally run together, and then explains why knowing something is not enough.",
    thesis: "Vigilance is defined carefully, because the whole book turns on the state rather than on the acts.",
    moves: [
      { title: "Give the ordinary sense", body: "The reality of vigilance is regarding the watcher and turning one's concern to him. Whoever guards against some matter on account of another is said to be watching him and observing his side." },
      { title: "Separate the three", body: "What is meant is a state of the heart, which a kind of knowledge fruits, and which itself fruits acts in the limbs and in the heart. So there is a knowledge, a state that follows from it, and acts that follow from the state." },
      { title: "Name the knowledge", body: "The knowledge is this: God knows every inner thought and every secret. He watches over what people do, and stands over every soul with what it has earned. The secret of the heart is as open to Him as the skin is open to people — and more." },
      { title: "Give the condition", body: "This knowledge must become certainty, meaning free of doubt, and then must take possession of the heart and subdue it. For many a knowledge in which there is no doubt does not dominate the heart, like the knowledge of death." },
      { title: "Note the three-part structure again", body: "Watchfulness is given the standard shape: a piece of knowledge, a state that grows out of it, and actions that grow out of the state. That puts it alongside every other stage in this quarter. It means you cannot produce it by deciding to be more watchful. The work goes into the knowledge, which is what the section goes on to spell out." },
      { title: "Take the condition seriously", body: "The condition attached to it is the sharp part. The knowledge must become certainty, and then it must take hold of the heart and master it. Many things are known beyond doubt and still rule nobody — and his example is death, which nobody disputes and almost nobody is governed by. So holding the right belief is not even the start of this stage." },
    ],
    closer: [
      { title: "The force of that last clause", body: "Everyone reading knows they will die, without a trace of doubt, and it governs almost nothing. Ghazali names that as the exact failure mode of the knowledge he has just described, which means the chapter cannot be satisfied by assenting to it. It is the same move as Book 37's sick man, who sees the food and knows it agrees with him and does not reach." },
      { title: "Why the state matters more than the acts", body: "Actions are the fruit two steps further down. Work directly on the actions without the state, and you get the surface compliance this book has no interest in. The two levels in the chapters that follow are levels of the state, not of the performance." },
    ],
    distinction: ["Two things a person can have of this knowledge", "Assent without dominion", "Free of doubt and governing nothing, as with the knowledge of death.", "Certainty that has taken possession", "The same knowledge having subdued the heart, which is what produces the state."],
    misreading: "Do not treat agreement with the doctrine as having the stage. The chapter's whole point is that undoubted knowledge routinely fails to govern, and it names the commonest example so the reader cannot claim otherwise.",
    reflection: "Take a thing you do not doubt at all and that changes nothing about your day. That gap is what this chapter is about.",
    audit: ["What do I know and not act on?", "Has this knowledge taken possession or only been agreed?", "Am I working on the acts or on the state?", "What would move it from assent to dominion?"],
    nodes: ["muraqaba", "knowledge", "certainty"],
    model: chain("Knowledge, state, acts", "Each stage produces the next, and the first stage commonly fails.", [["Knowledge", "That the inmost is disclosed, more than the skin is to others.", "support"], ["Possession", "The knowledge subduing the heart, which undoubted knowledge often fails to do.", "balance"], ["The state", "The heart's regard for the Watcher and its turning to Him.", "support"], ["The acts", "What follows in the limbs and in the heart, twice removed.", "support"]]),
  }),
  makeChapter({
    id: 5, shortTitle: "The shepherd", formalTitle: "The first degree: the vigilance of the near",
    overview: "The higher degree, and Ghazali treats it briefly and then spends most of the chapter proving that it is not exotic.",
    thesis: "The higher degree is described briefly and then set aside as not the reader's business yet.",
    moves: [
      { title: "Name it", body: "The first level is the watchfulness of those brought near, among the truthful. It is watchfulness made of awe and reverence. The heart is absorbed in gazing at God's majesty and broken beneath the awe, so that there is no room left in it to turn to anything else at all." },
      { title: "Say why its acts are not detailed", body: "Ghazali does not spend long on the actions of this level, because it all happens in the heart. The limbs can no longer turn even to what is permitted, let alone to what is forbidden. When they move in obedience, they move as if they were being used, and need no managing to keep them straight." },
      { title: "Give the image", body: "The shepherd keeps the flock in order, and the heart plays that role for the limbs. When the heart becomes absorbed in the One worshipped, the limbs move rightly without constant management. The person's many concerns have become one concern, and God has made the remaining concerns sufficient." },
      { title: "Describe what it looks like", body: "Someone who reaches this point can be so oblivious to the people around him that he does not see who is standing in front of him, though his eyes are open. He does not hear what is said to him, though he is not deaf. He walks past his own son without a word. One of them, told off for it, said: “Give me a shake when you pass.”" },
      { title: "Note why the acts are not detailed", body: "Ghazali does not work through the actions of this level, and the reason is built into it, not shyness. At this level everything is in the heart, and the limbs follow without being managed. They cannot turn even to what is permitted, and when they move in obedience they move as if being used. There is nothing to prescribe because nothing is being steered." },
      { title: "Take the shepherd image", body: "His image explains why: the flock is kept in order by the shepherd, and the heart is the shepherd. That is the claim the whole Ihya rests on — that how we act flows from the state of the heart — stated here where it becomes visible. This is the man whose many concerns have become one concern, so that God has taken care of all the rest for him." },
      { title: "Note the honesty of the description", body: "What this level actually looks like is not flattering. He does not see who is in front of him, though his eyes are open. He does not hear what is said, though he is not deaf. He walks past his own son without a word. One of them, told off for it, simply asked to be given a shake when people passed. It is reported as a condition someone is in, not as a model to copy — which is why the second level is the one Ghazali writes up in detail." },
    ],
    closer: [
      { title: "The argument that it is ordinary", body: "“Do not think it far-fetched,” he says. You find something like it in hearts that are in awe of earthly kings. A king's servants may not notice what is happening to them in the royal court, they are so absorbed. The heart can even get so caught up in some trivial worldly matter that a man, lost in thought, walks past the place he meant to go and forgets the errand he set out on." },
      { title: "Why he argues for it that way", body: "The degree is rare and the anecdotes about it invite disbelief. Rather than defending the anecdotes, Ghazali points at an absorption every reader has experienced over something trivial, and lets the reader supply the proof that the mechanism exists." },
    ],
    distinction: ["Two ways the limbs are kept straight", "By management", "Each act watched, weighed, and steadied, which is the second degree.", "By a single concern", "The heart is absorbed, so the limbs run straight without constant management."],
    misreading: "Do not aim at this degree by imitating its symptoms. What is described is a consequence of absorption, and the descriptions of not seeing and not hearing are effects rather than practices.",
    reflection: "Recall walking past the place you were going to because you were thinking about something small. The mechanism is not in question.",
    audit: ["Has my concern ever been one concern?", "What absorbs me involuntarily?", "Am I managing the limbs or the heart?", "Would I recognise this if I saw it?"],
    nodes: ["muraqaba", "absorption", "qalb"],
    model: pair("Two routes to straight limbs", "The first degree does without the management entirely.", [["The shepherd absorbed", "A single concern, and the limbs run straight without constant management.", "support"], ["Each act managed", "Weighed and steadied one by one, which is the second degree's work.", "balance"]]),
  }),
  makeChapter({
    id: 6, shortTitle: "Pause at the intent", formalTitle: "The second degree: the vigilance of the companions of the right hand",
    overview: "The degree almost every reader is in, and the one with an actual procedure. It is a rule about timing rather than about intensity.",
    thesis: "The degree almost every reader is in, and the one that comes with something you can actually do.",
    moves: [
      { title: "Give al-Hasan's rule", body: "“God have mercy on a person who paused at his intention: if it was for God, he went ahead, and if it was for something else, he held back.” The whole second level is in that pause." },
      { title: "State it as an obligation", body: "Ghazali says everyone must watch the self at the moment of intending an act and at the moment of starting to move. Pause before committing to the intention and the effort. Let knowledge show whether the act is for God — in which case, do it — or whether it serves the self's whim — in which case, guard against it." },
      { title: "Say what to do with the thought", body: "He restrains the heart from thinking about it and from intending it, which is a different instruction from refusing the act. The object of the second degree is the thought and not the deed." },
      { title: "Note who can do it", body: "He adds that someone who knows the faults of the self, the devil's tricks, and where the traps are will watch out for them. Someone who does not know them cannot possibly watch out for them. The pause only helps if you know what you are looking for." },
      { title: "Take the pause as the whole degree", body: "Al-Hasan's rule is the whole second level in one sentence: pause at your intention, and if it is for God go ahead, and if it is for anything else hold back. It is small enough to do and hard enough to matter. It costs a moment. It happens before the act. And it demands an honest answer to a question most people would rather not ask." },
      { title: "Note what the object of the pause is", body: "The instruction is to stop the heart from thinking about the thing and intending it — which is different from refusing to do it. The target of the second level is the thought, not the action. That is why the next section's chain comes straight after, and why someone can practise this level before he has stopped doing anything." },
      { title: "Take the qualification about knowledge", body: "One condition keeps this level from being easy. Someone who knows the faults of the self, the devil's tricks and where the traps lie will watch for them; someone who does not cannot possibly watch for them. The pause is worthless without the knowledge of the Quarter of Perils behind it. That knowledge is what a person is meant to be checking against, in the moment." },
    ],
    closer: [
      { title: "Why the pause and not the resistance", body: "Resistance operates at the end of the sequence, where the act is already wanted and the cost of refusing is highest. The pause operates at the point where refusing costs almost nothing, which is why the next chapter sets out the sequence explicitly." },
      { title: "When it does not resolve", body: "“When it stays unclear and nothing becomes plain, think it through in the light of what you know, and ask to be protected from the devil's trick dressed up as your own preference.” Ghazali does not pretend that the pause always produces an answer." },
    ],
    distinction: ["Two places to intervene in an act", "At the intent", "Before desire has formed, where holding back costs least and the light of knowledge can still be brought.", "At the deed", "After the sequence has run, where the act is wanted and refusal is hardest."],
    misreading: "Do not read the pause as hesitation or anxious scruple. It has an end point. It ends when knowledge shows which of the two the intention is — and Ghazali says what to do when it does not.",
    reflection: "Try it once at the smallest scale, on something you are about to do for no particular reason.",
    audit: ["Where do I usually intervene?", "Do I know what I am looking for?", "What happens when the pause yields nothing?", "Which of my acts never get paused at all?"],
    nodes: ["muraqaba", "khatir", "knowledge"],
    model: chain("Where the pause sits", "It intervenes at the point where intervening is cheapest.", [["The intent", "Where the second degree acts, before desire has formed.", "support"], ["The effort", "The limb already moving, where holding back is harder.", "balance"], ["The deed", "Where resistance usually operates, and where it costs most.", "warning"]]),
  }),
  makeChapter({
    id: 7, shortTitle: "The first step", formalTitle: "The sequence from a passing thought",
    overview: "The reason the pause belongs where it does. Ghazali sets out a chain of five links and says the material of evil is to be cut at the first.",
    thesis: "A chain of five links, with the instruction to cut it at the first.",
    moves: [
      { title: "State the chain", body: "“The first step towards what is false, if it is not pushed away, gives birth to desire. Desire gives birth to intention. Intention gives birth to firm resolve. Resolve gives birth to the act. And the act gives birth to ruin and God's displeasure.”" },
      { title: "Draw the instruction", body: "So the material of evil should be cut off at its first source, which is the passing thought, since everything after it follows it." },
      { title: "Explain the leverage", body: "Each link is easier to break than the one after it, because each one supplies the motive for the next. The chain is an argument about cost, not a claim that a thought is already a sin." },
      { title: "Connect it to the definition of intention", body: "Book 37 defined intention as the self being stirred towards what it sees as serving its purpose, and said that an inclination cannot be called up or dismissed at will. This chain is where that becomes practical. The inclination cannot be cancelled once it has formed — but the passing thought that forms it can be turned away." },
      { title: "Follow the chain link by link", body: "The chain is a sequence of things giving birth to the next. The passing thought gives birth to desire; desire to intention; intention to firm resolve; resolve to the act; and the act to ruin. Five links, each producing the next. The point of laying it out is that the last link is usually the only one anybody tries to stop — and it is the one where nothing can be done." },
      { title: "Take the argument about leverage", body: "The reason for cutting at the first link is an argument about cost, not a claim that a thought is already a sin. Each link supplies the push for the next, so each is harder to break than the one before. That makes turning away a passing thought the cheapest move available, and refusing the act at the end the most expensive. Most people spend all their effort at the expensive end." },
      { title: "Note what this makes practical", body: "This is where the previous book's hardest claim becomes usable. Intention was defined as an inclination, and an inclination cannot be called up or dismissed at will — which sounded like a dead end. The chain is the way out. The inclination cannot be cancelled once it has formed, but the passing thought that forms it can be turned away while it is still just a thought." },
    ],
    closer: [
      { title: "Why a passing thought is not blamed", body: "Nothing in the sequence says the first link is blameworthy. It says the first link is where you can intervene. That is a point about leverage, not about guilt. Reading it as guilt produces exactly the anxious scruple that the previous chapter's end point rules out." },
      { title: "How this reframes failure", body: "A person who repeatedly loses at the fourth or fifth link concludes that his will is weak. The chain says instead that he is intervening late, and that the same will would succeed at the first link. That is a diagnosis with a remedy attached." },
    ],
    distinction: ["Two accounts of losing an argument with yourself", "Weak will", "The capacity to refuse is insufficient, which suggests only trying harder.", "Late intervention", "The capacity is being applied at the fifth link instead of the first, which suggests moving it."],
    misreading: "Do not turn the chain into a rule that thoughts must be policed. Its claim is that the first link is where the cost of declining is lowest, and it makes no claim that having the thought is a fault.",
    reflection: "Take something you lost this week and locate which link you were fighting at.",
    audit: ["Which link do I fight at?", "What would declining at the first have cost?", "Have I diagnosed leverage as weakness?", "Where is my first source?"],
    nodes: ["khatir", "muraqaba", "nafs"],
    model: chain("Five links", "Each supplies the motive for the next, and the first is the cheapest to break.", [["A passing thought", "Not blamed, and the only place intervention is cheap.", "balance"], ["Desire", "What the unrepelled thought bequeaths.", "warning"], ["Intent", "What desire bequeaths.", "warning"], ["Firm purpose", "What intent bequeaths.", "warning"], ["The act", "And what the act bequeaths after it.", "warning"]]),
  }),
  makeChapter({
    id: 8, shortTitle: "Three registers", formalTitle: "The three registers spread for every motion",
    overview: "The most exacting passage in the book, and the one this edition builds its diagnostic on. Three questions are put to a single act, and each is a gate to the next.",
    thesis: "Three registers are spread for every movement, which is the most exacting passage in the book.",
    moves: [
      { title: "Give the frame", body: "For every motion of a servant's motions, however small, three registers are spread: the first is why, the second is how, and the third is for whom." },
      { title: "The first register", body: "Why did you do this? Was it required of you for your Master, or did appetite and personal desire draw you toward it? If the act passes this first question, the person is asked about the second register." },
      { title: "The second register", body: "How did you do this? For God has in every act a condition and a ruling whose measure and time and quality are grasped only by knowledge. So: did you do it by verified knowledge, or by ignorance and conjecture? If he is safe from this, the third is spread." },
      { title: "The third register", body: "For whom did you act? Purely for the face of God, in fulfilment of your saying that there is no god but God, so that your wage is upon God? Or to be seen by a creature like you, so take your wage from him? Or to attain your immediate world, and we have paid you your share of it? Or in inadvertence and heedlessness, so that your wage has fallen." },
      { title: "Note that the three questions are sequential", body: "The three registers are spread in order and each is only reached by surviving the last — which is what makes the frame more demanding than a checklist. Why did you do it, how did you do it, and for whom. A man can have an impeccable answer to the third and never reach it, because the second stopped him." },
      { title: "Take the second register seriously", body: "The second question is the one nobody expects in an examination of motives. Every act has conditions, a ruling, a measure, a time and a manner, and only knowledge can grasp them. So the question is whether the act was done from real knowledge or from guesswork. That puts ignorance alongside bad intention, and makes learning part of the audit rather than a separate duty." },
      { title: "Follow the third register's four outcomes", body: "The third question has four answers, not two, which is what makes it usable. Purely for God — so the reward is God's to give. To be seen by some person — so take your reward from him. For some immediate worldly gain — and you have already been paid your share. Or without thinking — in which case the reward has simply lapsed. Three of the four are ways of having been paid already." },
    ],
    closer: [
      { title: "Why the order is a sequence and not a list", body: "The second question is only reached by someone safe from the first, and the third only by someone safe from the second. A person who fails at why never arrives at for whom, which means the familiar anxiety about sincerity is often being felt at the wrong gate." },
      { title: "What the second register asks that the others do not", body: "It is the only question about competence rather than motive, and it is the one readers skip. Ghazali states the standard plainly: the measure, the time and the manner of an act are known only through knowledge. So an act done out of habit and guesswork fails here, even when the motive was good." },
    ],
    distinction: ["Two failures that feel the same", "Failing at why", "The act was not owed and was reached for by appetite, whatever was intended by it.", "Failing at for whom", "The act was owed and correctly done, and was performed to be seen."],
    misreading: "Do not collapse the three into a general demand for sincerity. Two of the three are not about sincerity at all, and the sequence is what tells you which question your case actually stops at.",
    reflection: "Take one thing you did today and put the three questions to it in Ghazali's order rather than in the order you would have chosen.",
    audit: ["Which register does this act stop at?", "Was it owed, or reached for?", "Do I know how it is to be done, or do I guess?", "Am I anxious at the wrong gate?"],
    nodes: ["registers", "ikhlas", "knowledge"],
    model: chain("Three gates", "Each is reached only by passing the one before it.", [["Why", "Owed to your Master, or inclined to by appetite.", "support"], ["How", "By verified knowledge, or by ignorance and conjecture.", "support"], ["For whom", "For the face of God, to be seen, for an immediate return, or in heedlessness.", "support"]]),
  }),
  makeChapter({
    id: 9, shortTitle: "Before you are reckoned", formalTitle: "The third stage: the excellence of reckoning with the soul",
    overview: "The stage that gives the book half its title. Ghazali gathers the testimony and, in doing so, quietly connects reckoning to repentance.",
    thesis: "The stage that gives the book half its title, and it is an audit rather than a mood.",
    moves: [
      { title: "Give the verse", body: "O you who believe, fear God, and let a soul look to what it has sent forward for tomorrow. Ghazali reads this as a pointer to reckoning over acts already past." },
      { title: "Give Umar's rule", body: "Reckon with yourselves before you are reckoned with, and weigh yourselves before you are weighed. The sentence is the stage in miniature and supplies its whole rationale." },
      { title: "Give the forward version", body: "A man asked for advice, and was asked back whether he was the kind who takes it. He said yes, and was told: “When you mean to do something, look at how it will end. If it leads somewhere good, do it. If it leads somewhere wrong, stop.” So the reckoning works forwards as a warning, as well as backwards as an audit." },
      { title: "Connect it to repentance", body: "God says to turn to Him all together, and repentance is a looking into the act after finishing it, with regret over it. So reckoning and repentance are the same operation described from two sides, which is why Book 31 stands behind this stage." },
      { title: "Note that the reckoning runs both ways", body: "The stage is presented as an audit of what is past, but the advice given to the man who asked for it runs the other way: when you mean to do something, look at where it ends; if it leads somewhere good, do it, and if it leads somewhere wrong, stop. So the same act of reckoning works as a warning before and as an audit after. That is why it can take in both the second stage and the eleventh." },
      { title: "Take Umar's sentence", body: "Umar's rule gives the whole reason in one line: “Call yourselves to account before you are called to account, and weigh yourselves before you are weighed.” That makes the practice not an extra piety but a rehearsal of something that will happen anyway — the only version of it in which you can still act on what you find." },
      { title: "Note the identity with repentance", body: "The connection drawn at the end is worth noticing. Repentance is looking back at an act after you have finished it, with regret. That is the same operation as reckoning, seen from the other side. So this stage is not a new demand on a reader who has already read the book on repentance. It is the first part of that book, turned into a daily hour." },
    ],
    closer: [
      { title: "The four hours", body: "Among the reports carried here is that the intelligent person should have four hours, one of them an hour in which he reckons with himself. The stage is given a place in a day rather than being left as a disposition." },
      { title: "Why forward and backward both", body: "A purely retrospective audit can only produce regret. Ghazali's inclusion of the forward form, considering the outcome before acting, joins this stage to the second: the pause at the intent is reckoning done in advance." },
    ],
    distinction: ["Two directions of the same operation", "Backward", "Looking into what has been sent forward, which produces regret and correction.", "Forward", "Considering the outcome before acting, which is the pause of the second stage."],
    misreading: "Do not read this as a call to general self-scrutiny. What is specified is an hour, and the following chapter specifies what is done in it.",
    reflection: "Notice whether your self-examination has a time or is merely a mood that arrives.",
    audit: ["Does my reckoning have an hour?", "Do I only look backward?", "What did I send forward today?", "Would I accept this audit from someone else?"],
    nodes: ["muhasaba", "tawba", "musharata"],
    model: pair("Two directions", "Joining them is what connects this stage to the second.", [["Backward", "An audit of what was sent forward, producing regret and correction.", "support"], ["Forward", "Considering the outcome before acting, which is the pause at the intent.", "support"]]),
  }),
  makeChapter({
    id: 10, shortTitle: "Capital, profit, loss", formalTitle: "The reality of reckoning after the act",
    overview: "The analogy returns with its full machinery, and Ghazali extracts an actual procedure from it rather than a sentiment.",
    thesis: "The commercial machinery returns in full, and this is where it does the most work.",
    moves: [
      { title: "Place the hour", body: "Just as you set terms with yourself at the start of the day, you should have an hour at the end of it when you call yourself to account for everything you did, and everything you left undone." },
      { title: "Give the commercial parallel", body: "It is what merchants do with their partners at the end of every year, month or day. They do it out of eagerness for this world and fear of missing any of it. Yet if they had missed it, the missing might well have been the better outcome; and even when they get it, it lasts only a few days." },
      { title: "Draw the reproach", body: "So how should the intelligent man not reckon with himself in what carries the risk of wretchedness and happiness for all time? This laxity is only from heedlessness and abandonment." },
      { title: "State the procedure", body: "Reckoning with a partner means looking at the capital, and at the profit and the loss, so that what has grown can be told from what has shrunk. If there is a surplus, the merchant takes it in full and gives thanks. If there is a loss, he demands that the partner make it good, and charges him with it." },
      { title: "Take the shape of the day", body: "The two stages bracket the day: terms set in the morning, accounts settled in the evening. Together they form one complete structure, not two separate exercises. The evening hour has something specific to check against, and the morning's terms are written knowing they will be checked. Neither works nearly as well without the other." },
      { title: "Follow the merchant's reproach", body: "The argument works by comparison rather than by preaching, and that is what gives it force. Merchants reckon with their partners every year, month or day, out of eagerness for this world and fear of missing something. And yet if they had missed it, the missing might have been the better outcome — and even when they get it, it lasts a few days. The care is real. It is just being spent on the smaller thing." },
      { title: "Note the procedure itself", body: "The method is given in business terms exactly. Look at the capital, then at the profit and the loss, so that growth stands out from shrinkage. Take the surplus and give thanks. Where there is a loss, demand that it be made good and charge it to the partner. That last clause is not just a figure of speech. It is what the fourth stage consists of, arriving here as the next step in the accounts." },
    ],
    closer: [
      { title: "What the capital is", body: "The analogy names three quantities, and only two of them are usually thought about. The capital is what was given before any trading began, which is why the reckoning ends in thanks where there is surplus rather than in satisfaction." },
      { title: "The force of the comparison", body: "The argument is not that merchants are worldly but that they are diligent, and that their diligence is spent on something that lasts a few days at best. Ghazali's reproach is about proportion between effort and stake, which is why it lands on the reader as a practical embarrassment rather than as a moral charge." },
    ],
    distinction: ["Two ways to close a day", "Reckoning", "Capital, profit, and loss looked at separately, with a demand made where there is loss.", "Reviewing", "A general impression of how the day went, which yields neither thanks nor a charge."],
    misreading: "Do not skip the third quantity. A reckoning that looks only at profit and loss omits the capital, and the capital is what makes thanks the response to a good day.",
    reflection: "Close one day this way, with the three quantities named separately, and notice which of them you have never counted.",
    audit: ["What was my capital here?", "Where was the surplus, and did I give thanks?", "Where was the loss, and did I charge it?", "Is my hour at the end of the day, or nowhere?"],
    nodes: ["muhasaba", "murabata", "capital"],
    model: chain("Three quantities", "Most reckonings count two of them.", [["Capital", "What was given before any trading began, and why the response to surplus is thanks.", "support"], ["Profit", "The surplus obtained, taken in full and acknowledged.", "support"], ["Loss", "The decrease, which is not merely noted but charged.", "warning"]]),
  }),
  makeChapter({
    id: 11, shortTitle: "Charging the loss", formalTitle: "The fourth stage: punishing the soul for its shortfall",
    overview: "The stage modern readers find hardest, and it is worth reading closely for what it actually specifies and what it merely reports.",
    thesis: "The stage modern readers find hardest, and it is worth reading before deciding about it.",
    moves: [
      { title: "State why the stage exists", body: "Whenever he calls the self to account and it has not come out clear of doing wrong or falling short, he must not let it go. If he lets it go, doing wrong becomes easy for him. His self grows used to it, and weaning it off becomes hard — and in that lies its ruin." },
      { title: "Give the principle", body: "The punishment is matched to the part of the body that took the profit. If he ate a doubtful mouthful out of appetite, he should punish his stomach with hunger. If he looked at what he had no right to look at, he should punish his eye by denying it the look. Every other limb is treated the same way, by keeping it from its appetites." },
      { title: "Note the logic", body: "It is the merchant's charge for a loss, applied to the party that caused it. The stage is not an addition to the analogy but its fourth term, which is why it arrives here rather than being argued for separately." },
      { title: "Mark what follows", body: "He then reports how people who went down this road actually behaved, and what he passes on is severe. One man held his hand in a fire after touching a woman. Another left his foot out in the rain and snow after catching it moving towards something wrong." },
      { title: "Note the reason the stage exists", body: "The argument for punishing the self is about prevention, not revenge, and it is stated plainly. Let the shortfall go, and doing wrong becomes easy; the self gets used to it, and weaning it off becomes hard. That is the process the book on delusion described, where familiarity deepens the stain. The fourth stage exists to interrupt it before the habit sets." },
      { title: "Take the principle of matching", body: "The principle is exact: the punishment goes to the limb that took the profit. A doubtful mouthful eaten from appetite is answered by hunger. A look that was not his to take is answered by holding back the look. It is the merchant charging the loss to the party that caused it — the fourth term of the comparison, not a new idea, so it needs no separate defence." },
      { title: "Note how the examples are reported", body: "What he passes on is severe, and he passes it on without recommending it. A man held his hand in the fire after touching a woman. Another left his foot out in rain and snow after catching it moving towards something wrong. These are reported as what people on this road actually did. The next section notes that severity like this is scaled to the person, which keeps the examples from becoming a price list." },
    ],
    closer: [
      { title: "What is specified and what is reported", body: "What Ghazali specifies is the withholding of an appetite from the limb that indulged it. What he reports afterward is what particular people did, introduced as the custom of those who travelled the road. The two are different in kind, and the chapter's own instruction is the first." },
      { title: "Why the stage is not optional in his scheme", body: "His argument is about habituation rather than about desert: a loss that is never charged is a loss that repeats, because the soul grows familiar with it. Remove this stage and the reckoning of the previous one produces information and no consequence." },
    ],
    distinction: ["Two responses to a loss found in the reckoning", "Charged to the limb", "The appetite withheld from what indulged it, which is what the chapter specifies.", "Noted and passed over", "Which Ghazali says makes the wrong easy and the weaning hard."],
    misreading: "Do not take the transmitted anecdotes as the instruction. They are reported as what particular people did; what the chapter prescribes is withholding an appetite from the limb that took it, and nothing in it authorises self-harm.",
    reflection: "Ask what happens in your own accounting when something comes out in the red. For most people the answer is that it is noted.",
    audit: ["What happens when I find a loss?", "Which limb took the profit?", "Is my response information or consequence?", "Am I confusing severity with seriousness?"],
    nodes: ["muaqaba", "muhasaba", "nafs"],
    model: pair("Two ways an audit can end", "Only one of them changes the next day.", [["A charge", "The appetite withheld from the limb that indulged it.", "support"], ["A note", "Recorded and passed over, which Ghazali says breeds familiarity.", "warning"]]),
  }),
  makeChapter({
    id: 12, shortTitle: "Making good", formalTitle: "The fifth stage: striving",
    overview: "The stage that distinguishes stopping a leak from repairing the damage, and it addresses a failure the previous stages do not reach.",
    thesis: "Striving is what separates stopping a leak from actually going somewhere.",
    moves: [
      { title: "Separate the two cases", body: "If he reckons and sees that his soul has committed a wrong, he punishes it with the punishments already given. If he sees it slackening through laziness in some virtue or some regular practice, that is a different failure and takes a different treatment." },
      { title: "Give the treatment", body: "He should discipline the self by making its regular practices heavier, and binding it to extra kinds of duty, to mend what was missed and make up for what it neglected." },
      { title: "Give the examples", body: "Umar once missed the afternoon prayer in congregation, and punished himself by giving away land worth two hundred thousand dirhams. When Ibn Umar missed a prayer in congregation, he would spend that night in prayer. Once, when he delayed the sunset prayer until two stars had appeared, he freed two slaves." },
      { title: "Name what it is", body: "All of that is a watch kept on the soul and a taking of it to task with what its deliverance lies in. The severity of the examples is proportioned to the means of the people in them, which is what makes them illustrations rather than a tariff." },
      { title: "Note the distinction that opens the stage", body: "Two kinds of failure are separated and given different treatments, and that is the useful move. A wrong actually done is answered by the punishments of the previous stage. Slacking off out of laziness in a virtue or a regular practice is a different kind of failure — nothing was done that should not have been. It is answered by making the practices heavier, to make good what was missed." },
      { title: "Take the examples and their scale", body: "The examples are extreme on purpose. Umar gave away land worth two hundred thousand dirhams for missing one afternoon prayer in congregation. Ibn Umar spent a night in prayer for one missed congregation, and freed two slaves for delaying the sunset prayer until two stars showed. These are illustrations, not a price list. The severity is scaled to what each of these men could give, and that scaling is the part you can carry over." },
    ],
    closer: [
      { title: "Why laziness needs its own stage", body: "Punishment answers an act that was done. Slackness is the absence of an act, and withholding an appetite does nothing about it. The fifth stage exists because the fourth cannot reach a failure that consists in nothing having happened, which is exactly the empty treasury of Chapter 3." },
      { title: "The shape of the remedy", body: "The response to having done less is to be assigned more, which inverts the intuitive response of lowering the expectation until it is comfortably met. Ghazali's word for it is mending, and the debt language is deliberate." },
    ],
    distinction: ["Two failures found in a reckoning", "Something done", "A wrong committed, answered by withholding the appetite from the limb.", "Something not done", "Slackness in a practice, answered by making the practice heavier."],
    misreading: "Do not read the examples as setting an amount. Two hundred thousand dirhams is what one particular man could give. The principle is that a missed practice is made good with interest — not that there is a fixed scale.",
    reflection: "Notice your instinct when you miss something repeatedly. It is usually to require less of yourself, and this stage goes the other way.",
    audit: ["Which of the two failures is mine?", "Do I lower the bar when I miss it?", "What would making it good look like?", "Have I confused a tariff with a principle?"],
    nodes: ["mujahada", "muaqaba", "treasuries"],
    model: pair("Two failures, two remedies", "Applying the wrong one leaves the failure untouched.", [["A wrong done", "Answered by withholding the appetite from the limb that took it.", "warning"], ["A practice missed", "Answered by making the practice heavier, as a mending of what was neglected.", "balance"]]),
  }),
  makeChapter({
    id: 13, shortTitle: "When it will not comply", formalTitle: "The treatment when the soul does not obey",
    overview: "Ghazali raises the objection every reader has by this point in the book, and his answer is notably practical and notably modest.",
    thesis: "The objection every reader has by now — what if it does not obey — is raised and answered.",
    moves: [
      { title: "Put the objection", body: "If you say that my soul does not comply with me in striving and in persevering in the regular practices, what is the way to treat it? The question is posed in the first person and taken at face value." },
      { title: "The first answer", body: "Your way in that is to make it hear what has come in the reports concerning the excellence of those who strive. The soul is treated by what it is exposed to rather than by being commanded again." },
      { title: "The second and stronger answer", body: "One of the most helpful treatments is to keep company with someone who works hard at worship, so that you can watch what he says and does and take him as your model." },
      { title: "Note the form of the answer", body: "Neither answer is an instruction to try harder. Both of them are arrangements of circumstance: what you hear, and whom you are near. Ghazali calls them causes of treatment, which is the same vocabulary Book 37 used for the causes of an inclination." },
      { title: "Note that the objection is taken at face value", body: "The objection is put in the first person — my soul does not comply with me — and it is not treated as an excuse. Which matters, because everything up to this point has assumed a soul that can be set terms with, watched, audited and charged. The question is what to do when the partner simply refuses, and Ghazali answers it rather than repeating the instruction." },
      { title: "Take the form of both answers", body: "Neither answer is “try harder.” One is to expose the self to reports about people who strove. The other, and the stronger, is to keep company with someone who actually does it, so that you watch him and take him as a pattern. Both are ways of arranging your circumstances — what you hear and who you are near. Ghazali calls them causes of treatment, the same language the previous book used for the causes of an inclination." },
    ],
    closer: [
      { title: "Why companionship rather than resolve", body: "Book 37 argued that an inclination cannot be produced by willing and that the only route is acquiring its causes. A companion who actually strives is a cause: proximity does what exhortation cannot, and the chapter's word for the mechanism is observing and imitating rather than being persuaded." },
      { title: "What the answer concedes", body: "It concedes that the soul will not comply on demand, which is the honest premise of the whole book. The six stages are a way of dealing with a party that does not comply, and this chapter is where that is said plainly." },
    ],
    distinction: ["Two responses to a soul that will not comply", "Arrange the causes", "What you hear and whom you are near, which Ghazali calls the causes of treatment.", "Command it again", "A second and firmer resolution, which the objection has already shown does not work."],
    misreading: "Do not read the counsel of companionship as merely encouraging. It is offered as the most beneficial of the causes, above exhortation, and it is a change of circumstance rather than of attitude.",
    reflection: "Ask who you are actually near, and what that proximity has been doing to you without being asked.",
    audit: ["What am I exposed to?", "Whose practice do I actually observe?", "Have I answered non-compliance with more resolve?", "Which cause could I arrange this week?"],
    nodes: ["mujahada", "companionship", "nafs"],
    model: chain("Two causes of treatment", "Both are arrangements rather than acts of will.", [["What you hear", "The reports on those who strive, which the soul is exposed to.", "balance"], ["Whom you are near", "A companion who actually strives, named as the most beneficial.", "support"], ["What follows", "Observation and imitation, rather than persuasion.", "support"]]),
  }),
  makeChapter({
    id: 14, shortTitle: "Your worst enemy", formalTitle: "The sixth stage: rebuking and reproaching the soul",
    overview: "The book closes on the stage the commercial model does not predict, and it turns out to be the mechanism by which the soul changes what it is.",
    thesis: "The book closes on the one stage the commercial model cannot supply, because you cannot dissolve this partnership.",
    moves: [
      { title: "Name the adversary", body: "“Your worst enemy is your own self, which lives between your two sides. It was created urging evil, leaning towards wickedness, and running from good. You were commanded to purify it, straighten it, and lead it in chains of compulsion to the worship of its Lord.”" },
      { title: "State the alternative", body: "If you neglect it, it bolts and runs off, and you will not get hold of it afterward. And if you keep at it with rebuke and reproach and censure and blame, your soul is the reproachful soul by which God swore." },
      { title: "Name the destination", body: "You may hope that it become the tranquil soul, called to enter among the servants of God, content and found pleasing. So the three souls are not three kinds of person but three states of one soul, and reproach is the passage between them." },
      { title: "Set the order", body: "Do not go an hour without reminding it and reproaching it. And do not busy yourself with warning anyone else until you have first busied yourself with warning your own self. As God revealed to Jesus: “Warn yourself. If you take the warning, then warn people. Otherwise, be ashamed before Me.”" },
      { title: "Note the three souls as three states", body: "The three names from the book on the heart return here as a sequence rather than as three kinds of person. Left alone, the soul commanding to evil bolts and cannot be caught afterwards. Kept at with rebuke and reproach, it is the reproachful soul that God swore by. And it may be hoped that it becomes the tranquil soul, called to enter content and found pleasing. Reproach is what moves a person between them." },
      { title: "Take the instruction about order", body: "The last instruction reverses the natural direction of this whole quarter: do not busy yourself warning anybody else until you have warned yourself. The revelation to Jesus makes it a condition: warn yourself; if you take the warning, then warn people; otherwise, be ashamed before Me. That is where a book of six stages of self-examination has to end. It is aimed squarely at a reader who has just finished thirty-seven books about faults — and is tempted to spot them in others." },
    ],
    closer: [
      { title: "Why this stage is not in the analogy", body: "A merchant sets terms, watches, settles up, and writes off a loss — and there the business model runs out. Telling yourself off is aimed at a partner you cannot walk away from and whose character can actually change. Ghazali needs that step because the aim of the whole book is getting the self clean, not merely keeping it in check." },
      { title: "The clause about admonishing others", body: "It is placed here, not in a book on preaching, and its position is the argument. The urge to correct someone else comes most strongly to a person who has skipped this stage. The instruction is not to stay silent, but to take the same treatment first." },
    ],
    distinction: ["Two ways to handle an adversary you cannot remove", "Reproach it", "Keep at it with censure and blame, which is what makes it the reproachful soul.", "Neglect it", "Which Ghazali says makes it bolt, after which you will not get hold of it."],
    misreading: "Do not read the reproach as self-contempt. Its stated destination is the tranquil soul, content and found pleasing, and a reproach that has no such destination is a different thing wearing the same name.",
    reflection: "Notice how quickly the urge to correct someone else arrives, and where the passage places it.",
    audit: ["Which of the three states is mine now?", "Do I reproach or do I neglect?", "Where is my reproach heading?", "Whom am I admonishing instead of myself?"],
    nodes: ["muataba", "three-souls", "nafs"],
    model: spectrum("Three states of one soul", "Reproach is the passage, not the destination.", [["Commanding", "Created inclining to wickedness and fleeing from good.", "warning"], ["Reproachful", "The soul kept at with censure and blame, and the one God swore by.", "balance"], ["Tranquil", "Called to enter among the servants, content and found pleasing.", "support"]]),
  }),
];

export const book38ConceptNodes: ConceptNode[] = [
  ["murabata", "The watch", "A trade with a partner", "The intellect is the merchant, the soul the partner, and the profit is the soul's purifying."],
  ["six-stations", "Six stages", "Derived, not listed", "Set terms, watch, reckon, punish, strive, reproach."],
  ["nafs", "The soul", "A partner who disputes", "Not merely lazy but holding interests of its own, which is why six stages are needed."],
  ["musharata", "Setting terms", "Terms on a day", "Duties assigned and conditions imposed before anything is done, renewed daily."],
  ["treasuries", "Twenty-four treasuries", "Lit, dark, empty", "The third is the hour of sleep, heedlessness, or permitted business."],
  ["mubah", "The permitted", "Not neutral in effect", "An hour spent in it is an empty treasury, which is a loss and not a debit."],
  ["muraqaba", "Vigilance", "A state, not an act", "Fruited by a knowledge and fruiting acts, in that order."],
  ["knowledge", "Knowledge", "Which may not govern", "Undoubted knowledge often fails to dominate the heart, as with the knowledge of death."],
  ["certainty", "Possession", "Knowledge that subdues", "The condition that turns assent into a state."],
  ["absorption", "Absorption", "The first degree", "A single concern, so the limbs run straight without management."],
  ["qalb", "The heart", "The shepherd", "When it is absorbed in the One worshipped the flock keeps itself."],
  ["khatir", "The passing thought", "The first link", "Desire, intent, purpose, act; the material is cut at its first source."],
  ["registers", "Three registers", "Why, how, for whom", "Each is reached only by passing the one before it."],
  ["ikhlas", "Sincerity", "The third register", "Reached only by an act that was owed and correctly done."],
  ["muhasaba", "Reckoning", "An hour, not a mood", "Capital, profit, and loss, looked at separately at the end of the day."],
  ["capital", "The capital", "The quantity nobody counts", "What was given before trading began, and why surplus is met with thanks."],
  ["tawba", "Repentance", "The same operation", "A looking into the act after finishing it, with regret over it."],
  ["muaqaba", "Punishment", "Charging the loss", "The appetite withheld from the limb that indulged it."],
  ["mujahada", "Striving", "Making good", "The remedy for slackness is a heavier practice, not a lighter one."],
  ["companionship", "Companionship", "A cause, not a counsel", "Named as the most beneficial of the treatments when the soul will not comply."],
  ["muataba", "Reproach", "Outside the analogy", "The stage a merchant has no use for, and the one that changes the partner."],
  ["three-souls", "Three souls", "One soul, three states", "Commanding, reproachful, tranquil, with reproach as the passage."],
].map(([id, label, kicker, description], index) => ({ id, label, kicker, description, position: ["left", "right", "top", "bottom"][index % 4] }));

const node = (id: string, label: string, micro: string, summary: string, guardrail: string, chapterId: number, glyph: Journey["nodes"][number]["glyph"]): Journey["nodes"][number] => ({ id, label, micro, summary, guardrail, chapterId, glyph });

export const book38Journeys: Journey[] = [
  {
    id: "who-am-i-dealing-with", number: "01", question: "Who am I actually dealing with?", title: "Meet the partner",
    description: "Take the comparison the whole book is built from, and see why it needs six stages rather than one. Then count a day in the unit Ghazali counts it in.",
    payoff: "You get an architecture instead of an exhortation, and one image that changes how an ordinary hour looks.",
    image: assetUrl("assets/system/book38-the-ledger.jpg"), imageAlt: "A merchant's counter at dawn where an open ledger, a set of scales and a sealed purse are laid out untouched.", minutes: 13, color: "#278d91",
    nodes: [
      node("the-trade", "Set the trade", "Profit is purifying", "The intellect is the merchant and the soul's purifying is the return.", "The analogy is the architecture, not an illustration.", 1, "know"),
      node("adversary", "Meet the adversary", "A partner, not a servant", "He disputes over the profit, which is what generates stages four to six.", "A soul that were merely lazy would need instruction only.", 1, "diagnose"),
      node("the-terms", "Set the terms", "Before anything is done", "Duties assigned and conditions imposed, and renewed each day.", "Book 37 already refused the resolution made on the spot.", 2, "order"),
      node("the-unit", "Take the unit", "Twenty-four", "Small and countable, which is what makes an evening audit possible.", "The unit is load-bearing; the severity of the address is not.", 2, "pattern"),
      node("the-empty-one", "Find the empty treasury", "Neither credit nor debit", "The hour of sleep, heedlessness, or permitted business.", "Named as chagrin at a missed profit, not as guilt.", 3, "witness"),
    ],
  },
  {
    id: "what-is-watching", number: "02", question: "What does watching actually mean?", title: "Separate knowing from being governed",
    description: "Get the definition in three parts, meet the clause that stops the chapter being satisfied by agreement, and see the two degrees the stage divides into.",
    payoff: "You learn why undoubted knowledge governs nothing, and which of the two degrees you are working in.",
    image: assetUrl("assets/system/book38-the-shepherd.jpg"), imageAlt: "A hillside at midday where a flock grazes in a close group with no fence in sight and one figure seated above them.", minutes: 13, color: "#bf7a35",
    nodes: [
      node("three-parts", "Separate the three", "Knowledge, state, acts", "The state is fruited by a knowledge and itself fruits the acts.", "Working on the acts alone produces conformity and nothing else.", 4, "order"),
      node("death-clause", "Take the clause", "Like the knowledge of death", "Many an undoubted knowledge does not dominate the heart.", "This is what makes assent insufficient, and it names the commonest case.", 4, "diagnose"),
      node("first-degree", "See the first degree", "The shepherd absorbed", "A single concern, and the limbs run straight without management.", "The descriptions are effects, not practices to imitate.", 5, "witness"),
      node("ordinary-proof", "Take the ordinary proof", "Walking past your street", "Absorption in something trivial produces the same blindness.", "The mechanism is not in question, only its object.", 5, "pattern"),
      node("second-degree", "Enter the second", "Pause at the intent", "Hold back until the light of knowledge discloses which it is.", "It has a termination condition, so it is not scrupulosity.", 6, "steady"),
    ],
  },
  {
    id: "where-do-i-stop-it", number: "03", question: "Where do I stop it?", title: "Move the intervention to the first link",
    description: "Follow the chain from a passing thought to an act, find why fighting late feels like weakness, and put Ghazali's three questions to a single thing you did.",
    payoff: "You get a diagnosis with leverage in it, and three gates that tell you which question your case stops at.",
    image: assetUrl("assets/system/book38-first-link.jpg"), imageAlt: "A fine chain of five links laid out straight on pale stone, the first link open and the rest closed.", minutes: 14, color: "#c25f50",
    nodes: [
      node("the-chain", "Take the chain", "Five links", "Thought bequeaths desire, desire intent, intent purpose, purpose the act.", "Nothing here says the first link is a fault.", 7, "pattern"),
      node("cut-first", "Cut at the source", "Where it is cheapest", "Everything after the first link follows it.", "A claim about leverage, not about guilt.", 7, "clear"),
      node("not-weakness", "Rename the failure", "Late, not weak", "Losing at the fifth link is a placement problem, not a capacity problem.", "This is a diagnosis with a remedy attached.", 7, "diagnose"),
      node("register-why", "Open the first register", "Why", "Owed to your Master, or inclined to by appetite.", "Failing here means you never reach the other two.", 8, "know"),
      node("register-how", "Open the second", "How", "By verified knowledge, or by habit and guess.", "The only one about competence rather than motive, and the one readers skip.", 8, "order"),
      node("register-whom", "Open the third", "For whom", "For the face of God, to be seen, for a return, or in heedlessness.", "Reached only by an act that was owed and correctly done.", 8, "guard"),
    ],
  },
  {
    id: "audit-a-day", number: "04", question: "How do I actually audit a day?", title: "Count three quantities and charge the loss",
    description: "Place the hour, run the merchant's procedure with all three of its quantities, and follow what Ghazali says has to happen when something comes out in the red.",
    payoff: "You get a closing procedure that ends in something other than a feeling.",
    image: assetUrl("assets/system/book38-days-end.jpg"), imageAlt: "The same merchant's counter at dusk, the ledger now open at a written page, the scales holding two unequal weights.", minutes: 13, color: "#586fa8",
    nodes: [
      node("umars-rule", "Take Umar's rule", "Before you are reckoned", "Reckon with yourselves, and weigh yourselves, first.", "The stage is given an hour rather than left as a disposition.", 9, "order"),
      node("both-directions", "Run it both ways", "Backward and forward", "Considering the outcome before acting is reckoning in advance.", "A purely retrospective audit can only produce regret.", 9, "balance"),
      node("three-quantities", "Count three", "Capital, profit, loss", "The capital is the one nobody counts, and it is why surplus is met with thanks.", "Two quantities give you a review, not a reckoning.", 10, "pattern"),
      node("the-proportion", "Feel the reproach", "Effort against stake", "Merchants are diligent about something that lasts a few days.", "The charge is about proportion, not about worldliness.", 10, "witness"),
      node("charge-it", "Charge the loss", "To the limb that took it", "The appetite withheld from what indulged it.", "The transmitted anecdotes are reports, not the instruction.", 11, "guard"),
    ],
  },
  {
    id: "will-not-comply", number: "05", question: "What if it simply will not comply?", title: "Arrange the causes, then reproach",
    description: "Separate the failure of doing something wrong from the failure of nothing happening. Take Ghazali's two practical treatments. And end on the stage his own comparison does not predict.",
    payoff: "You leave with the remedy that inverts the obvious one, and with the three souls as a passage rather than a ranking.",
    image: assetUrl("assets/system/book38-three-souls.jpg"), imageAlt: "One lamp carried along a corridor, shown at three points on its path, the far end open and lit.", minutes: 14, color: "#a97837",
    nodes: [
      node("two-failures", "Separate the failures", "Done, or not done", "Punishment cannot reach a failure that consists in nothing happening.", "This is the empty treasury arriving as a practical problem.", 12, "diagnose"),
      node("heavier", "Take the inversion", "Make it heavier", "The remedy for slackness is more of the practice, not less.", "The examples show a principle, not a tariff.", 12, "clear"),
      node("the-objection", "Put the objection", "It does not comply", "Ghazali asks it in the first person and answers it directly.", "The whole book assumes a party that does not comply.", 13, "know"),
      node("companionship", "Take the strongest cause", "Whom you are near", "Named as the most beneficial of the treatments, above exhortation.", "A change of circumstance, not of attitude.", 13, "forces"),
      node("the-enemy", "Meet the enemy", "Between your two sides", "Neglected it bolts; reproached it becomes the reproachful soul.", "The destination is the tranquil soul, so this is not self-contempt.", 14, "witness"),
      node("three-souls", "Read the three", "One soul, three states", "Commanding, reproachful, tranquil, with reproach as the passage.", "Not three kinds of person.", 14, "steady"),
    ],
  },
];

export const book38Movements: TaxonomyGroup[] = [
  ["musharata", "1. Setting terms", "The partnership, the morning terms, and the twenty-four treasuries.", [1, 2, 3]],
  ["muraqaba", "2. Vigilance", "The definition, the two degrees, the chain from a thought, and the three registers.", [4, 5, 6, 7, 8]],
  ["muhasaba", "3. Reckoning", "The hour at day's end, and the merchant's three quantities.", [9, 10]],
  ["muaqaba", "4. Punishment", "The loss charged to the limb that took it.", [11]],
  ["mujahada", "5. Striving", "Making good what was missed, and what to do when the soul will not comply.", [12, 13]],
  ["muataba", "6. Reproach", "The stage the analogy does not predict, and the three souls.", [14]],
].map(([id, label, description, chapterIds], index) => ({ id, label, description, chapterIds, color: ["#bf7a35", "#278d91", "#c25f50", "#586fa8", "#a97837"][index % 5] })) as TaxonomyGroup[];

export const book38Instrument: Instrument = {
  title: "The three registers",
  note: "Ghazali says that for every motion of a servant, however small, three registers are spread: why, how, and for whom. They are a sequence rather than a list — the second is reached only by one who is safe from the first, and the third only by one safe from the second. Take a single thing you actually did today, and answer in his order rather than the order you would have chosen.",
  items: [
    {
      id: "motion", label: "One thing you did today", lede: "Something ordinary and specific, not a category",
      note: "All three questions are Ghazali's own, in his words and his order. Most readers arrive at this book anxious about the third register; the sequence is designed to show which gate the case actually stops at, and it is very often not that one.",
      axes: [
        {
          id: "why", kicker: "The first register", question: "Why did you do it?",
          options: [
            { id: "owed", label: "It was owed — I had to do it", note: "Required of you for your Master, which is what passing this gate means." },
            { id: "appetite", label: "I inclined to it by appetite", note: "The alternative Ghazali names: you leaned toward it by your own want and whim." },
            { id: "both", label: "Both, and I cannot separate them", note: "The honest answer for most ordinary acts, and it does not clear the gate." },
          ],
        },
        {
          id: "how", kicker: "The second register", question: "How did you do it?",
          options: [
            { id: "knowledge", label: "By knowledge of how it is to be done", note: "God has in every act a condition and a ruling whose measure, time, and quality are known only by knowledge." },
            { id: "guess", label: "By habit and guess", note: "The alternative Ghazali names: ignorance and conjecture. This is a failure of competence, not of motive." },
            { id: "outline", label: "I knew the outline, not the conditions", note: "The commonest real answer, and the register exists to make it visible." },
          ],
        },
        {
          id: "whom", kicker: "The third register", question: "For whom did you do it?",
          options: [
            { id: "god", label: "For the face of God alone", note: "In fulfilment of the words of unity, so that the wage is upon God." },
            { id: "seen", label: "To be seen by someone", note: "Ghazali's answer to this is that you should take your wage from the one you did it for." },
            { id: "world", label: "For something immediate", note: "His answer is that you have already been paid your share of it." },
            { id: "heedless", label: "In heedlessness — I never asked", note: "His answer is that the wage has fallen; this is where the empty treasury of Chapter 3 comes from." },
          ],
        },
      ],
      verdicts: [
        { key: "appetite|*|*", name: "It stops at the first register", role: "warning", chapterId: 8, body: "Ghazali's first question is whether the act was required of you for your Master or whether appetite and personal desire drew you toward it. Your answer places this act in the second category, so the second and third registers are never opened for it.", action: "This is useful rather than damning. If you came to this book worried about sincerity, the sequence shows that your work is not yet there. It is at the first gate, where Chapter 6's pause before intention is practiced." },
        { key: "both|*|*", name: "The first register is not settled", role: "balance", chapterId: 6, body: "You cannot separate what was owed from what you leaned toward, which is the ordinary condition of most acts and is exactly why the second stage exists. Ghazali does not treat this as failure; he treats it as the point at which the pause is needed.", action: "Al-Hasan's rule is the one to apply, and it works forward rather than backward: pause at the intent, and hold back until it is disclosed by the light of knowledge which of the two it is. Ghazali also says plainly what to do when nothing is disclosed." },
        { key: "owed|guess|*", name: "It stops at the second register", role: "warning", chapterId: 8, body: "The act was owed, so the first gate is passed, and it was done by habit and guess. Ghazali's second question is exactly this, and his standard is explicit: God has in every act a condition and a ruling whose measure and time and quality are grasped only by knowledge.", action: "This is the register readers skip, because it is about competence and not about motive, and a sound motive does not answer it. He adds that one who knows the blights of souls guards against them while the ignorant cannot, so the remedy here is learning the act rather than meaning it harder." },
        { key: "owed|outline|*", name: "The second register, partly", role: "balance", chapterId: 8, body: "The act was owed and you know its outline but not its conditions. Ghazali's second register asks for the measure, the time, and the quality, and it is precisely the conditions rather than the outline that he says are known only by knowledge.", action: "Name the one condition you are least sure of and settle it. This is the least dramatic work in the book and the most tractable, and unlike the other two registers it can be finished." },
        { key: "owed|knowledge|seen", name: "The third register: take your wage from him", role: "warning", chapterId: 8, body: "The act was owed and correctly done, and it was done to be seen. You have reached the third register, which most people assume is the only one, and Ghazali's answer to this option is given in his own voice: take your wage from the one you performed for.", action: "Read Book 37's chapter on the two grades of showing off next, and use its test rather than introspection: the question is not what you were thinking but whether the act improved when someone came into the room. Then Book 37's rule on a mixed act tells you what the proportion is actually worth." },
        { key: "owed|knowledge|world", name: "The third register: already paid", role: "balance", chapterId: 8, body: "The act was owed and correctly done, and it was done for something immediate. Ghazali's answer is that your share of the world has been paid to you, which is a statement about settlement rather than about wickedness.", action: "Nothing here says the immediate return was forbidden. What is said is that it was the wage, and the question worth putting is whether you would still have done the act had the return not been attached — which is Book 37's question about the strength of the motive." },
        { key: "owed|knowledge|heedless", name: "The third register: the empty treasury", role: "balance", chapterId: 3, body: "The act was owed and correctly done, and the question of for whom never arose. Ghazali's answer is that the wage has fallen, and this is the same result as the third of the twenty-four treasuries: an hour that is neither credit nor debit and is still a loss.", action: "The remedy is the first stage rather than more scrutiny after the fact. Terms set on the day in advance are what put the question in front of an act before it is done, and Chapter 2 is explicit that they have to be renewed daily." },
        { key: "owed|knowledge|god", name: "All three registers pass", role: "support", chapterId: 8, body: "The act was owed, done by knowledge, and done for the face of God. That is what passing all three of Ghazali's gates means, and the book states the result plainly: your wage is upon God.", action: "Hold it lightly. Book 37 carries al-Susi's saying that whoever witnesses sincerity in his own sincerity has a sincerity that needs a sincerity, and Ghazali reads it as pointing at self-admiration in the act. The three registers are for finding where the work is, not for issuing yourself a receipt." },
        { key: "*|*|*", name: "Read the sequence", role: "balance", chapterId: 8, body: "Three answers, which Ghazali arranges as gates rather than as a checklist. The point of the order is that the question you are worried about is often not the question your case actually stops at.", action: "Find the first of the three you did not clear and start there. Everything after it is not yet the issue, and the chapter that treats that register is the one to read next." },
      ],
    },
  ],
};

export const book38Sources: SourceLink[] = [
  { label: "Primary Arabic text", note: "The complete public Arabic of Book 38 was read and used to establish the merchant analogy, the six stages of the watch, the two degrees of vigilance, the three registers, and the reckoning procedure.", url: "https://shamela.ws/book/9472/1552" },
  { label: "The first stage and the treasuries", note: "The passage deriving the six stages from the partnership, and the morning charge with the image of the twenty-four treasuries and the empty one.", url: "https://shamela.ws/book/9472/1553" },
  { label: "The reality of vigilance", note: "The passage separating the knowledge, the state, and the acts, and giving the clause that undoubted knowledge may fail to govern, as with the knowledge of death.", url: "https://shamela.ws/book/9472/1557" },
  { label: "The three registers", note: "The passage setting out the three registers spread for every motion — why, how, and for whom — which the diagnostic in this edition follows.", url: "https://shamela.ws/book/9472/1559" },
  { label: "The reality of reckoning", note: "The passage placing an hour at the end of the day and giving the merchant's procedure of capital, profit, and loss.", url: "https://shamela.ws/book/9472/1564" },
  { label: "The sixth stage", note: "The passage on rebuking and reproaching the soul, and on the passage from the commanding soul through the reproachful to the tranquil.", url: "https://shamela.ws/book/9472/1575" },
  { label: "Forty-book structure", note: "Ghazali.org's listing places Book 38 as the eighth book of the Quarter of Deliverance and confirms its title.", url: "https://www.ghazali.org/listing-the-forty-books/" },
];

export const book38: SystemBook = {
  id: 38,
  title: "Vigilance and Self-Examination",
  shortTitle: "Vigilance and Reckoning",
  defaultJourneyId: "who-am-i-dealing-with",
  chapters: book38Chapters,
  conceptNodes: book38ConceptNodes,
  journeys: book38Journeys,
  sources: book38Sources,
  taxonomy: {
    title: "The six stages of the watch",
    note: "Unlike the other books in this quarter, Book 38 has a single derived structure rather than a sequence of expositions. Ghazali builds a merchant's partnership and takes six stages out of it, and the fourteen reading sections here are grouped under the stage each belongs to.",
    groups: book38Movements,
  },
  instrument: book38Instrument,
  editorialNote: "The five journeys, fourteen reading sections, visual models, and diagnostic are editorial learning aids. The sections follow Ghazali's own six stages in his order and are grouped under them in the movements list. The English is an original synthesis made from a reading of the public Arabic text, not a translation and not a substitute for one. Reports and inherited anecdotes are presented as material Ghazali transmitted; this edition does not independently grade every narration. The fourth stage requires particular care: what Ghazali prescribes is the withholding of an appetite from the limb that indulged it, and what he reports afterward are accounts of what particular individuals did, several of which involve self-inflicted harm. Those accounts are described here rather than reproduced as practice, and nothing in this book or this edition recommends them; the distinction between the prescription and the transmitted anecdote is stated in the section itself. The fifth stage's examples of restitution are proportioned to the means of the people in them and are presented as illustrating a principle rather than setting an amount. The diagnostic puts Ghazali's own three questions to a single act in his own order and reports which register the case stops at; it cannot pronounce on anyone's state.",
};
