import { assetUrl } from "./assetUrl";
import type { Journey } from "./systemTypes";

export const book21Journeys: Journey[] = [
  {
    id: "identity",
    number: "01",
    question: "What is the heart?",
    title: "Build a map of the inside",
    description: "Learn the four words and their five meanings, then see the heart's armies, the king's household, and the pig, dog, devil and sage living under one skin.",
    payoff: "You leave with a working map of what is going on inside you, and a question to ask of each day: who was in charge?",
    image: assetUrl("assets/system/journey-heart.jpg"),
    imageAlt: "Symbolic painted compass surrounded by four balanced coloured medallions and flowering plants.",
    minutes: 12,
    color: "#3567a6",
    nodes: [
      { id: "name-the-faculty", label: "Name the heart", micro: "Five meanings, four words", summary: "The heart Ghazali means is the part of you that knows, is spoken to by God and is held to account — not the organ.", guardrail: "Most mistakes in this subject come from mixing up the meanings.", chapterId: 1, glyph: "name" },
      { id: "three-selves", label: "One self, three states", micro: "At peace, blaming, urging", summary: "The real person is called the self at peace, the self that blames, or the self that urges evil, by its state.", guardrail: "The self that blames is already a step up.", chapterId: 1, glyph: "steady" },
      { id: "map-the-forces", label: "Map its armies", micro: "Seen and unseen", summary: "Limbs obey like angels without knowing it; desire, anger and ten senses serve the journey to God.", guardrail: "Every force was given because the journey needs it.", chapterId: 2, glyph: "forces" },
      { id: "see-the-order", label: "See the order", micro: "King, frontier, rider", summary: "The minister should rule the lying supplier; the hunter should master horse and dog.", guardrail: "Fixing yourself means putting things in order, not wiping out every urge.", chapterId: 3, glyph: "order" },
      { id: "add-knowledge-will", label: "Knowledge and will", micro: "What only humans have", summary: "Knowing beyond the senses, and a will that follows reason against desire.", guardrail: "Whoever wastes them sinks below the animals.", chapterId: 4, glyph: "know" },
      { id: "watch-character-form", label: "Four under one skin", micro: "Pig, dog, devil, sage", summary: "Whichever rules leaves its traits on the heart, polishing it or blackening it.", guardrail: "Watch yourself for one day before judging anyone else.", chapterId: 5, glyph: "pattern" },
      { id: "the-black-spot", label: "The black spot", micro: "Breath on the glass", summary: "Each sin marks the heart; repentance wipes it, but the lost gain stays lost.", guardrail: "Mindfulness is the door to remembrance, and remembrance to unveiling.", chapterId: 5, glyph: "mirror" },
    ],
  },
  {
    id: "knowing",
    number: "02",
    question: "How does knowing happen?",
    title: "Trace knowledge into the heart",
    description: "Follow the mirror and its five blocks, the three levels of faith, the pool fed from above or below, and the painters who only polished.",
    payoff: "You see why knowledge needs both study and a prepared heart, and what the difference is worth on the Day of Resurrection.",
    image: assetUrl("assets/system/journey-knowing.jpg"),
    imageAlt: "Symbolic painted reservoir receiving clear water beside a polished brass mirror reflecting light.",
    minutes: 16,
    color: "#21867e",
    nodes: [
      { id: "receive-the-form", label: "The picture appears", micro: "The heart as mirror", summary: "Knowing is the true picture of a thing arriving in the heart.", guardrail: "The heart, the thing and the picture are three, not one.", chapterId: 6, glyph: "receive" },
      { id: "clear-obstructions", label: "Clear what's in the way", micro: "Five blocks", summary: "Unfinished, rusty, facing away, curtained, or not knowing where to look.", guardrail: "Every heart is by nature fit to carry the Trust.", chapterId: 6, glyph: "clear" },
      { id: "zayd-in-the-house", label: "Zayd in the house", micro: "Told, heard, seen", summary: "Three levels of faith: on someone's word, from his voice, by seeing him.", guardrail: "The first level still saves.", chapterId: 7, glyph: "witness" },
      { id: "food-and-medicine", label: "Food and medicine", micro: "Reason and revelation", summary: "Reason cannot do without revelation, nor revelation without reason.", guardrail: "Blame your blindness before the pots.", chapterId: 8, glyph: "know" },
      { id: "inspiration-and-learning", label: "Inspiration and learning", micro: "One knowledge, two roads", summary: "They differ only in how the veil is lifted; revelation adds the angel seen.", guardrail: "The thinkers warn of twenty years in one fancy.", chapterId: 9, glyph: "learn" },
      { id: "pool-and-doors", label: "The pool and two doors", micro: "Streams or springs", summary: "One door opens to the senses, one to the unseen kingdom; true dreams prove it.", guardrail: "The world exists on four levels, from the Tablet to the heart.", chapterId: 10, glyph: "prepare" },
      { id: "the-polished-wall", label: "The polished wall", micro: "Painters and polishers", summary: "The Chinese only polished, and their wall showed everything, brighter.", guardrail: "No happiness without knowledge; lights differ on the Bridge.", chapterId: 11, glyph: "mirror" },
      { id: "read-in-register", label: "Proofs of the inner door", micro: "Law, experience, reason", summary: "Umar's call to Sariya, Uthman's insight, al-Shibli's dinars, the lion that feared.", guardrail: "Inspiration is never treated as a prophet's revelation.", chapterId: 12, glyph: "witness" },
    ],
  },
  {
    id: "action",
    number: "03",
    question: "How does a thought become an action?",
    title: "Slow down the moment of choice",
    description: "Pull apart the steps that feel like one: the thought that arrives, the two touches, the pull, the judgment, the resolve, and the act.",
    payoff: "You find where you are forgiven, where you are answerable, and how dropping a bad plan for God becomes a good deed.",
    image: assetUrl("assets/system/journey-action.jpg"),
    imageAlt: "A luminous seed travelling through six coloured brass gates before becoming a clear outward footprint.",
    minutes: 12,
    color: "#c85b42",
    nodes: [
      { id: "prompting-arrives", label: "A thought arrives", micro: "The dome with doors", summary: "Thoughts pour in from the senses and from within; every act begins with one.", guardrail: "A thought arriving is not a choice.", chapterId: 13, glyph: "arrive" },
      { id: "two-touches", label: "Two touches", micro: "Angel or devil", summary: "A promise of good and truth, or of evil and denial.", guardrail: "Praise God for the first; seek refuge from the second.", chapterId: 13, glyph: "leverage" },
      { id: "sort-the-thought", label: "Stop at the concern", micro: "Evil dressed as good", summary: "The hardest thoughts are the ones that look like good advice.", guardrail: "Judge by mindfulness and knowledge, not by craving.", chapterId: 14, glyph: "diagnose" },
      { id: "attention-holds", label: "The pull", micro: "Nature stirs", summary: "Desire moves in answer to the thought.", guardrail: "Not chosen, so forgiven.", chapterId: 19, glyph: "attend" },
      { id: "judgment-assents", label: "The judgment", micro: "I should", summary: "The heart rules that the thing should be done.", guardrail: "Held against you when chosen.", chapterId: 19, glyph: "assent" },
      { id: "resolve-commits", label: "The resolve", micro: "I will", summary: "A firm intention; people are raised on their intentions.", guardrail: "Dropped for fear of God, it becomes a good deed.", chapterId: 19, glyph: "resolve" },
      { id: "action-follows", label: "The act", micro: "Both swords", summary: "The one killed was in the Fire for wanting to kill.", guardrail: "The heart is the root, and more answerable than the limbs.", chapterId: 19, glyph: "act" },
    ],
  },
  {
    id: "change",
    number: "04",
    question: "What makes change last?",
    title: "Turn what you learn into daily care",
    description: "Go from naming the pattern to closing the gates, taking the diet before the medicine, and backing the better voice when your heart is torn.",
    payoff: "You swap one dramatic fix for honest, steady watchfulness — and the Prophet's prayer to be kept firm.",
    image: assetUrl("assets/system/journey-change.jpg"),
    imageAlt: "A painted brass compass encircled by blue and coral currents and a flowering pomegranate branch.",
    minutes: 12,
    color: "#86577f",
    nodes: [
      { id: "name-ruling-pattern", label: "Name the pattern", micro: "Which master?", summary: "Pig, dog or devil — whichever you serve leaves its traits.", guardrail: "A pattern is not who you are forever.", chapterId: 5, glyph: "pattern" },
      { id: "find-entrances", label: "Find the gates", micro: "Your own traits", summary: "Anger, envy, greed, fullness, haste, money, partisanship, suspicion.", guardrail: "Knowing your gates is a duty.", chapterId: 15, glyph: "guard" },
      { id: "diet-then-medicine", label: "Diet, then medicine", micro: "The hungry dog", summary: "Remembrance drives off the devil once the heart is emptied of his food.", guardrail: "Watch your heart in prayer: it is the touchstone.", chapterId: 17, glyph: "remember" },
      { id: "remember-without-panic", label: "Remember without panic", micro: "An hour, not a lifetime", summary: "Each kind of whisper answers to something different; none stops for good.", guardrail: "A thought that keeps coming back does not prove remembrance failed.", chapterId: 20, glyph: "remember" },
      { id: "support-better-influence", label: "Back the better voice", micro: "The cool house", summary: "The devil argues from what others do; the angel argues from the end.", guardrail: "Other people's sins will not cool the Fire.", chapterId: 21, glyph: "steady" },
      { id: "repeat-care", label: "Pray to be kept firm", micro: "The Turner of hearts", summary: "The heart turns faster than a pot at the boil.", guardrail: "Firmness on either side is rare; care must be daily.", chapterId: 21, glyph: "act" },
    ],
  },
  {
    id: "the-gates",
    number: "05",
    question: "How does the devil get in?",
    title: "Walk the walls of the fortress",
    description: "Follow the devil's ways into the heart as Ghazali lays them out. See his touch, his hidden paths and the great gates one by one. Then the remedy, his armies, and why the whisper never quite stops.",
    payoff: "You know the enemy by his weapons rather than his pedigree, and you know which of your own gates is open.",
    image: assetUrl("assets/system/book21-the-gates.jpg"),
    imageAlt: "A walled fortress at dusk seen from above, many small gates in its wall standing ajar and a single lit gate facing upward.",
    minutes: 18,
    color: "#5d6b3a",
    nodes: [
      { id: "battlefield", label: "The battlefield", micro: "Most hearts are taken", summary: "Angels and devils chase each other in the heart until one settles in.", guardrail: "Empty the heart of desire, fill it with remembrance.", chapterId: 13, glyph: "forces" },
      { id: "snake-in-clothes", label: "The snake in your clothes", micro: "Weapons, not pedigree", summary: "Do not study the devil's nature; drive him off.", guardrail: "Many doors are his; the angels have one.", chapterId: 14, glyph: "clear" },
      { id: "the-monk", label: "The monk's first step", micro: "A kindness that ruined him", summary: "One small agreement dragged him to murder and prostration.", guardrail: "Whoever grazes near the fence falls in.", chapterId: 14, glyph: "diagnose" },
      { id: "moses-and-iblis", label: "Anger and envy", micro: "Three places Iblis gave away", summary: "Anger, the battlefield, and being alone with a woman not closely related.", guardrail: "Envy is his greatest way in.", chapterId: 15, glyph: "guard" },
      { id: "hundred-to-nine-hundred", label: "Money and haste", micro: "A hundred calls for nine hundred", summary: "Everything beyond need is the devil's lodging.", guardrail: "Even a stone pillow can be his tool.", chapterId: 15, glyph: "order" },
      { id: "partisans", label: "Loyal in name", micro: "Abu Bakr, Ali, the imams", summary: "Partisanship is a sin no one asks forgiveness for.", guardrail: "The believer looks for excuses, the hypocrite for faults.", chapterId: 16, glyph: "company" },
      { id: "the-thin-devil", label: "The thin devil", micro: "Diet before medicine", summary: "Say God's name at food, drink and dress, and the devil starves.", guardrail: "Remembrance works in an emptied heart.", chapterId: 17, glyph: "remember" },
      { id: "frog-and-crystal", label: "Seen and unseen", micro: "Armies and likenesses", summary: "A hundred and sixty angels guard you; the devil appears as what he is.", guardrail: "Images from the unseen never lie about their meaning.", chapterId: 18, glyph: "witness" },
      { id: "honey-and-flies", label: "Honey and flies", micro: "The last rung", summary: "Freedom for an hour is near; for a lifetime, impossible.", guardrail: "The final trap is vanity at your own goodness.", chapterId: 20, glyph: "steady" },
    ],
  },
];
