import { assetUrl } from "./assetUrl";
import type { Chapter, ConceptNode, VisualModel } from "./data";
import type { Instrument, Journey, SourceLink, SystemBook, TaxonomyGroup } from "./systemTypes";

type Seed = { id: number; shortTitle: string; formalTitle: string; overview: string; thesis?: string; moves: Array<{ title: string; body: string }>; closer: Array<{ title: string; body: string }>; distinction: [string, string, string, string, string]; misreading: string; reflection: string; audit: string[]; nodes: string[]; model: VisualModel };
const half = (id: number) => (id <= 14 ? "the first half, to the blast of the trumpet" : "the second half, from the blast of the trumpet");
const makeChapter = (seed: Seed): Chapter => ({
  id: seed.id, shortTitle: seed.shortTitle, formalTitle: seed.formalTitle, overview: seed.overview,
  points: seed.moves.slice(0, 3).map((m) => m.body), reflection: seed.reflection, relatedNodes: seed.nodes, visualModel: seed.model,
  deep: { thesis: seed.thesis ?? seed.moves[0].body, context: seed.overview, moves: seed.moves, closeReading: seed.closer,
    distinction: { title: seed.distinction[0], firstLabel: seed.distinction[1], first: seed.distinction[2], secondLabel: seed.distinction[3], second: seed.distinction[4] },
    misreading: seed.misreading, observation: seed.reflection, selfAudit: seed.audit,
    sourceAnchor: `Book 40, ${half(seed.id)}, ${seed.formalTitle}.` },
});
const chain = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "chain", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const pair = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "pair", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });
const spectrum = (title: string, caption: string, items: Array<[string, string, "support" | "balance" | "warning"]>): VisualModel => ({ kind: "spectrum", title, caption, items: items.map(([label, body, role]) => ({ label, body, role })) });

export const book40Chapters: Chapter[] = [
  makeChapter({
    id: 1, shortTitle: "The last book", formalTitle: "The excellence of remembering death",
    overview: "The longest book in the Ihya opens, and its opening is a structure rather than an argument. Ghazali announces two halves and eight chapters, and the announcement is worth reading closely.",
    thesis: "The longest book in the Ihya opens on a practice, not a doctrine — and the practice is remembering.",
    moves: [
      { title: "Gather the testimony", body: "The verses and reports commending the remembrance of death are assembled, including the exchange in which the wisest of people is named as the one most frequent in remembering it and best in preparing for it." },
      { title: "Announce the first half", body: "The first half treats death's preliminaries and what follows it, up to the blast of the trumpet, in eight chapters: the excellence of remembering it; long hope; the throes; the deaths of the Messenger and the caliphs; the speech of the dying; the sayings at funerals and graves; the reality of death and what the dead meets in the grave; and what is known of the dead through dreams." },
      { title: "Announce the second", body: "The second half treats the states of the dead from the blast onward, and Ghazali lists its contents in order, ending with the description of looking upon the face of God and then a chapter on the breadth of God's mercy." },
      { title: "Note the sentence about the ending", body: "Of that last chapter he says plainly that with it the book is sealed. The ending of the whole forty-book work is therefore announced at the start of the last book, and it is not the ending most readers would predict." },
    ],
    closer: [
      { title: "What the proportions tell you", body: "Only two of the eight chapters in the first half are analytic; the rest are deaths, dying words, sayings at graves, and dreams. This is the one book in the Ihya where narration is the method rather than the illustration, and reading it for arguments alone misreads what it is doing." },
      { title: "Why it is placed last", body: "The Quarter of Deliverance has moved through repentance, patience, fear and hope, poverty, trust, love, sincerity, vigilance, and reflection. Every one of them has assumed a horizon. This book is where the horizon itself is examined, which is why it can only come at the end." },
    ],
    distinction: ["Two ways to read a book made mostly of stories", "Narration as method", "The deaths and dying words are how the book works on a reader, not decoration around a thesis.", "Narration as illustration", "Stories supporting arguments, which would make three quarters of this book redundant."],
    misreading: "Do not skip to the analytic chapters. Ghazali structured the largest book in his work around accounts of particular deaths, and that structure is a claim about how this subject is learned.",
    reflection: "Notice that the last thing in the Ihya is announced on its first page as a chapter on mercy, and hold that while reading everything before it.",
    audit: ["What did I expect this book to be?", "Why is it placed last?", "Do I read stories as decoration?", "What ending was I expecting?"],
    nodes: ["dhikr-mawt", "structure", "rahma"],
    model: pair("Two halves", "The second is announced in order, and its last item is stated in advance.", [["To the trumpet", "Eight chapters: the remembrance, hope, the throes, the deaths, the words, the graves, the reality, the dreams.", "support"], ["From the trumpet", "The Day, the Balance, the Bridge, the Fire, the Garden, the looking, and then mercy.", "support"]]),
  }),
  makeChapter({
    id: 2, shortTitle: "An occupied heart", formalTitle: "The way to realise the remembrance of death",
    overview: "The first analytic chapter, and it answers a question most readers have already asked themselves: why does thinking about death change nothing?",
    thesis: "Most readers assume the thought of death simply arrives; Ghazali explains why it lands on nothing.",
    moves: [
      { title: "State the diagnosis", body: "Death is dreadful and the danger in it is enormous, and the ordinary explanation for why people ignore it is that they hardly ever think about it. On that account the fix would be obvious: think about it more. Set a reminder, read something sobering, sit through a funeral. Ghazali starts here because it is what everybody already believes, and because the advice that follows from it is what everybody has already tried. He is going to accept the diagnosis only far enough to show you where it fails, and the failure is not in the amount of thinking." },
      { title: "Correct the diagnosis", body: "Because plenty of people do think about death, and nothing happens. The reason is that they are not thinking with an empty heart. The heart is already occupied — with what they want, what they are owed, what they are building, who has wronged them. The thought of death arrives into a room with no space in it, gets acknowledged, and leaves. That is the whole experience most people have of it: a passing sadness at a graveside that is gone by the car park. The thought did not fail. It landed on nothing." },
      { title: "Give the remedy", body: "So the work is not to increase the thought but to clear the ground it lands on: empty the heart of everything except the death in front of you. Ghazali means the death in front of you specifically, not death as a general truth about human beings. Everyone concedes the general truth and it costs them nothing. What has to occupy the heart is that you personally are going to stop, at a date already fixed, possibly this year, and that every arrangement you are currently maintaining will continue for a while without you and then be forgotten." },
      { title: "Give the image", body: "Think of somebody about to cross a killing desert, or put out to sea in bad weather. He is not being encouraged to reflect on the crossing; he simply cannot think about anything else, and nobody has to remind him. Nothing else can get a foothold. When the thought lands on a heart cleared like that it usually does something — his appetite for what is here drops away, and something in him breaks a little. That break is the point. It is the difference between having considered death and having been reached by it." },
      { title: "Make the method concrete", body: "And Ghazali does not leave you to arrange that emptiness by force of will. He gives a method: go to the graves, and go to the sick. Stand where somebody you knew is buried and put the questions directly. How did he talk, when the worms have eaten his tongue? How did he laugh, when the dirt has eaten his teeth? He was making plans he would not need for another ten years, and there was a month left between him and death — and he had no idea what was being prepared for him, until it arrived on a day he had not counted, and the angel's form was uncovered to him, and the call reached his ear: either to the Garden or to the Fire." },
      { title: "Turn it on yourself", body: "Then the move that makes the visit work rather than merely sadden: you look at yourself and see that you are one of them. Your obliviousness is their obliviousness. Your ending will be their ending. Abu al-Darda' put it as an instruction — when you remember the dead, count yourself as one of them. Ibn Mas'ud said the fortunate person is the one who takes the warning from somebody else, which is the only way anybody gets to take it in time. Umar b. Abd al-Aziz asked people to notice what they were doing every single day: you send somebody off to God, morning or evening, and lay him in a crack in the ground with dust for a pillow, his loved ones behind him and every thread of his life cut." },
      { title: "Say what fails", body: "Sticking with thoughts like these, with actual visits to graves and to the sick, is what keeps the remembrance of death alive in the heart until it takes the heart over and sits permanently in front of his eyes. At that point he is close to getting ready, and close to keeping his distance from a house that has been lying to him. Short of that, remembering with the surface of the heart and the tip of the tongue does very little warning and very little waking — which is Ghazali's verdict on nearly all the remembering people actually do." },
      { title: "Give the daily drill", body: "And there is a smaller practice for ordinary days. Any time your heart takes real pleasure in something of this world, remind yourself right then that you will certainly be separated from it. Ibn Muti' looked at his house one day and was struck by how beautiful it was, and then wept and said: by God, if it were not for death, I would be delighted with you. Notice what he is not doing. He does not deny the house is lovely or scold himself for noticing. He lets the pleasure be real and lets the parting be real at the same time, and the second is what stops the first from turning into a claim on him." },
    ],
    closer: [
      { title: "Why the correction matters", body: "The first sentence names the ordinary explanation, that people do not think about death enough. The second withdraws it: many do, and it lands on nothing. The failure is located in the condition of the heart receiving the thought rather than in the frequency of the thought, which changes what there is to do about it." },
      { title: "What the traveller supplies", body: "The analogy is not about fear. Someone about to cross a desert is not terrified; he is occupied by one thing because one thing is genuinely in front of him. Ghazali is describing a redirection of attention that the situation itself justifies, and the word he uses for the result is that the heart is broken." },
    ],
    distinction: ["Two accounts of why it does not work", "Too little thought", "The ordinary explanation, which Ghazali states and then sets aside.", "An occupied heart", "The thought arrives into a heart taken up with appetite, so nothing takes effect."],
    misreading: "Do not read the emptying as a demand for morbidity. The traveller's model is a person with one real thing in front of him, and the chapter asks for that condition rather than for gloom.",
    reflection: "Recall the last time death crossed your mind and what it changed. That gap is the chapter's subject.",
    audit: ["Do I think about it, and does it land?", "What is my heart occupied with when it arrives?", "Have I blamed frequency?", "What would emptying actually involve?"],
    nodes: ["dhikr-mawt", "occupied-heart", "ghafla"],
    model: pair("Where the failure is", "Only the second has a remedy attached.", [["The frequency", "How often the thought arrives, which is what people try to fix.", "warning"], ["The reception", "What the heart is holding when it arrives, which is where Ghazali locates it.", "support"]]),
  }),
  makeChapter({
    id: 3, shortTitle: "Two causes", formalTitle: "The cause of long hope and its treatment",
    overview: "The heart of the book's analytic content. Ghazali names two causes of the long horizon, and the second one is described with unusual precision.",
    thesis: "Two causes of a long horizon are named, which is the heart of the book's analytic content.",
    moves: [
      { title: "Name them", body: "Long hope — the settled assumption that there is plenty of time left — has two causes, and Ghazali is careful to keep them apart because they need different treatment. One is ignorance. The other is love of the world. The first is a mistake about the facts and can in principle be corrected by being told the facts. The second is not a mistake at all; it is a preference, and telling somebody the facts does nothing to a preference. Most people have both, which is why arguments about mortality bounce off them so reliably." },
      { title: "Work the second", body: "Take the harder one first. Once somebody has settled into the world — its appetites, its pleasures, the particular things that hold him in place — leaving becomes heavy, and his heart simply refuses to entertain the thought of death, because death is what will do the leaving. This is not a considered position. It is the ordinary way anyone handles a thought they do not want: they do not refute it, they decline to look at it. You already know this from smaller cases. Nobody argues themselves out of opening the letter from the hospital; they just find the day gets full." },
      { title: "Name the mechanism", body: "And the refusal is not passive, which is Ghazali's real point. A person is in love with false hopes, so he keeps making himself promises that agree with what he wants, and what he wants is to stay. Then he goes further and starts working out the arrangements: how much money staying will require, what the family will need, the house, the friends, the plans that follow from the plans. Each calculation is perfectly sensible on its own. Taken together they are an enormous structure whose sole hidden premise is that he is not going to die soon." },
      { title: "State the result", body: "So the heart settles onto this thinking and stops there, held in place by work that always feels responsible rather than evasive. He is not distracted from the remembrance of death by anything scandalous. He is distracted by his own diligence. And because he never once puts a number on how close death might be, the question of nearness is not answered wrongly — it is never raised at all, which is a far more durable way of avoiding it than getting it wrong would be." },
    ],
    closer: [
      { title: "Why aversion is the engine", body: "The account does not require anyone to believe he will not die. It requires only that he dislike the thought, and it observes that what a person dislikes he pushes away. The long horizon is therefore not a belief a person holds but a consequence of an avoidance he performs, which is why arguing him out of it does not work." },
      { title: "The other cause", body: "Ignorance is given first and treated more briefly, because it is the tractable one: a person who supposes he has time can be shown otherwise. The chapter spends its length on the cause that cannot be corrected by information, which is the same asymmetry Book 39 drew between knowing something and being governed by it." },
    ],
    distinction: ["Two causes of the same horizon", "Ignorance", "Supposing that time remains, which can be addressed by being shown otherwise.", "Love of the world", "Disliking the thought and therefore pushing it away, which information does not touch."],
    misreading: "Do not treat long hope as an intellectual error. Ghazali gives ignorance as only one of two causes and spends the chapter on the other one, which is a disposition rather than a belief.",
    reflection: "Ask whether you have ever been argued out of a horizon, or whether the horizon moved for other reasons.",
    audit: ["Which of the two causes is mine?", "What am I pushing away?", "Do I dislike the thought or doubt it?", "What am I already reckoning the consequences of?"],
    nodes: ["tul-amal", "dunya", "ghafla"],
    model: pair("Two causes, two tractabilities", "The chapter's length is spent on the harder one.", [["Ignorance", "Supposing time remains, and correctable by being shown.", "balance"], ["Love of the world", "Aversion, which pushes the thought away and is untouched by argument.", "warning"]]),
  }),
  makeChapter({
    id: 4, shortTitle: "Ten more attach", formalTitle: "The machinery of deferral",
    overview: "The most recognisable passage in the book, and one of the most exact descriptions of procrastination in any literature.",
    thesis: "The machinery of putting it off, and it is the most recognisable passage in the book.",
    moves: [
      { title: "Set the scene", body: "If death and the need to get ready for it do cross his mind, he puts it off and makes himself a promise, and says: the days are before you, until you grow older, and then you will repent." },
      { title: "Follow the ladder down", body: "When he gets older it becomes: wait until you are actually old. And when he is old: wait until you have finished building this house, or planting this land, or got back from this trip." },
      { title: "Keep following it", body: "Or finish settling this child and his outfitting and arranging a dwelling for him; or finish subduing this enemy who gloats over you. The examples are chosen so that each one is a real obligation." },
      { title: "Name the mechanism", body: "So he keeps deferring and delaying, and he plunges into no occupation but that ten other occupations attach themselves to the completion of that occupation, and so on by degrees." },
    ],
    closer: [
      { title: "Why the ladder starts with age", body: "The first two rungs are about a stage of life and the rest are about tasks, and the transition is where the passage turns. A person who was waiting to be old finds, on becoming old, that he has been waiting for something else the whole time and simply had not noticed the substitution." },
      { title: "The sentence that does the work", body: "Ten occupations attaching to the completion of one is not a complaint about busyness. It is a structural claim: the set of things to be finished before starting does not shrink as you work through it, because working through it generates more. On that account no amount of diligence reaches the end of the list, which is why the remedy in the next chapters is not efficiency." },
    ],
    distinction: ["Two ways to be too busy to begin", "A long list", "Which would shorten as you worked through it, and would eventually end.", "A generating list", "Where finishing one item attaches ten more, so that diligence never reaches the end."],
    misreading: "Do not read the deferred tasks as trivial or as excuses. Every example Ghazali gives is a genuine responsibility, and that is precisely what makes the mechanism work.",
    reflection: "Name the thing you are currently waiting to finish. Then ask what you were waiting to finish two years ago, and whether you finished it.",
    audit: ["What am I waiting to finish?", "What was I waiting to finish before?", "Did finishing it free me?", "How many things attached to the last thing I completed?"],
    nodes: ["tul-amal", "taswif", "dunya"],
    model: chain("The ladder", "Each rung is real, and the last one names the mechanism.", [["Until you are older", "A stage of life, which arrives and does not release you.", "warning"], ["Until you are old", "The same move again, and the substitution goes unnoticed.", "warning"], ["Until this is finished", "A genuine obligation, which is what makes it effective.", "warning"], ["And ten attach", "The list generates faster than it is worked through.", "warning"]]),
  }),
  makeChapter({
    id: 5, shortTitle: "Seven horizons", formalTitle: "The ranks of people in long and short hope",
    overview: "A ladder of seven rungs, and its measure is startlingly concrete: not what a person believes about death but how far ahead he provisions.",
    thesis: "Seven rungs, measured not by what a person believes but by how far ahead he has actually provisioned.",
    moves: [
      { title: "The first two rungs", body: "Some expect to go on and want to go on forever. Some expect to last until they are worn out with age — the furthest they have ever seen anyone get — and that is somebody who loves this world hard." },
      { title: "The third and fourth", body: "Some hope to a year, and do not busy themselves arranging beyond it, and reckon no existence for themselves in the coming year — but such a one prepares in summer for winter and in winter for summer, and when he has gathered his year's sufficiency he busies himself with worship. And some hope for the length of a summer or a winter, so he does not store winter clothes in summer nor summer clothes in winter." },
      { title: "The fifth and sixth", body: "Some have a hope that returns to a day and a night, so he prepares only for his day and not for tomorrow. And some have a hope that does not pass an hour, on the counsel that when you rise in the morning you do not speak to yourself of the evening, and when evening comes you do not speak to yourself of the morning." },
      { title: "The seventh", body: "Some do not reckon remaining even an hour. The ladder therefore ends where planning ends, and the rungs are separated by nothing except the length of the horizon a person actually provisions for." },
    ],
    closer: [
      { title: "Why the measure is provisioning", body: "The rungs could have been described by conviction, and are not. Each one is given by what a person stores, buys, arranges, and does not arrange, which is a fact about him that he cannot be mistaken about. Ghazali has made a spiritual rank into something checkable against a cupboard." },
      { title: "The third rung is not condemned", body: "Notice what the man at the third rung does: he provisions for the year and then, having gathered what suffices, he turns to worship. He is on a ladder whose top he has not reached and he is not described as failing. The rungs are a scale rather than a threshold, which is what makes the chapter usable." },
    ],
    distinction: ["Two ways to measure a horizon", "By what is provisioned", "What a person actually stores and arranges, which he cannot be wrong about.", "By what is believed", "What he says about the shortness of life, which the rest of the book shows can coexist with anything."],
    misreading: "Do not read the ladder as demanding the top rung. Ghazali describes the man at the third rung doing something sensible and then turning to worship, and Jesus's counsel he quotes concerns tomorrow's provision rather than this year's.",
    reflection: "Find your rung by looking at what you have stored rather than at what you believe.",
    audit: ["How far ahead have I actually provisioned?", "Which rung does that put me on?", "Would my belongings agree with my beliefs?", "What would the next rung down change?"],
    nodes: ["tul-amal", "ranks", "istidad"],
    model: spectrum("Seven rungs", "Separated only by the length of what is provisioned for.", [["Forever", "Hoping to remain and desiring it without end.", "warning"], ["To old age", "The furthest age witnessed; one who loves the world intensely.", "warning"], ["A year", "Provisions the year, then turns to worship.", "balance"], ["A season", "No winter clothes stored in summer.", "balance"], ["A day", "Prepares for the day and not for tomorrow.", "support"], ["An hour", "Does not speak to himself of the evening.", "support"], ["Not an hour", "Reckons no remaining at all.", "support"]]),
  }),
  makeChapter({
    id: 6, shortTitle: "The two brothers", formalTitle: "Hastening to act, and the blight of delay",
    overview: "The chapter that explains why the horizon matters at all, using an analogy anyone can check, and then makes an observation about time that is easy to miss.",
    thesis: "Why the horizon matters at all: it is what decides whether anything gets done today.",
    moves: [
      { title: "Give the analogy", body: "A man with two absent brothers, expecting one tomorrow and the other after a month or a year, does not prepare for the one arriving in a month or a year. He prepares for the one he expects tomorrow." },
      { title: "Draw the principle", body: "So preparation is the result of the nearness of the expectation. It is not the result of conviction, or of affection, or of the importance of the visitor." },
      { title: "Apply it", body: "Somebody who expects to die in a year has his mind on the year and forgets what comes after it — and that is exactly what stops him hurrying, because he can see room to move inside it." },
      { title: "Make the observation", body: "Then he rises each day still expecting the full year, and does not subtract the day that has passed. The horizon does not shorten as it is spent, which is why a distant expectation never becomes a near one on its own." },
    ],
    closer: [
      { title: "What the two brothers rule out", body: "The analogy separates preparation from every other attitude. Both brothers are loved, both arrivals are certain, and only the near one produces action. So a person who is not preparing has learned nothing about what he believes or how much he cares — only about where his expectation sits." },
      { title: "The counsel that follows", body: "The chapter carries the counsel to seize five before five: youth before decrepitude, health before sickness, wealth before poverty, leisure before occupation, and life before death. Each pair names a resource and the state that removes it, and all five are things whose loss cannot be scheduled." },
    ],
    distinction: ["Two things that could produce preparation", "Nearness of expectation", "Which the two brothers show is what actually does it.", "Conviction or concern", "Both of which the analogy holds constant across the two brothers, and neither of which acts."],
    misreading: "Do not take the observation about not subtracting the day as a call to anxious counting. It explains why a distant horizon is stable, which is an argument for shortening it rather than for watching it.",
    reflection: "Notice how differently you prepare for something tomorrow and something in a year, and that the difference is not about how much either matters.",
    audit: ["Where does my expectation actually sit?", "Have I subtracted the days I have spent?", "What am I preparing for, by that measure?", "Which of the five do I still have?"],
    nodes: ["istidad", "taswif", "ranks"],
    model: chain("Why the distant never becomes near", "The horizon does not shorten as it is spent.", [["A year expected", "The heart occupies itself with the period and forgets what is past it.", "warning"], ["Room seen", "There is space in the year, so the act is deferred.", "warning"], ["The day passes", "And the year is not reduced by it, so tomorrow looks the same.", "warning"]]),
  }),
  makeChapter({
    id: 7, shortTitle: "Five blows", formalTitle: "The throes of death and their severity",
    overview: "The third chapter of the first half, and it opens with an argument before it opens with descriptions.",
    thesis: "The third chapter opens on what dying is actually like, and does not soften it.",
    moves: [
      { title: "State the minimum case", body: "If there were before the poor servant no distress and no terror and no punishment except the throes of death by themselves, that alone would be fit to spoil his living, cloud his joy, and part him from his inadvertence." },
      { title: "Add the timing", body: "It would be fit that he lengthen his thought about it and make his preparation great, especially since he is exposed to it at every breath." },
      { title: "Give the sayings", body: "As one of the sages said: a distress in another's hand, and you do not know when it will overtake you. And Luqman said to his son: a matter you do not know when it will meet you — prepare for it before it takes you by surprise." },
      { title: "Give the argument", body: "The marvel is that if a man were in the greatest of pleasures and the finest gathering, and expected a soldier to come in and strike him five blows with a stick, his pleasure would be spoiled and his enjoyment ruined." },
    ],
    closer: [
      { title: "How the five blows argue", body: "The comparison is calibrated deliberately low. Five blows are survivable, scheduled, and trivial beside what the chapter is about, and the anticipation of them would still ruin an evening. The argument is therefore not that death is terrible but that a person's reaction to it is wildly out of proportion with his reaction to everything else, which is a claim about inconsistency rather than about fear." },
      { title: "The rest of the chapter", body: "What follows is a long series of accounts of particular deaths and the states of those undergoing them. Ghazali has established the argument first and then, for the remainder, stops arguing — which is the pattern of the whole book." },
    ],
    distinction: ["Two ways to make the case", "By proportion", "Five expected blows would ruin an evening, and this does not, which is an inconsistency.", "By magnitude", "Describing how terrible it is, which the chapter does at length only after the argument."],
    misreading: "Do not treat the accounts that follow as the argument. The argument is the paragraph about the soldier, and it works by being small.",
    reflection: "Test the comparison honestly. Something minor and scheduled for this evening would occupy you more than this does.",
    audit: ["What small thing occupies me more than this?", "Is my reaction proportioned to anything?", "What would five blows tonight do to my day?", "Am I reading for argument or for feeling?"],
    nodes: ["sakarat", "istidad", "ghafla"],
    model: pair("A deliberately small comparison", "The argument works because the other side is trivial.", [["Five blows tonight", "Survivable, scheduled, and enough to spoil the finest evening.", "balance"], ["This, at any breath", "Unscheduled, unavoidable, and producing no comparable effect.", "warning"]]),
  }),
  makeChapter({
    id: 8, shortTitle: "Three things wanted", formalTitle: "The states recommended for the dying",
    overview: "A short and unusually gentle chapter, and its structure is a triad that covers the body, the tongue, and the heart.",
    thesis: "A short and unusually gentle chapter, whose structure is itself the argument.",
    moves: [
      { title: "The form", body: "What is loved at death, from the appearance of the dying person, is quietness and stillness." },
      { title: "The tongue", body: "From his tongue, that it be uttering the testimony." },
      { title: "The heart", body: "From his heart, that he hold a good opinion of God." },
      { title: "Note what the triad covers", body: "Body, speech, and heart, in that order, which is the same three-layer division Ghazali uses throughout the Ihya for describing any state of a person." },
    ],
    closer: [
      { title: "Why the third is placed last", body: "The order runs from what is most visible to what is least. Two of the three can be observed by those present and one cannot, and the one that cannot is the one Book 38 spent its length on. The chapter puts what matters most where it can least be confirmed." },
      { title: "Its relation to Book 33", body: "Good opinion of God at the end is where the whole treatment of fear and hope arrives. Book 33 argued that neither is superior in itself and that the question is which a person needs now; this chapter names what is wanted at the one moment when the answer stops varying." },
    ],
    distinction: ["Two ways to read the triad", "Three layers of one person", "Body, tongue, and heart, running from most visible to least.", "Three requirements", "A checklist to be satisfied, which would put the unobservable one on the same footing as the others."],
    misreading: "Do not treat the outward signs as a verdict on anyone. Chapter 14 of this book states plainly that the state of a particular person cannot be known, and the reports about outward signs stand under that restriction.",
    reflection: "Notice which of the three you would be most anxious about, and what that tells you.",
    audit: ["Which of the three concerns me most?", "What is my opinion of God now?", "Do I read outward signs as verdicts?", "Where does the fear and hope question land here?"],
    nodes: ["ihtidar", "husn-al-zann", "khawf-raja"],
    model: chain("Three layers", "Ordered from most visible to least.", [["The form", "Quietness and stillness, which those present can see.", "balance"], ["The tongue", "Uttering the testimony, which those present can hear.", "balance"], ["The heart", "Good opinion of God, which nobody present can confirm.", "support"]]),
  }),
  makeChapter({
    id: 9, shortTitle: "Particular deaths", formalTitle: "The deaths of the Messenger and the caliphs",
    overview: "The longest chapter in the first half, and the one that most clearly shows what the book is doing. Almost none of it is argument.",
    thesis: "The longest chapter of the first half, and the one that does most of its work by accumulation.",
    moves: [
      { title: "Say what it contains", body: "A sustained narrative of the last illness and death of the Messenger, followed by the deaths of Abu Bakr, Umar, Uthman, and Ali, given in detail and largely without commentary." },
      { title: "Note the absence of a thesis", body: "Ghazali does not extract a lesson at the close of each account. The accounts are laid end to end, and the reader is left with the particulars." },
      { title: "Name what the particularity does", body: "Death treated generally is a proposition, and propositions are what the earlier chapters showed can be held without effect. A named person, on a named day, saying a specific thing, is not a proposition." },
      { title: "Connect it to Chapter 2", body: "The stated problem of this book is that the remembrance of death arrives at an occupied heart and does not take. Chapters like this one are the remedy applied rather than described: the emptying is attempted on the reader by occupying him with something that cannot be held at arm's length." },
    ],
    closer: [
      { title: "Why these deaths", body: "They are the deaths of the people whose lives the reader knows best and admires most. If the argument of Chapter 7 is that our reactions are out of proportion, one way to correct the proportion is to attach it to people whose reality is not in doubt." },
      { title: "What this edition does with it", body: "This section describes the chapter and its function rather than retelling the accounts, which run to many pages and belong to the text rather than to a synthesis. A reader who wants them should go to Book 40 itself, and the editorial note records that decision." },
    ],
    distinction: ["Two ways a book can treat death", "In particular", "Named people, named days, specific words, which cannot be held as a proposition.", "In general", "A truth about everyone, which the earlier chapters showed can be assented to without effect."],
    misreading: "Do not read the absence of commentary as an absence of purpose. The chapter's method is that it does not comment, and adding a moral to each account would undo it.",
    reflection: "Notice how differently a particular death sits in you from the general fact, and that this book is built on that difference.",
    audit: ["Do particulars land differently in me?", "Whose death do I actually think about?", "Am I looking for the lesson?", "What is being done to the reader here?"],
    nodes: ["narration", "dhikr-mawt", "occupied-heart"],
    model: pair("Two registers", "The book spends most of its length in the second.", [["The proposition", "True of everyone, and held without effect, as Chapter 2 describes.", "warning"], ["The particular", "A named person on a named day, which cannot be held at arm's length.", "support"]]),
  }),
  makeChapter({
    id: 10, shortTitle: "What they said", formalTitle: "The speech of the dying",
    overview: "A collection of last words, and its selection is worth noticing: the powerful are placed first and they do not come off well.",
    thesis: "A collection of last words, and what was selected tells you what Ghazali thought they showed.",
    moves: [
      { title: "Open with a ruler", body: "The chapter opens with Muʿawiya, who at the end asked to be seated, praised God, wept, and said: you remember your Lord, Muʿawiya, after decrepitude and decline — would that this had been while the branch of youth was green and full." },
      { title: "Give his prayer", body: "He wept until the sound of it carried, and said: my Lord, have mercy on a sinning old man with a hard heart. Make the stumble smaller and forgive the slip, and turn with Your patience toward somebody who hopes in nobody but You and trusts nobody else." },
      { title: "Give the second voice", body: "An elder of Quraysh, seen with the creases of age in his skin, said: is the whole world anything but what we have tried and seen? We met its bloom in our vigour and our enjoyment of our living, and it did not leave us long before it undid that from us, state after state and handhold after handhold." },
      { title: "Note the ordering", body: "Caliphs and commanders come before the righteous in the chapter's own title, and the effect of that order is that the reader hears the regret before he hears the composure." },
    ],
    closer: [
      { title: "Why the powerful first", body: "The people with the most reason to have found the world satisfactory are the ones whose last words are recorded first, and what they say is that it was not. The argument is left entirely to the arrangement." },
      { title: "The phrase to keep", body: "State after state and handhold after handhold is the same structure as Chapter 4's ten occupations, run in the other direction. There, the list of things to finish grows; here, the handholds come away one at a time. Both describe a process that does not announce itself while it is happening." },
    ],
    distinction: ["Two things last words can be", "Evidence", "What people who had the most of the world said about it when it was over.", "Consolation", "Edifying sentiments collected for comfort, which the placement of the caliphs first rules out."],
    misreading: "Do not read the regret as despair. Muʿawiya's words end in a prayer that turns entirely on the forbearance of the one addressed, which is where the whole book is going.",
    reflection: "Notice that the complaint is not that the world was bad but that it was tried and found to be only what it was.",
    audit: ["What would I say?", "Which handholds have already come away?", "Do I expect the world to be other than tried?", "Where does the regret turn?"],
    nodes: ["narration", "dunya", "rahma"],
    model: spectrum("The order of voices", "The arrangement carries the argument.", [["Caliphs and commanders", "Those with most of the world, and the first to be heard.", "warning"], ["The righteous", "Placed after, so composure is heard second.", "balance"], ["What both arrive at", "A prayer resting on forbearance rather than on record.", "support"]]),
  }),
  makeChapter({
    id: 11, shortTitle: "Visiting graves", formalTitle: "The sayings at graves, and the ruling on visiting them",
    overview: "The sixth chapter, and the one place in the book where Ghazali gives a legal ruling with a stated history and a stated purpose.",
    thesis: "The one place in the book where visiting the dead is given a ruling rather than a description.",
    moves: [
      { title: "Give the ruling", body: "Visiting graves is recommended in general, for the sake of recollection and consideration. And visiting the graves of the righteous is for the sake of blessing along with consideration." },
      { title: "Give its history", body: "The Messenger had forbidden the visiting of graves and then permitted it afterward, in the report: I had forbidden you to visit graves, so visit them, for they remind you of the hereafter — only do not say anything improper." },
      { title: "Note what the permission carries", body: "The permission arrives with its purpose attached and with a condition attached, and both are in the same sentence. The visit is licensed by what it does to the visitor and bounded by what is said at the grave." },
      { title: "Give the account of Aisha", body: "Asked where she had come from, she said from her brother's grave; asked whether the Messenger had not forbidden it, she said yes, and then he commanded it." },
    ],
    closer: [
      { title: "What the reversal shows", body: "A prohibition that was lifted, with a reason given for the lifting, is a different kind of ruling from one that was always in force. Ghazali reports both halves, and the reason he reports is the same one this whole book runs on: that the visit reminds a person of the hereafter." },
      { title: "The restriction he adds", body: "Ghazali goes on to argue that the permission should not be extended to women going out to the graves, on the grounds of the wailing that is common there and the exposure on the way, concluding that the good of their visiting would not outweigh its harm. The restriction is his and is recorded here as his; it is a judgement about circumstances of his time and place rather than a report of the permission itself." },
    ],
    distinction: ["Two kinds of ruling", "Reversed, with a reason", "Forbidden and then commanded, with the purpose of the visit stated in the same breath.", "Standing", "Always in force, which would leave the purpose unstated and the visit unexplained."],
    misreading: "Do not detach the permission from the purpose given with it. The report licenses the visit by what it reminds a person of, and the condition on what is said at the grave is in the same sentence.",
    reflection: "Ask what a visit would actually be for, on the reason the report itself gives.",
    audit: ["Have I visited, and for what?", "What did it remind me of?", "Do I know why the ruling changed?", "What is said at the graves I have stood at?"],
    nodes: ["qubur", "itibar", "narration"],
    model: chain("A ruling with a history", "The purpose is stated in the same sentence as the permission.", [["Forbidden", "The earlier position, reported rather than passed over.", "balance"], ["Then commanded", "The reversal, given with its reason attached.", "support"], ["For they remind you", "The purpose, which is the whole book's subject.", "support"]]),
  }),
  makeChapter({
    id: 12, shortTitle: "A change of state", formalTitle: "The reality of death",
    overview: "The book's central definition, and Ghazali reaches it by clearing away three positions first. The definition itself is one line.",
    thesis: "The book's central definition, reached by a route rather than asserted.",
    moves: [
      { title: "Name the first supposition", body: "People hold false suppositions about the reality of death. Some supposed that death is annihilation, and that there is no gathering and no raising and no consequence for good or evil, and that a person's death is like the death of animals and the drying of plants." },
      { title: "The second", body: "A group supposed that he is annihilated by death and is neither pained by anything harmful nor delighted by any reward while he is in the grave, until he is returned at the time of the gathering." },
      { title: "The third", body: "Others said the spirit remains and is not annihilated by death, and that what is rewarded and punished is the spirits without the bodies, and that the bodies are not raised or gathered at all." },
      { title: "Give the definition", body: "All of these are corrupt suppositions that deviate from the truth. Rather what the paths of consideration testify to, and what the verses and reports speak, is that death means only a change of state, and that the spirit remains after separating from the body, either punished or blessed." },
    ],
    closer: [
      { title: "The weight of the word only", body: "Death means a change of state and nothing more. After eleven chapters of throes, graves, and last words, the definition when it arrives is deflationary. What is being denied is that death is an event of a different kind from the events of a life, not that it is serious." },
      { title: "How the three positions are arranged", body: "They run from most to least radical, and each concedes something the previous one denied. Ghazali does not argue against them individually; he names them, calls them corrupt, and states the alternative. The chapter's function is to fix a definition rather than to conduct a dispute." },
    ],
    distinction: ["Two things death could be", "A change of state", "The spirit remaining after the separation, in one condition or another.", "An interruption", "A gap in which nothing is undergone, which is the second of the three suppositions."],
    misreading: "Do not take the brevity of the definition as making the subject small. The claim that death changes the state and not the existence is what makes every chapter about the grave intelligible.",
    reflection: "Ask which of the three suppositions you have quietly been holding, and whether the second in particular is not what you assume.",
    audit: ["Which supposition is mine, in practice?", "Do I assume an interruption?", "What does only a change mean here?", "How does this change the grave chapters?"],
    nodes: ["haqiqat-mawt", "ruh", "qubur"],
    model: spectrum("Three refused, one held", "Arranged from most radical to least.", [["Annihilation", "No raising and no consequence; the view of those who deny the Last Day.", "warning"], ["An interruption", "Nothing undergone until the gathering.", "warning"], ["Spirits only", "Reward and punishment without any raising of bodies.", "warning"], ["A change of state", "The spirit remaining after the separation, in one condition or the other.", "support"]]),
  }),
  makeChapter({
    id: 13, shortTitle: "The questioning", formalTitle: "What the dead meets in the grave",
    overview: "The chapters on the grave, the questioning, and what precedes the trumpet. They are the most vivid material in the first half and rest entirely on the previous chapter's definition.",
    thesis: "The grave, the questioning, and what follows — presented as what the tradition transmits.",
    moves: [
      { title: "Say what they cover", body: "The speech of the grave to its occupant, the questioning by the two who come, the constriction of the grave, and the punishment of the grave, given through the reports at length." },
      { title: "Note what they presuppose", body: "Every one of these requires that something is undergone between death and the gathering, which is exactly what the second of the three refused suppositions denies. The definition in Chapter 12 is what licenses this chapter to exist." },
      { title: "Note the register", body: "Ghazali gives this material through reports rather than through argument, and the reports are given with the conventional attributions. The mode is transmission." },
      { title: "Mark the limit", body: "None of it is applied to any particular person. The next chapter states explicitly why that limit holds, and it holds over everything in this one." },
    ],
    closer: [
      { title: "Why the definition had to come first", body: "Read without Chapter 12, this material is a set of terrors. Read after it, it is the working out of a single claim: that the state changed and the person did not stop. The order is what makes the difference between a description and a doctrine." },
      { title: "What this edition does with it", body: "This section describes the chapter and its dependence on the definition rather than reproducing its detail, which runs to many pages of transmitted reports. That decision is recorded in the editorial note, and a reader who wants the material should go to the text." },
    ],
    distinction: ["Two ways this material can be read", "As the definition worked out", "What follows from the state changing while the person continues.", "As a set of terrors", "Images to be dwelt on, which is what reading it without Chapter 12 produces."],
    misreading: "Do not apply any of it to a particular person, living or dead. The next chapter closes that inference explicitly, and its argument covers everything here.",
    reflection: "Notice how much the order of the two chapters changes what this one is.",
    audit: ["Am I reading this after the definition?", "What does it presuppose?", "Have I applied it to anyone?", "What is the mode of this chapter?"],
    nodes: ["qubur", "haqiqat-mawt", "narration"],
    model: pair("What the order decides", "The same reports in two different lights.", [["After the definition", "The working out of the state having changed while the person continued.", "support"], ["Before it", "A collection of terrors with nothing holding them together.", "warning"]]),
  }),
  makeChapter({
    id: 14, shortTitle: "Zayd and Amr", formalTitle: "What can and cannot be known of a particular person",
    overview: "The most important guard in the book, and it sits at the opening of the chapter on dreams. Ghazali draws a hard line between general knowledge and particular judgement.",
    thesis: "The most important guard in the book: nothing here licenses a verdict about any particular person.",
    moves: [
      { title: "State what is known", body: "The lights of insight gained from the Book, the Sunna, and the paths of consideration acquaint us with the states of the dead in general, and with their division into the happy and the wretched." },
      { title: "State what is not", body: "But the state of this Zayd or that Amr in particular is not disclosed at all." },
      { title: "Close the first route", body: "If we rely on Zayd's or Amr's faith, we do not know what he died upon and how he was sealed." },
      { title: "Close the second", body: "Suppose we go on how upright he looks. But fear of God sits in the heart, where it is obscure and hidden even from the person who has it — let alone from anyone else. So looking upright settles nothing without the inward fear, since God accepts only from those who have it." },
    ],
    closer: [
      { title: "How far the guard reaches", body: "It is stated in the most general terms available: the two routes it closes are faith and visible righteousness, which are the only two anybody ever has. Ghazali is not restricting judgement about the wicked; he is restricting judgement about anyone, including the person judging himself." },
      { title: "Why it opens the chapter on dreams", body: "The chapter that follows reports dreams in which the states of particular dead people appear. Placing this argument at its head means the whole chapter is read as report rather than as evidence, and Ghazali sets that frame before giving a single account." },
    ],
    distinction: ["Two kinds of knowledge about the dead", "In general", "That they divide into the happy and the wretched, which the sources establish.", "In particular", "The state of a named person, which Ghazali says is not disclosed at all."],
    misreading: "Do not use the dreams that follow as verdicts about the people in them. The chapter opens by explaining why no such verdict is available, and the accounts are given inside that frame.",
    reflection: "Notice that the guard applies to favourable judgements exactly as much as to unfavourable ones.",
    audit: ["What have I concluded about someone who died?", "On which of the two closed routes?", "Do I apply this to myself as well?", "What can actually be known here?"],
    nodes: ["particular", "taqwa", "narration"],
    model: pair("Two routes, both closed", "They are the only two anyone ever has.", [["Their faith", "We do not know what he died upon or how he was sealed.", "warning"], ["Their outward righteousness", "Godfearing sits in the heart and is hidden even from its owner.", "warning"]]),
  }),
  makeChapter({
    id: 15, shortTitle: "From the trumpet", formalTitle: "The second half, and what it surveys",
    overview: "The whole second half of the book, and Ghazali lists its contents in order at its opening. The order itself is the argument of this section.",
    thesis: "The whole second half surveyed at once, with Ghazali listing what it covers.",
    moves: [
      { title: "Give the list", body: "The blast of the trumpet; the ground of the gathering and its people; the length of the Day; the Day and its calamities and its names; the questioning about sins; the Balance; the adversaries and the returning of wrongs; the Bridge; the intercession; the Basin." },
      { title: "Continue it", body: "Then Hell and its terrors; then the Garden and the kinds of its bliss, the number of the gardens and their gates and chambers and walls and rivers and trees, the clothing of its people and their couches, and the description of their food." },
      { title: "Reach the penultimate item", body: "Then the description of looking upon the face of God. It is placed after the entire description of the Garden and everything in it, and before only one thing." },
      { title: "Name the last", body: "A chapter on the breadth of the mercy of God, and with it the book is sealed. Ghazali states this at the opening of the second half, so the destination is known before any of the terrors are described." },
    ],
    closer: [
      { title: "Where the looking is placed", body: "Book 36 argued that the highest of pleasures is the knowledge of God and the sight of His face, and that the difference between knowing now and seeing then is a difference of clarity along one line rather than of kind. The second half of Book 40 places that sight after every other described bliss, which is the payoff of that argument arriving where the work ends." },
      { title: "What this edition does with the survey", body: "The second half runs to well over a hundred pages of transmitted description. This section presents its structure and the significance of its order rather than reproducing it; the decision is recorded in the editorial note, and the text is where the descriptions belong." },
    ],
    distinction: ["Two ways to order this material", "Ending in mercy", "The terrors described first and the destination announced in advance, which is Ghazali's order.", "Ending in the terrors", "Which would make the book a warning, and which its own table of contents rules out."],
    misreading: "Do not read the length of the terrifying material as its weight. Ghazali announces at the head of the second half where it is going, which means every page of terror is read by someone who has been told the ending.",
    reflection: "Notice that the destination is disclosed before the journey, and ask why a writer would do that.",
    audit: ["Did I know where this was going?", "Where is the looking placed?", "What does the order claim?", "Would I have ordered it this way?"],
    nodes: ["akhira", "nazar", "rahma"],
    model: chain("The order of the second half", "The last two items are the ones the order is for.", [["The Day and its terrors", "The blast, the Balance, the Bridge, and the Fire, at length.", "warning"], ["The Garden", "Its gardens, rivers, clothing, and food, described in detail.", "balance"], ["The looking", "Placed after every other described bliss.", "support"], ["Mercy", "And with it the book is sealed.", "support"]]),
  }),
  makeChapter({
    id: 16, shortTitle: "How it ends", formalTitle: "The breadth of mercy, with which the book is sealed",
    overview: "The last section of the last book of the Ihya. Forty books of scrutiny, reckoning, and warning close on a sequence about mercy, ending with a single image.",
    thesis: "Forty books end on the breadth of mercy, which is a decision about how to finish rather than an afterthought.",
    moves: [
      { title: "The first report", body: "God says on the Day of Resurrection: bring out of the Fire whoever remembered Me a day, or feared Me in a station." },
      { title: "The card", body: "A man is brought with scrolls of misdeeds, and a single card is produced bearing the testimony that there is no god but God and that Muhammad is His messenger. He says: my Lord, what is this card beside these scrolls? And he is told: you will not be wronged. The scrolls are placed in one pan and the card in the other, and the scrolls fly up and the card weighs heavy — for nothing outweighs the name of God." },
      { title: "The call", body: "A caller calls from beneath the Throne: O community of Muhammad, what was owed to Me I have forgiven you; what remains are the claims you hold against one another, so make them gifts among yourselves, and enter the Garden by My mercy." },
      { title: "The last image", body: "A woman among the captives, who had lost her child, found a child among them, took him and pressed him to her and nursed him. And the Messenger said: do you think this woman would throw her child into the fire? They said: no, by God, not while she is able not to. He said: God is more merciful to His servants than this woman is to her child." },
    ],
    closer: [
      { title: "What the ending does to the work", body: "The Ihya has spent forty books on the exactness of the reckoning: the three registers of Book 38, the atom's weight of Book 37, the charges and the punishments and the audits. It closes by putting a nursing woman beside all of it and saying that the mercy exceeds hers. Nothing in the preceding books is withdrawn, and everything in them is placed." },
      { title: "The one clause that is not forgiven", body: "The call from beneath the Throne distinguishes what was owed to God, which is forgiven, from the claims people hold against one another, which are not simply cancelled but handed back to them to make gifts of. The last movement of the work leaves exactly one thing in human hands, and it is what we owe each other." },
    ],
    distinction: ["Two ways a work of this kind can end", "In mercy", "The reckoning stated in full and then placed beside something that exceeds it.", "In warning", "Which would make everything before it a threat rather than a description."],
    misreading: "Do not read the ending as cancelling the forty books before it. The scrolls in the account are real and are weighed, and the claims between people are explicitly not waived; what is asserted is the proportion, not the absence of the reckoning.",
    reflection: "Read the last image and then ask what the whole work has been for. Ghazali arranged it so that this is the last thing you read.",
    audit: ["What did I expect the ending to be?", "What is left in human hands?", "Does this cancel or place what came before?", "Whose claims do I hold, and whose do I owe?"],
    nodes: ["rahma", "akhira", "mazalim"],
    model: chain("The closing sequence", "Each step widens, and the last is an ordinary woman.", [["Whoever remembered a day", "Brought out for a single remembrance or a single fear.", "support"], ["The card", "One testimony outweighing scrolls of misdeeds.", "support"], ["The call", "What was owed to God forgiven; the claims between people handed back.", "balance"], ["The nursing woman", "And the mercy exceeding hers, which is the last line of the Ihya.", "support"]]),
  }),
];

export const book40ConceptNodes: ConceptNode[] = [
  ["dhikr-mawt", "Remembering death", "An operation, not a mood", "Its failure is located in the heart receiving it, not in how often it arrives."],
  ["structure", "Two halves", "Announced in advance", "Eight chapters to the trumpet, and a listed survey after it ending in mercy."],
  ["occupied-heart", "An occupied heart", "Why it does not take", "The thought lands on a heart full of appetite and has no effect."],
  ["ghafla", "Heedlessness", "Not simple ignorance", "Sustained by aversion, which is why information does not correct it."],
  ["tul-amal", "Long hope", "Two causes", "Ignorance, which can be shown; and love of the world, which cannot."],
  ["dunya", "Love of the world", "The engine", "What a person dislikes he pushes away, and death is what parts him from it."],
  ["taswif", "Deferral", "A generating list", "Ten occupations attach to the completion of each one."],
  ["ranks", "Seven rungs", "Measured by provisioning", "A spiritual rank made checkable against what a person has actually stored."],
  ["istidad", "Preparation", "Follows nearness", "Not conviction and not concern; the two brothers hold both constant."],
  ["sakarat", "The throes", "A proportion argument", "Five expected blows would ruin an evening, and this does not."],
  ["ihtidar", "The dying", "Three layers", "Stillness in the form, the testimony on the tongue, good opinion in the heart."],
  ["husn-al-zann", "Good opinion", "Where fear and hope arrive", "Named as what is wanted at the one moment the answer stops varying."],
  ["khawf-raja", "Fear and hope", "Neither superior", "Book 33's question, answered here for a single moment."],
  ["narration", "Narration", "The method", "Particulars that cannot be held as propositions, which is the book's remedy applied."],
  ["qubur", "The grave", "Presupposes the definition", "Everything in these chapters requires that something is undergone before the gathering."],
  ["itibar", "Consideration", "Why visiting is permitted", "The reason is given in the same sentence as the permission."],
  ["haqiqat-mawt", "The reality of death", "Only a change of state", "Three suppositions refused, and a deflationary definition held."],
  ["ruh", "The spirit", "Remains after separating", "In one condition or the other, which is what the grave chapters rest on."],
  ["particular", "Zayd and Amr", "Not disclosed at all", "General knowledge yes; the state of a named person, no."],
  ["taqwa", "Godfearing", "Hidden from its owner", "Which is why outward righteousness settles nothing about anyone."],
  ["akhira", "The second half", "Ordered deliberately", "Terrors, then the Garden, then the looking, then mercy."],
  ["nazar", "The looking", "Book 36's payoff", "Placed after every other described bliss, and before only one thing."],
  ["rahma", "Mercy", "The seal of the work", "Announced at the head of the second half and delivered in its last line."],
  ["mazalim", "Claims between people", "Not waived", "What was owed to God is forgiven; these are handed back to be made gifts of."],
].map(([id, label, kicker, description], index) => ({ id, label, kicker, description, position: ["left", "right", "top", "bottom"][index % 4] }));

const node = (id: string, label: string, micro: string, summary: string, guardrail: string, chapterId: number, glyph: Journey["nodes"][number]["glyph"]): Journey["nodes"][number] => ({ id, label, micro, summary, guardrail, chapterId, glyph });

export const book40Journeys: Journey[] = [
  {
    id: "why-nothing-changes", number: "01", question: "Why does remembering death change nothing?", title: "Find where the thought lands",
    description: "Take the structure of the largest book in the Ihya, then get its first diagnosis: the trouble is not how often the thought arrives but what the heart is holding when it does.",
    payoff: "You stop trying to fix the frequency and see what the book says is actually wrong.",
    image: assetUrl("assets/system/book40-the-traveller.jpg"), imageAlt: "A packed travelling bag and a water-skin set by an open door, with an empty road running out into pale distance beyond it.", minutes: 12, color: "#278d91",
    nodes: [
      node("the-structure", "Take the structure", "Two halves, eight chapters", "The ending is announced on the first page: a chapter on mercy seals the work.", "Knowing the ending changes how the terrors are read.", 1, "order"),
      node("mostly-stories", "Notice the proportions", "Narration is the method", "Only two of eight chapters argue; the rest are deaths and last words.", "Reading it for arguments alone misreads what it does.", 1, "pattern"),
      node("wrong-diagnosis", "Refuse the easy diagnosis", "Not the frequency", "Many people do remember it, and it lands on nothing.", "Ghazali states the ordinary explanation and then withdraws it.", 2, "clear"),
      node("the-occupied", "Find the real one", "An occupied heart", "The thought arrives into a heart full of appetite and takes no effect.", "This is where a remedy becomes possible.", 2, "diagnose"),
      node("the-traveller", "Take the image", "One thing in front of you", "A man about to cross a waste thinks of nothing else, and is not terrified.", "The chapter asks for that condition, not for gloom.", 2, "witness"),
    ],
  },
  {
    id: "where-is-the-time", number: "02", question: "Where is the time actually going?", title: "Measure your horizon",
    description: "Get the two causes of a long horizon, meet the most exact description of procrastination in the tradition, place yourself on a seven-rung ladder, and find out what actually produces preparation.",
    payoff: "You locate your own rung by what you have stored rather than by what you believe, and you learn why diligence never reaches the end of the list.",
    image: assetUrl("assets/system/book40-two-brothers.jpg"), imageAlt: "A doorway laid for one arrival — a single place set, a made bed — and a second identical room beyond it, unprepared and dark.", minutes: 15, color: "#bf7a35",
    nodes: [
      node("two-causes", "Separate the causes", "Ignorance and love", "Only one of them can be corrected by being shown anything.", "Long hope is a disposition, not an intellectual error.", 3, "diagnose"),
      node("aversion", "Find the engine", "What you dislike you push away", "It requires no belief that you will not die, only that you dislike the thought.", "Which is why arguing does not shift it.", 3, "forces"),
      node("the-ladder", "Follow the deferral", "Until you are older", "Then until you are old, then until this one thing is finished.", "Every example he gives is a genuine responsibility.", 4, "pattern"),
      node("ten-attach", "Name the mechanism", "Ten attach to each", "The list generates faster than it is worked through.", "So no amount of diligence reaches the end of it.", 4, "witness"),
      node("seven-rungs", "Find your rung", "By what you provisioned", "Forever, old age, a year, a season, a day, an hour, none.", "The third rung is described doing something sensible, not failing.", 5, "know"),
      node("the-brothers", "Take the two brothers", "Nearness, not concern", "Both are loved and both are certain; only the near one produces preparation.", "And the year is never reduced by the day you spent.", 6, "steady"),
    ],
  },
  {
    id: "what-happens-at-the-end", number: "03", question: "What actually happens at the end?", title: "Read the particulars",
    description: "Meet the argument that works by being small, the three things wanted at the end, and the two long chapters of particular deaths and last words that are the book's real method.",
    payoff: "You see why a book about death is built out of stories, and hear what the people with most of the world said about it.",
    image: assetUrl("assets/system/book40-last-words.jpg"), imageAlt: "A low cushion set upright against a wall in an empty room, a shallow cup beside it, late light across the floor.", minutes: 13, color: "#c25f50",
    nodes: [
      node("five-blows", "Take the small argument", "Five blows tonight", "The anticipation alone would ruin the finest evening, and this does not.", "It works because the comparison is trivial.", 7, "clear"),
      node("three-wanted", "Take the triad", "Form, tongue, heart", "Stillness, the testimony, and a good opinion of God.", "The one that matters most is the one nobody can confirm.", 8, "order"),
      node("particulars", "See the method", "Named people, named days", "A particular death cannot be held as a proposition.", "The absence of commentary is deliberate.", 9, "pattern"),
      node("why-these", "Ask why these deaths", "The ones you know best", "Attaching the proportion to people whose reality is not in doubt.", "This is Chapter 2's remedy applied rather than described.", 9, "witness"),
      node("the-powerful", "Hear the powerful first", "And they regret it", "Those with most of the world are placed first, and say it was not enough.", "The argument is left entirely to the arrangement.", 10, "diagnose"),
      node("handholds", "Keep the phrase", "Handhold after handhold", "The same structure as the ten occupations, run in reverse.", "Neither process announces itself while it happens.", 10, "steady"),
    ],
  },
  {
    id: "what-is-death", number: "04", question: "What is death, and what is the grave?", title: "Fix the definition first",
    description: "Take the ruling on visiting graves with the reason attached to it, clear away three false suppositions, and see how one deflationary line makes the grave chapters intelligible.",
    payoff: "You get the definition the whole second half of the book rests on, and the order that turns a set of terrors into a doctrine.",
    image: assetUrl("assets/system/book40-change-of-state.jpg"), imageAlt: "A sealed clay lamp and an unsealed one side by side on a stone ledge, identical in shape, one lit.", minutes: 12, color: "#586fa8",
    nodes: [
      node("the-reversal", "Take the ruling", "Forbidden, then commanded", "The permission arrives with its purpose and its condition in one sentence.", "For they remind you of the hereafter.", 11, "order"),
      node("the-restriction", "Note what he adds", "His own judgement", "Ghazali restricts women's visiting on grounds of circumstance.", "Recorded here as his, and about his time and place.", 11, "guard"),
      node("three-refused", "Clear the suppositions", "Three positions", "Annihilation, an interruption, and spirits without bodies.", "Named and refused rather than disputed at length.", 12, "clear"),
      node("only-a-change", "Take the definition", "Only a change of state", "The spirit remains after the separation, in one condition or the other.", "Deflationary on purpose, and not a claim that it is small.", 12, "know"),
      node("what-it-licenses", "See what it licenses", "The grave chapters", "All of it requires something undergone before the gathering.", "Read before the definition, it is only terror.", 13, "pattern"),
    ],
  },
  {
    id: "how-does-it-end", number: "05", question: "What can be known, and how does it end?", title: "Take the guard, then the seal",
    description: "Meet the hardest limit in the book, follow the announced order of the second half, and arrive at the last line of the Ihya — which is not the line most readers expect.",
    payoff: "You leave with a restriction that applies to favourable judgements too, and with the ending the whole forty-book work was arranged around.",
    image: assetUrl("assets/system/book40-the-seal.jpg"), imageAlt: "A pair of brass scales at rest, one pan holding a thick stack of folded papers, the other a single small card, and the card is down.", minutes: 14, color: "#a97837",
    nodes: [
      node("general-yes", "Keep the general", "Happy and wretched", "The sources establish the division, and that much is known.", "The guard does not deny what is known.", 14, "know"),
      node("particular-no", "Take the limit", "Zayd and Amr", "The state of a named person is not disclosed at all.", "It applies to favourable judgements exactly as much.", 14, "guard"),
      node("both-routes", "See both routes closed", "Faith and outward good", "Godfearing sits in the heart and is hidden from its own owner.", "These are the only two routes anyone ever has.", 14, "clear"),
      node("the-order", "Read the order", "Announced in advance", "Terrors, the Garden, the looking, and then mercy seals the book.", "Every page of terror is read by someone told the ending.", 15, "order"),
      node("the-looking", "Place the looking", "After all other bliss", "The payoff of Book 36's argument, arriving where the work ends.", "Named as the description before the final chapter.", 15, "witness"),
      node("the-nursing-woman", "Take the last line", "More merciful than she is", "One card outweighing the scrolls, and a woman nursing a child not hers.", "The claims between people are handed back, not waived.", 16, "receive"),
    ],
  },
];

export const book40Movements: TaxonomyGroup[] = [
  ["bab1", "1. The excellence of remembering death", "The testimony, and why the remembrance fails to take.", [1, 2]],
  ["bab2", "2. Long hope and short hope", "Two causes, the deferral machine, seven rungs, and what produces preparation.", [3, 4, 5, 6]],
  ["bab3", "3. The throes of death", "The argument from proportion, and the three things wanted at the end.", [7, 8]],
  ["bab4", "4. The deaths of the Messenger and the caliphs", "The longest chapter of the half, and almost entirely narrative.", [9]],
  ["bab5", "5. The speech of the dying", "Caliphs and commanders placed first, and what they said.", [10]],
  ["bab6", "6. Funerals, graves, and visiting them", "A ruling that was reversed, with its reason attached.", [11]],
  ["bab7", "7. The reality of death and the grave", "Three suppositions refused, and what the definition licenses.", [12, 13]],
  ["bab8", "8. What is known through dreams", "The guard that opens it, and how far it reaches.", [14]],
  ["shatr2", "The second half, from the trumpet", "The announced order, and the chapter that seals the work.", [15, 16]],
].map(([id, label, description, chapterIds], index) => ({ id, label, description, chapterIds, color: ["#bf7a35", "#278d91", "#c25f50", "#586fa8", "#a97837"][index % 5] })) as TaxonomyGroup[];

export const book40Instrument: Instrument = {
  title: "How far ahead have you provisioned?",
  note: "Ghazali sorts people into seven ranks of hope, and his measure is not what anyone believes about the shortness of life but how far ahead he actually stores, buys, and arranges. Answer from your cupboards and your calendar rather than from your convictions, and then say what happens when death does cross your mind.",
  items: [
    {
      id: "horizon", label: "Your actual horizon", lede: "Answer from what you have arranged, not from what you hold",
      note: "The first question is his seven-rung ladder, compressed to four. The second is the pair of causes he gives for a long horizon, together with the diagnosis from his chapter on why the remembrance of death takes no effect. Neither question has a right answer, and the third rung of the ladder is described doing something entirely sensible.",
      axes: [
        {
          id: "rung", kicker: "The seven ranks", question: "How far ahead are your arrangements actually made?",
          options: [
            { id: "indefinite", label: "Indefinitely, or as far as I can", note: "The first two rungs: hoping to remain without end, or to the furthest age witnessed." },
            { id: "year", label: "About a year", note: "The third rung. Ghazali's example provisions the year and then turns to worship." },
            { id: "season", label: "A season or a few months", note: "The fourth rung: no winter clothes stored in summer." },
            { id: "day", label: "A day, or less", note: "The fifth rung and beyond, up to those who reckon no remaining at all." },
          ],
        },
        {
          id: "response", kicker: "The causes", question: "When death does cross your mind, what happens?",
          options: [
            { id: "defer", label: "I think: after this one thing", note: "The deferral machine, and Ghazali follows it down four rungs." },
            { id: "occupied", label: "It arrives and nothing changes", note: "His own diagnosis: the thought lands on a heart occupied by appetite." },
            { id: "rarely", label: "It rarely crosses my mind at all", note: "What he explains by aversion rather than by ignorance." },
            { id: "lands", label: "It lands, and it changes the day", note: "The condition the second chapter is written to produce." },
          ],
        },
      ],
      verdicts: [
        { key: "*|defer", name: "The list is generating", role: "warning", chapterId: 4, body: "Ghazali follows this exact move down four rungs: until you are older, then until you are old, then until you finish building this house, then until you have settled this child. Every example he chooses is a real obligation, which is what makes the mechanism work.", action: "His sentence is the one to sit with: you plunge into no occupation but that ten other occupations attach themselves to its completion. That means the list does not shorten as you work through it, so the remedy is not to get through it faster. Ask instead what you were waiting to finish two years ago, and whether finishing it freed you." },
        { key: "*|occupied", name: "It is landing on an occupied heart", role: "balance", chapterId: 2, body: "This is Ghazali's own diagnosis, and he gives it by correcting the obvious one. People's heedlessness is usually blamed on how little they think about death; he says that many do think about it, and that it arrives at a heart occupied by the appetite of this world, so it takes no effect.", action: "The remedy he gives is not more frequent thought but an emptier reception, and his image is a man about to cross a perilous waste, who thinks of one thing because one thing is genuinely in front of him. Note that the traveller is not frightened — what is asked for is the occupancy, not the dread." },
        { key: "*|rarely", name: "Two causes, and only one is ignorance", role: "warning", chapterId: 3, body: "Ghazali gives two causes for a long horizon and treats them very differently. Ignorance is the tractable one, and he passes over it quickly. The other is love of the world: when parting from it weighs on the heart, the heart refuses to think about what causes the parting, and everyone pushes away what he dislikes.", action: "The useful consequence is that this will not be corrected by being told anything, including by this book. What his account asks is a smaller question than belief: not whether you accept that you will die, but what specifically you are unwilling to be parted from." },
        { key: "indefinite|lands", name: "Preparation follows nearness", role: "balance", chapterId: 6, body: "The thought lands, and your arrangements still run out indefinitely. Ghazali's two brothers explain exactly this: one expected tomorrow and one in a year, both loved and both certain, and only the near arrival produces any preparation. Conviction is held constant in his analogy and does nothing.", action: "His sharper observation is the one to take: a man expecting a year rises each morning still expecting the whole year, and does not subtract the day that has passed. A distant horizon is stable and does not become near on its own, which is why he treats shortening it as a separate act rather than as something time performs for you." },
        { key: "year|lands", name: "The third rung, and it is not a failure", role: "support", chapterId: 5, body: "The thought lands and you provision about a year ahead. Read what Ghazali says the man at this rung does: he prepares in summer for winter and in winter for summer, and when he has gathered his year's sufficiency he turns to worship. He is not described as failing at anything.", action: "The rungs are a scale and not a threshold, so the question is not how to leap to the top but what the next one down would change. Jesus's counsel that he quotes concerns tomorrow's provision rather than this year's, which is worth noticing before you dismantle anything." },
        { key: "season|lands", name: "The fourth rung", role: "support", chapterId: 5, body: "The thought lands and your arrangements reach a season. Ghazali's marker for this rung is exact and domestic: he does not store winter clothes in summer nor summer clothes in winter. It is a rank measured entirely by a cupboard.", action: "Take the concreteness as the lesson. What makes his ladder usable is that it can be checked against what you own rather than against what you feel, and it cannot be flattered. If you want to test the rung below, the measure there is a single day." },
        { key: "day|lands", name: "The fifth rung and beyond", role: "support", chapterId: 5, body: "The thought lands and you arrange for a day or less. On Ghazali's ladder that is the fifth rung, and above it lie those whose hope does not pass an hour and those who reckon no remaining at all.", action: "The counsel he attaches is the one to hold rather than any further ascent: when you rise in the morning do not speak to yourself of the evening, and when evening comes do not speak to yourself of the morning. Note also that this book's last chapter is about mercy, and that a short horizon held without it is not what the work is arranging for." },
        { key: "*|*", name: "Read the rung with the response", role: "balance", chapterId: 5, body: "A horizon, and what happens when the thought arrives. Ghazali's two chapters do different work: the ranks place you, and the causes explain why the placement holds.", action: "Take the response as the diagnosis and the rung as the measurement. The chapter that treats your response is where the work is, and the ladder is there to be checked against your arrangements rather than against your convictions." },
      ],
    },
  ],
};

export const book40Sources: SourceLink[] = [
  { label: "Primary Arabic text", note: "The complete public Arabic of Book 40 was read and used to establish its two-part structure, the analysis of long hope, the definition of death, the guard on particular judgement, and the ordering of the second half.", url: "https://shamela.ws/book/9472/1607" },
  { label: "The way to realise the remembrance", note: "The passage correcting the ordinary diagnosis and locating the failure in a heart occupied by appetite, with the image of the traveller into a perilous waste.", url: "https://shamela.ws/book/9472/1610" },
  { label: "The cause of long hope", note: "The passage naming ignorance and love of the world as its two causes, and following the deferral through its rungs to the ten occupations that attach to each.", url: "https://shamela.ws/book/9472/1615" },
  { label: "The ranks of hope", note: "The passage sorting people into seven ranks measured by how far ahead they provision, which the diagnostic in this edition follows.", url: "https://shamela.ws/book/9472/1617" },
  { label: "Hastening to act", note: "The passage giving the analogy of the two expected brothers and the observation that a year's horizon is not reduced by the day that has passed.", url: "https://shamela.ws/book/9472/1618" },
  { label: "The reality of death", note: "The passage refusing three suppositions about death and defining it as only a change of state, with the spirit remaining after separation.", url: "https://shamela.ws/book/9472/1652" },
  { label: "What can be known of a particular person", note: "The passage opening the chapter on dreams, closing both routes to judging the state of any named person.", url: "https://shamela.ws/book/9472/1663" },
  { label: "The second half", note: "The passage listing the contents of the second half in order and stating that a chapter on the breadth of God's mercy seals the book.", url: "https://shamela.ws/book/9472/1670" },
  { label: "Forty-book structure", note: "Ghazali.org's listing places Book 40 as the tenth and last book of the Quarter of Deliverance and confirms its title.", url: "https://www.ghazali.org/listing-the-forty-books/" },
];

export const book40: SystemBook = {
  id: 40,
  title: "Remembrance of Death and the Afterlife",
  shortTitle: "Death and What Follows",
  defaultJourneyId: "why-nothing-changes",
  chapters: book40Chapters,
  conceptNodes: book40ConceptNodes,
  journeys: book40Journeys,
  sources: book40Sources,
  taxonomy: {
    title: "Eight chapters and a second half",
    note: "Ghazali's own division. The first half runs to the blast of the trumpet in eight chapters, and the second surveys what follows it. Only two of the eight chapters are analytic; the rest are accounts of particular deaths, the words of the dying, sayings at graves, and dreams, and that proportion is a claim about how this subject is learned.",
    groups: book40Movements,
  },
  instrument: book40Instrument,
  editorialNote: "The five journeys, sixteen reading sections, visual models, and diagnostic are editorial learning aids. The sections follow Ghazali's own eight chapters and his second half, in his order. The English is an original synthesis made from a reading of the public Arabic text, not a translation and not a substitute for one. Reports and inherited anecdotes are presented as material Ghazali transmitted; this prototype does not independently grade every narration, and Book 40 carries a great many narrations whose graders' notes appear in the Arabic alongside them. Two editorial decisions should be stated plainly. First, this is by a wide margin the longest book in the Ihya, and the majority of it is narrative rather than argument: the deaths of the Messenger and the caliphs, the words of the dying, the sayings at graves, the dreams, and the entire second half surveying the Day, the Fire, and the Garden. Sections 9, 13, and 15 describe those chapters, their method, and what they depend on, rather than reproducing them, and a reader who wants that material should go to the text — it is the substance of the book and not an appendix to it. Second, the eschatological descriptions are presented here through their structure and the significance of their order rather than rendered in detail; the order is load-bearing, since Ghazali announces at the head of the second half that a chapter on the breadth of God's mercy seals the work. His restriction on women visiting graves is recorded in Section 11 as his own judgement, with the grounds he gives, which concern the circumstances of his time and place. The guard in Section 14 governs the whole book: Ghazali states that the state of any particular person who has died is not disclosed at all, and that both available routes to such a judgement are closed, and nothing here or in the reports it carries should be applied to any named person. The diagnostic applies his seven ranks and his two causes to answers the reader supplies about his own arrangements and cannot pronounce on anyone's state.",
};
