/** Add standalone companions here; the Ihya's forty books remain one collection. */
export const companionBooks = [
  {
    id: 'beautiful-names',
    title: 'The Beautiful Names',
    author: 'A companion to al-Ghazali',
    description: 'Know Allah through His Names: 99 illustrated readings, connected paths, and a personal reading room.',
    path: 'beautiful-names/',
    coverLabel: 'Beautiful Names',
    coverStyle: 'names',
    coverImage: 'assets/beautiful-names/art/cover-day.webp',
    coverNightImage: 'assets/beautiful-names/art/cover-night.webp',
    coverSubtitle: 'A garden for knowing Him',
  },
  {
    id: 'inner-dimensions',
    title: 'Inner Dimensions of the Prayer',
    author: 'Ibn al-Qayyim',
    description: 'An illustrated reading companion to the inward life of prayer.',
    path: 'inner-dimensions-of-the-prayer.html',
    coverLabel: 'Prayer',
    coverStyle: 'companion',
    coverSubtitle: 'Inner dimensions',
  },
  {
    id: 'timeless-seeds',
    title: 'Timeless Seeds of Advice',
    author: 'B. B. Abdulla',
    description: 'A hopeful collection of 111 readings, six gentle paths, and space for reflection.',
    path: 'timeless-seeds.html',
    coverLabel: 'Timeless Seeds',
    coverStyle: 'seeds',
    coverImage: 'assets/timeless-seeds/coastal/coastal-home-480.webp',
    coverNightImage: 'assets/timeless-seeds/coastal/starlight/coastal-home-480.webp',
    coverSubtitle: 'Small seeds. Lasting hope.',
  },
];
