import { assetUrl } from "./assetUrl";
import type { Chapter, ConceptNode, DeepReading, VisualModel } from "./data";
import type { Journey, ProcessStage, SourceLink, SystemBook } from "./systemTypes";

type ChapterDraft = Omit<Chapter, "deep" | "visualModel"> & {
  thesis: string;
  context: string;
  moves: Array<{ title: string; body: string }>;
  closeReading: Array<{ title: string; body: string }>;
  distinction: DeepReading["distinction"];
  misreading: string;
  selfAudit: string[];
  sourceAnchor: string;
  model: VisualModel;
};

const chapter = (draft: ChapterDraft): Chapter => ({
  id: draft.id,
  shortTitle: draft.shortTitle,
  formalTitle: draft.formalTitle,
  overview: draft.overview,
  points: draft.points,
  reflection: draft.reflection,
  relatedNodes: draft.relatedNodes,
  visualModel: draft.model,
  deep: {
    thesis: draft.thesis,
    context: draft.context,
    moves: draft.moves,
    closeReading: draft.closeReading,
    distinction: draft.distinction,
    misreading: draft.misreading,
    observation: draft.reflection,
    selfAudit: draft.selfAudit,
    sourceAnchor: draft.sourceAnchor,
  },
});

export const book25Chapters: Chapter[] = [
  chapter({
    id: 1,
    shortTitle: "The fire and what follows it",
    formalTitle: "Opening discourse and the condemnation of anger",
    overview: "Ghazali opens with anger as a concealed fire that can be stirred into motion, especially by buried pride. He does not stop at the angry moment. He announces a sequence in which anger produces rancour and rancour produces envy, making the book an account of how one ungoverned state leaves another behind.",
    points: ["The danger lies in being carried beyond truth and right action.", "Anger is presented as the root from which rancour and envy can grow.", "Strength is recast as mastery of the self when anger is present."],
    reflection: "Recall one recent angry episode. Do not begin with what the other person did. Begin with the first inner movement you can honestly identify and then trace what remained after the event ended.",
    relatedNodes: ["anger", "pride", "mastery", "residue"],
    thesis: "Anger becomes spiritually destructive when its heat governs the person and continues after the incident as a new interior disposition.",
    context: "The opening praise, warning, and reports establish the book's urgency. Ghazali then gives his own roadmap: blame of anger, its nature, training, causes, immediate treatment, restraint, forbearance, lawful response, rancour, pardon, gentleness, envy, and cure.",
    moves: [
      { title: "Begin beneath the surface", body: "The image of embers beneath ash locates danger before visible explosion. A person may appear calm while pride and readiness for retaliation remain available." },
      { title: "Watch what awakens it", body: "Ghazali links the hidden fire to pride. Frustration does not enter an empty interior; it meets a view of what the self deserves and what others must yield." },
      { title: "Refuse borrowed strength", body: "The reports gathered here deny that overpowering another person is the decisive form of strength. The harder strength is remaining governed at the point of anger." },
      { title: "Follow the remainder", body: "The event is not over when the voice lowers. Anger can settle inwardly as aversion, rancour, pleasure at harm, and grief at another person's good." },
      { title: "Learn the whole pathway", body: "The announced order matters because treatment at the first spark differs from treatment after resentment has hardened or envy has attached itself to another person's blessing." },
    ],
    closeReading: [
      { title: "Why fire is an exact image", body: "Fire moves, spreads, consumes, and obscures. Ghazali uses the image to explain loss of settled judgment, not to claim that every experience of anger has the same moral status." },
      { title: "Why the book joins three vices", body: "Anger seeks an immediate answer. When that answer is withheld without inward release, the demand can remain as rancour. Rancour can then make the other person's good painful to witness." },
    ],
    distinction: { title: "Feeling heat is not the same as obeying it", firstLabel: "Anger occurs", first: "A protective force is stirred by obstruction or injury and becomes present to awareness.", secondLabel: "Anger rules", second: "Speech, action, judgment, or lasting hostility now takes its direction from the demand to retaliate." },
    misreading: "Do not read the opening as proof that every flash of anger makes a person vicious. The rest of the book carefully distinguishes the created power, its degrees, its governance, and its aftereffects.",
    selfAudit: ["What claim about my own importance was threatened?", "What did the anger ask me to say or do?", "What residue did I permit to remain after the incident?"],
    sourceAnchor: "Book 25, opening discourse and section on the condemnation of anger.",
    model: { kind: "chain", title: "The concealed fire becomes a moral sequence", items: [
      { label: "Hidden ember", body: "A readiness rooted in pride or attachment can remain quiet before any incident occurs.", role: "support" },
      { label: "Anger", body: "Obstruction or injury stirs heat and a demand to repel or retaliate.", role: "warning" },
      { label: "Rancour", body: "Unreleased hostility settles into durable aversion after the visible heat falls.", role: "warning" },
      { label: "Envy", body: "The other person's good itself becomes painful, and its removal becomes desirable.", role: "warning" },
    ], caption: "This causal reading follows Ghazali's explicit statement that rancour is a fruit of anger and envy can be a fruit of rancour." },
  }),
  chapter({
    id: 2,
    shortTitle: "A power with three conditions",
    formalTitle: "The nature of anger and its deficiency, excess, and mean",
    overview: "Anger is created as a protective power that can repel injury. Ghazali therefore rejects both its disappearance and its domination. He describes deficiency, excess, and an ordered mean in which anger waits for the direction of reason and religion, rising where protective force is due and subsiding where forbearance is better.",
    points: ["Deficient anger can abandon rightful protection and moral courage.", "Excessive anger blinds judgment and disorders body, speech, limbs, and heart.", "The mean is not weak feeling but force governed by sound direction."],
    reflection: "When you think of being calm, ask whether you mean governed strength or merely avoidance. When you think of being strong, ask whether judgment still has the power to stop you.",
    relatedNodes: ["protection", "measure", "reason", "body"],
    thesis: "The aim of training is not emotional numbness but a protective power made obedient to reason and religion.",
    context: "Ghazali explains anger through its protective function and a bodily account of rising heat. He then maps three degrees and traces the visible and inward consequences of excess, as well as the moral failures produced by deficiency.",
    moves: [
      { title: "Start with function", body: "Living creatures need a power that resists external harm. Anger is first placed within this protective economy rather than treated as a foreign substance in the human being." },
      { title: "See the demand for retaliation", body: "When stirred, the power seeks to repel harm before it occurs and to retaliate after it occurs. Retaliation becomes its immediate appetite." },
      { title: "Name deficiency", body: "A person can lack necessary protective force, accept humiliation where resistance is due, or fail to oppose what should be opposed." },
      { title: "Name excess", body: "When anger leaves the rule of reason and religion, counsel is obscured. Ghazali traces the disorder through appearance, language, bodily action, and the hostile states of the heart." },
      { title: "Locate the mean", body: "Governed anger responds to the right signal. It is capable of firmness without becoming autonomous, and capable of subsiding without collapsing into cowardice." },
    ],
    closeReading: [
      { title: "The body is evidence, not destiny", body: "Redness, pallor, trembling, and agitation reveal that anger is embodied. They help the person recognize a state whose judgment should not be treated as neutral." },
      { title: "The middle is directional", body: "The mean cannot be reduced to a moderate amount of heat. Its defining feature is obedience: the force rises and falls according to a rule beyond its own appetite." },
    ],
    distinction: { title: "Gentleness and weakness are not identical", firstLabel: "Governed gentleness", first: "The person can act firmly but chooses proportion because judgment sees it as better.", secondLabel: "Deficient force", second: "The person cannot protect a right or oppose wrong because courage and protective concern have collapsed." },
    misreading: "Do not convert Ghazali's mean into a modern instruction to suppress all anger. He explicitly criticizes both the loss of protective force and its excess.",
    selfAudit: ["Can I act firmly without needing to humiliate?", "At what bodily sign does my judgment usually narrow?", "Where have I renamed avoidance as patience?"],
    sourceAnchor: "Book 25, section on the nature of anger and its three degrees.",
    model: { kind: "spectrum", title: "The power of anger under three conditions", items: [
      { label: "Deficiency", body: "Protective force is too weak to defend what reason and religion require.", role: "warning" },
      { label: "Governed mean", body: "Anger serves judgment, rising for a right and subsiding where restraint is sound.", role: "balance" },
      { label: "Excess", body: "The force becomes ruler, clouds counsel, and seeks retaliation as though it were the final good.", role: "warning" },
    ], caption: "The mean is a relationship of governance, not simply the midpoint of a mood scale." },
  }),
  chapter({
    id: 3,
    shortTitle: "Can anger be uprooted?",
    formalTitle: "Whether the root of anger can be removed through discipline",
    overview: "Ghazali argues that the created root of anger cannot and should not be erased, because it serves necessary protection. What discipline can change is its intensity, its objects, and its obedience. He also describes rare moments of absorption in a greater concern, while refusing to make such passing states the ordinary standard.",
    points: ["Necessary protective anger remains part of human nature.", "Training can weaken avoidable causes and prevent anger from carrying action beyond truth.", "Complete nonreaction is not set as the ordinary human requirement."],
    reflection: "Replace the question 'How do I never feel this?' with 'What would it mean for this power to wait for sound judgment before it moves me?'",
    relatedNodes: ["training", "measure", "worldly-claims", "mastery"],
    thesis: "Discipline reforms anger by changing what feeds it and who commands it, not by attempting to remove every protective movement from the human being.",
    context: "This section answers an objection raised by the prior threefold model. If anger has necessary and excessive forms, is total eradication possible or desirable? Ghazali's answer preserves human nature while making demanding reform possible.",
    moves: [
      { title: "Reject impossible eradication", body: "The source of anger belongs to created human equipment. A program built on abolishing the root mistakes the kind of change discipline can normally achieve." },
      { title: "Preserve necessary protection", body: "The person still needs force where life, religion, responsibility, or those under one's protection are threatened." },
      { title: "Weaken optional attachments", body: "Many angry episodes arise around comforts, status, surplus possessions, and expectations that can be reduced. Fewer rigid claims mean fewer ignition points." },
      { title: "Change the action channel", body: "Even when anger occurs, it need not make speech or action depart from truth. The person can remain responsible for what the force is permitted to command." },
      { title: "Do not absolutize rare states", body: "Absorption in a greater concern may make an insult or loss scarcely felt, but Ghazali describes such dominance as intermittent rather than a constant human baseline." },
    ],
    closeReading: [
      { title: "Training works upstream", body: "The deepest reform is not an emergency technique. It loosens the self's attachment to advantages whose interruption repeatedly produces anger." },
      { title: "Control is more than concealment", body: "A quiet face can hide a heart rehearsing injury. Governance reaches intention, judgment, and residue, not only public behaviour." },
    ],
    distinction: { title: "Eradication differs from subordination", firstLabel: "Eradication", first: "The protective root would disappear, leaving no force to rise even when firmness is required.", secondLabel: "Subordination", second: "The force remains but receives its objects, limits, and permission to act from reason and religion." },
    misreading: "Do not use the impossibility of uprooting anger as permission to leave temperament unchanged. Ghazali immediately turns toward reducing its materials, retraining its habits, and stopping its commands.",
    selfAudit: ["Which nonessential advantage has become emotionally nonnegotiable?", "Does my calm continue inwardly after the scene ends?", "What can anger no longer make me do?"],
    sourceAnchor: "Book 25, section on whether anger's root can be removed by discipline.",
    model: { kind: "pair", title: "What discipline can and cannot remove", items: [
      { label: "Created capacity remains", body: "Protective force is part of human equipment and can still answer a rightful need.", role: "support" },
      { label: "Rule and fuel can change", body: "Attachments, habits, intensity, action, and lasting residue can all be brought under training.", role: "balance" },
    ], caption: "The aim is a transformed relationship to anger, not a claim never to experience its first movement." },
  }),
  chapter({
    id: 4,
    shortTitle: "What feeds the flame",
    formalTitle: "The causes that inflame anger",
    overview: "Ghazali names pride, self-admiration, boasting, rivalry, mockery, fault-finding, disputation, opposition, betrayal, and intense greed for surplus wealth or status among the materials that inflame anger. He treats cure as removal by opposites rather than waiting for the next crisis.",
    points: ["Anger has recurring materials, not only isolated triggers.", "Many causes are forms of self-importance and competition.", "Each cause is weakened through an opposing trait and a revised understanding of strength."],
    reflection: "Choose the repeated cause beneath three recent episodes, not the three surface incidents. What opposite trait would reduce the shared material?",
    relatedNodes: ["pride", "competition", "fuel", "training"],
    thesis: "Lasting treatment identifies the character trait that makes many different incidents combustible and trains its opposite.",
    context: "Having shown that anger can be governed, Ghazali moves upstream. The list of causes is not a personality inventory. It explains why repeated anger often survives changes of place and circumstance.",
    moves: [
      { title: "Look below the incident", body: "The immediate event may vary, yet the same pride, hunger for status, argumentative habit, or demand for advantage can be present each time." },
      { title: "Group the fuels", body: "Some causes magnify the self, some turn social life into contest, some normalize humiliation, and some make surplus possessions or rank feel necessary." },
      { title: "Treat by opposites", body: "Pride is answered with humility, self-admiration with knowledge of the self, boastfulness with a truer account of shared human origin and real excellence." },
      { title: "Revise the model of courage", body: "A culture can praise quick retaliation as manliness. Ghazali opposes this learned admiration with examples of restraint, pardon, and mastery." },
      { title: "Reduce exposure and rehearsal", body: "Habits are strengthened by company, stories, and repeated self-description. Reform includes changing what the person celebrates and practices before anger comes." },
    ],
    closeReading: [
      { title: "A cause is not an excuse", body: "Naming pride or competition does not remove responsibility. It identifies the material that must be worked on if the cycle is to become less likely." },
      { title: "The list is relational", body: "Mockery, disputation, betrayal, and status rivalry show that anger is shaped in social patterns. The cure therefore involves manners of company as well as private reflection." },
    ],
    distinction: { title: "Trigger management is not character treatment", firstLabel: "Managing triggers", first: "The person avoids or delays a particular situation so that immediate harm is less likely.", secondLabel: "Removing material", second: "The underlying pride, rivalry, greed, or habit that makes many situations ignite is trained through its opposite." },
    misreading: "Do not assume that another person's betrayal or mockery becomes morally irrelevant. Ghazali's focus here is the part of the anger cycle the reader can reform in the self.",
    selfAudit: ["Which fuel appears across otherwise unrelated conflicts?", "What kind of anger does my social environment praise?", "Which opposite trait can I practice before the next incident?"],
    sourceAnchor: "Book 25, section on the causes that inflame anger.",
    model: { kind: "chain", title: "From repeated fuel to a trained opposite", items: [
      { label: "Recurring fuel", body: "Pride, rivalry, mockery, argument, betrayal, or greed gives many incidents the same inner material.", role: "warning" },
      { label: "Small obstruction", body: "A present event touches the established claim and becomes larger than its outward size.", role: "support" },
      { label: "Rapid ignition", body: "The practised interpretation makes retaliatory heat feel immediate and justified.", role: "warning" },
      { label: "Opposite training", body: "Humility, self-knowledge, restraint, and reduced attachment gradually remove combustible material.", role: "balance" },
    ], caption: "Emergency restraint prevents damage. Opposite training changes why the same class of event keeps becoming an emergency." },
  }),
  chapter({
    id: 5,
    shortTitle: "When anger has already risen",
    formalTitle: "Treatment of anger after it has been aroused",
    overview: "Once anger has risen, Ghazali prescribes a compound of knowledge and action. Reflection interrupts the imagined right to retaliate, while bodily and verbal practices prevent the force from obtaining its usual outlet. The treatment is deliberately redundant because heated judgment is unreliable.",
    points: ["Six reflections challenge the story anger tells about power, desert, and consequence.", "Action includes seeking refuge in God, silence, lowering the body, and cooling with water.", "The immediate task is to prevent anger from converting its demand into harmful action."],
    reflection: "Build a short emergency sequence while calm. Make each step observable enough that you can perform it before you agree with the story anger is telling.",
    relatedNodes: ["interruption", "knowledge", "body", "silence"],
    thesis: "At the peak of anger, the person needs both a corrected interpretation and a bodily interruption strong enough to keep the demand for retaliation from becoming action.",
    context: "This section explicitly distinguishes prevention from crisis treatment. Ghazali calls the latter a compound of knowledge and action, then supplies multiple cognitive and practical routes rather than relying on a single insight.",
    moves: [
      { title: "Remember the worth of restraint", body: "Reflection on the merit of restraint, pardon, forbearance, and patient endurance gives desire a better object than the immediate sweetness of retaliation." },
      { title: "Place power under greater power", body: "The person remembers divine power and accountability rather than treating temporary power over another person as a private license." },
      { title: "Calculate worldly consequence", body: "Even a person moved weakly by the hereafter can recognize that retaliation creates counter-retaliation, enduring hostility, and new vulnerability." },
      { title: "Break self-exemption", body: "One reflection asks why the angry person expects another to bear what they themselves would not bear, exposing a double standard beneath the demand." },
      { title: "Interrupt through action", body: "Seeking refuge, becoming silent, lowering posture, and using water change the scene and deny anger the speech, height, speed, and heat through which it usually advances." },
    ],
    closeReading: [
      { title: "Why there are several reflections", body: "A heated person may not be reached by the same reason every time. Reward, accountability, consequence, humility, and recognition of human weakness provide several handles on one state." },
      { title: "Why posture matters", body: "The remedy does not pretend judgment is disembodied. Lowering the body is a concrete refusal of the upward, forward motion by which anger prepares to dominate." },
    ],
    distinction: { title: "Cooling the state does not decide the dispute", firstLabel: "Immediate treatment", first: "Prevent speech and action while judgment is narrowed and retaliation feels self-authorizing.", secondLabel: "Later judgment", second: "After the state cools, determine truth, boundaries, repair, or proportionate response with clearer counsel." },
    misreading: "Do not use silence and cooling as a command to bury harm or abandon justice. They protect the later decision from being made by the appetite for retaliation.",
    selfAudit: ["Which intervention can I perform before speaking?", "What false permission does anger usually give me?", "Who can safely help me delay a decision made under heat?"],
    sourceAnchor: "Book 25, section on treating anger after its arousal through knowledge and action.",
    model: { kind: "chain", title: "A crisis sequence that protects judgment", items: [
      { label: "Recognize heat", body: "Treat bodily and verbal acceleration as evidence that judgment needs protection.", role: "support" },
      { label: "Stop the outlet", body: "Silence and delay keep the force from feeding itself through speech and action.", role: "balance" },
      { label: "Lower and cool", body: "Change posture and use water to interrupt the embodied momentum of the state.", role: "balance" },
      { label: "Reframe power", body: "Remember accountability, consequence, shared weakness, and the worth of restraint.", role: "balance" },
      { label: "Judge later", body: "Return to the actual wrong only after the demand for retaliation no longer controls the verdict.", role: "support" },
    ], caption: "The sequence is synthesized from Ghazali's compound of knowledge and action. It is a bridge to sound judgment, not a verdict on the original dispute." },
  }),
  chapter({
    id: 6,
    shortTitle: "Restraint becomes forbearance",
    formalTitle: "The virtue of restraining anger and the virtue of forbearance",
    overview: "Restraining anger means holding back a force that has already risen. Forbearance is a more settled condition in which the force is less easily stirred and less difficult to govern. Ghazali ranks forbearance above episodic restraint while explaining that it is acquired through repeated acts of restraint.",
    points: ["Restraint is morally valuable precisely when retaliation remains possible.", "Forbearance is not passivity but the settled rule of reason over anger.", "Repeated, effortful restraint can become an easier disposition."],
    reflection: "Do not judge a hard act of restraint as fake merely because it required effort. Ask what kind of person repeated effort is training you to become.",
    relatedNodes: ["restraint", "forbearance", "habit", "mastery"],
    thesis: "The difficult act of restraining anger is the training ground from which a stable disposition of forbearance can grow.",
    context: "Ghazali first gathers praise of restraining anger, then explains why forbearance is more complete. The relation between them is developmental: one practises the act before possessing the effortless trait.",
    moves: [
      { title: "Preserve real capacity", body: "Restraint has its fullest meaning where the person could retaliate. Inability alone does not reveal the same inward mastery." },
      { title: "Choose the higher object", body: "The person relinquishes the immediate satisfaction of anger in hope of divine approval, safety, and a sounder condition of heart." },
      { title: "Repeat against habit", body: "At first, forbearance is practised with effort. The old route remains easier, so the person deliberately chooses another response." },
      { title: "Let repetition reshape readiness", body: "Repeated restraint weakens automatic ignition and makes calm response less costly. What began as effort becomes more like character." },
      { title: "Recognize mature mastery", body: "Forbearance signals the predominance of reason and the submission of anger, not the absence of strength or the inability to answer." },
    ],
    closeReading: [
      { title: "Effort is not hypocrisy", body: "Ghazali's account of acquiring forbearance depends on acting better than one's present ease. Sincerity does not require virtue to feel effortless at the beginning." },
      { title: "Capacity changes the meaning", body: "Not retaliating because one is unable and not retaliating while able may look similar from outside. The interior relation to power differs." },
    ],
    distinction: { title: "Restraint is an act; forbearance is a formed readiness", firstLabel: "Restraining anger", first: "Heat rises and the person must exert effort to prevent it from commanding action.", secondLabel: "Forbearance", second: "The person has become less readily provoked and can govern the force with greater ease and steadiness." },
    misreading: "Do not treat forbearance as a temperament some people simply possess. Ghazali presents deliberate practice as the route by which it is acquired.",
    selfAudit: ["Where is restraint still costly but possible?", "Am I unable to retaliate or freely choosing not to?", "What repeated response is becoming easier in me?"],
    sourceAnchor: "Book 25, sections on the virtue of restraining anger and the virtue of forbearance.",
    model: { kind: "chain", title: "How an effort becomes a disposition", items: [
      { label: "Heat rises", body: "The old reaction is present and asks to be carried out.",role:"warning" },
      { label: "Restraint", body: "The person withholds tongue and hand despite the felt possibility of retaliation.", role: "balance" },
      { label: "Repetition", body: "The better action is practised across incidents instead of remaining an exceptional success.", role: "support" },
      { label: "Forbearance", body: "Reason's rule becomes more stable and anger less easily acquires command.", role: "balance" },
    ], caption: "The line from restraint to forbearance is Ghazali's account of moral formation through repeated practice." },
  }),
  chapter({
    id: 7,
    shortTitle: "The narrow right of reply",
    formalTitle: "The permitted measure of verbal retaliation and self-redress",
    overview: "A wrong does not make every matching wrong permissible. Ghazali narrows verbal self-redress through truth, proportion, and the legal limits of response, while repeatedly presenting silence and pardon as safer and better. He also warns that a person who punishes while personally angry can confuse justice with private revenge.",
    points: ["Wrongdoing cannot generally be answered through another prohibited act.", "Any permitted reply remains bounded by truth and proportion.", "Personal anger is a reason to delay punishment or authoritative action."],
    reflection: "Before replying to injury, write the smallest truthful sentence that protects the right. Remove every phrase whose only work is to make the other person feel smaller.",
    relatedNodes: ["justice", "proportion", "speech", "pardon"],
    thesis: "Being wronged establishes a claim to justice, not a general license for the angry self to choose the form and measure of retaliation.",
    context: "This section follows praise of restraint and forbearance with a practical legal and moral boundary. Ghazali distinguishes authorized redress from copying another person's sin and illustrates the danger of acting while private anger is active.",
    moves: [
      { title: "Refuse moral symmetry", body: "Backbiting does not become permissible because one was backbitten, nor spying because one was spied upon. The other person's wrong does not redesign the moral rule." },
      { title: "Keep speech truthful", body: "Even views that permit a limited reply do not permit fabrication, hidden accusation, or expansion beyond what is known." },
      { title: "Limit the measure", body: "A response that begins as self-redress can continue into insult and surplus injury. Proportion marks where the claim ends." },
      { title: "Prefer release where possible", body: "Ghazali repeatedly places silence, restraint, and pardon above taking the full measure one might claim." },
      { title: "Delay authority under private anger", body: "The examples of rulers who stopped when personally provoked show a further safeguard: power should not execute a public duty through a private appetite." },
    ],
    closeReading: [
      { title: "Justice needs a stopping rule", body: "Without a defined end, injury can justify an endless series of increasingly distant reprisals. Truth and proportion tell the response when its work is complete." },
      { title: "Anger contaminates mixed motives", body: "A necessary sanction can become personally gratifying. Delay makes room to distinguish the public or moral reason from the wish to settle one's own heat." },
    ],
    distinction: { title: "A right to respond is not a right to become like the wrong", firstLabel: "Bounded redress", first: "Truthful, proportionate action protects or restores a right and stops when that work is complete.", secondLabel: "Retaliatory likeness", second: "The injured person adopts the same prohibited means, adds humiliation, or uses justice as cover for personal gratification." },
    misreading: "Do not tell an injured person that pardon is the only possible response. The section preserves bounded redress while arguing that anger cannot set its terms.",
    selfAudit: ["What exact right needs protection or restoration?", "Which part of my proposed reply serves only humiliation?", "Would I choose the same measure after my anger cooled?"],
    sourceAnchor: "Book 25, section on the permitted measure of verbal retaliation and self-redress.",
    model: { kind: "chain", title: "A claim passes through three limits", items: [
      { label: "Real injury", body: "A wrong has occurred and may require protection, remedy, or answer.", role: "support" },
      { label: "Truth", body: "The response may not invent, distort, or copy a forbidden means.", role: "balance" },
      { label: "Proportion", body: "Only the measure needed for the right survives the gate.", role: "balance" },
      { label: "Pardon or redress", body: "The person can release the claim or pursue its bounded form without surplus revenge.", role: "balance" },
    ], caption: "The model preserves both paths Ghazali discusses while denying anger authority to define either one." },
  }),
  chapter({
    id: 8,
    shortTitle: "When anger becomes rancour",
    formalTitle: "The meaning of rancour and its eight consequences",
    overview: "When anger cannot or does not obtain immediate retaliation, it can turn inward and remain. Ghazali defines rancour as lasting aversion, heaviness, and dislike toward another person. He then lists eight consequences, ranging from envy and delight at misfortune to estrangement, unlawful speech, mockery, bodily harm, and withholding rights.",
    points: ["Rancour is enduring hostility, not simply the memory of being harmed.", "Its fruits move from inward pleasure at harm to outward violations of relationship and rights.", "Avoiding the eight forbidden outcomes is a minimum, not the highest condition of the heart."],
    reflection: "Think of a person whose name changes your inner state. Which ordinary goods have you quietly withdrawn, even if you have committed none of the most visible eight harms?",
    relatedNodes: ["residue", "rancour", "rights", "relationship"],
    thesis: "Rancour is anger preserved as a relationship to a person, and it reveals itself through what their good, pain, presence, and rights now mean to the heart.",
    context: "This is the book's central state transition. Ghazali explains how blocked retaliation can be stored rather than resolved, then maps the increasingly outward forms through which stored hostility reorganizes conduct.",
    moves: [
      { title: "See the inward storage", body: "The visible episode cools, but the demand for retaliation returns to the heart and becomes settled dislike, heaviness, and avoidance." },
      { title: "Notice envy and gloating", body: "The first fruits change how the person receives another's fortune: blessing becomes painful, while misfortune becomes satisfying." },
      { title: "Watch relation contract", body: "Estrangement, refusal to meet, and dismissive turning away make rancour into a new social arrangement." },
      { title: "Watch injury become active", body: "Unlawful speech, exposure, mockery, bodily injury, and violation of rights externalize what has been rehearsed within." },
      { title: "Do not confuse minimum with health", body: "A person may avoid the eight prohibited fruits yet still withhold warmth, help, prayer, praise, and voluntary good. Ghazali describes this as a real loss of excellence." },
    ],
    closeReading: [
      { title: "Rancour edits perception", body: "The person is no longer seen freshly. Their acts and blessings arrive through a settled judgment that has already assigned emotional weight." },
      { title: "The quiet losses matter", body: "Not every consequence is an attack. Some are absences: the greeting withheld, the help no longer offered, and the prayer the person no longer receives." },
    ],
    distinction: { title: "A boundary can remain without a heart committed to hostility", firstLabel: "Protective boundary", first: "Contact or trust is limited for a real reason while rights, truth, and the wish for good remain intact.", secondLabel: "Rancorous withdrawal", second: "The person's pain feels welcome, their good feels offensive, and ordinary goodness is withheld to preserve hostility." },
    misreading: "Do not use the critique of rancour to require unsafe closeness or restored trust without evidence. Ghazali's target is the inward commitment to hostility and its unjust fruits.",
    selfAudit: ["Does this person's good still feel like a loss to me?", "Which right or voluntary kindness has resentment made harder?", "Can I maintain a necessary boundary without rehearsing their harm?"],
    sourceAnchor: "Book 25, section on the meaning of rancour and its eight consequences.",
    model: { kind: "chain", title: "How heat hardens into a relationship", items: [
      { label: "Anger blocked", body: "Immediate retaliation does not occur, but the inward demand has not been released.", role: "support" },
      { label: "Stored aversion", body: "Dislike becomes durable and attaches to the person beyond the original event.", role: "warning" },
      { label: "Changed perception", body: "Their blessing pains, their misfortune pleases, and their presence feels heavy.", role: "warning" },
      { label: "Eight fruits", body: "Hostility moves toward estrangement, unlawful speech, mockery, injury, and withheld rights.", role: "warning" },
    ], caption: "The chain follows Ghazali's definition of rancour as anger retained inwardly and his ordered list of its consequences." },
  }),
  chapter({
    id: 9,
    shortTitle: "Pardon, beneficence, and gentleness",
    formalTitle: "The virtues of pardon, beneficence, and gentleness",
    overview: "Ghazali does not treat freedom from rancour as empty neutrality. He gathers praise of pardon and then moves beyond pardon to beneficence. He also presents gentleness as the fruit of good character and governed appetite and anger, while acknowledging that force has rare and properly judged uses.",
    points: ["Pardon releases a claim rather than pretending no wrong occurred.", "Beneficence can answer injury with voluntary good and break the relation rancour tried to create.", "Gentleness is the default where judgment is uncertain because it succeeds in most situations."],
    reflection: "Ask what freedom from this grievance would positively look like. Is there a truthful form of pardon, prayer, fair speech, or good action that does not deny the boundary you still need?",
    relatedNodes: ["pardon", "gentleness", "beneficence", "measure"],
    thesis: "The cure for retained hostility is not merely to stop injuring but to recover the capacity for pardon, voluntary good, and gentleness under disciplined judgment.",
    context: "The long rancour section includes extensive material on pardon, beneficence, and gentleness. These virtues are not identical: one releases a claim, another adds good, and the third governs the manner by which aims are pursued.",
    moves: [
      { title: "Begin with a real claim", body: "Pardon only has meaning where the person could pursue or retain a claim. It is release, not a declaration that the injury was unreal." },
      { title: "Move beyond non-retaliation", body: "Beneficence adds a voluntary good where rancour would prefer deprivation. It reverses the direction of the relationship rather than merely stopping harm." },
      { title: "Recover a humane manner", body: "Gentleness emerges when anger and appetite are kept within measure. It preserves steadiness, thought, and the other person's humanity." },
      { title: "Keep moral discernment", body: "Ghazali does not say force is never needed. The complete person recognizes the rare place of firmness and gives each situation its due." },
      { title: "Default wisely under uncertainty", body: "When a person lacks full discernment, Ghazali recommends leaning toward gentleness because success accompanies it in most affairs." },
    ],
    closeReading: [
      { title: "Pardon and reconciliation differ", body: "One may release personal retaliation without restoring access, trust, or the prior relationship. The virtue does not erase prudence." },
      { title: "Gentleness is a method of power", body: "It is not the absence of an aim. It pursues the aim without the haste and roughness that anger or greed introduce into judgment." },
    ],
    distinction: { title: "Pardon does not require denial", firstLabel: "Release with truth", first: "The wrong is named, protection remains possible, and the personal demand for retaliation is relinquished.", secondLabel: "False peace", second: "The wrong is minimized, safety is abandoned, or the injured person is pressured to restore trust before grounds exist." },
    misreading: "Do not weaponize these virtues against an injured person. Their moral worth depends on agency, truth, and judgment, not forced proximity or denial.",
    selfAudit: ["Which claim am I holding because justice requires it, and which because anger enjoys it?", "Can I speak fairly about this person while keeping a boundary?", "Where would gentleness improve the method without weakening the aim?"],
    sourceAnchor: "Book 25, continuation of the rancour section on pardon, beneficence, and gentleness.",
    model: { kind: "spectrum", title: "Three movements beyond retaliation", items: [
      { label: "Restraint", body: "The person prevents anger from producing a prohibited answer.", role: "support" },
      { label: "Pardon", body: "A personal claim to retaliation is released without denying the wrong.", role: "balance" },
      { label: "Beneficence", body: "Voluntary good is offered where rancour would prefer deprivation.", role: "balance" },
      { label: "Gentleness", body: "A stable manner carries aims without haste, roughness, or needless injury.", role: "balance" },
    ], caption: "The terms overlap in practice but name distinct moral achievements in Ghazali's treatment." },
  }),
  chapter({
    id: 10,
    shortTitle: "Envy and emulation",
    formalTitle: "The blame, definition, divisions, and degrees of envy",
    overview: "Envy concerns a blessing. Ghazali defines it as disliking another person's blessing and wanting it removed. He distinguishes this from emulation, in which one desires a similar good without wanting the other person to lose theirs, and then maps four degrees according to what one wants for oneself and the other person.",
    points: ["Envy is defined by hostility to another person's blessing, not by aspiration alone.", "Emulation preserves the other person's good while desiring a similar good.", "The four degrees reveal different mixtures of desire, comparison, and wish for removal."],
    reflection: "When comparison hurts, finish two sentences separately: 'I want...' and 'I want them to lose...' The second sentence reveals what aspiration alone cannot explain.",
    relatedNodes: ["envy", "blessing", "emulation", "comparison"],
    thesis: "The decisive line between envy and sound emulation is whether the other person's good is allowed to remain good in one's own heart.",
    context: "After condemning envy through scriptural reports and examples, Ghazali defines its object and separates it from ghibta, often rendered here as emulation. The four degrees refine the analysis beyond a single undifferentiated feeling.",
    moves: [
      { title: "Locate the object", body: "Envy arises in relation to a blessing another person possesses. The heart's response to that blessing is the subject of examination." },
      { title: "Define envy", body: "The person dislikes the blessing and wants it removed from the one who has received it." },
      { title: "Preserve emulation", body: "One may desire a similar religious or worldly good without objecting to its continued presence in another person." },
      { title: "Map the first two degrees", body: "At the harshest level, removal is desired whether or not the blessing comes to oneself. At another level, one wants the very advantage another holds." },
      { title: "Map the final two degrees", body: "A person may want an equal good and, if unable to obtain it, want the difference erased. The sounder degree desires an equal good yet still permits the other person's blessing to remain." },
    ],
    closeReading: [
      { title: "Aspiration can hide a second wish", body: "Saying 'I only want the same' is not enough if inability to reach it makes the other person's loss feel relieving. The counterfactual reveals the structure." },
      { title: "A corrupt use can change the object", body: "Ghazali allows dislike of a resource insofar as it serves corruption and harm. The target is its destructive use, not blessing as blessing." },
    ],
    distinction: { title: "Wanting the same is not wanting theirs gone", firstLabel: "Emulation", first: "Their blessing remains welcome while its goodness awakens a desire for a similar gift and the work it requires.", secondLabel: "Envy", second: "Their possession itself becomes painful, and removal begins to feel like a solution to one's own lack." },
    misreading: "Do not label every uncomfortable comparison as fully formed envy. Ghazali's definitions and degrees ask what the heart actually wishes for the other person's good.",
    selfAudit: ["Would I still want this if no one knew who possessed it?", "If I could not obtain the same, would their loss relieve me?", "Can I ask God to preserve and bless their good while seeking my own?"],
    sourceAnchor: "Book 25, sections on the blame, reality, divisions, and degrees of envy.",
    model: { kind: "spectrum", title: "Four degrees around another person's blessing", items: [
      { label: "Remove it", body: "The blessing should disappear even if it never comes to me.", role: "warning" },
      { label: "Transfer it", body: "I want the very advantage they hold and therefore want them to lose it.", role: "warning" },
      { label: "Equalize downward", body: "I want an equal good, but if I cannot have it I want the difference removed.", role: "warning" },
      { label: "Emulate without removal", body: "I seek a similar good while continuing to welcome its presence in them.", role: "balance" },
    ], caption: "The labels are editorial translations of the four degrees Ghazali enumerates. They expose the wish concerning the other person's blessing." },
  }),
  chapter({
    id: 11,
    shortTitle: "Seven roots of envy",
    formalTitle: "The seven causes of envy and emulation",
    overview: "Ghazali gathers the causes of blameworthy envy into seven roots: enmity, fear of another's superiority, the wish to dominate, astonishment that a comparable person received a great blessing, fear of losing a desired aim, love of unique leadership, and a soul that is stingy with good for God's servants.",
    points: ["Different causes can produce the same wish for another's loss.", "Several causes concern rank and relative position rather than the blessing itself.", "More than one cause usually combines in a serious case."],
    reflection: "Do not stop at 'I am jealous.' Name the threatened relation: enemy, superior, subordinate, rival, exceptional equal, competitor for a scarce aim, or simply another recipient of good.",
    relatedNodes: ["envy", "rank", "competition", "scarcity"],
    thesis: "Envy becomes treatable when the person identifies the particular relation to rank, rivalry, injury, scarcity, or goodness that makes another's blessing feel intolerable.",
    context: "The source moves from definition to diagnosis. The seven causes explain why identical blessings disturb different people for different reasons and why a single case often contains several motives at once.",
    moves: [
      { title: "Enmity seeks cosmic retaliation", body: "A person harmed by another may want time itself to punish the enemy and reads continued blessing as a defeat of their grievance." },
      { title: "Rank can be feared from below", body: "One may not wish to dominate, yet cannot bear the thought that another's blessing will allow them to act superior." },
      { title: "Rank can be demanded from above", body: "The wish to command or belittle another is threatened when their blessing gives them independence or parity." },
      { title: "Comparison and competition narrow the field", body: "A person may resent an equal receiving an exceptional good, fear losing a shared aim, or need to remain singular in a valued quality." },
      { title: "Good itself can become unwelcome", body: "The final cause is a general stinginess toward divine generosity, where reports of another's flourishing hurt even without rivalry or practical loss." },
    ],
    closeReading: [
      { title: "Rank is often the hidden object", body: "The visible blessing may be money, knowledge, beauty, influence, or devotion, but the inward contest concerns who is above, equal, singular, or obeyed." },
      { title: "Mixed causes require mixed treatment", body: "Humility alone may not cure a case also sustained by enmity and scarcity. Diagnosis must follow the actual bundle rather than the most flattering explanation." },
    ],
    distinction: { title: "The blessing and the position it signals are different objects", firstLabel: "Desire for the good", first: "The quality itself is loved and sought for its proper use without hostility to other recipients.", secondLabel: "Desire for relative rank", second: "The quality matters because it secures superiority, uniqueness, safety from another's rise, or victory in a shared field." },
    misreading: "Do not treat the seven causes as mutually exclusive personality types. Ghazali explicitly says several or all can gather in one person.",
    selfAudit: ["What relative position would their blessing change?", "Is my pain about losing a good or losing uniqueness?", "Which causes are combining rather than appearing alone?"],
    sourceAnchor: "Book 25, section on the seven causes of envy and emulation.",
    model: { kind: "chain", title: "The blessing enters a social interpretation", items: [
      { label: "Another is blessed", body: "A good becomes visible in a person nearby or significant to me.", role: "support" },
      { label: "Relation is named", body: "Enemy, rival, equal, subordinate, or competitor gives the blessing a positional meaning.", role: "support" },
      { label: "Rank feels threatened", body: "Safety, uniqueness, superiority, or access to a desired aim seems reduced.", role: "warning" },
      { label: "Removal feels useful", body: "The other person's loss is imagined as repair of my position.", role: "warning" },
    ], caption: "The chain helps locate the cause beneath the feeling. It does not imply that every envy begins with all seven causes." },
  }),
  chapter({
    id: 12,
    shortTitle: "Why peers envy peers",
    formalTitle: "Why envy intensifies among peers, siblings, relatives, neighbours, and colleagues",
    overview: "Envy becomes more common where people share a field, audience, craft, household, market, school, or aim. Ghazali's explanation is structural: similar people repeatedly meet, seek overlapping goods, and can imagine one another as direct causes of relative loss. Distant people rarely compete over the same narrow object.",
    points: ["Similarity and proximity create repeated comparison.", "Shared aims feel narrow when one person's gain appears to reduce another's standing or access.", "Wider, nonrival goods weaken the structure of envy."],
    reflection: "Map the field in which comparison is sharpest. What shared audience, scarce opportunity, or claim to uniqueness makes a nearby person's good feel like information about you?",
    relatedNodes: ["proximity", "competition", "scarcity", "comparison"],
    thesis: "Peers envy one another not merely because they are near, but because nearness and similarity place them before the same audience and around the same apparently scarce aims.",
    context: "Ghazali uses examples from trades, scholarship, preaching, courage, kinship, and household relations. The durable argument concerns overlap of purpose: the shoemaker compares with another shoemaker because they seek the same kind of custom and recognition.",
    moves: [
      { title: "Begin with repeated contact", body: "People joined by family, neighbourhood, craft, school, or social setting encounter one another's gains and differences again and again." },
      { title: "Add a shared aim", body: "The comparison sharpens where both seek the same customers, authority, praise, affection, position, or distinction." },
      { title: "Interpret gain as displacement", body: "The field is imagined as too narrow for both. Another person's rise then appears to occupy a place that should have been one's own." },
      { title: "See why distance weakens envy", body: "A person in a distant field or unrelated craft usually does not threaten the same aim, so their blessing carries less comparative force." },
      { title: "Turn toward a good without crowding", body: "Ghazali contrasts narrow worldly competition with knowledge of God, a good not diminished by another person's participation and not exhausted by many seekers." },
    ],
    closeReading: [
      { title: "Proximity is an amplifier", body: "Nearness supplies information, repetition, and a shared audience. It does not mechanically cause envy, but it gives envy frequent material." },
      { title: "Scarcity can be interpreted as well as real", body: "Some opportunities are genuinely limited. Yet the need to be singular can create scarcity even around goods that could be shared, multiplied, or pursued together." },
    ],
    distinction: { title: "A shared field can support cooperation or positional comparison", firstLabel: "Shared pursuit", first: "Another person's excellence reveals possibility, contributes to a common good, and can be welcomed without erasing one's own path.", secondLabel: "Narrow rivalry", second: "The field becomes a single seat, audience, or identity that only one person is allowed to occupy." },
    misreading: "Do not conclude that closeness, family, or professional ambition is itself corrupt. The analysis shows why these settings need deliberate generosity and a less narrow account of success.",
    selfAudit: ["Who feels comparable enough to threaten me?", "What audience am I imagining as able to value only one of us?", "Which part of this good can expand through cooperation?"],
    sourceAnchor: "Book 25, section on why envy is frequent among peers, siblings, relatives, neighbours, and those sharing a craft or aim.",
    model: { kind: "chain", title: "Why nearness can make a blessing feel scarce", items: [
      { label: "Similarity", body: "We share a role, craft, family place, audience, or valued identity.", role: "support" },
      { label: "Proximity", body: "Their gains and my differences remain repeatedly visible.", role: "support" },
      { label: "Overlapping aim", body: "We seek the same recognition, affection, customer, opportunity, or claim to excellence.", role: "warning" },
      { label: "Narrow field", body: "Their gain is interpreted as my displacement, making removal appear useful.", role: "warning" },
    ], caption: "This is Ghazali's explanation for the concentration of envy among comparable and connected people." },
  }),
  chapter({
    id: 13,
    shortTitle: "The cure for envy",
    formalTitle: "The treatment that removes envy from the heart through knowledge and action",
    overview: "Ghazali again joins knowledge to action. Knowledge sees that envy immediately harms the envier without removing the envied person's blessing. Action then opposes every demand of envy: praise instead of detraction, humility instead of superiority, generosity instead of withholding, and visible gladness instead of coldness.",
    points: ["Envy punishes the envier in the present while failing to control the blessing.", "The practical cure deliberately acts against envy rather than waiting to feel sincere ease.", "Repeated opposite action can produce mutual affection and retrain the heart."],
    reflection: "Choose one lawful opposite action small enough to perform honestly: acknowledge a real good, make a sincere prayer, offer fair credit, or refuse the detraction envy proposed.",
    relatedNodes: ["cure", "opposite-action", "knowledge", "generosity"],
    thesis: "Envy is weakened when clear knowledge exposes its self-injury and repeated opposite action denies it the conduct through which it sustains itself.",
    context: "This treatment closely parallels the earlier cure of anger. Ghazali first changes what the person believes envy accomplishes, then prescribes difficult conduct that contradicts its speech, posture, and withholding.",
    moves: [
      { title: "See the immediate self-harm", body: "Another person's recurring blessings become recurring occasions of grief. Envy turns the heart into the place where the desired punishment is already happening." },
      { title: "See the failure of control", body: "The blessing does not leave because one resents it. The envier bears spiritual and worldly pain without obtaining the imagined correction." },
      { title: "Recover the possibility of love", body: "Ghazali argues that loving good for others lets a person share in the moral worth of what they cannot personally attain. Envy forfeits even this route." },
      { title: "Command the opposite act", body: "Where envy asks for detraction, practise truthful praise; where it asks for pride, practise humility; where it asks for withholding, add generosity." },
      { title: "Let action reshape relation", body: "The difficult outward act can soften the other person, invite reciprocal good, and train what was first performed with effort into a more settled inclination." },
    ],
    closeReading: [
      { title: "Opposite action must remain truthful", body: "Praise does not mean fabrication and generosity does not mean enabling harm. The cure opposes envy within the bounds of truth and wise responsibility." },
      { title: "The medicine is bitter by design", body: "Ghazali expects the practice to feel humiliating or artificial to the envious self. Its resistance is part of the diagnosis, not proof that the treatment is false." },
    ],
    distinction: { title: "Acting against envy is not performing false affection", firstLabel: "Truthful opposite action", first: "A real good is acknowledged, a fair right is given, and the person refuses conduct that envy demanded.", secondLabel: "Flattery or denial", second: "Speech invents virtues, hides needed boundaries, or seeks approval without confronting the wish for another's loss." },
    misreading: "Do not turn opposite action into unsafe intimacy or dishonest praise. Ghazali's remedy contradicts envy while remaining answerable to truth, rights, and the actual situation.",
    selfAudit: ["What conduct is envy currently requesting?", "What is its truthful opposite?", "Can I welcome their good without making their path my measure?"],
    sourceAnchor: "Book 25, section on the treatment that removes envy through knowledge and action.",
    model: { kind: "pair", title: "The double medicine", items: [
      { label: "Knowledge", body: "See that envy injures your faith and present life, fails to remove the blessing, and can even benefit the person you attack.", role: "support" },
      { label: "Opposite action", body: "Make tongue, posture, generosity, and visible response contradict the direction envy demanded.", role: "balance" },
    ], caption: "Neither half is sufficient alone: insight makes the bitter action intelligible, and action prevents insight from remaining abstract." },
  }),
  chapter({
    id: 14,
    shortTitle: "What must be removed",
    formalTitle: "The required degree in removing envy from the heart",
    overview: "The final section makes a demanding but realistic distinction. An involuntary natural inclination may arise, especially toward someone who has caused harm. What is required is to oppose that inclination inwardly, refuse to approve it, and keep voluntary speech and action from obeying it. Ghazali distinguishes three states by how the person relates to the unwanted wish.",
    points: ["An involuntary inclination and willing approval are not the same condition.", "The person must inwardly dislike the envious wish and prevent voluntary harm.", "Open expression is clearly prohibited, while silent approval of the inward wish remains morally dangerous."],
    reflection: "When the unwanted wish appears, add a second response: 'I do not consent to this, and I will not feed it.' Then choose the next action that proves the second response is governing.",
    relatedNodes: ["inclination", "consent", "resistance", "responsibility"],
    thesis: "Moral responsibility is located not in never experiencing an unwanted inclination, but in whether the person approves, resists, and acts from it.",
    context: "Ghazali closes by addressing the exact problem readers often fear: what if the heart still registers an enemy's good painfully? He preserves responsibility for the heart while acknowledging limits of direct control over the first natural movement.",
    moves: [
      { title: "Acknowledge the involuntary contest", body: "A person harmed by another may naturally find their good difficult to witness. Ghazali does not pretend the heart can always make friend and enemy feel identical on command." },
      { title: "Add rational and religious refusal", body: "The person can dislike the envious inclination, blame it in the self, and wish for freedom from it even while the first movement persists." },
      { title: "Block voluntary expression", body: "Speech, gesture, and action must not turn the inward wish into detraction, gloating, obstruction, or injury." },
      { title: "Distinguish three states", body: "Resisted inclination is pardoned; outward expression is clearly prohibited; inward approval without outward action occupies a disputed and dangerous middle." },
      { title: "Keep practising beyond the minimum", body: "The required floor protects from obedience to envy, while the larger treatment of knowledge, opposite action, and love of good continues to reform the heart." },
    ],
    closeReading: [
      { title: "Resistance is an inward act", body: "The heart is not treated as morally irrelevant until the limbs move. The person's refusal, regret, and wish to be rid of envy are themselves part of responsibility." },
      { title: "The minimum is not the destination", body: "Merely containing outward injury can prevent grave harm, but Ghazali's cure aims at a heart increasingly able to welcome good and escape the pain of comparison." },
    ],
    distinction: { title: "Occurrence, consent, and expression must not be collapsed", firstLabel: "Unwanted and resisted", first: "The inclination occurs without invitation, is inwardly rejected, and is not allowed to direct voluntary conduct.", secondLabel: "Approved or expressed", second: "The person welcomes the wish for loss, preserves it without objection, or carries it into speech and action." },
    misreading: "Do not turn involuntary comparison into grounds for despair. Ghazali's three states preserve a real field of agency between first occurrence and chosen harm.",
    selfAudit: ["Did I invite this wish, approve it, or merely notice it?", "What inward refusal am I making?", "What voluntary action would show that envy is not governing?"],
    sourceAnchor: "Book 25, final section on the required degree in removing envy from the heart.",
    model: { kind: "spectrum", title: "Three relations to an envious inclination", items: [
      { label: "Resisted", body: "The wish arises, is inwardly disliked, and receives no voluntary speech or action.", role: "balance" },
      { label: "Contained but approved", body: "The person keeps the limbs back but preserves the wish without inward objection, a disputed and dangerous middle.", role: "warning" },
      { label: "Expressed", body: "The wish is carried into gloating, detraction, obstruction, or injury and is clearly prohibited.", role: "warning" },
    ], caption: "The three states preserve Ghazali's closing distinction between natural inclination, inward consent, and voluntary expression." },
  }),
];

export const book25ConceptNodes: ConceptNode[] = [
  { id: "anger", label: "Anger", kicker: "Protective heat seeking command", description: "A created power that can repel harm, but becomes destructive when it stops waiting for reason and religion.", position: "left" },
  { id: "protection", label: "Protection", kicker: "The created purpose", description: "Anger has a necessary function in defending life, right, responsibility, and what deserves firm concern.", position: "right" },
  { id: "measure", label: "Measure", kicker: "Deficiency, mean, excess", description: "The sound condition is not numbness but a force whose rise, degree, and end receive direction.", position: "top" },
  { id: "pride", label: "Pride", kicker: "A claim waiting to be touched", description: "Buried self-importance supplies combustible material when another person obstructs, corrects, or appears to diminish the self.", position: "bottom" },
  { id: "mastery", label: "Mastery", kicker: "Strength that can stop", description: "The ability to govern oneself at anger is a deeper power than the capacity to overpower another person.", position: "left" },
  { id: "residue", label: "Residue", kicker: "What remains after heat", description: "An incident can end outwardly while the demand for retaliation remains in the heart and changes the relation.", position: "right" },
  { id: "reason", label: "Reason and religion", kicker: "The rule beyond appetite", description: "Ghazali's mean requires anger to wait for a judgment that its own desire for retaliation cannot supply.", position: "top" },
  { id: "body", label: "Embodied heat", kicker: "The state shows itself", description: "Posture, colour, trembling, speech, and acceleration provide early evidence that counsel needs protection.", position: "bottom" },
  { id: "training", label: "Training", kicker: "Remove material before crisis", description: "Discipline weakens recurring fuels, rehearses opposites, and makes a governed response increasingly available.", position: "left" },
  { id: "fuel", label: "Fuel", kicker: "The cause beneath the trigger", description: "Pride, rivalry, mockery, argument, betrayal, and attachment to surplus advantage make many incidents combustible.", position: "right" },
  { id: "interruption", label: "Interruption", kicker: "Protect judgment at the peak", description: "Knowledge, silence, changed posture, and cooling action keep anger from obtaining an immediate outlet.", position: "top" },
  { id: "restraint", label: "Restraint", kicker: "Withhold while able", description: "The person prevents a present force from commanding speech or action even where retaliation feels possible.", position: "bottom" },
  { id: "forbearance", label: "Forbearance", kicker: "A settled calm capacity", description: "Repeated restraint becomes a more stable disposition in which anger is less easily stirred and more easily governed.", position: "left" },
  { id: "justice", label: "Justice", kicker: "A right with a stopping rule", description: "Truth and proportion preserve redress without allowing injury to authorize another prohibited act.", position: "right" },
  { id: "rancour", label: "Rancour", kicker: "Anger stored as relation", description: "Lasting aversion makes another person's presence heavy, their good painful, and their misfortune satisfying.", position: "top" },
  { id: "rights", label: "Rights", kicker: "Hostility cannot cancel a claim", description: "Rancour reaches a grave outward form when it withholds debts, kinship, redress, or other rights owed to the disliked person.", position: "bottom" },
  { id: "pardon", label: "Pardon", kicker: "Release without denial", description: "A person can relinquish personal retaliation while naming the wrong and keeping a prudent boundary.", position: "left" },
  { id: "gentleness", label: "Gentleness", kicker: "Power without needless roughness", description: "A governed manner pursues aims with steadiness and thought rather than haste and harshness.", position: "right" },
  { id: "envy", label: "Envy", kicker: "Another's blessing becomes painful", description: "Envy dislikes a blessing in another person and wants it removed, whether or not it comes to the envier.", position: "top" },
  { id: "emulation", label: "Emulation", kicker: "Aspiration without removal", description: "One seeks a similar good while continuing to welcome the blessing already given to another person.", position: "bottom" },
  { id: "comparison", label: "Comparison", kicker: "The field narrows", description: "Similarity, proximity, shared audiences, and overlapping aims can turn another person's gain into a verdict on the self.", position: "left" },
  { id: "opposite-action", label: "Opposite action", kicker: "Do not wait for ease", description: "Truthful praise, humility, generosity, and gladness contradict envy and retrain the relationship through action.", position: "right" },
  { id: "inclination", label: "Inclination", kicker: "Occurrence before consent", description: "An unwanted wish can arise without invitation, especially toward one who caused harm, and still be inwardly resisted.", position: "top" },
  { id: "responsibility", label: "Responsibility", kicker: "Resist, refuse, redirect", description: "Agency appears in whether the person approves the wish, carries it into action, or opposes it inwardly and outwardly.", position: "bottom" },
];

export const book25Journeys: Journey[] = [
  {
    id: "governing-heat", number: "01", question: "What is anger for?", title: "Enter the chamber of governed heat",
    description: "Separate protective force from deficiency and excess, then see why discipline changes anger's rule rather than erasing its created root.",
    payoff: "You leave with a non-suppressive model of anger under moral command.",
    image: assetUrl("assets/system/book25-governed-heat.jpg"), imageAlt: "A luminous white and gold Islamic hydraulic chamber with a central amber brazier governed by three measured water channels.", minutes: 8, color: "#c56a3f",
    nodes: [
      { id: "trace-the-fire", label: "Trace what the fire leaves", micro: "Anger, rancour, envy", summary: "Ghazali begins with concealed fire and immediately follows its residue into rancour and envy.", guardrail: "The first movement and its chosen rule are not the same.", chapterId: 1, glyph: "arrive" },
      { id: "recover-the-purpose", label: "Recover protective purpose", micro: "A created power", summary: "Anger exists to repel harm, so reform cannot mean removing every capacity for firmness.", guardrail: "Protection does not authorize excess.", chapterId: 2, glyph: "guard" },
      { id: "find-the-mean", label: "Find the governed mean", micro: "Deficiency, command, excess", summary: "The sound middle is force obedient to reason and religion, not merely a medium-intensity feeling.", guardrail: "Gentleness and inability are not identical.", chapterId: 2, glyph: "balance" },
      { id: "train-the-rule", label: "Train the rule, not numbness", micro: "Fuel, habit, action", summary: "Discipline weakens avoidable attachments and stops anger from carrying speech and action beyond truth.", guardrail: "A remaining root is not permission to remain unchanged.", chapterId: 3, glyph: "practice" },
    ],
  },
  {
    id: "interrupting-surge", number: "02", question: "Where can the surge be interrupted?", title: "Pass through the cooling arcade",
    description: "Move from recurring fuel to emergency interruption, then from effortful restraint to forbearance and proportionate redress.",
    payoff: "You gain an upstream and in-the-moment treatment map.",
    image: assetUrl("assets/system/book25-cooling-arcade.jpg"), imageAlt: "A bright white marble mosque arcade where amber heat passes through shaded arches, descending steps, a turquoise fountain, and a balanced brass gate.", minutes: 11, color: "#248f9b",
    nodes: [
      { id: "name-the-fuel", label: "Name recurring fuel", micro: "The cause beneath the event", summary: "Pride, rivalry, mockery, dispute, betrayal, and greed for advantage make different incidents burn alike.", guardrail: "Explanation does not erase another person's wrong.", chapterId: 4, glyph: "diagnose" },
      { id: "stop-the-outlet", label: "Stop the immediate outlet", micro: "Knowledge joined to action", summary: "Silence, changed posture, cooling, and several reflections protect judgment after anger has risen.", guardrail: "Cooling the state does not decide the dispute.", chapterId: 5, glyph: "clear" },
      { id: "practice-restraint", label: "Let restraint form character", micro: "Effort becomes forbearance", summary: "Repeatedly withholding retaliation while able can make reason's rule steadier and anger less easily stirred.", guardrail: "Effortful virtue is not false virtue.", chapterId: 6, glyph: "cultivate" },
      { id: "bound-the-reply", label: "Give reply a stopping rule", micro: "Truth and proportion", summary: "A real injury permits only the truthful, proportionate response that protects or restores the right.", guardrail: "Pardon is higher, but bounded redress remains distinct from revenge.", chapterId: 7, glyph: "balance" },
    ],
  },
  {
    id: "cooling-residue", number: "03", question: "What remains after the argument?", title: "Descend into the reservoir of residue",
    description: "See how blocked anger settles into rancour, how its eight fruits reorganize a relationship, and how pardon and gentleness reverse the direction.",
    payoff: "You learn to diagnose quiet hostility, not only visible aggression.",
    image: assetUrl("assets/system/book25-residue-reservoir.jpg"), imageAlt: "A sunlit Islamic cistern cutaway where dark red sediment settles below a white and gold courtyard while clear channels, lilies, and a gentle overflow restore the water.", minutes: 9, color: "#8a5e9b",
    nodes: [
      { id: "notice-the-remainder", label: "Notice what the scene left", micro: "Outward calm, inward demand", summary: "Rancour begins when anger returns inward and remains as durable aversion after the visible incident ends.", guardrail: "Memory and prudent caution are not identical to rancour.", chapterId: 8, glyph: "receive" },
      { id: "read-the-eight-fruits", label: "Read the eight fruits", micro: "From envy to withheld rights", summary: "Stored hostility moves through gloating, estrangement, unlawful speech, mockery, injury, and denial of rights.", guardrail: "Avoiding visible harm is the minimum, not full recovery.", chapterId: 8, glyph: "pattern" },
      { id: "keep-safe-boundaries", label: "Keep boundary without hostility", micro: "Protection and inward release", summary: "Distance can remain where safety or trust requires it while the wish for another's harm is refused.", guardrail: "Release does not require unsafe access.", chapterId: 9, glyph: "guard" },
      { id: "recover-positive-good", label: "Recover positive good", micro: "Pardon, beneficence, gentleness", summary: "Freedom from rancour becomes visible in fair speech, released retaliation, voluntary good, and a governed manner.", guardrail: "Truth is not sacrificed to forced peace.", chapterId: 9, glyph: "cultivate" },
    ],
  },
  {
    id: "understanding-envy", number: "04", question: "Why does another's good hurt?", title: "Walk the court of comparison",
    description: "Distinguish envy from emulation, uncover seven roots, and see why peers, relatives, neighbours, and colleagues provide the sharpest comparisons.",
    payoff: "You can identify the wish, rank, and social field beneath comparison.",
    image: assetUrl("assets/system/book25-comparison-court.jpg"), imageAlt: "A radiant Islamic courtyard with two equally lit garden pavilions, seven brass channels of comparison, and a wide sky that visually removes scarcity.", minutes: 12, color: "#b48a2f",
    nodes: [
      { id: "name-the-wish", label: "Name the actual wish", micro: "What should happen to their good?", summary: "Envy wants the blessing removed; emulation wants a similar good while allowing theirs to remain.", guardrail: "Painful comparison is not yet a complete diagnosis.", chapterId: 10, glyph: "name" },
      { id: "test-the-counterfactual", label: "Test the counterfactual", micro: "If I cannot have it", summary: "The clearest divide appears when personal attainment is impossible: does the other person's loss now feel relieving?", guardrail: "Aspiration can be sound without guaranteed attainment.", chapterId: 10, glyph: "diagnose" },
      { id: "find-the-root", label: "Find the root relation", micro: "Enemy, rival, equal, subordinate", summary: "Seven causes locate envy in enmity, rank, fear, astonishment, competition, uniqueness, or stinginess with good.", guardrail: "Several roots may combine in one case.", chapterId: 11, glyph: "pattern" },
      { id: "map-the-shared-field", label: "Map the shared field", micro: "Proximity plus overlapping aims", summary: "Comparable people envy more where they repeatedly meet before the same audience and seek apparently scarce goods.", guardrail: "Closeness and ambition are not themselves corrupt.", chapterId: 12, glyph: "forces" },
      { id: "widen-the-good", label: "Widen the field of good", micro: "A blessing without crowding", summary: "Ghazali redirects desire toward knowledge of God, a good not diminished by the participation of many seekers.", guardrail: "Real worldly scarcity still needs just structures and wise action.", chapterId: 12, glyph: "clear" },
    ],
  },
  {
    id: "reversing-envy", number: "05", question: "How is envy actually reversed?", title: "Enter the garden of opposite action",
    description: "Join knowledge to deliberate action, then separate involuntary occurrence from consent and outward expression.",
    payoff: "You leave with a truthful practice for resisting envy without pretending it never occurs.",
    image: assetUrl("assets/system/book25-opposite-garden.jpg"), imageAlt: "A luminous white and gold Islamic garden where a returning arrow becomes irrigation, nourishing two flowering trees under an open turquoise sky.", minutes: 9, color: "#3f8c68",
    nodes: [
      { id: "see-self-injury", label: "See where the harm lands", micro: "Pain without control", summary: "Envy repeatedly grieves the envier while failing to remove the blessing that triggered it.", guardrail: "Insight must lead to changed conduct.", chapterId: 13, glyph: "mirror" },
      { id: "act-against-the-demand", label: "Act against the demand", micro: "Truthful praise, humility, generosity", summary: "The cure commands the opposite of the detraction, superiority, and withholding that envy proposes.", guardrail: "Opposite action remains truthful and bounded.", chapterId: 13, glyph: "practice" },
      { id: "separate-occurrence-consent", label: "Separate occurrence from consent", micro: "A wish can be resisted", summary: "An unwanted inclination may appear without invitation, while inward refusal and voluntary conduct remain open to agency.", guardrail: "The heart is not ignored merely because the limbs stay still.", chapterId: 14, glyph: "attend" },
      { id: "prove-the-governing-wish", label: "Prove which wish governs", micro: "Refuse, redirect, continue", summary: "A chosen action that protects another's right or acknowledges their good shows that envy has not received command.", guardrail: "The minimum containment is a floor, not the end of purification.", chapterId: 14, glyph: "resolve" },
    ],
  },
];

export const book25Process: ProcessStage[] = [
  { id: "capacity", label: "Protective capacity", description: "The created power, its three conditions, and the aim of discipline.", color: "#c56a3f", chapterIds: [1, 2, 3] },
  { id: "ignition", label: "Fuel and ignition", description: "Recurring causes make different incidents touch the same combustible claim.", color: "#d58a3c", chapterIds: [4] },
  { id: "surge", label: "Surge and interruption", description: "Knowledge, action, restraint, forbearance, and bounded reply govern the active state.", color: "#248f9b", chapterIds: [5, 6, 7] },
  { id: "residue", label: "Residue and rancour", description: "Anger settles inwardly, bears eight fruits, and is answered by pardon and gentleness.", color: "#8a5e9b", chapterIds: [8, 9] },
  { id: "comparison", label: "Comparison and envy", description: "Another's blessing enters a field of rank, rivalry, proximity, and apparent scarcity.", color: "#b48a2f", chapterIds: [10, 11, 12] },
  { id: "reversal", label: "Knowledge and reversal", description: "Insight, opposite action, inward refusal, and voluntary restraint reverse envy.", color: "#3f8c68", chapterIds: [13, 14] },
];

export const book25Sources: SourceLink[] = [
  { label: "Primary Arabic text", note: "Public Arabic text used to verify the complete announced sequence, definitions, three degrees of anger, causes, treatments, eight fruits of rancour, four degrees and seven causes of envy, peer comparison, and final three states.", url: "https://ar.wikisource.org/wiki/%D8%A5%D8%AD%D9%8A%D8%A7%D8%A1_%D8%B9%D9%84%D9%88%D9%85_%D8%A7%D9%84%D8%AF%D9%8A%D9%86/%D9%83%D8%AA%D8%A7%D8%A8_%D8%B0%D9%85_%D8%A7%D9%84%D8%BA%D8%B6%D8%A8_%D9%88%D8%A7%D9%84%D8%AD%D9%82%D8%AF_%D9%88%D8%A7%D9%84%D8%AD%D8%B3%D8%AF" },
  { label: "Ihya bibliography and Book 25 status", note: "Ghazali.org's book-by-book bibliography identifies Book 25 as The Condemnation of Rancor and Envy and notes that a complete standalone English translation remains in progress.", url: "https://www.ghazali.org/ihya/" },
  { label: "Older English rendering", note: "The public Volume 3 rendering provides an accessible but explicitly abridged English comparison for the anger, hatred, and envy material. It is not treated as a complete critical translation.", url: "https://ghazali.org/ihya/english/ihya-vol3.htm" },
  { label: "Historical English study text", note: "Project Gutenberg's public edition of selected moral and religious teachings includes an older English chapter on anger, enmity, and envy for historical comparison.", url: "https://www.gutenberg.org/files/73140/73140-h/73140-h.htm" },
];

export const book25: SystemBook = {
  id: 25,
  title: "The Condemnation of Anger, Rancour, and Envy",
  shortTitle: "Anger, Rancour, and Envy",
  defaultJourneyId: "governing-heat",
  chapters: book25Chapters,
  conceptNodes: book25ConceptNodes,
  journeys: book25Journeys,
  sources: book25Sources,
  process: {
    title: "Moral state path",
    note: "An editorial causal navigation layer from created capacity through excess, residue, and reversal. Ghazali's source order remains visible in the numbered sections.",
    stages: book25Process,
  },
  editorialNote: "The five journeys and six-stage moral state path are editorial learning aids, not divisions named by Ghazali. The fourteen reading sections follow the full order he announces, with closely connected source sections combined where they form one argument. The English is an original synthesis checked against the complete public Arabic text and older English comparison texts. It does not independently grade every narration or replace a critical Arabic edition, a complete published translation, or qualified scholarly guidance.",
};
